export type PackageStatus = "active" | "sold_out" | "upcoming" | "closed";
export type LeadStatus = "new" | "contacted" | "interested" | "booked" | "cold" | "lost";
export type LeadSource = "website" | "whatsapp" | "referral" | "social" | "walk_in" | "phone";
export type BookingStatus = "confirmed" | "pending" | "cancelled";
export type PaymentStatus = "partial" | "full" | "pending" | "refunded";
export type VendorCategory = "ground_partner" | "hotel" | "guide" | "visa_agent" | "transport" | "flights" | "insurance";

export interface TourPackage {
  id: string;
  slug: string;
  name: string;
  destination: string;
  duration_days: number;
  duration_nights: number;
  price_inr: number;
  original_price_inr: number | null;
  discount_percent: number | null;
  price_note: string;
  advance_amount: number;
  max_pax: number;
  hotel_stars: 3 | 4 | 5;
  hotel_name: string;
  status: PackageStatus;
  seats_available: number;
  start_date: string | null;
  end_date: string | null;
  highlights: string[];
  inclusions: string[];
  exclusions: string[];
  itinerary: { day: number; title: string; description: string }[];
  category: "Canton Fair" | "Custom Tour" | "Sourcing Tour";
}

export interface Lead {
  id: string;
  name: string;
  phone: string;
  email: string;
  city: string;
  state: string;
  business_type: string;
  interested_package_id: string;
  source: LeadSource;
  status: LeadStatus;
  notes: string;
  assigned_to: string;
  created_at: string;
  follow_up_date: string;
  budget_range: string;
}

export interface Payment {
  date: string;
  amount: number;
  mode: string;
  reference: string;
  note: string;
}

export interface Booking {
  id: string;
  lead_id: string;
  package_id: string;
  client_name: string;
  client_phone: string;
  client_email: string;
  client_city: string;
  passengers: number;
  package_name: string;
  total_amount: number;
  advance_paid: number;
  balance_due: number;
  payment_status: PaymentStatus;
  booking_status: BookingStatus;
  booking_date: string;
  travel_date: string;
  notes: string;
  visa_status: "pending" | "applied" | "approved" | "rejected";
  flight_status: "not_booked" | "booked";
  special_requests: string;
  payments: Payment[];
}

export interface ChinaHotel {
  id: string;
  name: string;
  city: string;
  country: string;
  stars: 3 | 4 | 5;
  address: string;
  contact_person: string;
  contact_phone: string;
  contact_email: string;
  rate_usd_per_night: number;
  our_rate_usd: number;
  amenities: string[];
  packages_used_in: string[];
  notes: string;
  status: "active" | "inactive";
}

export interface TourVendor {
  id: string;
  name: string;
  category: VendorCategory;
  country: string;
  city: string;
  contact_person: string;
  phone: string;
  email: string;
  whatsapp: string;
  rating: number;
  notes: string;
  services: string[];
  status: "active" | "inactive";
}

export const tourPackages: TourPackage[] = [
  {
    id: "PKG-001",
    slug: "hk-canton-exclusive",
    name: "Suprans Exclusive Hong Kong & Canton Trip",
    destination: "Hong Kong & Guangzhou",
    duration_days: 8,
    duration_nights: 7,
    price_inr: 169990,
    original_price_inr: null,
    discount_percent: null,
    price_note: "+5% GST +5% TCS applicable",
    advance_amount: 30000,
    max_pax: 20,
    hotel_stars: 5,
    hotel_name: "Marriott Hotel Guangzhou",
    status: "active",
    seats_available: 10,
    start_date: null,
    end_date: null,
    highlights: ["5-star hotel stay", "Canton Fair visit", "Victoria Harbour cruise", "HK Disneyland option", "Dim Sum dinner", "Shopping at Wan Chai"],
    inclusions: [
      "Return airfare (Mumbai/Delhi to HK)",
      "7 nights 5-star hotel accommodation",
      "All transfers by private AC coach",
      "Daily breakfast + 3 group dinners",
      "Canton Fair registration & escort",
      "English + Hindi speaking guide",
      "Hong Kong city tour",
      "Visa assistance support",
      "Travel insurance",
      "Dedicated tour manager",
    ],
    exclusions: [
      "5% GST + 5% TCS on total package",
      "Personal shopping expenses",
      "Lunch & dinner (except group dinners)",
      "HK Disneyland tickets (optional add-on ₹8,000)",
      "Visa fees (approx ₹6,500 per person)",
      "Porter charges",
      "Any personal expenses",
    ],
    itinerary: [
      { day: 1, title: "Departure — Mumbai/Delhi to Hong Kong", description: "Fly to Hong Kong. Arrive, immigration, transfer to hotel. Evening free for Tsim Sha Tsui shopping. Welcome dinner at local Cantonese restaurant." },
      { day: 2, title: "Hong Kong City Tour", description: "Victoria Peak by tram, Aberdeen Fishing Village, Repulse Bay, Stanley Market. Evening harbour cruise with skyline views. Group dinner included." },
      { day: 3, title: "Hong Kong Free Day + Optional Disneyland", description: "Free day for shopping — Mong Kok, Ladies Market, Jade Market. Optional: HK Disneyland (₹8,000 per person). Evening ferry to Macau optional." },
      { day: 4, title: "HK to Guangzhou by Train", description: "Morning high-speed train to Guangzhou (1hr). Check in 5-star hotel. Afternoon visit Guangzhou wholesale markets — Zhanxi garments cluster. Dinner with guide." },
      { day: 5, title: "Canton Fair — Day 1", description: "Full day at Canton Fair Phase 1 (Pazhou Complex). Sector focus: electronics, machinery, hardware. Guided walkthrough of relevant halls. Evening networking with Indian traders." },
      { day: 6, title: "Canton Fair — Day 2 + Factory Visits", description: "Morning Canton Fair continued. Afternoon optional factory visits to supplier facilities in Panyu/Foshan area. Group dinner at Guangzhou old restaurant street." },
      { day: 7, title: "Guangzhou Local Markets + Departure Prep", description: "Morning visit: Yide Road (stationery/toys wholesale), Fangcun timber market (optional). Afternoon shopping + packing. Farewell group dinner." },
      { day: 8, title: "Return — Guangzhou to Mumbai/Delhi", description: "Transfer to Guangzhou Baiyun Airport. Depart for India. Arrive Mumbai/Delhi. Tour ends." },
    ],
    category: "Custom Tour",
  },
  {
    id: "PKG-002",
    slug: "canton-fair-phase1",
    name: "Canton Fair Phase 1 — Apr 15–19, 2026",
    destination: "Guangzhou, China",
    duration_days: 5,
    duration_nights: 4,
    price_inr: 99990,
    original_price_inr: null,
    discount_percent: null,
    price_note: "+GST +TCS applicable",
    advance_amount: 30000,
    max_pax: 40,
    hotel_stars: 4,
    hotel_name: "Guangzhou International Hotel",
    status: "active",
    seats_available: 22,
    start_date: "2026-04-15",
    end_date: "2026-04-19",
    highlights: ["Phase 1: Electronics & Machinery", "4-star hotel near Canton Fair", "Guided fair walkthrough", "Indian food arrangement", "Group transfers"],
    inclusions: [
      "Return airfare (economy)",
      "4 nights 4-star hotel accommodation",
      "Airport and fair transfers",
      "Daily breakfast",
      "Canton Fair registration & escort",
      "Hindi + English speaking guide",
      "Group dinner (2 evenings)",
      "Visa assistance support",
    ],
    exclusions: [
      "GST + TCS on package",
      "Visa fees",
      "Personal meals (lunch/some dinners)",
      "Personal shopping",
      "Factory visit transport",
      "Travel insurance (can add ₹1,500)",
    ],
    itinerary: [
      { day: 1, title: "Arrive Guangzhou", description: "Fly from Mumbai/Delhi. Arrive Guangzhou Baiyun Airport. Transfer to hotel. Orientation briefing by tour manager. Group dinner." },
      { day: 2, title: "Canton Fair Phase 1 — Day 1", description: "Full day Canton Fair — Phase 1 opens. Focus: Electronics, appliances, consumer goods. Guided hall walkthrough by sector. Networking with suppliers. Evening free." },
      { day: 3, title: "Canton Fair Phase 1 — Day 2", description: "Continue Phase 1. Machinery, hardware, tools, building materials sections. Afternoon: arranged meetings with pre-selected suppliers if required. Group dinner." },
      { day: 4, title: "Canton Fair Phase 1 — Day 3 + Wholesale Markets", description: "Morning fair. Afternoon: Zhanxi garments wholesale street, Yide Road (toys, stationery). Farewell dinner with local specialties." },
      { day: 5, title: "Departure — Guangzhou to India", description: "Morning free. Transfer to airport. Depart for India." },
    ],
    category: "Canton Fair",
  },
  {
    id: "PKG-003",
    slug: "canton-fair-phase2",
    name: "Canton Fair Phase 2 — Apr 23–27, 2026",
    destination: "Guangzhou, China",
    duration_days: 5,
    duration_nights: 4,
    price_inr: 89990,
    original_price_inr: 120000,
    discount_percent: 25,
    price_note: "+GST +TCS applicable",
    advance_amount: 30000,
    max_pax: 40,
    hotel_stars: 4,
    hotel_name: "Guangzhou International Hotel",
    status: "active",
    seats_available: 18,
    start_date: "2026-04-23",
    end_date: "2026-04-27",
    highlights: ["Phase 2: Gifts, Home & Garden, Toys", "25% early-bird discount", "4-star hotel near Pazhou", "Factory visit option", "Indian meal options"],
    inclusions: [
      "Return airfare (economy)",
      "4 nights 4-star hotel",
      "Airport and fair transfers",
      "Daily breakfast",
      "Canton Fair registration",
      "Hindi-speaking guide",
      "2 group dinners",
      "Visa support",
    ],
    exclusions: [
      "GST + TCS",
      "Visa fees",
      "Personal meals",
      "Shopping expenses",
      "Travel insurance",
    ],
    itinerary: [
      { day: 1, title: "Arrive Guangzhou", description: "Arrive Guangzhou, transfer to hotel. Briefing session. Group dinner." },
      { day: 2, title: "Phase 2 — Day 1: Gifts & Home Decor", description: "Phase 2 focus: gifts, toys, home & garden, craft items. Visit Pazhou Exhibition Halls. Guide-assisted walkthrough." },
      { day: 3, title: "Phase 2 — Day 2: Seasonal & Festive Goods", description: "Continue phase 2 — seasonal products, festive décor, premium gifts. Meeting arrangements with suppliers. Group dinner." },
      { day: 4, title: "Wholesale Markets + Free Time", description: "Morning: Yide Road toys & gifts wholesale. Afternoon: personal shopping time in Guangzhou malls. Farewell dinner." },
      { day: 5, title: "Departure", description: "Check out, transfer to Baiyun Airport, depart for India." },
    ],
    category: "Canton Fair",
  },
  {
    id: "PKG-004",
    slug: "canton-fair-phase3",
    name: "Canton Fair Phase 3 — May 1–5, 2026",
    destination: "Guangzhou, China",
    duration_days: 5,
    duration_nights: 4,
    price_inr: 89900,
    original_price_inr: 110000,
    discount_percent: 18,
    price_note: "+GST +TCS applicable",
    advance_amount: 30000,
    max_pax: 40,
    hotel_stars: 4,
    hotel_name: "Guangzhou International Hotel",
    status: "active",
    seats_available: 25,
    start_date: "2026-05-01",
    end_date: "2026-05-05",
    highlights: ["Phase 3: Textiles & Apparel", "18% off regular price", "Textile sourcing specialists", "Fabric market visits", "Group buying support"],
    inclusions: [
      "Return airfare",
      "4 nights 4-star hotel",
      "All transfers",
      "Daily breakfast",
      "Canton Fair registration",
      "Guide with textile expertise",
      "2 group dinners",
    ],
    exclusions: [
      "GST + TCS",
      "Visa fees",
      "Personal meals",
      "Shopping expenses",
    ],
    itinerary: [
      { day: 1, title: "Arrive Guangzhou", description: "Arrive, transfer to hotel. Evening briefing on Phase 3 halls and strategy for textile buyers." },
      { day: 2, title: "Phase 3 — Day 1: Textiles & Fabrics", description: "Focus: textiles, fabric, yarn, home textiles, bedding. Expert guide helps identify key supplier booths and quality checks." },
      { day: 3, title: "Phase 3 — Day 2: Apparel & Garments", description: "Apparel, fashion accessories, shoes, bags. Introduction to Canton Fair trade contacts. Group dinner." },
      { day: 4, title: "Guangzhou Garment Market + Haggling Support", description: "Visit Zhanxi garment wholesale hub. Guide assists in price negotiation and sample ordering. Farewell dinner." },
      { day: 5, title: "Departure", description: "Transfer to airport, depart for India." },
    ],
    category: "Canton Fair",
  },
  {
    id: "PKG-005",
    slug: "foshan-furniture-tour",
    name: "Foshan Furniture & Lighting Market Tour",
    destination: "Foshan & Guangzhou, China",
    duration_days: 5,
    duration_nights: 4,
    price_inr: 99990,
    original_price_inr: null,
    discount_percent: null,
    price_note: "+GST +TCS applicable",
    advance_amount: 30000,
    max_pax: 30,
    hotel_stars: 4,
    hotel_name: "Foshan Grand Hotel",
    status: "active",
    seats_available: 20,
    start_date: null,
    end_date: null,
    highlights: ["World's largest furniture market", "Foshan lighting wholesale district", "Lecong furniture city", "Factory direct sourcing", "Interior design consultants"],
    inclusions: [
      "Return airfare",
      "4 nights 4-star hotel (Foshan/Guangzhou)",
      "All transfers including Guangzhou-Foshan",
      "Daily breakfast",
      "Guided market visits (English + Hindi)",
      "2 group dinners",
      "Visa assistance",
    ],
    exclusions: [
      "GST + TCS",
      "Visa fees",
      "Personal meals",
      "Freight/shipping charges for purchases",
      "Travel insurance",
    ],
    itinerary: [
      { day: 1, title: "Arrive Guangzhou → Foshan", description: "Fly to Guangzhou, transfer to Foshan hotel (45 min). Evening walk around Shunde area, briefing session, welcome dinner." },
      { day: 2, title: "Lecong Furniture City", description: "Full day at Lecong International Furniture Exhibition Centre — world's largest. Living room, bedroom, office, kids' furniture clusters. Guide assists with supplier contacts." },
      { day: 3, title: "Foshan Lighting Wholesale District", description: "Morning: China International Lighting Fair cluster, Guzhen lighting town. Afternoon: Ceramic tile market, Sanshui fixtures market. Group dinner." },
      { day: 4, title: "Factory Visits + Guangzhou Wholesale", description: "Morning: Optional factory visits to furniture manufacturers in Shunde. Afternoon: Guangzhou wholesale — Yide Road, building materials market. Farewell dinner." },
      { day: 5, title: "Departure from Guangzhou", description: "Transfer to Guangzhou Baiyun Airport, depart for India." },
    ],
    category: "Sourcing Tour",
  },
  {
    id: "PKG-006",
    slug: "yiwu-shanghai-sourcing",
    name: "Yiwu & Shanghai Sourcing Tour",
    destination: "Yiwu & Shanghai, China",
    duration_days: 5,
    duration_nights: 4,
    price_inr: 99990,
    original_price_inr: null,
    discount_percent: null,
    price_note: "+GST +TCS applicable",
    advance_amount: 30000,
    max_pax: 30,
    hotel_stars: 4,
    hotel_name: "Yiwu International Trade Hotel",
    status: "active",
    seats_available: 15,
    start_date: null,
    end_date: null,
    highlights: ["Yiwu International Trade City", "World's largest small commodities market", "Shanghai tech & innovation hub", "Sourcing agent connections", "High-speed train experience"],
    inclusions: [
      "Return airfare to Shanghai",
      "4 nights 4-star hotel (2 Yiwu + 2 Shanghai)",
      "Yiwu-Shanghai high-speed train",
      "All local transfers",
      "Daily breakfast",
      "Guided tours with sourcing expertise",
      "2 group dinners",
      "Visa assistance",
    ],
    exclusions: [
      "GST + TCS",
      "Visa fees",
      "Personal meals",
      "Shipping costs",
      "Personal shopping",
    ],
    itinerary: [
      { day: 1, title: "Arrive Shanghai → Yiwu", description: "Fly to Shanghai Pudong Airport. Take high-speed train to Yiwu (1.5 hrs). Check in, orientation by guide. Welcome dinner." },
      { day: 2, title: "Yiwu International Trade City — Day 1", description: "Full day in the world's largest small commodities market — 5 districts. Focus: toys, accessories, artificial flowers, hardware. Guide assists navigation." },
      { day: 3, title: "Yiwu Trade City — Day 2 + Agent Introductions", description: "Continue Yiwu market: textiles, printing, electronics accessories. Afternoon: introductions to 2-3 vetted Yiwu sourcing agents for ongoing business. Group dinner." },
      { day: 4, title: "High-speed Train to Shanghai — Innovation Tour", description: "Morning train to Shanghai. Visit Alibaba showcase, Lujiazui financial district, The Bund. Evening: Shanghai Tech Hub visit, electronics clusters in Zhongguancun-equivalent." },
      { day: 5, title: "Depart Shanghai", description: "Morning free for last-minute shopping. Transfer to Pudong Airport, depart for India." },
    ],
    category: "Sourcing Tour",
  },
  {
    id: "PKG-007",
    slug: "wuxi-ev-factory-tour",
    name: "Wuxi EV & Battery Factory Manufacturing Tour",
    destination: "Wuxi & Shanghai, China",
    duration_days: 5,
    duration_nights: 4,
    price_inr: 99990,
    original_price_inr: null,
    discount_percent: null,
    price_note: "+GST +TCS applicable",
    advance_amount: 30000,
    max_pax: 25,
    hotel_stars: 4,
    hotel_name: "Wuxi Lihu Lake Hotel",
    status: "upcoming",
    seats_available: 25,
    start_date: null,
    end_date: null,
    highlights: ["EV manufacturing cluster — Wuxi", "Battery & cell factory tours", "Solar panel production visit", "BYD / CATL supplier ecosystem", "B2B meeting with factory owners"],
    inclusions: [
      "Return airfare to Shanghai",
      "4 nights 4-star hotel (2 Wuxi + 2 Shanghai)",
      "Shanghai-Wuxi high-speed train",
      "All factory transfer coaches",
      "Daily breakfast",
      "Manufacturing specialist guide",
      "Factory visit pre-arrangements",
      "2 group dinners",
      "Visa assistance",
    ],
    exclusions: [
      "GST + TCS",
      "Visa fees",
      "MOQ sample costs",
      "Personal expenses",
      "Travel insurance",
    ],
    itinerary: [
      { day: 1, title: "Arrive Shanghai → Wuxi", description: "Fly to Shanghai, transfer to Wuxi by high-speed train (35 min). Hotel check-in. Evening overview of Wuxi EV cluster by specialist guide." },
      { day: 2, title: "EV Battery Factory Visits", description: "Visit 2 EV battery manufacturing plants (lithium-ion, LFP battery suppliers). Meet factory owners/managers. Q&A session, sample viewing, MOQ discussions." },
      { day: 3, title: "Solar & Electronics Factory Tour", description: "Solar panel manufacturer tour in Wuxi (one of China's top solar clusters). EV charger assembly plant. Afternoon: Wuxi High-tech Industrial Park. Group dinner." },
      { day: 4, title: "Shanghai — Tech & Import Export Hub", description: "Transfer to Shanghai. Visit Shanghai Import-Export facilitation zone. Meeting with trade agents. Optional: Shanghai electronics market." },
      { day: 5, title: "Depart Shanghai", description: "Transfer to Pudong Airport. Depart for India." },
    ],
    category: "Sourcing Tour",
  },
];

export const leads: Lead[] = [
  { id: "LD-001", name: "Rajesh Agarwal", phone: "+91 98101 11111", email: "rajesh@agarwaltextiles.in", city: "Surat", state: "Gujarat", business_type: "Textile Importer", interested_package_id: "PKG-004", source: "whatsapp", status: "booked", notes: "Phase 3 textiles. Interested in yarn and fabric. Has been to China before.", assigned_to: "Priya Kapoor", created_at: "2025-12-15", follow_up_date: "2026-01-10", budget_range: "₹1-2L" },
  { id: "LD-002", name: "Sunita Mehta", phone: "+91 98202 22222", email: "sunita@mehtagifts.com", city: "Mumbai", state: "Maharashtra", business_type: "Gift & Novelty Importer", interested_package_id: "PKG-003", source: "referral", status: "booked", notes: "Phase 2 gifts. Referred by Rajesh. Wants group booking for 2 people.", assigned_to: "Amit Verma", created_at: "2025-12-20", follow_up_date: "2026-01-15", budget_range: "₹1-2L" },
  { id: "LD-003", name: "Kiran Patel", phone: "+91 98303 33333", email: "kiran@homedecorindia.com", city: "Ahmedabad", state: "Gujarat", business_type: "Home Decor Retailer", interested_package_id: "PKG-005", source: "website", status: "interested", notes: "Foshan furniture. Looking to source living room furniture. Needs confirmed dates.", assigned_to: "Priya Kapoor", created_at: "2026-01-05", follow_up_date: "2026-02-10", budget_range: "₹1-2L" },
  { id: "LD-004", name: "Mohd. Imran Khan", phone: "+91 98404 44444", email: "imran@khansupplies.net", city: "Delhi", state: "Delhi", business_type: "Electronics Distributor", interested_package_id: "PKG-002", source: "phone", status: "contacted", notes: "Phase 1 Canton Fair. Wants to source smartphone accessories. Follow up on pricing.", assigned_to: "Amit Verma", created_at: "2026-01-08", follow_up_date: "2026-02-15", budget_range: "₹1L" },
  { id: "LD-005", name: "Deepa Sharma", phone: "+91 98505 55555", email: "deepa@furnitureplusdelhi.com", city: "Noida", state: "Uttar Pradesh", business_type: "Furniture Dealer", interested_package_id: "PKG-005", source: "social", status: "interested", notes: "Foshan furniture tour. Wants 2 pax. Impressed with itinerary. Negotiating on price.", assigned_to: "Priya Kapoor", created_at: "2026-01-10", follow_up_date: "2026-02-20", budget_range: "₹1-2L" },
  { id: "LD-006", name: "Ravi Krishnamurthy", phone: "+91 98606 66666", email: "ravi@southindiaelectronics.com", city: "Chennai", state: "Tamil Nadu", business_type: "Electronics Retailer", interested_package_id: "PKG-007", source: "website", status: "new", notes: "EV battery tour. Running EV charging station business, interested in battery sourcing.", assigned_to: "Amit Verma", created_at: "2026-01-18", follow_up_date: "2026-02-28", budget_range: "₹1-2L" },
  { id: "LD-007", name: "Neha Joshi", phone: "+91 98707 77777", email: "neha@yiwuimports.in", city: "Jaipur", state: "Rajasthan", business_type: "Wholesale Trader", interested_package_id: "PKG-006", source: "whatsapp", status: "contacted", notes: "Yiwu sourcing tour. Looking for small commodities — toys and accessories. First time to China.", assigned_to: "Priya Kapoor", created_at: "2026-01-12", follow_up_date: "2026-02-18", budget_range: "₹1L" },
  { id: "LD-008", name: "Suresh Bansal", phone: "+91 98808 88888", email: "suresh@bansalimex.com", city: "Ludhiana", state: "Punjab", business_type: "Auto Parts Importer", interested_package_id: "PKG-001", source: "referral", status: "booked", notes: "HK Canton exclusive. Senior trader, has been twice before with us. 1 pax.", assigned_to: "Amit Verma", created_at: "2025-12-10", follow_up_date: "2026-01-05", budget_range: "₹2L+" },
  { id: "LD-009", name: "Preeti Ahluwalia", phone: "+91 98909 99999", email: "preeti@designhomeindia.com", city: "Pune", state: "Maharashtra", business_type: "Interior Designer", interested_package_id: "PKG-005", source: "social", status: "interested", notes: "Foshan furniture. High-end furniture sourcing for clients. Wants private tour option.", assigned_to: "Priya Kapoor", created_at: "2026-01-15", follow_up_date: "2026-02-25", budget_range: "₹2L+" },
  { id: "LD-010", name: "Anand Goswami", phone: "+91 97010 10101", email: "anand@cantonimports.com", city: "Surat", state: "Gujarat", business_type: "General Importer", interested_package_id: "PKG-002", source: "website", status: "new", notes: "First Canton Fair trip. Wants to explore options. Send brochure.", assigned_to: "Amit Verma", created_at: "2026-01-20", follow_up_date: "2026-03-01", budget_range: "₹1L" },
  { id: "LD-011", name: "Meena Pillai", phone: "+91 97111 11112", email: "meena@pillaitextiles.com", city: "Coimbatore", state: "Tamil Nadu", business_type: "Textile Manufacturer", interested_package_id: "PKG-004", source: "phone", status: "cold", notes: "Phase 3 textiles. Price sensitive. Not convinced yet. Try again in March.", assigned_to: "Priya Kapoor", created_at: "2026-01-02", follow_up_date: "2026-03-10", budget_range: "₹1L" },
  { id: "LD-012", name: "Vijay Gupta", phone: "+91 97212 12121", email: "vijay@guptahardware.com", city: "Kanpur", state: "Uttar Pradesh", business_type: "Hardware Dealer", interested_package_id: "PKG-002", source: "walk_in", status: "lost", notes: "Phase 1 hardware. Decided to go independently. Not interested in group tour.", assigned_to: "Amit Verma", created_at: "2025-12-28", follow_up_date: "2026-01-20", budget_range: "₹1L" },
  { id: "LD-013", name: "Farhan Sheikh", phone: "+91 97313 13131", email: "farhan@sheikhimports.com", city: "Hyderabad", state: "Telangana", business_type: "FMCG Importer", interested_package_id: "PKG-003", source: "whatsapp", status: "contacted", notes: "Phase 2 gifts/FMCG. Budget approved. Checking with partner for travel dates.", assigned_to: "Priya Kapoor", created_at: "2026-01-14", follow_up_date: "2026-02-22", budget_range: "₹1L" },
  { id: "LD-014", name: "Savita Reddy", phone: "+91 97414 14141", email: "savita@reddyelectricals.in", city: "Vizag", state: "Andhra Pradesh", business_type: "Electrical Goods Dealer", interested_package_id: "PKG-007", source: "referral", status: "new", notes: "EV battery. Interested in EV charging infrastructure supply. New lead via Ravi.", assigned_to: "Amit Verma", created_at: "2026-01-22", follow_up_date: "2026-03-05", budget_range: "₹1-2L" },
  { id: "LD-015", name: "Harish Chand", phone: "+91 97515 15151", email: "harish@chandfurnitures.com", city: "Bengaluru", state: "Karnataka", business_type: "Furniture Retailer", interested_package_id: "PKG-005", source: "website", status: "interested", notes: "Foshan. Looking to diversify from local to imported furniture. 2 pax.", assigned_to: "Priya Kapoor", created_at: "2026-01-09", follow_up_date: "2026-02-15", budget_range: "₹1-2L" },
  { id: "LD-016", name: "Pooja Nair", phone: "+91 97616 16161", email: "pooja@shopifyindia.com", city: "Kochi", state: "Kerala", business_type: "E-commerce Seller", interested_package_id: "PKG-006", source: "social", status: "new", notes: "Yiwu sourcing. Runs Myntra/Amazon stores. Looking for unique imported products.", assigned_to: "Amit Verma", created_at: "2026-01-21", follow_up_date: "2026-03-03", budget_range: "₹1L" },
  { id: "LD-017", name: "Ramesh Choudhary", phone: "+91 97717 17171", email: "ramesh@choudharyauto.com", city: "Jaipur", state: "Rajasthan", business_type: "Auto Parts Distributor", interested_package_id: "PKG-001", source: "phone", status: "interested", notes: "HK Canton exclusive. Interested in 2 pax (husband + wife). Wants single room supplement info.", assigned_to: "Priya Kapoor", created_at: "2026-01-06", follow_up_date: "2026-02-12", budget_range: "₹2L+" },
  { id: "LD-018", name: "Alka Tiwari", phone: "+91 97818 18181", email: "alka@tiwaricrafts.com", city: "Varanasi", state: "Uttar Pradesh", business_type: "Handicraft Exporter", interested_package_id: "PKG-003", source: "whatsapp", status: "cold", notes: "Phase 2 gifts. More interested in reverse — exporting Indian crafts to China. Wrong lead.", assigned_to: "Amit Verma", created_at: "2026-01-03", follow_up_date: "2026-02-01", budget_range: "₹1L" },
];

export const bookings: Booking[] = [
  {
    id: "BKG-001",
    lead_id: "LD-001",
    package_id: "PKG-004",
    client_name: "Rajesh Agarwal",
    client_phone: "+91 98101 11111",
    client_email: "rajesh@agarwaltextiles.in",
    client_city: "Surat",
    passengers: 1,
    package_name: "Canton Fair Phase 3 — May 1–5, 2026",
    total_amount: 89900,
    advance_paid: 30000,
    balance_due: 59900,
    payment_status: "partial",
    booking_status: "confirmed",
    booking_date: "2026-01-10",
    travel_date: "2026-05-01",
    notes: "Aisle seat preference on flight. Vegetarian meals.",
    visa_status: "applied",
    flight_status: "not_booked",
    special_requests: "Vegetarian meals only. Window seat on train.",
    payments: [
      { date: "2026-01-10", amount: 30000, mode: "UPI", reference: "UPI26011001234", note: "Advance booking amount" },
    ],
  },
  {
    id: "BKG-002",
    lead_id: "LD-002",
    package_id: "PKG-003",
    client_name: "Sunita Mehta",
    client_phone: "+91 98202 22222",
    client_email: "sunita@mehtagifts.com",
    client_city: "Mumbai",
    passengers: 2,
    package_name: "Canton Fair Phase 2 — Apr 23–27, 2026",
    total_amount: 179980,
    advance_paid: 60000,
    balance_due: 119980,
    payment_status: "partial",
    booking_status: "confirmed",
    booking_date: "2026-01-15",
    travel_date: "2026-04-23",
    notes: "2 pax — Sunita + husband. Adjacent seats required.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Twin beds in hotel room please.",
    payments: [
      { date: "2026-01-15", amount: 30000, mode: "NEFT", reference: "NEFT0115MEHTA", note: "1st installment — pax 1" },
      { date: "2026-01-15", amount: 30000, mode: "NEFT", reference: "NEFT0115MEHTA2", note: "1st installment — pax 2" },
    ],
  },
  {
    id: "BKG-003",
    lead_id: "LD-008",
    package_id: "PKG-001",
    client_name: "Suresh Bansal",
    client_phone: "+91 98808 88888",
    client_email: "suresh@bansalimex.com",
    client_city: "Ludhiana",
    passengers: 1,
    package_name: "Suprans Exclusive Hong Kong & Canton Trip",
    total_amount: 169990,
    advance_paid: 169990,
    balance_due: 0,
    payment_status: "full",
    booking_status: "confirmed",
    booking_date: "2025-12-20",
    travel_date: "2026-04-10",
    notes: "Repeat client. Loyal. VIP attention required.",
    visa_status: "approved",
    flight_status: "booked",
    special_requests: "Business class upgrade if available within budget.",
    payments: [
      { date: "2025-12-20", amount: 30000, mode: "UPI", reference: "UPISURESH001", note: "Advance" },
      { date: "2026-01-05", amount: 69990, mode: "Bank Transfer", reference: "NEFTBANSAL2ND", note: "2nd installment" },
      { date: "2026-01-25", amount: 70000, mode: "Cheque", reference: "CHQ00234", note: "Final balance cleared" },
    ],
  },
  {
    id: "BKG-004",
    lead_id: "LD-003",
    package_id: "PKG-005",
    client_name: "Kiran Patel",
    client_phone: "+91 98303 33333",
    client_email: "kiran@homedecorindia.com",
    client_city: "Ahmedabad",
    passengers: 1,
    package_name: "Foshan Furniture & Lighting Market Tour",
    total_amount: 99990,
    advance_paid: 30000,
    balance_due: 69990,
    payment_status: "partial",
    booking_status: "confirmed",
    booking_date: "2026-01-20",
    travel_date: "2026-03-15",
    notes: "Interior design firm owner. Interested in high-end furniture.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Need extra time at Lecong Furniture City.",
    payments: [
      { date: "2026-01-20", amount: 30000, mode: "UPI", reference: "UPIKIRAN001", note: "Advance paid" },
    ],
  },
  {
    id: "BKG-005",
    lead_id: "LD-009",
    package_id: "PKG-005",
    client_name: "Preeti Ahluwalia",
    client_phone: "+91 98909 99999",
    client_email: "preeti@designhomeindia.com",
    client_city: "Pune",
    passengers: 2,
    package_name: "Foshan Furniture & Lighting Market Tour",
    total_amount: 199980,
    advance_paid: 60000,
    balance_due: 139980,
    payment_status: "partial",
    booking_status: "pending",
    booking_date: "2026-01-22",
    travel_date: "2026-03-15",
    notes: "Interior designer. 2 pax. Pending final confirmation.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Private consultation with furniture suppliers if possible.",
    payments: [
      { date: "2026-01-22", amount: 60000, mode: "UPI", reference: "UPIPREETI001", note: "Advance for 2 pax" },
    ],
  },
  {
    id: "BKG-006",
    lead_id: "LD-007",
    package_id: "PKG-006",
    client_name: "Neha Joshi",
    client_phone: "+91 98707 77777",
    client_email: "neha@yiwuimports.in",
    client_city: "Jaipur",
    passengers: 1,
    package_name: "Yiwu & Shanghai Sourcing Tour",
    total_amount: 99990,
    advance_paid: 99990,
    balance_due: 0,
    payment_status: "full",
    booking_status: "confirmed",
    booking_date: "2026-01-18",
    travel_date: "2026-03-20",
    notes: "Paid in full. Eager traveller. First trip to China.",
    visa_status: "applied",
    flight_status: "booked",
    special_requests: "Help with Mandarin phrasebook. Needs sourcing agent intro.",
    payments: [
      { date: "2026-01-18", amount: 30000, mode: "UPI", reference: "UPINEHA001", note: "Advance" },
      { date: "2026-01-28", amount: 69990, mode: "NEFT", reference: "NEFTNEHA002", note: "Full balance cleared" },
    ],
  },
  {
    id: "BKG-007",
    lead_id: "LD-015",
    package_id: "PKG-005",
    client_name: "Harish Chand",
    client_phone: "+91 97515 15151",
    client_email: "harish@chandfurnitures.com",
    client_city: "Bengaluru",
    passengers: 2,
    package_name: "Foshan Furniture & Lighting Market Tour",
    total_amount: 199980,
    advance_paid: 30000,
    balance_due: 169980,
    payment_status: "partial",
    booking_status: "pending",
    booking_date: "2026-01-25",
    travel_date: "2026-03-15",
    notes: "2 pax. 2nd pax payment pending.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Need to visit Foshan showrooms for modular kitchen too.",
    payments: [
      { date: "2026-01-25", amount: 30000, mode: "Cash", reference: "CASH-001", note: "Cash advance received at office" },
    ],
  },
  {
    id: "BKG-008",
    lead_id: "LD-017",
    package_id: "PKG-001",
    client_name: "Ramesh Choudhary",
    client_phone: "+91 97717 17171",
    client_email: "ramesh@choudharyauto.com",
    client_city: "Jaipur",
    passengers: 2,
    package_name: "Suprans Exclusive Hong Kong & Canton Trip",
    total_amount: 339980,
    advance_paid: 60000,
    balance_due: 279980,
    payment_status: "partial",
    booking_status: "confirmed",
    booking_date: "2026-01-28",
    travel_date: "2026-04-10",
    notes: "Couple booking. Wife (Seema Choudhary) as 2nd pax.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Double bed room. Jain vegetarian meals.",
    payments: [
      { date: "2026-01-28", amount: 60000, mode: "UPI", reference: "UPIRAMESH001", note: "Advance for 2 pax" },
    ],
  },
  {
    id: "BKG-009",
    lead_id: "LD-004",
    package_id: "PKG-002",
    client_name: "Mohd. Imran Khan",
    client_phone: "+91 98404 44444",
    client_email: "imran@khansupplies.net",
    client_city: "Delhi",
    passengers: 1,
    package_name: "Canton Fair Phase 1 — Apr 15–19, 2026",
    total_amount: 99990,
    advance_paid: 30000,
    balance_due: 69990,
    payment_status: "partial",
    booking_status: "confirmed",
    booking_date: "2026-02-01",
    travel_date: "2026-04-15",
    notes: "Electronics sourcing. Wants to visit Huaqiangbei area too.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Halal food options at hotel.",
    payments: [
      { date: "2026-02-01", amount: 30000, mode: "UPI", reference: "UPIIMRAN001", note: "Advance" },
    ],
  },
  {
    id: "BKG-010",
    lead_id: "LD-013",
    package_id: "PKG-003",
    client_name: "Farhan Sheikh",
    client_phone: "+91 97313 13131",
    client_email: "farhan@sheikhimports.com",
    client_city: "Hyderabad",
    passengers: 1,
    package_name: "Canton Fair Phase 2 — Apr 23–27, 2026",
    total_amount: 89990,
    advance_paid: 89990,
    balance_due: 0,
    payment_status: "full",
    booking_status: "confirmed",
    booking_date: "2026-01-30",
    travel_date: "2026-04-23",
    notes: "Full payment cleared upfront. Reliable client.",
    visa_status: "applied",
    flight_status: "booked",
    special_requests: "Halal meals. Mosque nearby hotel.",
    payments: [
      { date: "2026-01-30", amount: 30000, mode: "UPI", reference: "UPIFARHAN001", note: "Advance" },
      { date: "2026-02-05", amount: 59990, mode: "Bank Transfer", reference: "NEFTFARHAN002", note: "Full balance cleared" },
    ],
  },
  {
    id: "BKG-011",
    lead_id: "LD-005",
    package_id: "PKG-005",
    client_name: "Deepa Sharma",
    client_phone: "+91 98505 55555",
    client_email: "deepa@furnitureplusdelhi.com",
    client_city: "Noida",
    passengers: 1,
    package_name: "Foshan Furniture & Lighting Market Tour",
    total_amount: 99990,
    advance_paid: 30000,
    balance_due: 69990,
    payment_status: "partial",
    booking_status: "confirmed",
    booking_date: "2026-02-05",
    travel_date: "2026-03-15",
    notes: "Furniture dealer. Very specific about high-end office furniture.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Need contacts for Foshan sofa manufacturers specifically.",
    payments: [
      { date: "2026-02-05", amount: 30000, mode: "NEFT", reference: "NEFTDEEPA001", note: "Advance paid" },
    ],
  },
  {
    id: "BKG-012",
    lead_id: "LD-006",
    package_id: "PKG-007",
    client_name: "Ravi Krishnamurthy",
    client_phone: "+91 98606 66666",
    client_email: "ravi@southindiaelectronics.com",
    client_city: "Chennai",
    passengers: 1,
    package_name: "Wuxi EV & Battery Factory Manufacturing Tour",
    total_amount: 99990,
    advance_paid: 30000,
    balance_due: 69990,
    payment_status: "partial",
    booking_status: "pending",
    booking_date: "2026-02-08",
    travel_date: "2026-05-10",
    notes: "EV charging business. Wants factory direct for LFP batteries.",
    visa_status: "pending",
    flight_status: "not_booked",
    special_requests: "Needs to meet CATL supplier ecosystem contacts.",
    payments: [
      { date: "2026-02-08", amount: 30000, mode: "UPI", reference: "UPIRAVI001", note: "Advance" },
    ],
  },
];

export const chinaHotels: ChinaHotel[] = [
  {
    id: "HTL-001",
    name: "Marriott Hotel Guangzhou",
    city: "Guangzhou",
    country: "China",
    stars: 5,
    address: "Tianhe Road, Tianhe District, Guangzhou, 510620",
    contact_person: "Ms. Liu Wei (Sales Manager)",
    contact_phone: "+86 20 8666 6888",
    contact_email: "sales.guangzhou@marriott.com",
    rate_usd_per_night: 180,
    our_rate_usd: 145,
    amenities: ["Free WiFi", "Swimming Pool", "Gym", "Business Centre", "Multiple Restaurants", "Airport Shuttle", "Laundry"],
    packages_used_in: ["PKG-001"],
    notes: "5-star partner hotel for our exclusive HK Canton package. Great location near Tianhe.",
    status: "active",
  },
  {
    id: "HTL-002",
    name: "Guangzhou International Hotel",
    city: "Guangzhou",
    country: "China",
    stars: 4,
    address: "Huanshi East Road, Yuexiu District, Guangzhou, 510060",
    contact_person: "Mr. Chen Jian (Group Sales)",
    contact_phone: "+86 20 8331 1888",
    contact_email: "groups@gzintlhotel.com",
    rate_usd_per_night: 110,
    our_rate_usd: 88,
    amenities: ["Free WiFi", "Gym", "Restaurant", "Airport Shuttle", "Business Centre", "Parking"],
    packages_used_in: ["PKG-002", "PKG-003", "PKG-004"],
    notes: "Close to Canton Fair Pazhou venue (20 min by metro). Good value for 4-star. Indian breakfast available.",
    status: "active",
  },
  {
    id: "HTL-003",
    name: "Harbour Grand Hong Kong",
    city: "Hong Kong",
    country: "China",
    stars: 5,
    address: "23 Oil Street, North Point, Hong Kong",
    contact_person: "Ms. Priya Lam (Group Reservations)",
    contact_phone: "+852 2121 2688",
    contact_email: "groups@harbourgrand.com.hk",
    rate_usd_per_night: 230,
    our_rate_usd: 190,
    amenities: ["Harbour View", "Free WiFi", "Pool", "Spa", "Multiple Restaurants", "Concierge", "Airport Express Close"],
    packages_used_in: ["PKG-001"],
    notes: "Harbour view rooms allocated for our group. Close to Wan Chai shopping. Excellent for business travellers.",
    status: "active",
  },
  {
    id: "HTL-004",
    name: "Foshan Grand Hotel",
    city: "Foshan",
    country: "China",
    stars: 4,
    address: "Hua Yuanlu, Chancheng District, Foshan, Guangdong",
    contact_person: "Mr. Wang Hong (Sales)",
    contact_phone: "+86 757 8288 8888",
    contact_email: "sales@foshan-grand.com",
    rate_usd_per_night: 95,
    our_rate_usd: 75,
    amenities: ["Free WiFi", "Restaurant", "Business Centre", "Shuttle to Lecong Market", "Parking"],
    packages_used_in: ["PKG-005"],
    notes: "Strategic location for furniture market. Provides shuttle to Lecong twice daily. No pool.",
    status: "active",
  },
  {
    id: "HTL-005",
    name: "Yiwu International Trade Hotel",
    city: "Yiwu",
    country: "China",
    stars: 4,
    address: "Chengbei Road, Yiwu, Zhejiang Province",
    contact_person: "Ms. Zhang Mei (Group Sales)",
    contact_phone: "+86 579 8552 8888",
    contact_email: "groups@yiwutradehotel.com",
    rate_usd_per_night: 100,
    our_rate_usd: 80,
    amenities: ["Free WiFi", "Restaurant (Indian menu available)", "Business Centre", "Free Market Shuttle", "Conference Room"],
    packages_used_in: ["PKG-006"],
    notes: "Walking distance to International Trade City District 1. Indian food available. Good for long stays.",
    status: "active",
  },
  {
    id: "HTL-006",
    name: "Wuxi Lihu Lake Hotel",
    city: "Wuxi",
    country: "China",
    stars: 4,
    address: "Lihu Avenue, Binhu District, Wuxi, Jiangsu",
    contact_person: "Mr. Li Jun (Group Manager)",
    contact_phone: "+86 510 8518 8888",
    contact_email: "groupsales@wuxilihu.com",
    rate_usd_per_night: 105,
    our_rate_usd: 82,
    amenities: ["Lake View", "Free WiFi", "Restaurant", "Business Centre", "Gym", "EV Charging Parking"],
    packages_used_in: ["PKG-007"],
    notes: "Near Wuxi High-tech Industrial Park and EV manufacturing cluster. EV charging in parking lot.",
    status: "active",
  },
  {
    id: "HTL-007",
    name: "Radisson Blu Shanghai New World",
    city: "Shanghai",
    country: "China",
    stars: 5,
    address: "88 Nanjing West Road, Huangpu District, Shanghai",
    contact_person: "Ms. Kelly Wang (Corporate Sales)",
    contact_phone: "+86 21 6359 9999",
    contact_email: "groups.shanghai@radissonblu.com",
    rate_usd_per_night: 200,
    our_rate_usd: 160,
    amenities: ["City View", "Free WiFi", "Pool", "Gym", "Revolving Restaurant", "Airport Shuttle", "Business Centre"],
    packages_used_in: ["PKG-006", "PKG-007"],
    notes: "Premium location on Nanjing Road. Used for Shanghai nights in Yiwu and Wuxi tours.",
    status: "active",
  },
  {
    id: "HTL-008",
    name: "Holiday Inn Express Guangzhou Science City",
    city: "Guangzhou",
    country: "China",
    stars: 3,
    address: "Science City, Huangpu District, Guangzhou",
    contact_person: "Mr. Zhao Wei (Reservations)",
    contact_phone: "+86 20 8239 6666",
    contact_email: "hiexpress.gz@ihg.com",
    rate_usd_per_night: 75,
    our_rate_usd: 58,
    amenities: ["Free WiFi", "Breakfast Included", "Business Centre", "Metro Access"],
    packages_used_in: [],
    notes: "Budget option. Used occasionally for single-day transit groups. No pool or gym.",
    status: "active",
  },
];

export const tourVendors: TourVendor[] = [
  {
    id: "VND-001",
    name: "Guangzhou Connect Tours",
    category: "ground_partner",
    country: "China",
    city: "Guangzhou",
    contact_person: "Mr. Jason Huang",
    phone: "+86 136 0020 8888",
    email: "jason@gzconnecttours.com",
    whatsapp: "8613600208888",
    rating: 4.9,
    notes: "Our primary China ground partner since 2022. Handles all transfers, guides, hotel coordination, and Canton Fair registrations in China. Reliable and transparent.",
    services: ["Airport Transfers", "Coach Hire", "Canton Fair Registration", "Hotel Coordination", "Guide Arrangement", "Factory Visit Setup", "Emergency Support 24/7"],
    status: "active",
  },
  {
    id: "VND-002",
    name: "Global Visa Services India",
    category: "visa_agent",
    country: "India",
    city: "Mumbai",
    contact_person: "Ms. Anita Sharma",
    phone: "+91 98200 12345",
    email: "anita@globalvisaindia.com",
    whatsapp: "919820012345",
    rating: 4.6,
    notes: "China visa specialist for group and individual travellers. Processes both tourist and business visas. 7-10 working day turnaround normally.",
    services: ["China Visa (Tourist)", "China Visa (Business)", "HK Visa", "Document Checklist Support", "Group Visa Application", "Visa Tracking"],
    status: "active",
  },
  {
    id: "VND-003",
    name: "Air India Cargo & Group Sales",
    category: "flights",
    country: "India",
    city: "Delhi",
    contact_person: "Mr. Rakesh Nair (Group Sales Manager)",
    phone: "+91 11 2462 2220",
    email: "groupsales@airindia.in",
    whatsapp: "911124622220",
    rating: 4.2,
    notes: "Group booking rates for 10+ pax on India-China routes. Good for Mumbai-Guangzhou, Delhi-Hong Kong.",
    services: ["Group Air Tickets (10+ pax)", "Seat Block Booking", "Ancillary Management", "Cancellation & Rebooking Support"],
    status: "active",
  },
  {
    id: "VND-004",
    name: "IndiGo Group Travel Desk",
    category: "flights",
    country: "India",
    city: "Gurugram",
    contact_person: "Ms. Richa Gupta (Group Bookings)",
    phone: "+91 124 617 3838",
    email: "groups@goindigo.in",
    whatsapp: "911246173838",
    rating: 4.0,
    notes: "Best for economy group travel. Mumbai-Hong Kong direct. Good cancellation policy for 15+ pax.",
    services: ["Group Air Tickets", "Connecting Flights India-HK", "Group Check-in Coordination"],
    status: "active",
  },
  {
    id: "VND-005",
    name: "Silk Route Guides — Guangzhou",
    category: "guide",
    country: "China",
    city: "Guangzhou",
    contact_person: "Ms. Jenny Li",
    phone: "+86 135 0021 9999",
    email: "jenny@silkrouteguides.cn",
    whatsapp: "8613500219999",
    rating: 4.8,
    notes: "Bilingual guide (Mandarin + Hindi/English). Specialist in Canton Fair navigation and wholesale market guidance for Indian buyers. 8+ years experience.",
    services: ["Canton Fair Escort & Navigation", "Wholesale Market Guide", "Mandarin Interpretation", "Supplier Negotiation Support", "Cultural Briefings"],
    status: "active",
  },
  {
    id: "VND-006",
    name: "Royal Star Travel Insurance",
    category: "insurance",
    country: "India",
    city: "Mumbai",
    contact_person: "Mr. Sunil Mehta",
    phone: "+91 98330 56789",
    email: "sunil@royalstarinsurance.com",
    whatsapp: "919833056789",
    rating: 4.4,
    notes: "Group travel insurance for China tours. Covers medical, trip cancellation, baggage loss. Best rates for 10+ pax groups.",
    services: ["Group Medical Insurance", "Trip Cancellation Cover", "Baggage Loss Cover", "Emergency Evacuation", "24/7 Claim Helpline"],
    status: "active",
  },
  {
    id: "VND-007",
    name: "Guangdong Coach Services",
    category: "transport",
    country: "China",
    city: "Guangzhou",
    contact_person: "Mr. David Wong",
    phone: "+86 137 0080 6688",
    email: "david@gdcoachservices.cn",
    whatsapp: "8613700806688",
    rating: 4.5,
    notes: "Backup transport vendor for large groups. 50-seater coaches for Canton Fair and factory trips. Air-conditioned, GPS tracked.",
    services: ["Airport Transfers (Large Groups)", "Canton Fair Shuttle", "Factory Visit Transport", "City Sightseeing Coaches"],
    status: "active",
  },
  {
    id: "VND-008",
    name: "HK Star Hospitality Services",
    category: "ground_partner",
    country: "China",
    city: "Hong Kong",
    contact_person: "Ms. Cathy Chan",
    phone: "+852 9123 4567",
    email: "cathy@hkstarhospitality.com",
    whatsapp: "85291234567",
    rating: 4.7,
    notes: "Hong Kong ground operations — transfers, local guides, harbour cruises, city tours. Handles all HK operations for our HK-Canton exclusive package.",
    services: ["Airport Transfers HK", "City Tour Guide", "Harbour Cruise Booking", "Dim Sum Restaurant Reservations", "Shopping Escort", "Kowloon & HK Island Tours"],
    status: "active",
  },
];
