import type { SupransService, SupransLeadStatus, LeadSource, LeadPriority, SupransLead, SupransService_ } from "@/types/suprans";
export type { SupransService, SupransLeadStatus, LeadSource, LeadPriority, SupransLead, SupransService_ };

export const VERTICAL_SERVICE_MAP: Record<SupransService, string> = {
  "company-formation": "legalnations",
  "tour-booking": "goyotours",
  "ecommerce-setup": "usdrop",
  "event-management": "eventhub",
  "hr-consulting": "hrms",
  "franchise": "ets",
};

export const VERTICAL_REP_MAP: Record<string, string[]> = {
  legalnations: ["Priya Sharma", "Rahul Mehta", "Ananya Singh"],
  goyotours: ["Vikram Patel", "Kavitha Nair", "Arjun Das"],
  usdrop: ["Ritu Agarwal", "Mohit Kapoor", "Sneha Iyer"],
  eventhub: ["Deepak Rao", "Sunita Joshi", "Kiran Kumar"],
  hrms: ["Lakshmi Reddy", "Arun Pillai", "Meena Thomas"],
  ets: ["Sanjay Malhotra", "Neha Gupta", "Vivek Sharma"],
};

export const supransServices: SupransService_[] = [
  { id: "company-formation", label: "Company Formation", vertical: "legalnations", verticalLabel: "LegalNations", color: "#225AEA" },
  { id: "tour-booking", label: "Tour Booking", vertical: "goyotours", verticalLabel: "GoyoTours", color: "#E91E63" },
  { id: "ecommerce-setup", label: "E-Commerce Setup", vertical: "usdrop", verticalLabel: "USDrop AI", color: "#F34147" },
  { id: "event-management", label: "Event Management", vertical: "eventhub", verticalLabel: "EventHub", color: "#7C3AED" },
  { id: "hr-consulting", label: "HR Consulting", vertical: "hrms", verticalLabel: "HRMS", color: "#0EA5E9" },
  { id: "franchise", label: "Franchise", vertical: "ets", verticalLabel: "EazyToSell", color: "#F97316" },
];

export const supransLeads: SupransLead[] = [
  {
    id: "sl-001",
    name: "Rajesh Kumar",
    phone: "+91 98765 43210",
    email: "rajesh.kumar@techstartup.in",
    service: "company-formation",
    source: "website",
    status: "new",
    notes: "",
    createdAt: "2026-02-28T08:30:00Z",
    priority: "high",
  },
  {
    id: "sl-002",
    name: "Priya Patel",
    phone: "+91 87654 32109",
    email: "priya.patel@gmail.com",
    service: "tour-booking",
    source: "instagram",
    status: "new",
    notes: "",
    createdAt: "2026-02-28T09:15:00Z",
    priority: "medium",
  },
  {
    id: "sl-003",
    name: "Amit Shah",
    phone: "+91 76543 21098",
    email: "amit.shah@dropship.co",
    service: "ecommerce-setup",
    source: "linkedin",
    status: "new",
    notes: "",
    createdAt: "2026-02-28T10:00:00Z",
    priority: "high",
  },
  {
    id: "sl-004",
    name: "Sunita Rao",
    phone: "+91 65432 10987",
    email: "sunita.rao@events.com",
    service: "event-management",
    source: "referral",
    status: "new",
    notes: "",
    createdAt: "2026-02-27T14:30:00Z",
    priority: "medium",
  },
  {
    id: "sl-005",
    name: "Vikram Singh",
    phone: "+91 54321 09876",
    email: "vikram.singh@hrfirm.in",
    service: "hr-consulting",
    source: "google-ads",
    status: "new",
    notes: "",
    createdAt: "2026-02-27T11:45:00Z",
    priority: "low",
  },
  {
    id: "sl-006",
    name: "Kavitha Menon",
    phone: "+91 43210 98765",
    email: "kavitha.menon@franchise.biz",
    service: "franchise",
    source: "walk-in",
    status: "new",
    notes: "",
    createdAt: "2026-02-27T09:00:00Z",
    priority: "high",
  },
  {
    id: "sl-007",
    name: "Deepak Joshi",
    phone: "+91 32109 87654",
    email: "deepak.joshi@startup.in",
    service: "company-formation",
    source: "whatsapp",
    status: "new",
    notes: "",
    createdAt: "2026-02-26T16:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-008",
    name: "Ananya Krishnan",
    phone: "+91 21098 76543",
    email: "ananya.k@touragency.com",
    service: "tour-booking",
    source: "instagram",
    status: "new",
    notes: "",
    createdAt: "2026-02-26T13:30:00Z",
    priority: "low",
  },
  {
    id: "sl-009",
    name: "Mohit Aggarwal",
    phone: "+91 90876 54321",
    email: "mohit.agg@retail.co",
    service: "ecommerce-setup",
    source: "website",
    status: "validated",
    notes: "Confirmed interested in Amazon FBA + Shopify setup. Budget ₹2L.",
    createdAt: "2026-02-25T10:00:00Z",
    priority: "high",
  },
  {
    id: "sl-010",
    name: "Neha Gupta",
    phone: "+91 80765 43210",
    email: "neha.gupta@eventco.in",
    service: "event-management",
    source: "referral",
    status: "validated",
    notes: "Referred by Arun Pillai. Looking to manage corporate networking events.",
    createdAt: "2026-02-25T09:00:00Z",
    priority: "high",
  },
  {
    id: "sl-011",
    name: "Sanjay Mehta",
    phone: "+91 70654 32109",
    email: "sanjay.mehta@lawfirm.com",
    service: "company-formation",
    source: "linkedin",
    status: "validated",
    notes: "Wants LLC formation in Delaware. Has existing India company.",
    createdAt: "2026-02-24T14:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-012",
    name: "Lakshmi Iyer",
    phone: "+91 60543 21098",
    email: "lakshmi.iyer@hrconsult.in",
    service: "hr-consulting",
    source: "google-ads",
    status: "validated",
    notes: "SME with 50 employees. Needs payroll + compliance setup.",
    createdAt: "2026-02-24T11:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-013",
    name: "Arjun Nair",
    phone: "+91 50432 10987",
    email: "arjun.nair@tourbiz.com",
    service: "tour-booking",
    source: "website",
    status: "validated",
    notes: "Group booking for 40 people — China industrial tour in April.",
    createdAt: "2026-02-23T15:30:00Z",
    priority: "high",
  },
  {
    id: "sl-014",
    name: "Ritu Sharma",
    phone: "+91 40321 09876",
    email: "ritu.sharma@foodchain.in",
    service: "franchise",
    source: "walk-in",
    status: "validated",
    notes: "Looking at F&B franchise. Has investment ready.",
    createdAt: "2026-02-23T10:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-015",
    name: "Arun Pillai",
    phone: "+91 30210 98765",
    email: "arun.pillai@techco.in",
    service: "ecommerce-setup",
    source: "referral",
    status: "enriched",
    notes: "Interested in Shopify + warehousing. Recommended: USDrop AI (Sales).",
    assignedVertical: "usdrop",
    enrichedAt: "2026-02-22T12:00:00Z",
    createdAt: "2026-02-20T10:00:00Z",
    priority: "high",
  },
  {
    id: "sl-016",
    name: "Meena Thomas",
    phone: "+91 20109 87654",
    email: "meena.thomas@events.in",
    service: "event-management",
    source: "instagram",
    status: "enriched",
    notes: "Wedding events coordinator. Recommended: EventHub.",
    assignedVertical: "eventhub",
    enrichedAt: "2026-02-22T10:00:00Z",
    createdAt: "2026-02-19T09:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-017",
    name: "Kiran Reddy",
    phone: "+91 98210 76543",
    email: "kiran.reddy@startup.com",
    service: "company-formation",
    source: "linkedin",
    status: "enriched",
    notes: "SaaS startup — needs Wyoming LLC. Recommended: LegalNations.",
    assignedVertical: "legalnations",
    enrichedAt: "2026-02-21T14:00:00Z",
    createdAt: "2026-02-18T11:00:00Z",
    priority: "high",
  },
  {
    id: "sl-018",
    name: "Divya Balan",
    phone: "+91 88109 65432",
    email: "divya.balan@travel.co",
    service: "tour-booking",
    source: "whatsapp",
    status: "enriched",
    notes: "Luxury China itinerary for 6 people. Recommended: GoyoTours.",
    assignedVertical: "goyotours",
    enrichedAt: "2026-02-20T16:00:00Z",
    createdAt: "2026-02-17T08:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-019",
    name: "Suresh Babu",
    phone: "+91 78098 54321",
    email: "suresh.babu@franchise.in",
    service: "franchise",
    source: "website",
    status: "enriched",
    notes: "Retail franchise model. Recommended: EazyToSell.",
    assignedVertical: "ets",
    enrichedAt: "2026-02-19T12:00:00Z",
    createdAt: "2026-02-16T10:00:00Z",
    priority: "low",
  },
  {
    id: "sl-020",
    name: "Pooja Kapoor",
    phone: "+91 68087 43210",
    email: "pooja.kapoor@corp.in",
    service: "hr-consulting",
    source: "google-ads",
    status: "assigned",
    notes: "Mid-size company. Needs HR audit + policy revision.",
    assignedVertical: "hrms",
    assignedRep: "Lakshmi Reddy",
    enrichedAt: "2026-02-18T09:00:00Z",
    assignedAt: "2026-02-19T10:00:00Z",
    createdAt: "2026-02-15T08:00:00Z",
    priority: "high",
  },
  {
    id: "sl-021",
    name: "Rahul Verma",
    phone: "+91 58076 32109",
    email: "rahul.verma@ecomm.co",
    service: "ecommerce-setup",
    source: "referral",
    status: "assigned",
    notes: "Dropshipping startup. Assigned to USDrop AI sales team.",
    assignedVertical: "usdrop",
    assignedRep: "Ritu Agarwal",
    enrichedAt: "2026-02-17T11:00:00Z",
    assignedAt: "2026-02-18T09:00:00Z",
    createdAt: "2026-02-14T10:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-022",
    name: "Anjali Das",
    phone: "+91 48065 21098",
    email: "anjali.das@eventplanner.com",
    service: "event-management",
    source: "instagram",
    status: "assigned",
    notes: "Corporate events. Assigned to EventHub ops team.",
    assignedVertical: "eventhub",
    assignedRep: "Deepak Rao",
    enrichedAt: "2026-02-16T14:00:00Z",
    assignedAt: "2026-02-17T10:00:00Z",
    createdAt: "2026-02-13T09:00:00Z",
    priority: "high",
  },
  {
    id: "sl-023",
    name: "Vivek Nambiar",
    phone: "+91 38054 10987",
    email: "vivek.nambiar@tourgroup.com",
    service: "tour-booking",
    source: "website",
    status: "assigned",
    notes: "B2B travel agent partnership. Assigned to GoyoTours BD.",
    assignedVertical: "goyotours",
    assignedRep: "Vikram Patel",
    enrichedAt: "2026-02-15T10:00:00Z",
    assignedAt: "2026-02-16T09:00:00Z",
    createdAt: "2026-02-12T11:00:00Z",
    priority: "medium",
  },
  {
    id: "sl-024",
    name: "Geeta Krishnamurthy",
    phone: "+91 28043 09876",
    email: "geeta.k@legalfirm.in",
    service: "company-formation",
    source: "linkedin",
    status: "converted",
    notes: "LLC formed. Client signed — conversion successful.",
    assignedVertical: "legalnations",
    assignedRep: "Priya Sharma",
    enrichedAt: "2026-02-10T10:00:00Z",
    assignedAt: "2026-02-11T09:00:00Z",
    createdAt: "2026-02-08T08:00:00Z",
    priority: "high",
  },
  {
    id: "sl-025",
    name: "Naresh Malhotra",
    phone: "+91 18032 98765",
    email: "naresh.m@retailgroup.in",
    service: "franchise",
    source: "referral",
    status: "converted",
    notes: "Franchise agreement signed. ETS onboarding in progress.",
    assignedVertical: "ets",
    assignedRep: "Sanjay Malhotra",
    enrichedAt: "2026-02-09T12:00:00Z",
    assignedAt: "2026-02-10T09:00:00Z",
    createdAt: "2026-02-05T10:00:00Z",
    priority: "high",
  },
];

export const supransReportTemplates = [
  {
    id: "sr-001",
    name: "Daily Lead Intake",
    category: "Leads",
    frequency: "Daily",
    lastSubmitted: "2026-02-28",
    submittedBy: "Kavitha Nair",
    status: "submitted" as const,
  },
  {
    id: "sr-002",
    name: "Weekly Assignment Summary",
    category: "Assignments",
    frequency: "Weekly",
    lastSubmitted: "2026-02-24",
    submittedBy: "Priya Sharma",
    status: "submitted" as const,
  },
];
