import type { ElementType } from "react";

import type { LmsCourseDetail, LmsModule, LmsLesson, LmsStudent, LmsReview } from "@/types/lms";
export type { LmsCourseDetail, LmsModule, LmsLesson, LmsStudent, LmsReview };


export const courseDetails: Record<string, LmsCourseDetail> = {
  "CRS-001": {
    id: "CRS-001",
    title: "Dropshipping Fundamentals",
    category: "Getting Started",
    status: "published",
    instructor: "Lakshay Takkar",
    description: "Master the fundamentals of dropshipping from product sourcing to store setup. This comprehensive course covers everything you need to know to launch your first profitable dropshipping business, including supplier selection, niche research, and order fulfillment strategies.",
    duration: "6h 30m",
    level: "Beginner",
    language: "English",
    enrolled: 2456,
    completionRate: 78,
    rating: 4.7,
    reviewCount: 412,
    lessonsCount: 12,
    lastUpdated: "2025-02-15",
    price: 49.99,
    modules: [
      {
        id: "MOD-001",
        title: "Introduction to Dropshipping",
        description: "Learn the basics of the dropshipping business model",
        lessonsCount: 3,
        duration: "1h 15m",
        lessons: [
          { id: "LES-001", title: "What is Dropshipping?", type: "video", duration: "18m", isPreview: true },
          { id: "LES-002", title: "How the Supply Chain Works", type: "video", duration: "22m", isPreview: false },
          { id: "LES-003", title: "Quiz: Dropshipping Basics", type: "quiz", duration: "15m", isPreview: false },
        ],
      },
      {
        id: "MOD-002",
        title: "Niche Selection & Market Research",
        description: "Find profitable niches and validate product ideas",
        lessonsCount: 3,
        duration: "1h 45m",
        lessons: [
          { id: "LES-004", title: "Finding Your Niche", type: "video", duration: "25m", isPreview: true },
          { id: "LES-005", title: "Market Validation Techniques", type: "article", duration: "20m", isPreview: false },
          { id: "LES-006", title: "Competitor Analysis Framework", type: "video", duration: "30m", isPreview: false },
        ],
      },
      {
        id: "MOD-003",
        title: "Supplier Sourcing",
        description: "Find and vet reliable suppliers for your products",
        lessonsCount: 3,
        duration: "1h 30m",
        lessons: [
          { id: "LES-007", title: "AliExpress vs CJDropshipping", type: "video", duration: "20m", isPreview: false },
          { id: "LES-008", title: "Evaluating Supplier Quality", type: "video", duration: "28m", isPreview: false },
          { id: "LES-009", title: "Supplier Communication Templates", type: "article", duration: "15m", isPreview: false },
        ],
      },
      {
        id: "MOD-004",
        title: "Store Setup & Launch",
        description: "Build and launch your first store from scratch",
        lessonsCount: 3,
        duration: "2h 00m",
        lessons: [
          { id: "LES-010", title: "Shopify Store Configuration", type: "video", duration: "35m", isPreview: false },
          { id: "LES-011", title: "Product Page Optimization", type: "exercise", duration: "40m", isPreview: false },
          { id: "LES-012", title: "Launch Checklist", type: "article", duration: "15m", isPreview: false },
        ],
      },
    ],
    students: [
      { id: "STU-001", name: "Alex Johnson", email: "alex@gmail.com", enrolledDate: "2025-01-12", progress: 92, lastActive: "2 hours ago", lessonsCompleted: 11, totalLessons: 12 },
      { id: "STU-002", name: "Maria Santos", email: "maria@outlook.com", enrolledDate: "2025-01-18", progress: 75, lastActive: "1 day ago", lessonsCompleted: 9, totalLessons: 12 },
      { id: "STU-003", name: "James Lee", email: "james@yahoo.com", enrolledDate: "2025-01-25", progress: 58, lastActive: "3 hours ago", lessonsCompleted: 7, totalLessons: 12 },
      { id: "STU-004", name: "Fatima Hassan", email: "fatima@gmail.com", enrolledDate: "2025-02-01", progress: 42, lastActive: "5 days ago", lessonsCompleted: 5, totalLessons: 12 },
      { id: "STU-005", name: "Ryan Chen", email: "ryan@protonmail.com", enrolledDate: "2025-02-05", progress: 33, lastActive: "12 hours ago", lessonsCompleted: 4, totalLessons: 12 },
      { id: "STU-006", name: "Priya Gupta", email: "priya@gmail.com", enrolledDate: "2025-02-10", progress: 25, lastActive: "1 day ago", lessonsCompleted: 3, totalLessons: 12 },
      { id: "STU-007", name: "Tom Bradley", email: "tom@outlook.com", enrolledDate: "2025-02-14", progress: 17, lastActive: "4 days ago", lessonsCompleted: 2, totalLessons: 12 },
      { id: "STU-008", name: "Sophie Dubois", email: "sophie@gmail.com", enrolledDate: "2025-02-18", progress: 8, lastActive: "6 hours ago", lessonsCompleted: 1, totalLessons: 12 },
    ],
    reviews: [
      { id: "REV-001", studentName: "Alex Johnson", rating: 5, comment: "Excellent course! Lakshay explains everything clearly. I launched my first store within a week of finishing this course and already made my first sale.", date: "2025-02-20", helpful: 34 },
      { id: "REV-002", studentName: "Maria Santos", rating: 4, comment: "Very comprehensive introduction to dropshipping. The supplier sourcing module was particularly valuable. Would love more advanced content.", date: "2025-02-18", helpful: 21 },
      { id: "REV-003", studentName: "James Lee", rating: 5, comment: "Best dropshipping course I have taken. The practical exercises and templates make it easy to follow along and implement what you learn.", date: "2025-02-15", helpful: 18 },
      { id: "REV-004", studentName: "Priya Gupta", rating: 4, comment: "Good content overall. The niche selection module helped me avoid a bad market. Some videos could be more concise though.", date: "2025-02-12", helpful: 12 },
      { id: "REV-005", studentName: "Ryan Chen", rating: 5, comment: "Lakshay is an amazing teacher. The step-by-step approach made it so easy to understand. Highly recommended for beginners!", date: "2025-02-10", helpful: 28 },
      { id: "REV-006", studentName: "Tom Bradley", rating: 3, comment: "Decent course but I felt some sections were too basic. Good for complete beginners but not much for those with some experience.", date: "2025-02-08", helpful: 8 },
    ],
  },
  "CRS-002": {
    id: "CRS-002",
    title: "Finding Winning Products",
    category: "Product Research",
    status: "published",
    instructor: "Lakshay Takkar",
    description: "Learn the exact strategies and tools used to find products that sell like crazy. This course reveals how to identify trending products, validate demand, and spot opportunities before your competitors do.",
    duration: "4h 20m",
    level: "Intermediate",
    language: "English",
    enrolled: 1890,
    completionRate: 65,
    rating: 4.5,
    reviewCount: 287,
    lessonsCount: 8,
    lastUpdated: "2025-02-10",
    price: 39.99,
    modules: [
      {
        id: "MOD-005",
        title: "Product Research Foundations",
        description: "Core principles of finding profitable products",
        lessonsCount: 2,
        duration: "55m",
        lessons: [
          { id: "LES-013", title: "What Makes a Product a Winner?", type: "video", duration: "25m", isPreview: true },
          { id: "LES-014", title: "Trend Analysis Tools", type: "video", duration: "30m", isPreview: false },
        ],
      },
      {
        id: "MOD-006",
        title: "Research Methods",
        description: "Proven methods to discover high-potential products",
        lessonsCount: 3,
        duration: "1h 40m",
        lessons: [
          { id: "LES-015", title: "Social Media Spying Techniques", type: "video", duration: "30m", isPreview: false },
          { id: "LES-016", title: "Using AliExpress Data", type: "video", duration: "35m", isPreview: false },
          { id: "LES-017", title: "Product Validation Exercise", type: "exercise", duration: "25m", isPreview: false },
        ],
      },
      {
        id: "MOD-007",
        title: "Advanced Strategies",
        description: "Scale your product research process",
        lessonsCount: 3,
        duration: "1h 45m",
        lessons: [
          { id: "LES-018", title: "Building a Product Pipeline", type: "video", duration: "28m", isPreview: false },
          { id: "LES-019", title: "Seasonal Product Strategies", type: "article", duration: "20m", isPreview: false },
          { id: "LES-020", title: "Final Assessment", type: "quiz", duration: "15m", isPreview: false },
        ],
      },
    ],
    students: [
      { id: "STU-009", name: "Diana Price", email: "diana@gmail.com", enrolledDate: "2025-01-20", progress: 88, lastActive: "1 hour ago", lessonsCompleted: 7, totalLessons: 8 },
      { id: "STU-010", name: "Kevin Park", email: "kevin@outlook.com", enrolledDate: "2025-01-28", progress: 63, lastActive: "2 days ago", lessonsCompleted: 5, totalLessons: 8 },
      { id: "STU-011", name: "Laura Martinez", email: "laura@gmail.com", enrolledDate: "2025-02-03", progress: 50, lastActive: "8 hours ago", lessonsCompleted: 4, totalLessons: 8 },
      { id: "STU-012", name: "Ahmed Raza", email: "ahmed@yahoo.com", enrolledDate: "2025-02-08", progress: 38, lastActive: "1 day ago", lessonsCompleted: 3, totalLessons: 8 },
      { id: "STU-013", name: "Emma Wilson", email: "emma@gmail.com", enrolledDate: "2025-02-12", progress: 25, lastActive: "3 days ago", lessonsCompleted: 2, totalLessons: 8 },
    ],
    reviews: [
      { id: "REV-007", studentName: "Diana Price", rating: 5, comment: "This course changed how I approach product research. Found 3 winning products within the first month!", date: "2025-02-22", helpful: 45 },
      { id: "REV-008", studentName: "Kevin Park", rating: 4, comment: "Great techniques and real examples. The social media spying module alone is worth the price.", date: "2025-02-19", helpful: 22 },
      { id: "REV-009", studentName: "Laura Martinez", rating: 5, comment: "Practical and actionable. Every lesson gives you something you can use right away.", date: "2025-02-16", helpful: 17 },
      { id: "REV-010", studentName: "Ahmed Raza", rating: 4, comment: "Solid course content. Would appreciate more case studies of actual winning products.", date: "2025-02-13", helpful: 9 },
    ],
  },
  "CRS-003": {
    id: "CRS-003",
    title: "Facebook Ads Mastery",
    category: "Marketing",
    status: "published",
    instructor: "Vikram Singh",
    description: "From setting up your first campaign to scaling with advanced strategies. Learn how to create profitable Facebook ad campaigns that drive consistent sales for your dropshipping store.",
    duration: "8h 15m",
    level: "Intermediate",
    language: "English",
    enrolled: 1234,
    completionRate: 52,
    rating: 4.3,
    reviewCount: 198,
    lessonsCount: 15,
    lastUpdated: "2025-01-28",
    price: 69.99,
    modules: [
      {
        id: "MOD-008",
        title: "Facebook Ads Basics",
        description: "Setting up your Business Manager and first campaigns",
        lessonsCount: 4,
        duration: "2h 10m",
        lessons: [
          { id: "LES-021", title: "Business Manager Setup", type: "video", duration: "25m", isPreview: true },
          { id: "LES-022", title: "Understanding Campaign Structure", type: "video", duration: "30m", isPreview: true },
          { id: "LES-023", title: "Pixel Installation & Events", type: "video", duration: "35m", isPreview: false },
          { id: "LES-024", title: "Setup Quiz", type: "quiz", duration: "10m", isPreview: false },
        ],
      },
      {
        id: "MOD-009",
        title: "Creative Strategy",
        description: "Creating ads that convert",
        lessonsCount: 4,
        duration: "2h 20m",
        lessons: [
          { id: "LES-025", title: "Ad Creative Best Practices", type: "video", duration: "28m", isPreview: false },
          { id: "LES-026", title: "Video Ad Production", type: "video", duration: "35m", isPreview: false },
          { id: "LES-027", title: "Copywriting for Ads", type: "article", duration: "20m", isPreview: false },
          { id: "LES-028", title: "Create Your First Ad", type: "exercise", duration: "30m", isPreview: false },
        ],
      },
      {
        id: "MOD-010",
        title: "Targeting & Audiences",
        description: "Find and reach your ideal customers",
        lessonsCount: 3,
        duration: "1h 30m",
        lessons: [
          { id: "LES-029", title: "Interest-Based Targeting", type: "video", duration: "25m", isPreview: false },
          { id: "LES-030", title: "Lookalike Audiences", type: "video", duration: "30m", isPreview: false },
          { id: "LES-031", title: "Retargeting Strategies", type: "video", duration: "25m", isPreview: false },
        ],
      },
      {
        id: "MOD-011",
        title: "Scaling & Optimization",
        description: "Scale winning campaigns profitably",
        lessonsCount: 4,
        duration: "2h 15m",
        lessons: [
          { id: "LES-032", title: "Reading Ad Metrics", type: "video", duration: "30m", isPreview: false },
          { id: "LES-033", title: "Horizontal vs Vertical Scaling", type: "video", duration: "35m", isPreview: false },
          { id: "LES-034", title: "Budget Management", type: "video", duration: "25m", isPreview: false },
          { id: "LES-035", title: "Final Exam", type: "quiz", duration: "20m", isPreview: false },
        ],
      },
    ],
    students: [
      { id: "STU-014", name: "Chris Anderson", email: "chris@gmail.com", enrolledDate: "2025-01-05", progress: 80, lastActive: "4 hours ago", lessonsCompleted: 12, totalLessons: 15 },
      { id: "STU-015", name: "Nina Patel", email: "nina@outlook.com", enrolledDate: "2025-01-15", progress: 60, lastActive: "1 day ago", lessonsCompleted: 9, totalLessons: 15 },
      { id: "STU-016", name: "Marcus Brown", email: "marcus@gmail.com", enrolledDate: "2025-01-22", progress: 47, lastActive: "6 hours ago", lessonsCompleted: 7, totalLessons: 15 },
      { id: "STU-017", name: "Yuki Tanaka", email: "yuki@yahoo.com", enrolledDate: "2025-02-01", progress: 33, lastActive: "2 days ago", lessonsCompleted: 5, totalLessons: 15 },
    ],
    reviews: [
      { id: "REV-011", studentName: "Chris Anderson", rating: 4, comment: "Vikram really knows Facebook Ads. The scaling module was the most valuable part for me.", date: "2025-02-20", helpful: 31 },
      { id: "REV-012", studentName: "Nina Patel", rating: 5, comment: "Finally a course that teaches Facebook Ads specifically for ecommerce. Love the practical approach!", date: "2025-02-17", helpful: 24 },
      { id: "REV-013", studentName: "Marcus Brown", rating: 4, comment: "Good course overall. Some content feels a bit dated with recent iOS changes but fundamentals are solid.", date: "2025-02-14", helpful: 15 },
    ],
  },
  "CRS-004": {
    id: "CRS-004",
    title: "Shopify Store Setup A-Z",
    category: "Store Building",
    status: "published",
    instructor: "Karan Gupta",
    description: "Build a professional Shopify store that converts visitors into buyers. This hands-on course walks you through every step of creating a high-converting dropshipping store, from theme selection to checkout optimization.",
    duration: "5h 45m",
    level: "Beginner",
    language: "English",
    enrolled: 3120,
    completionRate: 84,
    rating: 4.8,
    reviewCount: 523,
    lessonsCount: 10,
    lastUpdated: "2025-02-20",
    price: 44.99,
    modules: [
      {
        id: "MOD-012",
        title: "Store Foundation",
        description: "Account setup and store configuration",
        lessonsCount: 3,
        duration: "1h 30m",
        lessons: [
          { id: "LES-036", title: "Creating Your Shopify Account", type: "video", duration: "15m", isPreview: true },
          { id: "LES-037", title: "Theme Selection & Setup", type: "video", duration: "35m", isPreview: true },
          { id: "LES-038", title: "Essential Apps to Install", type: "video", duration: "25m", isPreview: false },
        ],
      },
      {
        id: "MOD-013",
        title: "Product Pages That Sell",
        description: "Create compelling product listings",
        lessonsCount: 3,
        duration: "1h 45m",
        lessons: [
          { id: "LES-039", title: "Product Descriptions That Convert", type: "video", duration: "30m", isPreview: false },
          { id: "LES-040", title: "Product Photography Tips", type: "video", duration: "25m", isPreview: false },
          { id: "LES-041", title: "Build Your First Product Page", type: "exercise", duration: "35m", isPreview: false },
        ],
      },
      {
        id: "MOD-014",
        title: "Checkout & Payments",
        description: "Optimize your checkout flow",
        lessonsCount: 2,
        duration: "1h 10m",
        lessons: [
          { id: "LES-042", title: "Payment Gateway Setup", type: "video", duration: "25m", isPreview: false },
          { id: "LES-043", title: "Checkout Optimization", type: "video", duration: "30m", isPreview: false },
        ],
      },
      {
        id: "MOD-015",
        title: "Launch & Go Live",
        description: "Final preparations and launch day",
        lessonsCount: 2,
        duration: "1h 20m",
        lessons: [
          { id: "LES-044", title: "Pre-Launch Checklist", type: "article", duration: "20m", isPreview: false },
          { id: "LES-045", title: "Your First Week Plan", type: "video", duration: "30m", isPreview: false },
        ],
      },
    ],
    students: [
      { id: "STU-018", name: "Sarah Mitchell", email: "sarah@gmail.com", enrolledDate: "2025-01-03", progress: 100, lastActive: "Completed", lessonsCompleted: 10, totalLessons: 10 },
      { id: "STU-019", name: "David Kim", email: "david@outlook.com", enrolledDate: "2025-01-10", progress: 90, lastActive: "3 hours ago", lessonsCompleted: 9, totalLessons: 10 },
      { id: "STU-020", name: "Rachel Green", email: "rachel@gmail.com", enrolledDate: "2025-01-20", progress: 70, lastActive: "1 day ago", lessonsCompleted: 7, totalLessons: 10 },
      { id: "STU-021", name: "Omar Farooq", email: "omar@yahoo.com", enrolledDate: "2025-01-28", progress: 50, lastActive: "5 hours ago", lessonsCompleted: 5, totalLessons: 10 },
      { id: "STU-022", name: "Lisa Wang", email: "lisa@gmail.com", enrolledDate: "2025-02-05", progress: 30, lastActive: "2 days ago", lessonsCompleted: 3, totalLessons: 10 },
      { id: "STU-023", name: "Jake Thompson", email: "jake@protonmail.com", enrolledDate: "2025-02-12", progress: 10, lastActive: "8 hours ago", lessonsCompleted: 1, totalLessons: 10 },
    ],
    reviews: [
      { id: "REV-014", studentName: "Sarah Mitchell", rating: 5, comment: "Karan makes everything so simple. I had my store live within 3 days of starting this course!", date: "2025-02-22", helpful: 56 },
      { id: "REV-015", studentName: "David Kim", rating: 5, comment: "The most practical Shopify course out there. Every lesson is actionable and well-structured.", date: "2025-02-19", helpful: 38 },
      { id: "REV-016", studentName: "Rachel Green", rating: 4, comment: "Great course for beginners. The theme setup and product page modules were incredibly helpful.", date: "2025-02-16", helpful: 22 },
      { id: "REV-017", studentName: "Omar Farooq", rating: 5, comment: "Clear, concise, and comprehensive. Exactly what I needed to get started with Shopify.", date: "2025-02-13", helpful: 19 },
      { id: "REV-018", studentName: "Lisa Wang", rating: 4, comment: "Well-organized content. Would love a follow-up course on advanced Shopify customization.", date: "2025-02-10", helpful: 14 },
    ],
  },
};

export function getCourseDetail(id: string): LmsCourseDetail | undefined {
  return courseDetails[id];
}
