import type {
  FormationClient,
  StageChecklist,
  ClientDocument,
  ComplianceItem,
  FormationTask,
  Escalation,
  TeamMember,
  FormationMetric,
  DocumentTemplate,
} from "@shared/schema";

export { stageDefinitions } from "@shared/schema";

export const teamMembers: TeamMember[] = [
  { id: "TM-001", name: "Sneha Patel", role: "ops-manager", activeClients: 8, completedThisMonth: 4, avgCompletionDays: 18, email: "sneha@legalnations.com" },
  { id: "TM-002", name: "Karan Gupta", role: "ops-manager", activeClients: 7, completedThisMonth: 5, avgCompletionDays: 16, email: "karan@legalnations.com" },
  { id: "TM-003", name: "Vikram Singh", role: "executive", activeClients: 5, completedThisMonth: 3, avgCompletionDays: 20, email: "vikram@legalnations.com" },
  { id: "TM-004", name: "Ananya Reddy", role: "executive", activeClients: 4, completedThisMonth: 2, avgCompletionDays: 22, email: "ananya@legalnations.com" },
  { id: "TM-005", name: "Rohan Joshi", role: "executive", activeClients: 3, completedThisMonth: 4, avgCompletionDays: 15, email: "rohan@legalnations.com" },
  { id: "TM-006", name: "Lakshay Takkar", role: "admin", activeClients: 0, completedThisMonth: 0, avgCompletionDays: 0, email: "lakshay@legalnations.com" },
];

export const formationClients: FormationClient[] = [
  { id: "CLT-001", clientName: "James Richardson", companyName: "Richardson Tech LLC", companyType: "LLC", state: "Delaware", packageType: "Premium", assignedManager: "Sneha Patel", currentStage: 5, priority: "high", riskFlag: "on-track", startDate: "2025-01-15", expectedCompletion: "2025-02-28", notes: "Fast-track requested, banking in progress", email: "james@richardsontech.com", phone: "+1 (555) 234-5678" },
  { id: "CLT-002", clientName: "Maria Santos", companyName: "Santos Digital Corp", companyType: "Corp", state: "Wyoming", packageType: "Standard", assignedManager: "Karan Gupta", currentStage: 3, priority: "medium", riskFlag: "on-track", startDate: "2025-01-22", expectedCompletion: "2025-03-10", notes: "EIN application submitted, awaiting IRS response", email: "maria@santosdigital.com", phone: "+1 (555) 345-6789" },
  { id: "CLT-003", clientName: "Ahmed Hassan", companyName: "Hassan Imports LLC", companyType: "LLC", state: "Texas", packageType: "Premium", assignedManager: "Sneha Patel", currentStage: 4, priority: "high", riskFlag: "delayed", startDate: "2025-01-10", expectedCompletion: "2025-02-25", notes: "BOI filing delayed due to missing beneficial owner info", email: "ahmed@hassanimports.com", phone: "+1 (555) 456-7890" },
  { id: "CLT-004", clientName: "Sarah Kim", companyName: "Kim Consulting LLC", companyType: "LLC", state: "California", packageType: "Basic", assignedManager: "Vikram Singh", currentStage: 1, priority: "low", riskFlag: "on-track", startDate: "2025-02-10", expectedCompletion: "2025-03-25", notes: "Intake in progress, waiting for passport copy", email: "sarah@kimconsulting.com", phone: "+1 (555) 567-8901" },
  { id: "CLT-005", clientName: "Roberto Martinez", companyName: "Martinez Ventures Inc", companyType: "Corp", state: "Florida", packageType: "Premium", assignedManager: "Karan Gupta", currentStage: 6, priority: "medium", riskFlag: "on-track", startDate: "2024-12-20", expectedCompletion: "2025-02-15", notes: "Completion stage — finalizing handover docs", email: "roberto@martinezventures.com", phone: "+1 (555) 678-9012" },
  { id: "CLT-006", clientName: "Priya Deshmukh", companyName: "Deshmukh Exports LLC", companyType: "LLC", state: "Delaware", packageType: "Standard", assignedManager: "Ananya Reddy", currentStage: 2, priority: "medium", riskFlag: "on-track", startDate: "2025-02-01", expectedCompletion: "2025-03-15", notes: "Articles filed with Delaware SOS", email: "priya@deshmukhexports.com", phone: "+91 98765 12345" },
  { id: "CLT-007", clientName: "David Chen", companyName: "Chen Tech Solutions LLC", companyType: "LLC", state: "Nevada", packageType: "Premium", assignedManager: "Sneha Patel", currentStage: 3, priority: "high", riskFlag: "at-risk", startDate: "2025-01-05", expectedCompletion: "2025-02-20", notes: "IRS EIN application rejected — resubmission required", email: "david@chentechsolutions.com", phone: "+1 (555) 789-0123" },
  { id: "CLT-008", clientName: "Fatima Al-Rashid", companyName: "Al-Rashid Trading LLC", companyType: "LLC", state: "Wyoming", packageType: "Standard", assignedManager: "Rohan Joshi", currentStage: 0, priority: "medium", riskFlag: "on-track", startDate: "2025-02-20", expectedCompletion: "2025-04-05", notes: "Payment received, package assigned, intake pending", email: "fatima@alrashidtrading.com", phone: "+971 50 123 4567" },
  { id: "CLT-009", clientName: "Michael O'Brien", companyName: "O'Brien Logistics Corp", companyType: "Corp", state: "New York", packageType: "Premium", assignedManager: "Karan Gupta", currentStage: 5, priority: "high", riskFlag: "delayed", startDate: "2025-01-08", expectedCompletion: "2025-02-22", notes: "Bank application under review — Chase requested additional docs", email: "michael@obrienlogistics.com", phone: "+1 (555) 890-1234" },
  { id: "CLT-010", clientName: "Lisa Wang", companyName: "Wang Digital LLC", companyType: "LLC", state: "Delaware", packageType: "Basic", assignedManager: "Vikram Singh", currentStage: 1, priority: "low", riskFlag: "on-track", startDate: "2025-02-15", expectedCompletion: "2025-04-01", notes: "KYC docs being collected", email: "lisa@wangdigital.com", phone: "+1 (555) 901-2345" },
  { id: "CLT-011", clientName: "Raj Malhotra", companyName: "Malhotra Media LLC", companyType: "LLC", state: "Texas", packageType: "Standard", assignedManager: "Ananya Reddy", currentStage: 4, priority: "medium", riskFlag: "on-track", startDate: "2025-01-25", expectedCompletion: "2025-03-10", notes: "BOI filing in progress", email: "raj@malhotramedia.com", phone: "+91 98765 67890" },
  { id: "CLT-012", clientName: "Jennifer Taylor", companyName: "Taylor & Associates S-Corp", companyType: "S-Corp", state: "California", packageType: "Premium", assignedManager: "Sneha Patel", currentStage: 2, priority: "high", riskFlag: "on-track", startDate: "2025-02-05", expectedCompletion: "2025-03-20", notes: "Formation filed, S-Corp election pending", email: "jennifer@taylorassociates.com", phone: "+1 (555) 012-3456" },
  { id: "CLT-013", clientName: "Yuki Tanaka", companyName: "Tanaka Commerce LLC", companyType: "LLC", state: "Florida", packageType: "Basic", assignedManager: "Rohan Joshi", currentStage: 0, priority: "low", riskFlag: "on-track", startDate: "2025-02-22", expectedCompletion: "2025-04-10", notes: "New client, payment confirmed today", email: "yuki@tanakacommerce.com", phone: "+81 90 1234 5678" },
  { id: "CLT-014", clientName: "Carlos Mendez", companyName: "Mendez Holdings LLC", companyType: "LLC", state: "Wyoming", packageType: "Standard", assignedManager: "Karan Gupta", currentStage: 6, priority: "low", riskFlag: "on-track", startDate: "2024-12-15", expectedCompletion: "2025-02-10", notes: "Handover complete, compliance calendar shared", email: "carlos@mendezholdings.com", phone: "+1 (555) 123-4567" },
  { id: "CLT-015", clientName: "Aisha Khan", companyName: "Khan Enterprises LLC", companyType: "LLC", state: "Delaware", packageType: "Premium", assignedManager: "Vikram Singh", currentStage: 3, priority: "high", riskFlag: "at-risk", startDate: "2025-01-12", expectedCompletion: "2025-02-26", notes: "EIN follow-up overdue — IRS not responding", email: "aisha@khanenterprises.com", phone: "+92 300 123 4567" },
  { id: "CLT-016", clientName: "Tom Bradley", companyName: "Bradley Software LLC", companyType: "LLC", state: "Texas", packageType: "Standard", assignedManager: "Ananya Reddy", currentStage: 2, priority: "medium", riskFlag: "on-track", startDate: "2025-02-08", expectedCompletion: "2025-03-22", notes: "Articles submitted to Texas SOS", email: "tom@bradleysoftware.com", phone: "+1 (555) 234-5679" },
  { id: "CLT-017", clientName: "Deepak Sharma", companyName: "Sharma Global LLC", companyType: "LLC", state: "Nevada", packageType: "Premium", assignedManager: "Rohan Joshi", currentStage: 1, priority: "medium", riskFlag: "delayed", startDate: "2025-02-03", expectedCompletion: "2025-03-18", notes: "Client unresponsive — address proof pending", email: "deepak@sharmaglobal.com", phone: "+91 98765 98765" },
  { id: "CLT-018", clientName: "Emma Wilson", companyName: "Wilson Creative Corp", companyType: "Corp", state: "New York", packageType: "Premium", assignedManager: "Sneha Patel", currentStage: 4, priority: "high", riskFlag: "on-track", startDate: "2025-01-18", expectedCompletion: "2025-03-05", notes: "BOI filing submitted to FinCEN", email: "emma@wilsoncreative.com", phone: "+1 (555) 345-6780" },
  { id: "CLT-019", clientName: "Omar Hassan", companyName: "Hassan Digital LLC", companyType: "LLC", state: "Florida", packageType: "Basic", assignedManager: "Vikram Singh", currentStage: 0, priority: "low", riskFlag: "on-track", startDate: "2025-02-25", expectedCompletion: "2025-04-12", notes: "Just converted, welcome email sent", email: "omar@hassandigital.com", phone: "+1 (555) 456-7891" },
  { id: "CLT-020", clientName: "Sophie Dubois", companyName: "Dubois Luxe LLC", companyType: "LLC", state: "Delaware", packageType: "Standard", assignedManager: "Karan Gupta", currentStage: 5, priority: "medium", riskFlag: "on-track", startDate: "2025-01-20", expectedCompletion: "2025-03-05", notes: "Stripe application submitted", email: "sophie@duboisluxe.com", phone: "+33 6 12 34 56 78" },
];

export const stageChecklists: StageChecklist[] = [
  { id: "CHK-001", clientId: "CLT-001", stage: 0, item: "Payment confirmed", responsible: "Sneha Patel", deadline: "2025-01-15", completed: true },
  { id: "CHK-002", clientId: "CLT-001", stage: 0, item: "Package selected", responsible: "Sneha Patel", deadline: "2025-01-15", completed: true },
  { id: "CHK-003", clientId: "CLT-001", stage: 0, item: "Client ID generated", responsible: "System", deadline: "2025-01-15", completed: true },
  { id: "CHK-004", clientId: "CLT-001", stage: 0, item: "Assigned to Ops Manager", responsible: "Lakshay Takkar", deadline: "2025-01-16", completed: true },
  { id: "CHK-005", clientId: "CLT-001", stage: 1, item: "Passport collected", responsible: "Sneha Patel", deadline: "2025-01-18", completed: true },
  { id: "CHK-006", clientId: "CLT-001", stage: 1, item: "Address proof collected", responsible: "Sneha Patel", deadline: "2025-01-18", completed: true },
  { id: "CHK-007", clientId: "CLT-001", stage: 1, item: "Email confirmed", responsible: "Vikram Singh", deadline: "2025-01-17", completed: true },
  { id: "CHK-008", clientId: "CLT-001", stage: 1, item: "Formation state finalized", responsible: "Sneha Patel", deadline: "2025-01-19", completed: true },
  { id: "CHK-009", clientId: "CLT-001", stage: 2, item: "Articles of incorporation drafted", responsible: "Karan Gupta", deadline: "2025-01-22", completed: true },
  { id: "CHK-010", clientId: "CLT-001", stage: 2, item: "Articles submitted to state", responsible: "Karan Gupta", deadline: "2025-01-24", completed: true },
  { id: "CHK-011", clientId: "CLT-001", stage: 2, item: "Filing receipt uploaded", responsible: "Sneha Patel", deadline: "2025-01-28", completed: true },
  { id: "CHK-012", clientId: "CLT-001", stage: 3, item: "EIN application submitted", responsible: "Ananya Reddy", deadline: "2025-02-01", completed: true },
  { id: "CHK-013", clientId: "CLT-001", stage: 3, item: "IRS confirmation received", responsible: "Ananya Reddy", deadline: "2025-02-08", completed: true },
  { id: "CHK-014", clientId: "CLT-001", stage: 3, item: "EIN letter uploaded", responsible: "Sneha Patel", deadline: "2025-02-09", completed: true },
  { id: "CHK-015", clientId: "CLT-001", stage: 4, item: "BOI form completed", responsible: "Rohan Joshi", deadline: "2025-02-12", completed: true },
  { id: "CHK-016", clientId: "CLT-001", stage: 4, item: "BOI submitted to FinCEN", responsible: "Rohan Joshi", deadline: "2025-02-13", completed: true },
  { id: "CHK-017", clientId: "CLT-001", stage: 5, item: "Bank application submitted", responsible: "Sneha Patel", deadline: "2025-02-18", completed: true },
  { id: "CHK-018", clientId: "CLT-001", stage: 5, item: "Bank account opened", responsible: "Sneha Patel", deadline: "2025-02-25", completed: false },
  { id: "CHK-019", clientId: "CLT-001", stage: 5, item: "Stripe application submitted", responsible: "Vikram Singh", deadline: "2025-02-20", completed: true },
  { id: "CHK-020", clientId: "CLT-007", stage: 0, item: "Payment confirmed", responsible: "Sneha Patel", deadline: "2025-01-05", completed: true },
  { id: "CHK-021", clientId: "CLT-007", stage: 1, item: "Passport collected", responsible: "Sneha Patel", deadline: "2025-01-08", completed: true },
  { id: "CHK-022", clientId: "CLT-007", stage: 1, item: "Address proof collected", responsible: "Vikram Singh", deadline: "2025-01-09", completed: true },
  { id: "CHK-023", clientId: "CLT-007", stage: 2, item: "Articles submitted to state", responsible: "Karan Gupta", deadline: "2025-01-14", completed: true },
  { id: "CHK-024", clientId: "CLT-007", stage: 3, item: "EIN application submitted", responsible: "Ananya Reddy", deadline: "2025-01-22", completed: true },
  { id: "CHK-025", clientId: "CLT-007", stage: 3, item: "IRS confirmation received", responsible: "Ananya Reddy", deadline: "2025-02-05", completed: false, documentAttachment: "Rejection notice" },
  { id: "CHK-026", clientId: "CLT-003", stage: 0, item: "Payment confirmed", responsible: "Sneha Patel", deadline: "2025-01-10", completed: true },
  { id: "CHK-027", clientId: "CLT-003", stage: 1, item: "Passport collected", responsible: "Sneha Patel", deadline: "2025-01-13", completed: true },
  { id: "CHK-028", clientId: "CLT-003", stage: 2, item: "Articles submitted to state", responsible: "Karan Gupta", deadline: "2025-01-18", completed: true },
  { id: "CHK-029", clientId: "CLT-003", stage: 3, item: "EIN application submitted", responsible: "Ananya Reddy", deadline: "2025-01-25", completed: true },
  { id: "CHK-030", clientId: "CLT-003", stage: 3, item: "IRS confirmation received", responsible: "Ananya Reddy", deadline: "2025-02-01", completed: true },
  { id: "CHK-031", clientId: "CLT-003", stage: 4, item: "BOI form completed", responsible: "Rohan Joshi", deadline: "2025-02-08", completed: true },
  { id: "CHK-032", clientId: "CLT-003", stage: 4, item: "BOI submitted to FinCEN", responsible: "Rohan Joshi", deadline: "2025-02-10", completed: false },
  { id: "CHK-033", clientId: "CLT-004", stage: 0, item: "Payment confirmed", responsible: "Vikram Singh", deadline: "2025-02-10", completed: true },
  { id: "CHK-034", clientId: "CLT-004", stage: 0, item: "Package selected", responsible: "Vikram Singh", deadline: "2025-02-10", completed: true },
  { id: "CHK-035", clientId: "CLT-004", stage: 1, item: "Passport collected", responsible: "Vikram Singh", deadline: "2025-02-15", completed: false },
  { id: "CHK-036", clientId: "CLT-004", stage: 1, item: "Address proof collected", responsible: "Vikram Singh", deadline: "2025-02-15", completed: true },
  { id: "CHK-037", clientId: "CLT-004", stage: 1, item: "Email confirmed", responsible: "Vikram Singh", deadline: "2025-02-12", completed: true },
  { id: "CHK-038", clientId: "CLT-015", stage: 0, item: "Payment confirmed", responsible: "Vikram Singh", deadline: "2025-01-12", completed: true },
  { id: "CHK-039", clientId: "CLT-015", stage: 1, item: "Passport collected", responsible: "Vikram Singh", deadline: "2025-01-15", completed: true },
  { id: "CHK-040", clientId: "CLT-015", stage: 2, item: "Articles submitted to state", responsible: "Karan Gupta", deadline: "2025-01-20", completed: true },
  { id: "CHK-041", clientId: "CLT-015", stage: 3, item: "EIN application submitted", responsible: "Ananya Reddy", deadline: "2025-01-28", completed: true },
  { id: "CHK-042", clientId: "CLT-015", stage: 3, item: "IRS confirmation received", responsible: "Ananya Reddy", deadline: "2025-02-10", completed: false },
  { id: "CHK-043", clientId: "CLT-017", stage: 0, item: "Payment confirmed", responsible: "Rohan Joshi", deadline: "2025-02-03", completed: true },
  { id: "CHK-044", clientId: "CLT-017", stage: 1, item: "Passport collected", responsible: "Rohan Joshi", deadline: "2025-02-08", completed: true },
  { id: "CHK-045", clientId: "CLT-017", stage: 1, item: "Address proof collected", responsible: "Rohan Joshi", deadline: "2025-02-08", completed: false },
];

export const clientDocuments: ClientDocument[] = [
  { id: "DOC-001", clientId: "CLT-001", clientName: "James Richardson", title: "Passport - James Richardson", category: "Passport", stage: 1, uploadDate: "2025-01-17", uploadedBy: "Sneha Patel", fileSize: "2.1 MB", status: "verified" },
  { id: "DOC-002", clientId: "CLT-001", clientName: "James Richardson", title: "Address Proof - Utility Bill", category: "Address Proof", stage: 1, uploadDate: "2025-01-17", uploadedBy: "Sneha Patel", fileSize: "1.4 MB", status: "verified" },
  { id: "DOC-003", clientId: "CLT-001", clientName: "James Richardson", title: "Articles of Organization - DE", category: "Articles", stage: 2, uploadDate: "2025-01-24", uploadedBy: "Karan Gupta", fileSize: "342 KB", status: "verified" },
  { id: "DOC-004", clientId: "CLT-001", clientName: "James Richardson", title: "Delaware Filing Receipt", category: "Filing Receipt", stage: 2, uploadDate: "2025-01-28", uploadedBy: "Sneha Patel", fileSize: "156 KB", status: "verified" },
  { id: "DOC-005", clientId: "CLT-001", clientName: "James Richardson", title: "EIN Confirmation Letter", category: "EIN Letter", stage: 3, uploadDate: "2025-02-08", uploadedBy: "Ananya Reddy", fileSize: "89 KB", status: "verified" },
  { id: "DOC-006", clientId: "CLT-001", clientName: "James Richardson", title: "IRS SS-4 Confirmation", category: "IRS Confirmation", stage: 3, uploadDate: "2025-02-08", uploadedBy: "Ananya Reddy", fileSize: "124 KB", status: "verified" },
  { id: "DOC-007", clientId: "CLT-001", clientName: "James Richardson", title: "BOI Report Confirmation", category: "BOI Receipt", stage: 4, uploadDate: "2025-02-13", uploadedBy: "Rohan Joshi", fileSize: "67 KB", status: "verified" },
  { id: "DOC-008", clientId: "CLT-002", clientName: "Maria Santos", title: "Passport - Maria Santos", category: "Passport", stage: 1, uploadDate: "2025-01-25", uploadedBy: "Karan Gupta", fileSize: "1.8 MB", status: "verified" },
  { id: "DOC-009", clientId: "CLT-002", clientName: "Maria Santos", title: "Articles of Incorporation - WY", category: "Articles", stage: 2, uploadDate: "2025-02-03", uploadedBy: "Karan Gupta", fileSize: "298 KB", status: "verified" },
  { id: "DOC-010", clientId: "CLT-003", clientName: "Ahmed Hassan", title: "Passport - Ahmed Hassan", category: "Passport", stage: 1, uploadDate: "2025-01-12", uploadedBy: "Sneha Patel", fileSize: "2.3 MB", status: "verified" },
  { id: "DOC-011", clientId: "CLT-003", clientName: "Ahmed Hassan", title: "Articles of Organization - TX", category: "Articles", stage: 2, uploadDate: "2025-01-18", uploadedBy: "Karan Gupta", fileSize: "312 KB", status: "verified" },
  { id: "DOC-012", clientId: "CLT-003", clientName: "Ahmed Hassan", title: "EIN Letter", category: "EIN Letter", stage: 3, uploadDate: "2025-02-01", uploadedBy: "Ananya Reddy", fileSize: "91 KB", status: "verified" },
  { id: "DOC-013", clientId: "CLT-005", clientName: "Roberto Martinez", title: "Operating Agreement", category: "Operating Agreement", stage: 6, uploadDate: "2025-02-10", uploadedBy: "Karan Gupta", fileSize: "456 KB", status: "verified" },
  { id: "DOC-014", clientId: "CLT-005", clientName: "Roberto Martinez", title: "Bank Account Details - Mercury", category: "Bank Docs", stage: 5, uploadDate: "2025-02-08", uploadedBy: "Karan Gupta", fileSize: "78 KB", status: "verified" },
  { id: "DOC-015", clientId: "CLT-006", clientName: "Priya Deshmukh", title: "Passport - Priya Deshmukh", category: "Passport", stage: 1, uploadDate: "2025-02-04", uploadedBy: "Ananya Reddy", fileSize: "1.9 MB", status: "verified" },
  { id: "DOC-016", clientId: "CLT-006", clientName: "Priya Deshmukh", title: "Articles of Organization - DE", category: "Articles", stage: 2, uploadDate: "2025-02-12", uploadedBy: "Ananya Reddy", fileSize: "338 KB", status: "uploaded" },
  { id: "DOC-017", clientId: "CLT-007", clientName: "David Chen", title: "IRS Rejection Notice", category: "IRS Confirmation", stage: 3, uploadDate: "2025-02-05", uploadedBy: "Ananya Reddy", fileSize: "112 KB", status: "uploaded" },
  { id: "DOC-018", clientId: "CLT-009", clientName: "Michael O'Brien", title: "Operating Agreement - Draft", category: "Operating Agreement", stage: 5, uploadDate: "2025-02-15", uploadedBy: "Karan Gupta", fileSize: "489 KB", status: "pending" },
  { id: "DOC-019", clientId: "CLT-012", clientName: "Jennifer Taylor", title: "Passport - Jennifer Taylor", category: "Passport", stage: 1, uploadDate: "2025-02-07", uploadedBy: "Sneha Patel", fileSize: "2.0 MB", status: "verified" },
  { id: "DOC-020", clientId: "CLT-012", clientName: "Jennifer Taylor", title: "S-Corp Election Form 2553", category: "Other", stage: 2, uploadDate: "2025-02-14", uploadedBy: "Sneha Patel", fileSize: "234 KB", status: "uploaded" },
  { id: "DOC-021", clientId: "CLT-014", clientName: "Carlos Mendez", title: "Complete Formation Package", category: "Other", stage: 6, uploadDate: "2025-02-10", uploadedBy: "Karan Gupta", fileSize: "3.2 MB", status: "verified" },
  { id: "DOC-022", clientId: "CLT-018", clientName: "Emma Wilson", title: "BOI Filing Receipt", category: "BOI Receipt", stage: 4, uploadDate: "2025-02-22", uploadedBy: "Rohan Joshi", fileSize: "72 KB", status: "uploaded" },
  { id: "DOC-023", clientId: "CLT-020", clientName: "Sophie Dubois", title: "Bank Application - Relay", category: "Bank Docs", stage: 5, uploadDate: "2025-02-20", uploadedBy: "Karan Gupta", fileSize: "145 KB", status: "pending" },
  { id: "DOC-024", clientId: "CLT-004", clientName: "Sarah Kim", title: "Address Proof - Bank Statement", category: "Address Proof", stage: 1, uploadDate: "2025-02-14", uploadedBy: "Vikram Singh", fileSize: "890 KB", status: "verified" },
  { id: "DOC-025", clientId: "CLT-011", clientName: "Raj Malhotra", title: "BOI Application Draft", category: "BOI Receipt", stage: 4, uploadDate: "2025-02-18", uploadedBy: "Ananya Reddy", fileSize: "98 KB", status: "pending" },
];

export const complianceItems: ComplianceItem[] = [
  { id: "CMP-001", clientId: "CLT-005", companyName: "Martinez Ventures Inc", type: "annual-report", dueDate: "2025-12-15", status: "upcoming", state: "Florida", notes: "First annual report due within first year" },
  { id: "CMP-002", clientId: "CLT-014", companyName: "Mendez Holdings LLC", type: "annual-report", dueDate: "2025-07-01", status: "upcoming", state: "Wyoming", notes: "Wyoming annual report due" },
  { id: "CMP-003", clientId: "CLT-001", companyName: "Richardson Tech LLC", type: "annual-report", dueDate: "2026-03-01", status: "upcoming", state: "Delaware", notes: "Delaware franchise tax due" },
  { id: "CMP-004", clientId: "CLT-005", companyName: "Martinez Ventures Inc", type: "boi-recheck", dueDate: "2026-01-15", status: "upcoming", state: "Florida", notes: "Annual BOI re-verification" },
  { id: "CMP-005", clientId: "CLT-007", companyName: "Chen Tech Solutions LLC", type: "irs-compliance", dueDate: "2025-03-15", status: "overdue", state: "Nevada", notes: "EIN resubmission required after rejection" },
  { id: "CMP-006", clientId: "CLT-003", companyName: "Hassan Imports LLC", type: "state-alert", dueDate: "2025-05-15", status: "upcoming", state: "Texas", notes: "Texas franchise tax report due" },
  { id: "CMP-007", clientId: "CLT-012", companyName: "Taylor & Associates S-Corp", type: "irs-compliance", dueDate: "2025-03-15", status: "upcoming", state: "California", notes: "S-Corp election deadline — Form 2553" },
  { id: "CMP-008", clientId: "CLT-009", companyName: "O'Brien Logistics Corp", type: "annual-report", dueDate: "2026-02-01", status: "upcoming", state: "New York", notes: "NY biennial statement due" },
  { id: "CMP-009", clientId: "CLT-006", companyName: "Deshmukh Exports LLC", type: "annual-report", dueDate: "2026-06-01", status: "upcoming", state: "Delaware", notes: "Delaware annual franchise tax" },
  { id: "CMP-010", clientId: "CLT-015", companyName: "Khan Enterprises LLC", type: "irs-compliance", dueDate: "2025-03-01", status: "overdue", state: "Delaware", notes: "IRS follow-up required for EIN" },
  { id: "CMP-011", clientId: "CLT-011", companyName: "Malhotra Media LLC", type: "state-alert", dueDate: "2025-05-15", status: "upcoming", state: "Texas", notes: "Texas franchise tax report" },
  { id: "CMP-012", clientId: "CLT-002", companyName: "Santos Digital Corp", type: "annual-report", dueDate: "2026-01-01", status: "upcoming", state: "Wyoming", notes: "Wyoming annual report" },
  { id: "CMP-013", clientId: "CLT-014", companyName: "Mendez Holdings LLC", type: "boi-recheck", dueDate: "2025-12-20", status: "completed", state: "Wyoming", notes: "BOI verified — no changes" },
  { id: "CMP-014", clientId: "CLT-020", companyName: "Dubois Luxe LLC", type: "annual-report", dueDate: "2026-06-01", status: "upcoming", state: "Delaware", notes: "Delaware franchise tax" },
  { id: "CMP-015", clientId: "CLT-018", companyName: "Wilson Creative Corp", type: "state-alert", dueDate: "2025-04-15", status: "upcoming", state: "New York", notes: "NY biennial statement filing window" },
];

export const formationTasks: FormationTask[] = [
  { id: "TSK-001", clientId: "CLT-001", clientName: "Richardson Tech LLC", title: "Follow up on bank account status", description: "Check with Mercury Bank on account opening progress", assignedTo: "Sneha Patel", dueDate: "2025-02-27", priority: "high", status: "in-progress", stage: 5, autoGenerated: true },
  { id: "TSK-002", clientId: "CLT-001", clientName: "Richardson Tech LLC", title: "Verify Stripe account activation", description: "Confirm Stripe account is fully verified and live", assignedTo: "Vikram Singh", dueDate: "2025-02-28", priority: "medium", status: "pending", stage: 5, autoGenerated: true },
  { id: "TSK-003", clientId: "CLT-002", clientName: "Santos Digital Corp", title: "Follow up IRS for EIN", description: "Call IRS after 7 business days of application", assignedTo: "Ananya Reddy", dueDate: "2025-02-26", priority: "high", status: "pending", stage: 3, autoGenerated: true },
  { id: "TSK-004", clientId: "CLT-003", clientName: "Hassan Imports LLC", title: "Collect missing BOI owner info", description: "Request beneficial owner details from Ahmed", assignedTo: "Sneha Patel", dueDate: "2025-02-25", priority: "high", status: "overdue", stage: 4, autoGenerated: false },
  { id: "TSK-005", clientId: "CLT-003", clientName: "Hassan Imports LLC", title: "Submit BOI to FinCEN", description: "File BOI once all owner information collected", assignedTo: "Rohan Joshi", dueDate: "2025-02-28", priority: "high", status: "pending", stage: 4, autoGenerated: true },
  { id: "TSK-006", clientId: "CLT-004", clientName: "Kim Consulting LLC", title: "Collect passport copy", description: "Follow up with Sarah Kim for passport document", assignedTo: "Vikram Singh", dueDate: "2025-02-20", priority: "medium", status: "overdue", stage: 1, autoGenerated: true },
  { id: "TSK-007", clientId: "CLT-005", clientName: "Martinez Ventures Inc", title: "Complete handover checklist", description: "Compile all docs and create compliance calendar", assignedTo: "Karan Gupta", dueDate: "2025-02-26", priority: "medium", status: "in-progress", stage: 6, autoGenerated: true },
  { id: "TSK-008", clientId: "CLT-005", clientName: "Martinez Ventures Inc", title: "Schedule client onboarding call", description: "Final walkthrough call with Roberto", assignedTo: "Karan Gupta", dueDate: "2025-02-27", priority: "low", status: "pending", stage: 6, autoGenerated: false },
  { id: "TSK-009", clientId: "CLT-007", clientName: "Chen Tech Solutions LLC", title: "Resubmit EIN application", description: "Correct errors from IRS rejection and resubmit SS-4", assignedTo: "Ananya Reddy", dueDate: "2025-02-24", priority: "high", status: "overdue", stage: 3, autoGenerated: false },
  { id: "TSK-010", clientId: "CLT-009", clientName: "O'Brien Logistics Corp", title: "Provide additional bank documents", description: "Chase Bank requested additional proof of address", assignedTo: "Karan Gupta", dueDate: "2025-02-26", priority: "high", status: "in-progress", stage: 5, autoGenerated: false },
  { id: "TSK-011", clientId: "CLT-010", clientName: "Wang Digital LLC", title: "Complete KYC verification", description: "Verify submitted documents and confirm identity", assignedTo: "Vikram Singh", dueDate: "2025-02-25", priority: "low", status: "pending", stage: 1, autoGenerated: true },
  { id: "TSK-012", clientId: "CLT-011", clientName: "Malhotra Media LLC", title: "Submit BOI filing", description: "Complete BOI submission for Raj Malhotra", assignedTo: "Ananya Reddy", dueDate: "2025-02-28", priority: "medium", status: "in-progress", stage: 4, autoGenerated: true },
  { id: "TSK-013", clientId: "CLT-012", clientName: "Taylor & Associates S-Corp", title: "File S-Corp election Form 2553", description: "Submit IRS Form 2553 for S-Corp election", assignedTo: "Sneha Patel", dueDate: "2025-03-01", priority: "high", status: "pending", stage: 2, autoGenerated: false },
  { id: "TSK-014", clientId: "CLT-015", clientName: "Khan Enterprises LLC", title: "Follow up IRS — 2nd attempt", description: "IRS not responding to EIN application, escalate", assignedTo: "Vikram Singh", dueDate: "2025-02-24", priority: "high", status: "overdue", stage: 3, autoGenerated: true },
  { id: "TSK-015", clientId: "CLT-016", clientName: "Bradley Software LLC", title: "Confirm registered agent", description: "Verify registered agent assignment in Texas", assignedTo: "Ananya Reddy", dueDate: "2025-02-26", priority: "low", status: "pending", stage: 2, autoGenerated: true },
  { id: "TSK-016", clientId: "CLT-017", clientName: "Sharma Global LLC", title: "Contact client for address proof", description: "Deepak unresponsive — 3rd follow-up attempt", assignedTo: "Rohan Joshi", dueDate: "2025-02-22", priority: "high", status: "overdue", stage: 1, autoGenerated: false },
  { id: "TSK-017", clientId: "CLT-018", clientName: "Wilson Creative Corp", title: "Verify BOI submission receipt", description: "Confirm FinCEN received BOI filing", assignedTo: "Rohan Joshi", dueDate: "2025-02-27", priority: "medium", status: "pending", stage: 4, autoGenerated: true },
  { id: "TSK-018", clientId: "CLT-020", clientName: "Dubois Luxe LLC", title: "Track Stripe application status", description: "Check Stripe dashboard for verification progress", assignedTo: "Karan Gupta", dueDate: "2025-02-28", priority: "medium", status: "pending", stage: 5, autoGenerated: true },
  { id: "TSK-019", clientId: "CLT-006", clientName: "Deshmukh Exports LLC", title: "Upload filing receipt", description: "Download filing receipt from Delaware SOS portal", assignedTo: "Ananya Reddy", dueDate: "2025-02-20", priority: "medium", status: "completed", stage: 2, autoGenerated: true },
  { id: "TSK-020", clientId: "CLT-008", clientName: "Al-Rashid Trading LLC", title: "Send welcome email and intake form", description: "New client onboarding — send intake questionnaire", assignedTo: "Rohan Joshi", dueDate: "2025-02-22", priority: "medium", status: "completed", stage: 0, autoGenerated: true },
  { id: "TSK-021", clientId: "CLT-013", clientName: "Tanaka Commerce LLC", title: "Generate client ID and assign manager", description: "Set up new client in system", assignedTo: "Rohan Joshi", dueDate: "2025-02-24", priority: "low", status: "in-progress", stage: 0, autoGenerated: true },
  { id: "TSK-022", clientId: "CLT-019", clientName: "Hassan Digital LLC", title: "Send welcome email", description: "Welcome email and package overview", assignedTo: "Vikram Singh", dueDate: "2025-02-26", priority: "low", status: "pending", stage: 0, autoGenerated: true },
  { id: "TSK-023", clientId: "CLT-014", clientName: "Mendez Holdings LLC", title: "Create compliance calendar", description: "Set up annual compliance reminders for Carlos", assignedTo: "Karan Gupta", dueDate: "2025-02-15", priority: "low", status: "completed", stage: 6, autoGenerated: true },
  { id: "TSK-024", clientId: "CLT-002", clientName: "Santos Digital Corp", title: "Upload EIN letter once received", description: "Monitor mailbox for IRS EIN assignment letter", assignedTo: "Karan Gupta", dueDate: "2025-03-05", priority: "medium", status: "pending", stage: 3, autoGenerated: true },
  { id: "TSK-025", clientId: "CLT-009", clientName: "O'Brien Logistics Corp", title: "Apply for Stripe account", description: "Set up Stripe Connect for O'Brien Logistics", assignedTo: "Vikram Singh", dueDate: "2025-03-01", priority: "medium", status: "pending", stage: 5, autoGenerated: true },
];

export const escalations: Escalation[] = [
  { id: "ESC-001", clientId: "CLT-007", companyName: "Chen Tech Solutions LLC", type: "irs-rejection", severity: "critical", createdDate: "2025-02-05", assignedTo: "Ananya Reddy", notes: "IRS rejected EIN application — incorrect FEIN format. Resubmission needed immediately." },
  { id: "ESC-002", clientId: "CLT-003", companyName: "Hassan Imports LLC", type: "missing-docs", severity: "warning", createdDate: "2025-02-15", assignedTo: "Sneha Patel", notes: "Missing beneficial owner information for BOI filing. Client contacted 3 times." },
  { id: "ESC-003", clientId: "CLT-015", companyName: "Khan Enterprises LLC", type: "delayed", severity: "critical", createdDate: "2025-02-18", assignedTo: "Vikram Singh", notes: "EIN stage stuck for 30+ days. IRS not responding to follow-ups." },
  { id: "ESC-004", clientId: "CLT-009", companyName: "O'Brien Logistics Corp", type: "bank-rejection", severity: "warning", createdDate: "2025-02-20", assignedTo: "Karan Gupta", notes: "Chase Bank requested additional documentation. Application on hold." },
  { id: "ESC-005", clientId: "CLT-017", companyName: "Sharma Global LLC", type: "client-unresponsive", severity: "warning", createdDate: "2025-02-16", assignedTo: "Rohan Joshi", notes: "Client not responding to calls or emails for 10 days. Address proof still missing." },
  { id: "ESC-006", clientId: "CLT-004", companyName: "Kim Consulting LLC", type: "delayed", severity: "warning", createdDate: "2025-02-22", assignedTo: "Vikram Singh", notes: "Passport copy overdue by 5 days. Intake cannot proceed." },
  { id: "ESC-007", clientId: "CLT-007", companyName: "Chen Tech Solutions LLC", type: "delayed", severity: "critical", createdDate: "2025-02-10", assignedTo: "Sneha Patel", notes: "Formation stuck at EIN stage for 35+ days due to rejection." },
  { id: "ESC-008", clientId: "CLT-003", companyName: "Hassan Imports LLC", type: "delayed", severity: "warning", createdDate: "2025-02-22", assignedTo: "Sneha Patel", notes: "BOI stage delayed — expected completion date passed." },
  { id: "ESC-009", clientId: "CLT-009", companyName: "O'Brien Logistics Corp", type: "delayed", severity: "warning", createdDate: "2025-02-24", assignedTo: "Karan Gupta", notes: "Banking stage taking longer than expected. Client getting anxious." },
  { id: "ESC-010", clientId: "CLT-015", companyName: "Khan Enterprises LLC", type: "irs-rejection", severity: "critical", createdDate: "2025-02-25", resolvedDate: undefined, assignedTo: "Vikram Singh", notes: "Second IRS follow-up with no response. Considering fax submission." },
];

export const formationMetrics: FormationMetric[] = [
  { month: "Sep", formations: 12, completed: 10, avgDays: 22, rejections: 1 },
  { month: "Oct", formations: 15, completed: 13, avgDays: 20, rejections: 2 },
  { month: "Nov", formations: 18, completed: 15, avgDays: 19, rejections: 1 },
  { month: "Dec", formations: 14, completed: 12, avgDays: 21, rejections: 3 },
  { month: "Jan", formations: 22, completed: 18, avgDays: 18, rejections: 2 },
  { month: "Feb", formations: 25, completed: 14, avgDays: 17, rejections: 1 },
];

export const documentTemplates: DocumentTemplate[] = [
  { id: "TPL-001", name: "Articles of Organization (LLC)", category: "Formation", description: "Standard LLC formation articles template for all states", lastUpdated: "2025-01-15", version: "3.2" },
  { id: "TPL-002", name: "Articles of Incorporation (Corp)", category: "Formation", description: "Corporation formation articles template", lastUpdated: "2025-01-15", version: "2.8" },
  { id: "TPL-003", name: "Operating Agreement (Single Member)", category: "Agreement", description: "Single-member LLC operating agreement", lastUpdated: "2025-02-01", version: "4.1" },
  { id: "TPL-004", name: "Operating Agreement (Multi Member)", category: "Agreement", description: "Multi-member LLC operating agreement with voting provisions", lastUpdated: "2025-02-01", version: "3.5" },
  { id: "TPL-005", name: "EIN Application (SS-4)", category: "IRS", description: "IRS Form SS-4 for Employer Identification Number", lastUpdated: "2024-12-10", version: "1.0" },
  { id: "TPL-006", name: "BOI Report Template", category: "Compliance", description: "FinCEN Beneficial Ownership Information report template", lastUpdated: "2025-01-20", version: "2.0" },
  { id: "TPL-007", name: "S-Corp Election (Form 2553)", category: "IRS", description: "IRS Form 2553 for S-Corporation election", lastUpdated: "2024-11-15", version: "1.0" },
  { id: "TPL-008", name: "Client Intake Questionnaire", category: "Intake", description: "Standard questionnaire for new client onboarding", lastUpdated: "2025-02-10", version: "5.0" },
  { id: "TPL-009", name: "Compliance Calendar Template", category: "Compliance", description: "Annual compliance tracking calendar for each state", lastUpdated: "2025-01-05", version: "2.3" },
  { id: "TPL-010", name: "Client Handover Checklist", category: "Completion", description: "Final handover document checklist for completed formations", lastUpdated: "2025-02-15", version: "3.0" },
];
