import { employees } from "./mock-data-hrms";

import type { AssetCategory, AssetCondition, AssetStatus, Asset, AssetAssignment } from "@/types/assets";
export type { AssetCategory, AssetCondition, AssetStatus, Asset, AssetAssignment };


const ASSET_IMAGES: Record<AssetCategory, string> = {
  Laptop: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=120&h=120&fit=crop",
  Monitor: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=120&h=120&fit=crop",
  Mouse: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=120&h=120&fit=crop",
  Keyboard: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=120&h=120&fit=crop",
  Phone: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=120&h=120&fit=crop",
  Tablet: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=120&h=120&fit=crop",
  Headphones: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=120&h=120&fit=crop",
  Printer: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=120&h=120&fit=crop",
  Other: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=120&h=120&fit=crop",
};

export function getAssetImage(category: AssetCategory): string {
  return ASSET_IMAGES[category] || ASSET_IMAGES.Other;
}

export const assets: Asset[] = [
  {
    id: "AST-001",
    assetCode: "AST-001",
    name: 'MacBook Pro M1 13" (2021)',
    category: "Laptop",
    serialNumber: "C03VX2M6JG00",
    model: 'MacBook Pro 13"',
    manufacturer: "Apple",
    purchaseDate: "2021-03-15",
    purchasePrice: 557.85,
    condition: "good",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Laptop,
    warrantyExpiry: "2024-03-15",
    location: "Office – Desk 12",
    notes: "Primary dev machine",
  },
  {
    id: "AST-002",
    assetCode: "AST-002",
    name: "MacBook Air M1 (2020)",
    category: "Laptop",
    serialNumber: "D04LY8N3K90A",
    model: "MacBook Air M1",
    manufacturer: "Apple",
    purchaseDate: "2020-11-20",
    purchasePrice: 739.65,
    condition: "good",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Laptop,
    warrantyExpiry: "2023-11-20",
    location: "Office – Desk 7",
    notes: "",
  },
  {
    id: "AST-003",
    assetCode: "AST-003",
    name: "MacBook Pro 14 Inch 512GB M1 Pro",
    category: "Laptop",
    serialNumber: "F05PD1Q2H76B",
    model: "MacBook Pro 14",
    manufacturer: "Apple",
    purchaseDate: "2022-01-10",
    purchasePrice: 105.55,
    condition: "new",
    status: "available",
    imageUrl: ASSET_IMAGES.Laptop,
    warrantyExpiry: "2025-01-10",
    location: "IT Storage Room",
    notes: "Unassigned, ready for deployment",
  },
  {
    id: "AST-004",
    assetCode: "AST-004",
    name: 'Monitor MSI 27"',
    category: "Monitor",
    serialNumber: "G06RM9Z8L34C",
    model: "MSI Optix MAG274QRF",
    manufacturer: "MSI",
    purchaseDate: "2022-06-01",
    purchasePrice: 630.44,
    condition: "good",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Monitor,
    warrantyExpiry: "2025-06-01",
    location: "Office – Desk 3",
    notes: "27 inch QHD 165Hz",
  },
  {
    id: "AST-005",
    assetCode: "AST-005",
    name: "Magic Mouse Apple Gen 2",
    category: "Mouse",
    serialNumber: "H07TN0P5I2ID",
    model: "Magic Mouse 2",
    manufacturer: "Apple",
    purchaseDate: "2019-08-22",
    purchasePrice: 782.01,
    condition: "fair",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Mouse,
    warrantyExpiry: "2021-08-22",
    location: "Office – Desk 5",
    notes: "",
  },
  {
    id: "AST-006",
    assetCode: "AST-006",
    name: 'APPLE 32" R6KD Pro Display XDR',
    category: "Monitor",
    serialNumber: "J08QO4X6F98E",
    model: "Pro Display XDR",
    manufacturer: "Apple",
    purchaseDate: "2021-04-10",
    purchasePrice: 943.65,
    condition: "good",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Monitor,
    warrantyExpiry: "2024-04-10",
    location: "Office – Desk 1",
    notes: "Executive display",
  },
  {
    id: "AST-007",
    assetCode: "AST-007",
    name: 'APPLE 32" R6KD Pro Display XDR',
    category: "Monitor",
    serialNumber: "K09UA3W7E65F",
    model: "Pro Display XDR",
    manufacturer: "Apple",
    purchaseDate: "2021-05-15",
    purchasePrice: 202.87,
    condition: "good",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Monitor,
    warrantyExpiry: "2024-05-15",
    location: "Office – Desk 8",
    notes: "",
  },
  {
    id: "AST-008",
    assetCode: "AST-008",
    name: 'APPLE 32" R6KD Pro Display XDR',
    category: "Monitor",
    serialNumber: "L10VB5Y9D43G",
    model: "Pro Display XDR",
    manufacturer: "Apple",
    purchaseDate: "2021-06-20",
    purchasePrice: 169.43,
    condition: "fair",
    status: "in-repair",
    imageUrl: ASSET_IMAGES.Monitor,
    warrantyExpiry: "2024-06-20",
    location: "IT Repair Bench",
    notes: "Dead pixels — sent for repair",
  },
  {
    id: "AST-009",
    assetCode: "AST-009",
    name: "Logitech MX Master 3S",
    category: "Mouse",
    serialNumber: "M11WC6Z8C21H",
    model: "MX Master 3S",
    manufacturer: "Logitech",
    purchaseDate: "2023-02-14",
    purchasePrice: 99.99,
    condition: "new",
    status: "available",
    imageUrl: ASSET_IMAGES.Mouse,
    warrantyExpiry: "2026-02-14",
    location: "IT Storage Room",
    notes: "",
  },
  {
    id: "AST-010",
    assetCode: "AST-010",
    name: "MacBook Pro 14 Inch 512GB M1 Pro",
    category: "Laptop",
    serialNumber: "N12XD7A4B09I",
    model: "MacBook Pro 14",
    manufacturer: "Apple",
    purchaseDate: "2021-12-01",
    purchasePrice: 601.13,
    condition: "good",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Laptop,
    warrantyExpiry: "2024-12-01",
    location: "Office – Desk 14",
    notes: "",
  },
  {
    id: "AST-011",
    assetCode: "AST-011",
    name: "MacBook Pro 14 Inch 512GB M1 Pro",
    category: "Laptop",
    serialNumber: "P13YE8B2A76J",
    model: "MacBook Pro 14",
    manufacturer: "Apple",
    purchaseDate: "2021-09-05",
    purchasePrice: 778.35,
    condition: "good",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Laptop,
    warrantyExpiry: "2024-09-05",
    location: "Office – Desk 9",
    notes: "",
  },
  {
    id: "AST-012",
    assetCode: "AST-012",
    name: "Dell UltraSharp 27 4K",
    category: "Monitor",
    serialNumber: "Q14ZE9C3D54K",
    model: "U2723QE",
    manufacturer: "Dell",
    purchaseDate: "2023-01-20",
    purchasePrice: 710.68,
    condition: "new",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Monitor,
    warrantyExpiry: "2026-01-20",
    location: "Office – Desk 6",
    notes: "",
  },
  {
    id: "AST-013",
    assetCode: "AST-013",
    name: "MacBook Pro 14 Inch 512GB M1 Pro",
    category: "Laptop",
    serialNumber: "R15AF0D1E32L",
    model: "MacBook Pro 14",
    manufacturer: "Apple",
    purchaseDate: "2022-03-15",
    purchasePrice: 576.28,
    condition: "good",
    status: "available",
    imageUrl: ASSET_IMAGES.Laptop,
    warrantyExpiry: "2025-03-15",
    location: "IT Storage Room",
    notes: "Freshly wiped, ready for reassignment",
  },
  {
    id: "AST-014",
    assetCode: "AST-014",
    name: "Logitech MX Keys S",
    category: "Keyboard",
    serialNumber: "S16BG2E5F10M",
    model: "MX Keys S",
    manufacturer: "Logitech",
    purchaseDate: "2023-04-10",
    purchasePrice: 109.99,
    condition: "new",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Keyboard,
    warrantyExpiry: "2026-04-10",
    location: "Office – Desk 2",
    notes: "",
  },
  {
    id: "AST-015",
    assetCode: "AST-015",
    name: "MacBook Pro 14 Inch 512GB M1 Pro",
    category: "Laptop",
    serialNumber: "T17CH3F4G98N",
    model: "MacBook Pro 14",
    manufacturer: "Apple",
    purchaseDate: "2021-07-30",
    purchasePrice: 450.54,
    condition: "fair",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Laptop,
    warrantyExpiry: "2024-07-30",
    location: "Office – Desk 11",
    notes: "",
  },
  {
    id: "AST-016",
    assetCode: "AST-016",
    name: "Sony WH-1000XM5",
    category: "Headphones",
    serialNumber: "U18DI4G7H65O",
    model: "WH-1000XM5",
    manufacturer: "Sony",
    purchaseDate: "2023-06-15",
    purchasePrice: 348.0,
    condition: "new",
    status: "assigned",
    imageUrl: ASSET_IMAGES.Headphones,
    warrantyExpiry: "2025-06-15",
    location: "Office – Desk 4",
    notes: "Noise-cancelling headset",
  },
  {
    id: "AST-017",
    assetCode: "AST-017",
    name: "iPhone 14 Pro",
    category: "Phone",
    serialNumber: "V19EJ5H8I32P",
    model: "iPhone 14 Pro",
    manufacturer: "Apple",
    purchaseDate: "2022-10-05",
    purchasePrice: 999.0,
    condition: "good",
    status: "retired",
    imageUrl: ASSET_IMAGES.Phone,
    warrantyExpiry: "2024-10-05",
    location: "IT Storage Room",
    notes: "Retired — replaced by iPhone 15 Pro",
  },
  {
    id: "AST-018",
    assetCode: "AST-018",
    name: "HP LaserJet Pro MFP",
    category: "Printer",
    serialNumber: "W20FK6I9J21Q",
    model: "M428fdw",
    manufacturer: "HP",
    purchaseDate: "2021-02-28",
    purchasePrice: 449.99,
    condition: "good",
    status: "available",
    imageUrl: ASSET_IMAGES.Printer,
    warrantyExpiry: "2024-02-28",
    location: "Print Room",
    notes: "Shared office printer",
  },
];

export const assetAssignments: AssetAssignment[] = [
  { id: "ASGN-001", assetId: "AST-001", employeeId: "EMP-001", employeeName: employees.find(e => e.id === "EMP-001")?.name || "Sneha Patel", assignedDate: "2021-04-01", returnDate: null, notes: "Primary work machine" },
  { id: "ASGN-002", assetId: "AST-002", employeeId: "EMP-003", employeeName: employees.find(e => e.id === "EMP-003")?.name || "Vikram Singh", assignedDate: "2021-01-10", returnDate: null, notes: "" },
  { id: "ASGN-003", assetId: "AST-004", employeeId: "EMP-005", employeeName: employees.find(e => e.id === "EMP-005")?.name || "Priya Sharma", assignedDate: "2022-06-15", returnDate: null, notes: "External display for design work" },
  { id: "ASGN-004", assetId: "AST-005", employeeId: "EMP-007", employeeName: employees.find(e => e.id === "EMP-007")?.name || "Arjun Mehta", assignedDate: "2020-01-10", returnDate: null, notes: "" },
  { id: "ASGN-005", assetId: "AST-006", employeeId: "EMP-002", employeeName: employees.find(e => e.id === "EMP-002")?.name || "Rahul Kumar", assignedDate: "2021-05-01", returnDate: null, notes: "" },
  { id: "ASGN-006", assetId: "AST-007", employeeId: "EMP-004", employeeName: employees.find(e => e.id === "EMP-004")?.name || "Ananya Gupta", assignedDate: "2021-06-01", returnDate: null, notes: "" },
  { id: "ASGN-007", assetId: "AST-010", employeeId: "EMP-008", employeeName: employees.find(e => e.id === "EMP-008")?.name || "Karan Gupta", assignedDate: "2022-01-15", returnDate: null, notes: "" },
  { id: "ASGN-008", assetId: "AST-011", employeeId: "EMP-009", employeeName: employees.find(e => e.id === "EMP-009")?.name || "Meera Iyer", assignedDate: "2021-10-01", returnDate: null, notes: "" },
  { id: "ASGN-009", assetId: "AST-012", employeeId: "EMP-010", employeeName: employees.find(e => e.id === "EMP-010")?.name || "Deepak Verma", assignedDate: "2023-02-01", returnDate: null, notes: "" },
  { id: "ASGN-010", assetId: "AST-014", employeeId: "EMP-006", employeeName: employees.find(e => e.id === "EMP-006")?.name || "Nisha Reddy", assignedDate: "2023-05-01", returnDate: null, notes: "" },
  { id: "ASGN-011", assetId: "AST-015", employeeId: "EMP-011", employeeName: employees.find(e => e.id === "EMP-011")?.name || "Aditya Joshi", assignedDate: "2021-08-15", returnDate: null, notes: "" },
  { id: "ASGN-012", assetId: "AST-016", employeeId: "EMP-012", employeeName: employees.find(e => e.id === "EMP-012")?.name || "Ritika Nair", assignedDate: "2023-07-01", returnDate: null, notes: "Noise-cancelling for focus work" },
  { id: "ASGN-013", assetId: "AST-008", employeeId: "EMP-004", employeeName: employees.find(e => e.id === "EMP-004")?.name || "Ananya Gupta", assignedDate: "2021-07-01", returnDate: "2024-01-15", notes: "Returned due to dead pixels" },
  { id: "ASGN-014", assetId: "AST-003", employeeId: "EMP-006", employeeName: employees.find(e => e.id === "EMP-006")?.name || "Nisha Reddy", assignedDate: "2022-02-01", returnDate: "2023-11-30", notes: "Returned on role change" },
  { id: "ASGN-015", assetId: "AST-017", employeeId: "EMP-001", employeeName: employees.find(e => e.id === "EMP-001")?.name || "Sneha Patel", assignedDate: "2022-10-10", returnDate: "2024-09-20", notes: "Upgraded to iPhone 15 Pro" },
];

export function getAssetById(id: string): Asset | undefined {
  return assets.find((a) => a.id === id);
}

export function getAssignmentsForAsset(assetId: string): AssetAssignment[] {
  return assetAssignments.filter((a) => a.assetId === assetId);
}

export function getCurrentAssignment(assetId: string): AssetAssignment | undefined {
  return assetAssignments.find((a) => a.assetId === assetId && a.returnDate === null);
}

export function getAssetsForEmployee(employeeId: string): Asset[] {
  const activeAssignments = assetAssignments.filter((a) => a.employeeId === employeeId && a.returnDate === null);
  return activeAssignments.map((a) => assets.find((ast) => ast.id === a.assetId)).filter(Boolean) as Asset[];
}

export const ASSET_CATEGORIES: AssetCategory[] = ["Laptop", "Monitor", "Mouse", "Keyboard", "Phone", "Tablet", "Headphones", "Printer", "Other"];
