import type { Platform, MediaType, PostStage, AssetType, AssignmentType, SocialAccount, PostMetrics, SocialPost, Campaign, MediaAsset, ApprovalRequest, Assignment } from "@/types/social";
export type { Platform, MediaType, PostStage, AssetType, AssignmentType, SocialAccount, PostMetrics, SocialPost, Campaign, MediaAsset, ApprovalRequest, Assignment };


export const socialAccounts: SocialAccount[] = [
  { id: "ACC-001", brand: "Suprans", platform: "instagram", handle: "@suprans.in", followers: 42800, engagementRate: 4.2, postsThisMonth: 18, color: "#E11D48" },
  { id: "ACC-002", brand: "Suprans", platform: "youtube", handle: "Suprans Official", followers: 15600, engagementRate: 6.8, postsThisMonth: 8, color: "#DC2626" },
  { id: "ACC-003", brand: "Suprans", platform: "linkedin", handle: "Suprans", followers: 8200, engagementRate: 2.1, postsThisMonth: 12, color: "#2563EB" },
  { id: "ACC-004", brand: "LegalNations", platform: "instagram", handle: "@legalnations.official", followers: 12400, engagementRate: 3.8, postsThisMonth: 10, color: "#225AEA" },
  { id: "ACC-005", brand: "LegalNations", platform: "linkedin", handle: "LegalNations", followers: 19800, engagementRate: 3.2, postsThisMonth: 14, color: "#2563EB" },
  { id: "ACC-006", brand: "USDrop", platform: "instagram", handle: "@usdrop.ai", followers: 28600, engagementRate: 5.1, postsThisMonth: 22, color: "#F34147" },
  { id: "ACC-007", brand: "Gullee", platform: "instagram", handle: "@gullee.official", followers: 6400, engagementRate: 6.4, postsThisMonth: 6, color: "#7C3AED" },
  { id: "ACC-008", brand: "Gullee", platform: "threads", handle: "@gullee", followers: 2100, engagementRate: 3.5, postsThisMonth: 4, color: "#1F2937" },
  { id: "ACC-009", brand: "Suprans", platform: "facebook", handle: "Suprans India", followers: 9800, engagementRate: 1.8, postsThisMonth: 7, color: "#1D4ED8" },
  { id: "ACC-010", brand: "LegalNations", platform: "facebook", handle: "LegalNations India", followers: 5200, engagementRate: 1.4, postsThisMonth: 5, color: "#1D4ED8" },
];

export const socialPosts: SocialPost[] = [
  {
    id: "POST-001",
    title: "Suprans Diwali Reel",
    caption: "✨ This Diwali, let your business shine brighter than ever! 🪔 We helped 200+ founders register their US companies from India — and now it's your turn. Swipe to see the stories that lit up our year. 💼🇺🇸 #Suprans #USCompanyFormation #Diwali2025 #IndianFounders",
    mediaType: "reel",
    platforms: ["instagram", "facebook"],
    accountIds: ["ACC-001", "ACC-009"],
    campaignId: "CAMP-001",
    verticalTag: "Suprans",
    stage: "published",
    approvalStatus: "approved",
    scheduledDate: "2025-11-01",
    publishedDate: "2025-11-01",
    performanceScore: 92,
    createdBy: "Rahul",
    metrics: { reach: 84200, impressions: 142000, engagement: 6240, saves: 1840, shares: 920, watchTime: 38400, clicks: 2100, followerGain: 380 },
    notes: "Best performing reel of Q4. Boosted on Nov 2.",
  },
  {
    id: "POST-002",
    title: "LegalNations US LLC Guide Carousel",
    caption: "Starting a US LLC from India in 2025? Here's what nobody tells you 🧵👇 1/ You don't need to visit the US. 2/ It takes 3–5 business days. 3/ Your Indian bank can receive USD. Read the full breakdown → link in bio. #LegalNations #USLLCIndia #CompanyFormation #IndianEntrepreneur",
    mediaType: "carousel",
    platforms: ["instagram", "linkedin"],
    accountIds: ["ACC-004", "ACC-005"],
    campaignId: "CAMP-002",
    verticalTag: "LegalNations",
    stage: "published",
    approvalStatus: "approved",
    scheduledDate: "2026-01-15",
    publishedDate: "2026-01-15",
    performanceScore: 88,
    createdBy: "Priya",
    metrics: { reach: 52400, impressions: 89000, engagement: 4120, saves: 2860, shares: 640, watchTime: 0, clicks: 3200, followerGain: 210 },
    notes: "High saves — educational content performing well.",
  },
  {
    id: "POST-003",
    title: "USDrop Spring Drop Launch",
    caption: "🌸 Spring Drop is LIVE! 50 winning products, pre-vetted from our top US suppliers. Your store. Their inventory. Zero risk. Limited to 100 dropshippers — grab your spot now. Link in bio 👆 #USDrop #Dropshipping #SpringCollection #EcomIndia",
    mediaType: "reel",
    platforms: ["instagram"],
    accountIds: ["ACC-006"],
    campaignId: "CAMP-003",
    verticalTag: "USDrop",
    stage: "published",
    approvalStatus: "approved",
    scheduledDate: "2026-02-14",
    publishedDate: "2026-02-14",
    performanceScore: 79,
    createdBy: "Ananya",
    metrics: { reach: 31800, impressions: 58000, engagement: 2840, saves: 920, shares: 480, watchTime: 22600, clicks: 1640, followerGain: 142 },
    notes: "Launch day reel. Good performance considering small following.",
  },
  {
    id: "POST-004",
    title: "Suprans Brand Story Static",
    caption: "We started in a co-working space in Pune. Today, 500+ Indian founders have used Suprans to build globally. The story isn't about us — it's about every founder who dared to think bigger. 🙏 #Suprans #FounderStory #BrandMoment",
    mediaType: "static",
    platforms: ["instagram", "linkedin"],
    accountIds: ["ACC-001", "ACC-003"],
    campaignId: "CAMP-004",
    verticalTag: "Suprans",
    stage: "published",
    approvalStatus: "approved",
    scheduledDate: "2026-02-10",
    publishedDate: "2026-02-10",
    performanceScore: 71,
    createdBy: "Dev",
    metrics: { reach: 18400, impressions: 29000, engagement: 1280, saves: 340, shares: 220, watchTime: 0, clicks: 480, followerGain: 64 },
    notes: "Lower reach but high engagement rate from existing followers.",
  },
  {
    id: "POST-005",
    title: "Gullee Brand Intro Reel",
    caption: "Gullee is here — and we're changing how India buys homeware. Premium. Affordable. Fast delivery. Follow us for your first look 👀 #Gullee #HomeDecor #IndiaLaunch",
    mediaType: "reel",
    platforms: ["instagram", "threads"],
    accountIds: ["ACC-007", "ACC-008"],
    campaignId: "CAMP-005",
    verticalTag: "Gullee",
    stage: "published",
    approvalStatus: "approved",
    scheduledDate: "2026-02-20",
    publishedDate: "2026-02-20",
    performanceScore: 84,
    createdBy: "Rahul",
    metrics: { reach: 24600, impressions: 41000, engagement: 2160, saves: 680, shares: 560, watchTime: 18200, clicks: 920, followerGain: 284 },
    notes: "Intro reel. Very high follower gain relative to existing base.",
  },
  {
    id: "POST-006",
    title: "Suprans YouTube Webinar Recap",
    caption: "Did you miss our live webinar on 'How to Register Your US Company While Staying in India'? Full recording is now up! 45 mins packed with real steps, real costs, real experiences. Watch now 🎬 #Suprans #Webinar #USCompanyFormation",
    mediaType: "long-video",
    platforms: ["youtube"],
    accountIds: ["ACC-002"],
    campaignId: "CAMP-006",
    verticalTag: "Suprans",
    stage: "scheduled",
    approvalStatus: "approved",
    scheduledDate: "2026-03-05",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Rahul",
    metrics: null,
    notes: "Webinar recap video. Scheduled for Wednesday morning.",
  },
  {
    id: "POST-007",
    title: "LegalNations Compliance Alert",
    caption: "⚠️ IMPORTANT: If your US LLC was formed before Jan 2025, you now have a FinCEN BOI filing requirement. Deadline is March 31. Non-compliance = heavy fines. DM us or visit link in bio to file with LegalNations today. #LegalNations #BOI #Compliance #LLCUSA",
    mediaType: "static",
    platforms: ["instagram", "linkedin", "facebook"],
    accountIds: ["ACC-004", "ACC-005", "ACC-010"],
    campaignId: "CAMP-002",
    verticalTag: "LegalNations",
    stage: "scheduled",
    approvalStatus: "approved",
    scheduledDate: "2026-03-03",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "Urgent compliance post. Approved by Founder on Feb 28.",
  },
  {
    id: "POST-008",
    title: "USDrop Product Spotlight Carousel",
    caption: "5 winning products our dropshippers sold 1000+ units of last month 🔥 Slide through → see what's hot and add them to your store today. Available exclusively on USDrop. #USDrop #WinningProducts #DropshippingIndia #Ecom",
    mediaType: "carousel",
    platforms: ["instagram"],
    accountIds: ["ACC-006"],
    campaignId: "CAMP-003",
    verticalTag: "USDrop",
    stage: "scheduled",
    approvalStatus: "approved",
    scheduledDate: "2026-03-07",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Priya",
    metrics: null,
    notes: "Product spotlight series — 3rd in the sequence.",
  },
  {
    id: "POST-009",
    title: "Suprans Founder Testimonial",
    caption: '"I went from freelancer to global agency owner in 3 months — and Suprans made the legal side simple." — Karan Mehta, Design Studio, Pune. Your story could be next. DM us to start. 💬 #Suprans #FounderTestimonial #IndianFounders',
    mediaType: "static",
    platforms: ["instagram", "linkedin"],
    accountIds: ["ACC-001", "ACC-003"],
    campaignId: "CAMP-004",
    verticalTag: "Suprans",
    stage: "scheduled",
    approvalStatus: "approved",
    scheduledDate: "2026-03-10",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "Third testimonial in Suprans brand series.",
  },
  {
    id: "POST-010",
    title: "Gullee Homeware Carousel",
    caption: "10 homeware pieces under ₹999 that look like they cost 10x more 🏡✨ Save this for your next home refresh. Available now on gullee.com #Gullee #HomeDecorIndia #BudgetDecor #AffiliateReady",
    mediaType: "carousel",
    platforms: ["instagram"],
    accountIds: ["ACC-007"],
    campaignId: "CAMP-005",
    verticalTag: "Gullee",
    stage: "scheduled",
    approvalStatus: "approved",
    scheduledDate: "2026-03-12",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Priya",
    metrics: null,
    notes: "Budget homeware angle — targeting mass appeal.",
  },
  {
    id: "POST-011",
    title: "LegalNations Event Promo Reel",
    caption: "🎤 LIVE EVENT: 'Build Your Global Business from India' — Join our founder Arjun Sharma + 3 guest experts for an evening of insights, networking, and Q&A. Mumbai | March 20 | Free entry. Register now → link in bio. #LegalNations #Event #IndianFounders #Mumbai",
    mediaType: "reel",
    platforms: ["instagram", "linkedin"],
    accountIds: ["ACC-004", "ACC-005"],
    campaignId: "CAMP-002",
    verticalTag: "LegalNations",
    stage: "approval",
    approvalStatus: "pending",
    scheduledDate: "2026-03-08",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Ananya",
    metrics: null,
    notes: "Major event promo — requires founder approval before scheduling.",
  },
  {
    id: "POST-012",
    title: "Suprans Webinar Promo",
    caption: "Free LIVE Webinar: 'How Indian Founders Are Building US Businesses Without Moving Abroad' 📅 March 15 | 7PM IST | Zoom (link in bio) Spots are filling up — save your seat now! 🎯 #Suprans #Webinar #IndianEntrepreneur #USBusiness",
    mediaType: "static",
    platforms: ["instagram", "linkedin"],
    accountIds: ["ACC-001", "ACC-003"],
    campaignId: "CAMP-006",
    verticalTag: "Suprans",
    stage: "approval",
    approvalStatus: "pending",
    scheduledDate: "2026-03-06",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "Webinar promo needs founder approval — event post policy.",
  },
  {
    id: "POST-013",
    title: "USDrop AI Sourcing Feature",
    caption: "You asked. We built it. 🤖 Introducing AI-powered product sourcing on USDrop. Let our AI scan 10,000+ US suppliers and surface winning products for YOUR niche. Launch your store smarter. Try it free → link in bio. #USDrop #AIDropshipping #ProductSourcing",
    mediaType: "reel",
    platforms: ["instagram"],
    accountIds: ["ACC-006"],
    campaignId: "CAMP-003",
    verticalTag: "USDrop",
    stage: "approval",
    approvalStatus: "pending",
    scheduledDate: "2026-03-14",
    publishedDate: null,
    performanceScore: null,
    createdBy: "Rahul",
    metrics: null,
    notes: "New feature launch — high priority, needs approval.",
  },
  {
    id: "POST-014",
    title: "Gullee YouTube Short — Unboxing",
    caption: "POV: Your Gullee order just arrived 📦 We film every order before it ships — this is how we ensure every product meets quality standard. #Gullee #Unboxing #HomeDecor #YouTube",
    mediaType: "short",
    platforms: ["youtube", "instagram"],
    accountIds: ["ACC-002", "ACC-007"],
    campaignId: "CAMP-005",
    verticalTag: "Gullee",
    stage: "design",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Rahul",
    metrics: null,
    notes: "Short format for YouTube Shorts + Instagram Reels.",
  },
  {
    id: "POST-015",
    title: "Suprans Brand Series Episode 3",
    caption: "How do you build a brand that travels without a passport? Our latest episode explores 3 Indian founders building global brands from their laptops. Watch → link in bio. #Suprans #BrandStory #GlobalFounder",
    mediaType: "long-video",
    platforms: ["youtube"],
    accountIds: ["ACC-002"],
    campaignId: "CAMP-004",
    verticalTag: "Suprans",
    stage: "design",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Priya",
    metrics: null,
    notes: "Episode 3 of the brand series. Editing in progress.",
  },
  {
    id: "POST-016",
    title: "LegalNations LinkedIn Authority Post",
    caption: "Most founders don't realize: a US LLC gives you access to Stripe, Amazon, and global contracts that aren't available to Indian entities. Here's what changes when you go global → [Thread]",
    mediaType: "static",
    platforms: ["linkedin"],
    accountIds: ["ACC-005"],
    campaignId: "CAMP-002",
    verticalTag: "LegalNations",
    stage: "caption",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "Authority post for LinkedIn audience. Caption needs finalization.",
  },
  {
    id: "POST-017",
    title: "USDrop Success Story Carousel",
    caption: "[CAPTION DRAFT] Meet Simran — she started with 1 product and ₹0 ads budget. 6 months on USDrop, she's at ₹2.4L/month. Here's how she did it 👇",
    mediaType: "carousel",
    platforms: ["instagram"],
    accountIds: ["ACC-006"],
    campaignId: "CAMP-003",
    verticalTag: "USDrop",
    stage: "caption",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "Caption needs final review before sending for approval.",
  },
  {
    id: "POST-018",
    title: "Suprans EIN Guide Script",
    caption: "[SCRIPT IN PROGRESS] What is an EIN and why does every US company owner need one? Scripting underway for a 60-second explainer reel.",
    mediaType: "reel",
    platforms: ["instagram"],
    accountIds: ["ACC-001"],
    campaignId: "CAMP-002",
    verticalTag: "LegalNations",
    stage: "script",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Rahul",
    metrics: null,
    notes: "Script writing in progress. Targeting 50–60 second reel.",
  },
  {
    id: "POST-019",
    title: "Gullee Interior Styling Idea",
    caption: "[IDEA STAGE] 5 homeware items that interior designers swear by — under ₹1500. Quick styling tips.",
    mediaType: "carousel",
    platforms: ["instagram"],
    accountIds: ["ACC-007"],
    campaignId: null,
    verticalTag: "Gullee",
    stage: "idea",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Ananya",
    metrics: null,
    notes: "New idea — needs team review to move to script.",
  },
  {
    id: "POST-020",
    title: "Suprans Threads Brand Intro",
    caption: "hey threads 👋 suprans is finally here. we help indian founders register their US company without leaving india. ask us anything. seriously — anything.",
    mediaType: "static",
    platforms: ["threads"],
    accountIds: [],
    campaignId: null,
    verticalTag: "Suprans",
    stage: "idea",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Ananya",
    metrics: null,
    notes: "Casual Threads intro — explore platform voice.",
  },
  {
    id: "POST-021",
    title: "LegalNations BOI Explainer Reel",
    caption: "[SCRIPT DONE] What is FinCEN BOI? Why should you care? 60-second explainer for US LLC owners. Script approved, design pending.",
    mediaType: "reel",
    platforms: ["instagram", "linkedin"],
    accountIds: ["ACC-004"],
    campaignId: "CAMP-002",
    verticalTag: "LegalNations",
    stage: "script",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Rahul",
    metrics: null,
    notes: "Script complete, pending design handoff.",
  },
  {
    id: "POST-022",
    title: "USDrop Supplier Network Post",
    caption: "10,000+ US suppliers. Zero import headaches. Delivered to your customer in 3–5 days. That's the USDrop difference. #USDrop #DropshippingIndia",
    mediaType: "static",
    platforms: ["instagram"],
    accountIds: ["ACC-006"],
    campaignId: "CAMP-003",
    verticalTag: "USDrop",
    stage: "rejected",
    approvalStatus: "rejected",
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "Rejected — caption too generic. Needs more specific hook.",
  },
  {
    id: "POST-023",
    title: "Suprans Diwali Story Pack",
    caption: "Diwali greetings from the Suprans team 🪔🎉",
    mediaType: "story",
    platforms: ["instagram"],
    accountIds: ["ACC-001"],
    campaignId: "CAMP-001",
    verticalTag: "Suprans",
    stage: "rejected",
    approvalStatus: "rejected",
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Priya",
    metrics: null,
    notes: "Rejected — design quality below brand standard. Redesign needed.",
  },
  {
    id: "POST-024",
    title: "Gullee Threads Daily",
    caption: "your home should feel like a hug. 🏡 daily inspo from the gullee team.",
    mediaType: "static",
    platforms: ["threads"],
    accountIds: ["ACC-008"],
    campaignId: null,
    verticalTag: "Gullee",
    stage: "rejected",
    approvalStatus: "rejected",
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "Rejected — too casual. Brand voice not established yet.",
  },
  {
    id: "POST-025",
    title: "Suprans LinkedIn Growth Tip",
    caption: "The fastest way to grow your consulting revenue in 2025: Register a US entity. Here's why → A US company unlocks PayPal, Stripe, Amazon and 10,000+ global clients who prefer paying US entities. DM me to learn how Suprans does it in 5 business days.",
    mediaType: "static",
    platforms: ["linkedin"],
    accountIds: ["ACC-003"],
    campaignId: "CAMP-004",
    verticalTag: "Suprans",
    stage: "caption",
    approvalStatus: null,
    scheduledDate: null,
    publishedDate: null,
    performanceScore: null,
    createdBy: "Dev",
    metrics: null,
    notes: "LinkedIn authority play. Final caption review needed.",
  },
];

export const campaigns: Campaign[] = [
  {
    id: "CAMP-001",
    name: "Diwali Campaign 2025",
    brand: "Suprans",
    goal: "Brand awareness and lead generation during Diwali festive season",
    description: "Festive content across Instagram and Facebook targeting Indian founders during the Diwali period. Mix of celebratory brand content and CTAs for US company formation.",
    startDate: "2025-10-20",
    endDate: "2025-11-15",
    status: "completed",
    platforms: ["instagram", "facebook"],
    postCount: 12,
    totalReach: 184000,
    totalEngagement: 14200,
    leads: 68,
    revenue: 340000,
    managedBy: "Ananya",
  },
  {
    id: "CAMP-002",
    name: "LegalNations Brand Launch",
    brand: "LegalNations",
    goal: "Establish LegalNations as the go-to US company formation service for Indian founders",
    description: "Comprehensive launch campaign across Instagram, LinkedIn and Facebook. Mix of authority content, compliance alerts, testimonials and event promotions.",
    startDate: "2026-01-01",
    endDate: "2026-04-30",
    status: "active",
    platforms: ["instagram", "linkedin", "facebook"],
    postCount: 24,
    totalReach: 312000,
    totalEngagement: 22800,
    leads: 124,
    revenue: 860000,
    managedBy: "Ananya",
  },
  {
    id: "CAMP-003",
    name: "USDrop Spring Drop 2026",
    brand: "USDrop",
    goal: "Drive sign-ups for the Spring Drop product batch and grow dropshipper community",
    description: "Instagram-first campaign with product spotlights, success stories, and AI feature launches. Target: 200 new dropshipper signups.",
    startDate: "2026-02-01",
    endDate: "2026-03-31",
    status: "active",
    platforms: ["instagram"],
    postCount: 18,
    totalReach: 142000,
    totalEngagement: 9600,
    leads: 48,
    revenue: 520000,
    managedBy: "Rahul",
  },
  {
    id: "CAMP-004",
    name: "Suprans Brand Series",
    brand: "Suprans",
    goal: "Build long-term brand authority with founder stories and educational content",
    description: "Ongoing content series featuring Indian founders who've scaled globally using Suprans. YouTube long-form + Instagram static cuts.",
    startDate: "2026-01-15",
    endDate: "2026-06-30",
    status: "active",
    platforms: ["youtube", "instagram", "linkedin"],
    postCount: 16,
    totalReach: 96000,
    totalEngagement: 7200,
    leads: 34,
    revenue: 280000,
    managedBy: "Priya",
  },
  {
    id: "CAMP-005",
    name: "Gullee Brand Intro",
    brand: "Gullee",
    goal: "Launch Gullee brand on social media and acquire first 10K Instagram followers",
    description: "Launch campaign for Gullee homeware brand. Reels-first strategy on Instagram + organic Threads presence. Focus on brand personality establishment.",
    startDate: "2026-02-15",
    endDate: "2026-04-15",
    status: "active",
    platforms: ["instagram", "threads"],
    postCount: 10,
    totalReach: 58000,
    totalEngagement: 4800,
    leads: 12,
    revenue: 84000,
    managedBy: "Rahul",
  },
  {
    id: "CAMP-006",
    name: "Webinar Promo Series",
    brand: "Suprans",
    goal: "Drive webinar registrations and position Suprans as thought leaders",
    description: "Multi-channel campaign promoting the 'Build Your Global Business from India' webinar series. YouTube recordings + Instagram + LinkedIn promo posts.",
    startDate: "2026-02-28",
    endDate: "2026-03-20",
    status: "active",
    platforms: ["instagram", "youtube", "linkedin"],
    postCount: 8,
    totalReach: 28000,
    totalEngagement: 1800,
    leads: 86,
    revenue: 0,
    managedBy: "Dev",
  },
];

export const mediaAssets: MediaAsset[] = [
  { id: "MED-001", name: "Suprans Primary Logo (White)", type: "logo", brand: "Suprans", status: "approved", uploadedBy: "Priya", uploadedDate: "2025-06-10", tags: ["logo", "white", "primary"], size: "48 KB" },
  { id: "MED-002", name: "Suprans Primary Logo (Dark)", type: "logo", brand: "Suprans", status: "approved", uploadedBy: "Priya", uploadedDate: "2025-06-10", tags: ["logo", "dark", "primary"], size: "52 KB" },
  { id: "MED-003", name: "LegalNations Logo (Blue)", type: "logo", brand: "LegalNations", status: "approved", uploadedBy: "Priya", uploadedDate: "2025-09-14", tags: ["logo", "blue", "primary"], size: "38 KB" },
  { id: "MED-004", name: "USDrop AI Logo (White)", type: "logo", brand: "USDrop", status: "approved", uploadedBy: "Priya", uploadedDate: "2025-10-02", tags: ["logo", "white"], size: "44 KB" },
  { id: "MED-005", name: "Gullee Logo (Dark)", type: "logo", brand: "Gullee", status: "approved", uploadedBy: "Priya", uploadedDate: "2026-02-10", tags: ["logo", "dark"], size: "36 KB" },
  { id: "MED-006", name: "Diwali Reel Thumbnail", type: "thumbnail", brand: "Suprans", status: "approved", uploadedBy: "Priya", uploadedDate: "2025-10-28", tags: ["diwali", "reel", "thumbnail", "festive"], size: "320 KB" },
  { id: "MED-007", name: "US LLC Guide Cover", type: "image", brand: "LegalNations", status: "approved", uploadedBy: "Rahul", uploadedDate: "2026-01-10", tags: ["carousel", "cover", "guide"], size: "280 KB" },
  { id: "MED-008", name: "Spring Drop Hero Image", type: "image", brand: "USDrop", status: "approved", uploadedBy: "Priya", uploadedDate: "2026-02-12", tags: ["spring", "hero", "launch"], size: "480 KB" },
  { id: "MED-009", name: "Gullee Intro Reel Raw Footage", type: "reel", brand: "Gullee", status: "approved", uploadedBy: "Rahul", uploadedDate: "2026-02-18", tags: ["intro", "reel", "raw"], size: "84 MB" },
  { id: "MED-010", name: "Suprans Brand Story B-Roll", type: "video", brand: "Suprans", status: "approved", uploadedBy: "Rahul", uploadedDate: "2026-02-05", tags: ["brand", "b-roll", "founder"], size: "210 MB" },
  { id: "MED-011", name: "Instagram Story Template Pack", type: "story-template", brand: "Suprans", status: "approved", uploadedBy: "Priya", uploadedDate: "2025-12-01", tags: ["template", "story", "pack", "instagram"], size: "1.2 MB" },
  { id: "MED-012", name: "Gullee Story Template (Launch)", type: "story-template", brand: "Gullee", status: "approved", uploadedBy: "Priya", uploadedDate: "2026-02-14", tags: ["template", "story", "launch"], size: "840 KB" },
  { id: "MED-013", name: "Webinar Promo Static (Draft)", type: "image", brand: "Suprans", status: "draft", uploadedBy: "Priya", uploadedDate: "2026-02-25", tags: ["webinar", "promo", "draft"], size: "380 KB" },
  { id: "MED-014", name: "BOI Alert Graphic (Draft)", type: "image", brand: "LegalNations", status: "draft", uploadedBy: "Rahul", uploadedDate: "2026-02-24", tags: ["boi", "compliance", "alert", "draft"], size: "290 KB" },
  { id: "MED-015", name: "USDrop AI Feature Reel (Draft)", type: "reel", brand: "USDrop", status: "draft", uploadedBy: "Rahul", uploadedDate: "2026-02-26", tags: ["ai", "feature", "reel", "draft"], size: "62 MB" },
  { id: "MED-016", name: "LegalNations Event Flyer", type: "image", brand: "LegalNations", status: "draft", uploadedBy: "Priya", uploadedDate: "2026-02-27", tags: ["event", "flyer", "mumbai"], size: "440 KB" },
  { id: "MED-017", name: "Suprans EIN Guide Thumbnail", type: "thumbnail", brand: "Suprans", status: "draft", uploadedBy: "Priya", uploadedDate: "2026-02-28", tags: ["ein", "guide", "thumbnail"], size: "260 KB" },
  { id: "MED-018", name: "Gullee Homeware Lifestyle Photos", type: "image", brand: "Gullee", status: "approved", uploadedBy: "Rahul", uploadedDate: "2026-02-20", tags: ["lifestyle", "homeware", "photography"], size: "2.4 MB" },
  { id: "MED-019", name: "Suprans LinkedIn Banner", type: "image", brand: "Suprans", status: "approved", uploadedBy: "Priya", uploadedDate: "2025-11-15", tags: ["linkedin", "banner", "brand"], size: "180 KB" },
  { id: "MED-020", name: "Gullee Unboxing Raw Footage", type: "video", brand: "Gullee", status: "draft", uploadedBy: "Rahul", uploadedDate: "2026-02-27", tags: ["unboxing", "raw", "video"], size: "1.8 GB" },
];

export const approvalRequests: ApprovalRequest[] = [
  {
    id: "APR-001",
    postId: "POST-011",
    postTitle: "LegalNations Event Promo Reel",
    postCaption: "🎤 LIVE EVENT: 'Build Your Global Business from India' — Join our founder Arjun Sharma + 3 guest experts for an evening of insights, networking, and Q&A. Mumbai | March 20 | Free entry. Register now → link in bio.",
    platforms: ["instagram", "linkedin"],
    brand: "LegalNations",
    submittedBy: "Ananya",
    submittedDate: "2026-02-27",
    status: "pending",
    approverComment: "",
    reviewedDate: null,
    priority: "high",
  },
  {
    id: "APR-002",
    postId: "POST-012",
    postTitle: "Suprans Webinar Promo",
    postCaption: "Free LIVE Webinar: 'How Indian Founders Are Building US Businesses Without Moving Abroad' 📅 March 15 | 7PM IST | Zoom (link in bio) Spots are filling up — save your seat now!",
    platforms: ["instagram", "linkedin"],
    brand: "Suprans",
    submittedBy: "Dev",
    submittedDate: "2026-02-27",
    status: "pending",
    approverComment: "",
    reviewedDate: null,
    priority: "high",
  },
  {
    id: "APR-003",
    postId: "POST-013",
    postTitle: "USDrop AI Sourcing Feature",
    postCaption: "You asked. We built it. 🤖 Introducing AI-powered product sourcing on USDrop. Let our AI scan 10,000+ US suppliers and surface winning products for YOUR niche. Launch your store smarter. Try it free → link in bio.",
    platforms: ["instagram"],
    brand: "USDrop",
    submittedBy: "Rahul",
    submittedDate: "2026-02-28",
    status: "pending",
    approverComment: "",
    reviewedDate: null,
    priority: "high",
  },
  {
    id: "APR-004",
    postId: "POST-007",
    postTitle: "LegalNations Compliance Alert",
    postCaption: "⚠️ IMPORTANT: If your US LLC was formed before Jan 2025, you now have a FinCEN BOI filing requirement. Deadline is March 31. Non-compliance = heavy fines. DM us or visit link in bio to file with LegalNations today.",
    platforms: ["instagram", "linkedin", "facebook"],
    brand: "LegalNations",
    submittedBy: "Dev",
    submittedDate: "2026-02-24",
    status: "approved",
    approverComment: "Approved. Critical compliance content. Schedule immediately.",
    reviewedDate: "2026-02-25",
    priority: "high",
  },
  {
    id: "APR-005",
    postId: "POST-006",
    postTitle: "Suprans YouTube Webinar Recap",
    postCaption: "Did you miss our live webinar on 'How to Register Your US Company While Staying in India'? Full recording is now up! 45 mins packed with real steps, real costs, real experiences. Watch now.",
    platforms: ["youtube"],
    brand: "Suprans",
    submittedBy: "Rahul",
    submittedDate: "2026-02-26",
    status: "approved",
    approverComment: "Great recap. Schedule for Wednesday AM slot.",
    reviewedDate: "2026-02-27",
    priority: "normal",
  },
  {
    id: "APR-006",
    postId: "POST-022",
    postTitle: "USDrop Supplier Network Post",
    postCaption: "10,000+ US suppliers. Zero import headaches. Delivered to your customer in 3–5 days. That's the USDrop difference.",
    platforms: ["instagram"],
    brand: "USDrop",
    submittedBy: "Dev",
    submittedDate: "2026-02-20",
    status: "rejected",
    approverComment: "Too generic. This won't stop the scroll. Need a stronger opening hook and specific stat or story.",
    reviewedDate: "2026-02-21",
    priority: "normal",
  },
  {
    id: "APR-007",
    postId: "POST-023",
    postTitle: "Suprans Diwali Story Pack",
    postCaption: "Diwali greetings from the Suprans team 🪔🎉",
    platforms: ["instagram"],
    brand: "Suprans",
    submittedBy: "Priya",
    submittedDate: "2025-10-30",
    status: "rejected",
    approverComment: "Design doesn't meet our brand standards. Colors are off-brand. Please use the approved template from the media library.",
    reviewedDate: "2025-10-31",
    priority: "normal",
  },
  {
    id: "APR-008",
    postId: "POST-001",
    postTitle: "Suprans Diwali Reel",
    postCaption: "✨ This Diwali, let your business shine brighter than ever! 🪔 We helped 200+ founders register their US companies from India — and now it's your turn.",
    platforms: ["instagram", "facebook"],
    brand: "Suprans",
    submittedBy: "Ananya",
    submittedDate: "2025-10-28",
    status: "approved",
    approverComment: "Love this! The hook is strong. Approved. Add the Diwali discount code in the caption before posting.",
    reviewedDate: "2025-10-29",
    priority: "high",
  },
];

export const assignments: Assignment[] = [
  { id: "ASN-001", title: "Write 3 caption options for LegalNations Event Promo", type: "caption", assignedTo: "Dev", role: "Copywriter", postId: "POST-011", postTitle: "LegalNations Event Promo Reel", campaignId: "CAMP-002", dueDate: "2026-03-01", status: "done", notes: "All 3 options submitted. Ananya chose option 2." },
  { id: "ASN-002", title: "Design carousel slides for US LLC Guide", type: "design", assignedTo: "Priya", role: "Designer", postId: "POST-002", postTitle: "LegalNations US LLC Guide Carousel", campaignId: "CAMP-002", dueDate: "2026-01-12", status: "done", notes: "All 8 slides delivered and approved." },
  { id: "ASN-003", title: "Script for USDrop AI Feature Reel (60s)", type: "script", assignedTo: "Rahul", role: "Content Creator", postId: "POST-013", postTitle: "USDrop AI Sourcing Feature", campaignId: "CAMP-003", dueDate: "2026-02-25", status: "done", notes: "Script delivered. Approved by Ananya." },
  { id: "ASN-004", title: "Edit Gullee Intro Reel (final cut)", type: "design", assignedTo: "Priya", role: "Designer/Video Editor", postId: "POST-005", postTitle: "Gullee Brand Intro Reel", campaignId: "CAMP-005", dueDate: "2026-02-19", status: "done", notes: "Final cut delivered. Minor color grading done." },
  { id: "ASN-005", title: "Write caption for Suprans EIN Guide Reel", type: "caption", assignedTo: "Dev", role: "Copywriter", postId: "POST-018", postTitle: "Suprans EIN Guide Script", campaignId: "CAMP-002", dueDate: "2026-03-05", status: "in-progress", notes: "Waiting for script to be finalized first." },
  { id: "ASN-006", title: "Design BOI Alert graphic for Instagram + LinkedIn", type: "design", assignedTo: "Priya", role: "Designer", postId: "POST-021", postTitle: "LegalNations BOI Explainer Reel", campaignId: "CAMP-002", dueDate: "2026-03-04", status: "in-progress", notes: "Draft in progress. Brand colors to be verified." },
  { id: "ASN-007", title: "Schedule March 5–15 posts across all accounts", type: "scheduling", assignedTo: "Ananya", role: "Social Media Manager", postId: null, postTitle: null, campaignId: null, dueDate: "2026-03-04", status: "in-progress", notes: "10 posts to schedule. 4 done, 6 remaining." },
  { id: "ASN-008", title: "Write Gullee homeware carousel captions (10 slides)", type: "caption", assignedTo: "Dev", role: "Copywriter", postId: "POST-010", postTitle: "Gullee Homeware Carousel", campaignId: "CAMP-005", dueDate: "2026-03-03", status: "in-progress", notes: "7 of 10 captions written." },
  { id: "ASN-009", title: "Shoot Gullee unboxing content (3 SKUs)", type: "design", assignedTo: "Rahul", role: "Content Creator", postId: "POST-014", postTitle: "Gullee YouTube Short — Unboxing", campaignId: "CAMP-005", dueDate: "2026-03-02", status: "overdue", notes: "Shoot rescheduled twice due to product availability. Needs immediate action." },
  { id: "ASN-010", title: "February Monthly Analytics Report", type: "reporting", assignedTo: "Ananya", role: "Social Media Manager", postId: null, postTitle: null, campaignId: null, dueDate: "2026-02-28", status: "overdue", notes: "Due today. Platform data export pending from YouTube." },
  { id: "ASN-011", title: "Script for Suprans Webinar Promo Reel", type: "script", assignedTo: "Rahul", role: "Content Creator", postId: "POST-012", postTitle: "Suprans Webinar Promo", campaignId: "CAMP-006", dueDate: "2026-03-08", status: "pending", notes: "Not started. Waiting for webinar agenda from Dev." },
  { id: "ASN-012", title: "Design USDrop Spring Drop hero static", type: "design", assignedTo: "Priya", role: "Designer", postId: "POST-008", postTitle: "USDrop Product Spotlight Carousel", campaignId: "CAMP-003", dueDate: "2026-03-06", status: "pending", notes: "Brief shared. Not started." },
];
