import type { DealStage, ActivityType, TemplateType, ContactSource, CompanySize, CrmContact, CrmCompany, CrmDeal, CrmActivity, MessageTemplate, TeamPerformance } from "@/types/crm";
export type { DealStage, ActivityType, TemplateType, ContactSource, CompanySize, CrmContact, CrmCompany, CrmDeal, CrmActivity, MessageTemplate, TeamPerformance };


export const crmContacts: CrmContact[] = [
  {
    id: "c001",
    name: "Priya Sharma",
    email: "priya.sharma@nexatech.in",
    phone: "+91 98201 34567",
    company: "NexaTech Solutions",
    designation: "Head of Operations",
    vertical: "hr",
    source: "linkedin",
    city: "Mumbai",
    country: "India",
    assignedTo: "Rahul Verma",
    tags: ["enterprise", "HR-software"],
    lastActivity: "2026-02-25",
    addedDate: "2026-01-10",
    status: "prospect",
    nurtureScore: 82,
    nextAction: "Send proposal by Mar 3",
    expectedValue: 450000,
  },
  {
    id: "c002",
    name: "Aditya Kapoor",
    email: "aditya.kapoor@brightbridge.com",
    phone: "+91 99001 22345",
    company: "BrightBridge Commerce",
    designation: "CEO",
    vertical: "sales",
    source: "referral",
    city: "Bengaluru",
    country: "India",
    assignedTo: "Sneha Reddy",
    tags: ["d2c", "high-value"],
    lastActivity: "2026-02-26",
    addedDate: "2026-01-15",
    status: "prospect",
    nurtureScore: 74,
    nextAction: "Demo call scheduled Mar 5",
    expectedValue: 280000,
  },
  {
    id: "c003",
    name: "Mei Lin",
    email: "mei.lin@chinatradelink.cn",
    phone: "+86 138 0012 3456",
    company: "China Trade Link",
    designation: "VP Business Development",
    vertical: "events",
    source: "event",
    city: "Shanghai",
    country: "China",
    assignedTo: "Arjun Nair",
    tags: ["b2b-travel", "china"],
    lastActivity: "2026-02-24",
    addedDate: "2026-01-20",
    status: "prospect",
    nurtureScore: 91,
    nextAction: "Finalize tour package pricing",
    expectedValue: 1250000,
  },
  {
    id: "c004",
    name: "Suresh Iyer",
    email: "suresh@eventpro.in",
    phone: "+91 97303 88901",
    company: "EventPro India",
    designation: "Events Director",
    vertical: "eventhub",
    source: "website",
    city: "Delhi",
    country: "India",
    assignedTo: "Priya Menon",
    tags: ["events", "mid-market"],
    lastActivity: "2026-02-22",
    addedDate: "2026-01-25",
    status: "lead",
    nurtureScore: 45,
    nextAction: "Follow up after conference",
  },
  {
    id: "c005",
    name: "Kavita Nair",
    email: "kavita@luxelifestyle.in",
    phone: "+91 96010 77234",
    company: "Luxe Lifestyle Co.",
    designation: "Procurement Manager",
    vertical: "admin",
    source: "partner",
    city: "Pune",
    country: "India",
    assignedTo: "Rahul Verma",
    tags: ["b2b-ecommerce", "luxury"],
    lastActivity: "2026-02-20",
    addedDate: "2026-02-01",
    status: "prospect",
    nurtureScore: 63,
    nextAction: "Share catalog by Feb 28",
    expectedValue: 380000,
  },
  {
    id: "c006",
    name: "Rohan Mehta",
    email: "rohan@quicksell.io",
    phone: "+91 91234 56789",
    company: "QuickSell Retail",
    designation: "Founder",
    vertical: "ets",
    source: "cold-outreach",
    city: "Ahmedabad",
    country: "India",
    assignedTo: "Sneha Reddy",
    tags: ["retail", "franchise"],
    lastActivity: "2026-02-19",
    addedDate: "2026-02-05",
    status: "lead",
    nurtureScore: 38,
    nextAction: "Send intro deck",
  },
  {
    id: "c007",
    name: "Sarah Mitchell",
    email: "sarah@boutiquehaven.com",
    phone: "+1 415 555 0198",
    company: "Boutique Haven LLC",
    designation: "Buying Director",
    vertical: "faire",
    source: "inbound",
    city: "San Francisco",
    country: "USA",
    assignedTo: "Arjun Nair",
    tags: ["faire-marketplace", "usa"],
    lastActivity: "2026-02-27",
    addedDate: "2026-01-08",
    status: "customer",
    nurtureScore: 95,
    expectedValue: 18000,
  },
  {
    id: "c008",
    name: "Deepak Joshi",
    email: "deepak.joshi@peoplefirst.in",
    phone: "+91 90000 12345",
    company: "People First HR",
    designation: "CHRO",
    vertical: "hrms",
    source: "linkedin",
    city: "Hyderabad",
    country: "India",
    assignedTo: "Priya Menon",
    tags: ["hrms", "enterprise"],
    lastActivity: "2026-02-23",
    addedDate: "2026-01-30",
    status: "prospect",
    nurtureScore: 77,
    nextAction: "Product demo this Friday",
    expectedValue: 720000,
  },
  {
    id: "c009",
    name: "Ananya Singh",
    email: "ananya@talentrise.co",
    phone: "+91 87654 32100",
    company: "TalentRise Consulting",
    designation: "Head of Talent",
    vertical: "ats",
    source: "referral",
    city: "Chennai",
    country: "India",
    assignedTo: "Rahul Verma",
    tags: ["recruitment", "consulting"],
    lastActivity: "2026-02-26",
    addedDate: "2026-02-10",
    status: "prospect",
    nurtureScore: 69,
    nextAction: "Send ATS comparison document",
    expectedValue: 240000,
  },
  {
    id: "c010",
    name: "Vikram Bose",
    email: "vikram@buzzcraft.agency",
    phone: "+91 99990 87654",
    company: "BuzzCraft Agency",
    designation: "Creative Director",
    vertical: "social",
    source: "event",
    city: "Kolkata",
    country: "India",
    assignedTo: "Sneha Reddy",
    tags: ["content", "agency"],
    lastActivity: "2026-02-21",
    addedDate: "2026-02-08",
    status: "lead",
    nurtureScore: 52,
    nextAction: "Schedule discovery call",
  },
  {
    id: "c011",
    name: "Lin Wei",
    email: "lin.wei@horizongroup.cn",
    phone: "+86 135 9876 5432",
    company: "Horizon Group",
    designation: "GM Partnerships",
    vertical: "events",
    source: "partner",
    city: "Beijing",
    country: "China",
    assignedTo: "Arjun Nair",
    tags: ["china", "corporate-travel"],
    lastActivity: "2026-02-25",
    addedDate: "2026-01-12",
    status: "prospect",
    nurtureScore: 85,
    nextAction: "Finalize group booking terms",
    expectedValue: 850000,
  },
  {
    id: "c012",
    name: "Nisha Patel",
    email: "nisha@digitalhub.in",
    phone: "+91 93003 21098",
    company: "Digital Hub India",
    designation: "COO",
    vertical: "dev",
    source: "website",
    city: "Jaipur",
    country: "India",
    assignedTo: "Priya Menon",
    tags: ["tech", "internal-tools"],
    lastActivity: "2026-02-18",
    addedDate: "2026-02-12",
    status: "lead",
    nurtureScore: 41,
    nextAction: "Technical requirements call",
  },
  {
    id: "c013",
    name: "Amit Chaudhary",
    email: "amit@compliancezone.in",
    phone: "+91 98765 43210",
    company: "ComplianceZone",
    designation: "Legal Director",
    vertical: "hr",
    source: "cold-outreach",
    city: "Noida",
    country: "India",
    assignedTo: "Rahul Verma",
    tags: ["compliance", "legal"],
    lastActivity: "2026-02-27",
    addedDate: "2026-02-15",
    status: "prospect",
    nurtureScore: 78,
    nextAction: "Send contract draft",
    expectedValue: 560000,
  },
  {
    id: "c014",
    name: "Emma Thompson",
    email: "emma@artisangoods.co",
    phone: "+1 347 555 0167",
    company: "Artisan Goods Co.",
    designation: "Brand Manager",
    vertical: "faire",
    source: "inbound",
    city: "New York",
    country: "USA",
    assignedTo: "Arjun Nair",
    tags: ["faire", "artisan"],
    lastActivity: "2026-02-26",
    addedDate: "2026-01-22",
    status: "customer",
    nurtureScore: 88,
    expectedValue: 22000,
  },
  {
    id: "c015",
    name: "Pooja Krishnan",
    email: "pooja@fashionhub.in",
    phone: "+91 94400 55678",
    company: "FashionHub India",
    designation: "Business Head",
    vertical: "admin",
    source: "referral",
    city: "Mumbai",
    country: "India",
    assignedTo: "Sneha Reddy",
    tags: ["lifestyle", "fashion"],
    lastActivity: "2026-02-24",
    addedDate: "2026-02-03",
    status: "prospect",
    nurtureScore: 71,
    nextAction: "Review partnership terms",
    expectedValue: 490000,
  },
  {
    id: "c016",
    name: "Rajesh Kumar",
    email: "rajesh@supplychain.co.in",
    phone: "+91 92100 67890",
    company: "SupplyChain Co.",
    designation: "MD",
    vertical: "sales",
    source: "linkedin",
    city: "Surat",
    country: "India",
    assignedTo: "Priya Menon",
    tags: ["dropshipping", "supply-chain"],
    lastActivity: "2026-02-20",
    addedDate: "2026-01-28",
    status: "prospect",
    nurtureScore: 58,
    nextAction: "Integrate with USDrop platform",
    expectedValue: 160000,
  },
  {
    id: "c017",
    name: "Akira Tanaka",
    email: "akira.tanaka@tokyoevents.jp",
    phone: "+81 90-1234-5678",
    company: "Tokyo Events Corp",
    designation: "International Relations",
    vertical: "events",
    source: "event",
    city: "Tokyo",
    country: "Japan",
    assignedTo: "Arjun Nair",
    tags: ["japan", "travel"],
    lastActivity: "2026-02-22",
    addedDate: "2026-02-01",
    status: "lead",
    nurtureScore: 47,
    nextAction: "Follow up post webinar",
  },
  {
    id: "c018",
    name: "Geeta Rao",
    email: "geeta.rao@hrworks.in",
    phone: "+91 88810 34560",
    company: "HRWorks Pvt Ltd",
    designation: "VP HR",
    vertical: "hrms",
    source: "website",
    city: "Bengaluru",
    country: "India",
    assignedTo: "Rahul Verma",
    tags: ["hrms", "mid-market"],
    lastActivity: "2026-02-25",
    addedDate: "2026-02-07",
    status: "prospect",
    nurtureScore: 66,
    nextAction: "Free trial activation",
    expectedValue: 320000,
  },
  {
    id: "c019",
    name: "Karan Malhotra",
    email: "karan@socialboost.in",
    phone: "+91 99112 78900",
    company: "SocialBoost Agency",
    designation: "Founder",
    vertical: "social",
    source: "cold-outreach",
    city: "Delhi",
    country: "India",
    assignedTo: "Sneha Reddy",
    tags: ["social-media", "agency"],
    lastActivity: "2026-02-17",
    addedDate: "2026-02-14",
    status: "lead",
    nurtureScore: 33,
    nextAction: "Initial discovery email",
  },
  {
    id: "c020",
    name: "Sunita Desai",
    email: "sunita@legalconsult.in",
    phone: "+91 96780 12300",
    company: "LegalConsult India",
    designation: "Managing Partner",
    vertical: "hr",
    source: "referral",
    city: "Hyderabad",
    country: "India",
    assignedTo: "Priya Menon",
    tags: ["legal", "compliance"],
    lastActivity: "2026-02-27",
    addedDate: "2026-01-18",
    status: "customer",
    nurtureScore: 93,
    expectedValue: 680000,
  },
];

export const crmCompanies: CrmCompany[] = [
  {
    id: "co001",
    name: "NexaTech Solutions",
    website: "nexatech.in",
    industry: "Technology",
    size: "201-500",
    vertical: "hr",
    city: "Mumbai",
    country: "India",
    dealCount: 2,
    revenuePotential: 900000,
    assignedTo: "Rahul Verma",
    addedDate: "2026-01-10",
    contacts: ["c001"],
  },
  {
    id: "co002",
    name: "BrightBridge Commerce",
    website: "brightbridge.com",
    industry: "E-Commerce",
    size: "51-200",
    vertical: "sales",
    city: "Bengaluru",
    country: "India",
    dealCount: 1,
    revenuePotential: 280000,
    assignedTo: "Sneha Reddy",
    addedDate: "2026-01-15",
    contacts: ["c002"],
  },
  {
    id: "co003",
    name: "China Trade Link",
    website: "chinatradelink.cn",
    industry: "Travel & Hospitality",
    size: "201-500",
    vertical: "events",
    city: "Shanghai",
    country: "China",
    dealCount: 3,
    revenuePotential: 2500000,
    assignedTo: "Arjun Nair",
    addedDate: "2026-01-20",
    contacts: ["c003"],
  },
  {
    id: "co004",
    name: "EventPro India",
    website: "eventpro.in",
    industry: "Event Management",
    size: "11-50",
    vertical: "eventhub",
    city: "Delhi",
    country: "India",
    dealCount: 1,
    revenuePotential: 120000,
    assignedTo: "Priya Menon",
    addedDate: "2026-01-25",
    contacts: ["c004"],
  },
  {
    id: "co005",
    name: "Luxe Lifestyle Co.",
    website: "luxelifestyle.in",
    industry: "Lifestyle & Retail",
    size: "51-200",
    vertical: "admin",
    city: "Pune",
    country: "India",
    dealCount: 2,
    revenuePotential: 760000,
    assignedTo: "Rahul Verma",
    addedDate: "2026-02-01",
    contacts: ["c005"],
  },
  {
    id: "co006",
    name: "QuickSell Retail",
    website: "quicksell.io",
    industry: "Retail",
    size: "1-10",
    vertical: "ets",
    city: "Ahmedabad",
    country: "India",
    dealCount: 1,
    revenuePotential: 95000,
    assignedTo: "Sneha Reddy",
    addedDate: "2026-02-05",
    contacts: ["c006"],
  },
  {
    id: "co007",
    name: "Boutique Haven LLC",
    website: "boutiquehaven.com",
    industry: "Retail",
    size: "11-50",
    vertical: "faire",
    city: "San Francisco",
    country: "USA",
    dealCount: 2,
    revenuePotential: 36000,
    assignedTo: "Arjun Nair",
    addedDate: "2026-01-08",
    contacts: ["c007"],
  },
  {
    id: "co008",
    name: "People First HR",
    website: "peoplefirst.in",
    industry: "HR Consulting",
    size: "201-500",
    vertical: "hrms",
    city: "Hyderabad",
    country: "India",
    dealCount: 1,
    revenuePotential: 720000,
    assignedTo: "Priya Menon",
    addedDate: "2026-01-30",
    contacts: ["c008"],
  },
  {
    id: "co009",
    name: "TalentRise Consulting",
    website: "talentrise.co",
    industry: "Staffing",
    size: "51-200",
    vertical: "ats",
    city: "Chennai",
    country: "India",
    dealCount: 1,
    revenuePotential: 240000,
    assignedTo: "Rahul Verma",
    addedDate: "2026-02-10",
    contacts: ["c009"],
  },
  {
    id: "co010",
    name: "BuzzCraft Agency",
    website: "buzzcraft.agency",
    industry: "Marketing & Advertising",
    size: "11-50",
    vertical: "social",
    city: "Kolkata",
    country: "India",
    dealCount: 1,
    revenuePotential: 180000,
    assignedTo: "Sneha Reddy",
    addedDate: "2026-02-08",
    contacts: ["c010"],
  },
  {
    id: "co011",
    name: "Horizon Group",
    website: "horizongroup.cn",
    industry: "Conglomerate",
    size: "500+",
    vertical: "events",
    city: "Beijing",
    country: "China",
    dealCount: 2,
    revenuePotential: 1700000,
    assignedTo: "Arjun Nair",
    addedDate: "2026-01-12",
    contacts: ["c011"],
  },
  {
    id: "co012",
    name: "ComplianceZone",
    website: "compliancezone.in",
    industry: "Legal & Compliance",
    size: "51-200",
    vertical: "hr",
    city: "Noida",
    country: "India",
    dealCount: 1,
    revenuePotential: 560000,
    assignedTo: "Rahul Verma",
    addedDate: "2026-02-15",
    contacts: ["c013"],
  },
  {
    id: "co013",
    name: "Artisan Goods Co.",
    website: "artisangoods.co",
    industry: "Retail",
    size: "11-50",
    vertical: "faire",
    city: "New York",
    country: "USA",
    dealCount: 1,
    revenuePotential: 22000,
    assignedTo: "Arjun Nair",
    addedDate: "2026-01-22",
    contacts: ["c014"],
  },
  {
    id: "co014",
    name: "FashionHub India",
    website: "fashionhub.in",
    industry: "Fashion & Apparel",
    size: "201-500",
    vertical: "admin",
    city: "Mumbai",
    country: "India",
    dealCount: 2,
    revenuePotential: 980000,
    assignedTo: "Sneha Reddy",
    addedDate: "2026-02-03",
    contacts: ["c015"],
  },
  {
    id: "co015",
    name: "LegalConsult India",
    website: "legalconsult.in",
    industry: "Legal Services",
    size: "51-200",
    vertical: "hr",
    city: "Hyderabad",
    country: "India",
    dealCount: 3,
    revenuePotential: 1360000,
    assignedTo: "Priya Menon",
    addedDate: "2026-01-18",
    contacts: ["c020"],
  },
];

export const crmDeals: CrmDeal[] = [
  {
    id: "d001",
    title: "LegalNations HR Suite — Annual License",
    contactId: "c001",
    contactName: "Priya Sharma",
    companyName: "NexaTech Solutions",
    vertical: "hr",
    value: 450000,
    currency: "INR",
    stage: "proposal",
    probability: 70,
    expectedClose: "2026-03-15",
    assignedTo: "Rahul Verma",
    createdDate: "2026-01-20",
    lastActivity: "2026-02-25",
    source: "linkedin",
    priority: "high",
    notes: "Decision maker confirmed. Awaiting procurement approval.",
    tags: ["enterprise", "annual"],
  },
  {
    id: "d002",
    title: "USDrop AI Pro Plan — Q1 Onboarding",
    contactId: "c002",
    contactName: "Aditya Kapoor",
    companyName: "BrightBridge Commerce",
    vertical: "sales",
    value: 280000,
    currency: "INR",
    stage: "negotiation",
    probability: 80,
    expectedClose: "2026-03-05",
    assignedTo: "Sneha Reddy",
    createdDate: "2026-01-22",
    lastActivity: "2026-02-26",
    source: "referral",
    priority: "high",
    notes: "Discount requested. Final terms under review.",
    tags: ["d2c", "pro"],
  },
  {
    id: "d003",
    title: "GoyoTours China Group Package — 80 Pax",
    contactId: "c003",
    contactName: "Mei Lin",
    companyName: "China Trade Link",
    vertical: "events",
    value: 1250000,
    currency: "INR",
    stage: "negotiation",
    probability: 85,
    expectedClose: "2026-03-10",
    assignedTo: "Arjun Nair",
    createdDate: "2026-01-25",
    lastActivity: "2026-02-24",
    source: "event",
    priority: "high",
    notes: "Visa support confirmed. Pricing finalization pending.",
    tags: ["group-tour", "china"],
  },
  {
    id: "d004",
    title: "EventHub Corporate Membership",
    contactId: "c004",
    contactName: "Suresh Iyer",
    companyName: "EventPro India",
    vertical: "eventhub",
    value: 85000,
    currency: "INR",
    stage: "contacted",
    probability: 30,
    expectedClose: "2026-04-01",
    assignedTo: "Priya Menon",
    createdDate: "2026-02-01",
    lastActivity: "2026-02-22",
    source: "website",
    priority: "medium",
    notes: "Needs more info on event calendar.",
    tags: ["membership"],
  },
  {
    id: "d005",
    title: "LBM Lifestyle B2B Catalog — Season Drop",
    contactId: "c005",
    contactName: "Kavita Nair",
    companyName: "Luxe Lifestyle Co.",
    vertical: "admin",
    value: 380000,
    currency: "INR",
    stage: "proposal",
    probability: 60,
    expectedClose: "2026-03-20",
    assignedTo: "Rahul Verma",
    createdDate: "2026-02-05",
    lastActivity: "2026-02-20",
    source: "partner",
    priority: "medium",
    notes: "Catalog shared. Awaiting SKU selection confirmation.",
    tags: ["b2b", "catalog"],
  },
  {
    id: "d006",
    title: "EazyToSell Franchise Starter Kit",
    contactId: "c006",
    contactName: "Rohan Mehta",
    companyName: "QuickSell Retail",
    vertical: "ets",
    value: 95000,
    currency: "INR",
    stage: "new",
    probability: 20,
    expectedClose: "2026-04-15",
    assignedTo: "Sneha Reddy",
    createdDate: "2026-02-10",
    lastActivity: "2026-02-19",
    source: "cold-outreach",
    priority: "low",
    notes: "Initial interest. Intro deck to be sent.",
    tags: ["franchise", "starter"],
  },
  {
    id: "d007",
    title: "FaireDesk Premium Marketplace Access",
    contactId: "c007",
    contactName: "Sarah Mitchell",
    companyName: "Boutique Haven LLC",
    vertical: "faire",
    value: 18000,
    currency: "USD",
    stage: "won",
    probability: 100,
    expectedClose: "2026-02-15",
    assignedTo: "Arjun Nair",
    createdDate: "2026-01-10",
    lastActivity: "2026-02-15",
    source: "inbound",
    priority: "medium",
    notes: "Deal closed. Onboarding in progress.",
    tags: ["won", "premium"],
  },
  {
    id: "d008",
    title: "HRMS Enterprise Platform — 500 Seats",
    contactId: "c008",
    contactName: "Deepak Joshi",
    companyName: "People First HR",
    vertical: "hrms",
    value: 720000,
    currency: "INR",
    stage: "qualified",
    probability: 55,
    expectedClose: "2026-04-10",
    assignedTo: "Priya Menon",
    createdDate: "2026-02-02",
    lastActivity: "2026-02-23",
    source: "linkedin",
    priority: "high",
    notes: "Trial underway. Decision expected post-evaluation.",
    tags: ["enterprise", "hrms"],
  },
  {
    id: "d009",
    title: "ATS Pro — Annual Recruitment Suite",
    contactId: "c009",
    contactName: "Ananya Singh",
    companyName: "TalentRise Consulting",
    vertical: "ats",
    value: 240000,
    currency: "INR",
    stage: "qualified",
    probability: 50,
    expectedClose: "2026-03-28",
    assignedTo: "Rahul Verma",
    createdDate: "2026-02-12",
    lastActivity: "2026-02-26",
    source: "referral",
    priority: "medium",
    notes: "Comparison with competitors in progress.",
    tags: ["ats", "annual"],
  },
  {
    id: "d010",
    title: "SocialDesk Content Management — 6 Months",
    contactId: "c010",
    contactName: "Vikram Bose",
    companyName: "BuzzCraft Agency",
    vertical: "social",
    value: 180000,
    currency: "INR",
    stage: "new",
    probability: 15,
    expectedClose: "2026-05-01",
    assignedTo: "Sneha Reddy",
    createdDate: "2026-02-14",
    lastActivity: "2026-02-21",
    source: "event",
    priority: "low",
    notes: "Discovery call pending.",
    tags: ["social", "6-month"],
  },
  {
    id: "d011",
    title: "GoyoTours Beijing + Xi'an Package — 40 Pax",
    contactId: "c011",
    contactName: "Lin Wei",
    companyName: "Horizon Group",
    vertical: "events",
    value: 850000,
    currency: "INR",
    stage: "proposal",
    probability: 65,
    expectedClose: "2026-03-25",
    assignedTo: "Arjun Nair",
    createdDate: "2026-01-18",
    lastActivity: "2026-02-25",
    source: "partner",
    priority: "high",
    notes: "Proposal submitted. Awaiting group lead confirmation.",
    tags: ["group-tour", "enterprise"],
  },
  {
    id: "d012",
    title: "LegalNations Compliance Audit Module",
    contactId: "c013",
    contactName: "Amit Chaudhary",
    companyName: "ComplianceZone",
    vertical: "hr",
    value: 560000,
    currency: "INR",
    stage: "negotiation",
    probability: 75,
    expectedClose: "2026-03-08",
    assignedTo: "Rahul Verma",
    createdDate: "2026-02-16",
    lastActivity: "2026-02-27",
    source: "cold-outreach",
    priority: "high",
    notes: "Contract draft in review. Legal sign-off pending.",
    tags: ["compliance", "module"],
  },
  {
    id: "d013",
    title: "FaireDesk Annual Wholesale Access",
    contactId: "c014",
    contactName: "Emma Thompson",
    companyName: "Artisan Goods Co.",
    vertical: "faire",
    value: 22000,
    currency: "USD",
    stage: "won",
    probability: 100,
    expectedClose: "2026-02-20",
    assignedTo: "Arjun Nair",
    createdDate: "2026-01-25",
    lastActivity: "2026-02-20",
    source: "inbound",
    priority: "medium",
    notes: "Won. Annual renewal auto-flagged for Jan 2027.",
    tags: ["won", "annual"],
  },
  {
    id: "d014",
    title: "LBM Lifestyle Fashion Drop — Partnership",
    contactId: "c015",
    contactName: "Pooja Krishnan",
    companyName: "FashionHub India",
    vertical: "admin",
    value: 490000,
    currency: "INR",
    stage: "qualified",
    probability: 60,
    expectedClose: "2026-04-05",
    assignedTo: "Sneha Reddy",
    createdDate: "2026-02-06",
    lastActivity: "2026-02-24",
    source: "referral",
    priority: "medium",
    notes: "Terms discussion ongoing.",
    tags: ["partnership", "fashion"],
  },
  {
    id: "d015",
    title: "USDrop AI Supplier Integration",
    contactId: "c016",
    contactName: "Rajesh Kumar",
    companyName: "SupplyChain Co.",
    vertical: "sales",
    value: 160000,
    currency: "INR",
    stage: "contacted",
    probability: 35,
    expectedClose: "2026-04-20",
    assignedTo: "Priya Menon",
    createdDate: "2026-02-01",
    lastActivity: "2026-02-20",
    source: "linkedin",
    priority: "medium",
    notes: "Technical integration scoping call done.",
    tags: ["integration", "supplier"],
  },
  {
    id: "d016",
    title: "LegalNations Full Compliance Suite",
    contactId: "c020",
    contactName: "Sunita Desai",
    companyName: "LegalConsult India",
    vertical: "hr",
    value: 680000,
    currency: "INR",
    stage: "won",
    probability: 100,
    expectedClose: "2026-02-10",
    assignedTo: "Priya Menon",
    createdDate: "2026-01-20",
    lastActivity: "2026-02-10",
    source: "referral",
    priority: "high",
    notes: "Signed and live. Expansion discussions started.",
    tags: ["won", "full-suite"],
  },
  {
    id: "d017",
    title: "HRMS SME Bundle — Quarterly",
    contactId: "c018",
    contactName: "Geeta Rao",
    companyName: "HRWorks Pvt Ltd",
    vertical: "hrms",
    value: 320000,
    currency: "INR",
    stage: "proposal",
    probability: 55,
    expectedClose: "2026-03-22",
    assignedTo: "Rahul Verma",
    createdDate: "2026-02-09",
    lastActivity: "2026-02-25",
    source: "website",
    priority: "medium",
    notes: "Trial extended by 2 weeks at customer request.",
    tags: ["sme", "quarterly"],
  },
  {
    id: "d018",
    title: "GoyoTours Japan-China Bridge Tour",
    contactId: "c017",
    contactName: "Akira Tanaka",
    companyName: "Tokyo Events Corp",
    vertical: "events",
    value: 620000,
    currency: "INR",
    stage: "contacted",
    probability: 25,
    expectedClose: "2026-05-15",
    assignedTo: "Arjun Nair",
    createdDate: "2026-02-05",
    lastActivity: "2026-02-22",
    source: "event",
    priority: "medium",
    notes: "Interest confirmed post-webinar. Needs detailed itinerary.",
    tags: ["japan", "tour"],
  },
  {
    id: "d019",
    title: "ATS Basic — SME Plan",
    contactId: "c009",
    contactName: "Ananya Singh",
    companyName: "TalentRise Consulting",
    vertical: "ats",
    value: 85000,
    currency: "INR",
    stage: "lost",
    probability: 0,
    expectedClose: "2026-02-01",
    assignedTo: "Rahul Verma",
    createdDate: "2026-01-05",
    lastActivity: "2026-02-01",
    source: "referral",
    priority: "low",
    notes: "Lost to competitor. Cited price as main reason.",
    tags: ["lost", "price-sensitive"],
  },
  {
    id: "d020",
    title: "SocialDesk Brand Audit Package",
    contactId: "c019",
    contactName: "Karan Malhotra",
    companyName: "SocialBoost Agency",
    vertical: "social",
    value: 75000,
    currency: "INR",
    stage: "new",
    probability: 10,
    expectedClose: "2026-05-20",
    assignedTo: "Sneha Reddy",
    createdDate: "2026-02-15",
    lastActivity: "2026-02-17",
    source: "cold-outreach",
    priority: "low",
    notes: "Very early stage. No response yet.",
    tags: ["audit", "social"],
  },
  {
    id: "d021",
    title: "EazyToSell Multi-Store Expansion",
    contactId: "c006",
    contactName: "Rohan Mehta",
    companyName: "QuickSell Retail",
    vertical: "ets",
    value: 220000,
    currency: "INR",
    stage: "lost",
    probability: 0,
    expectedClose: "2026-02-05",
    assignedTo: "Sneha Reddy",
    createdDate: "2026-01-02",
    lastActivity: "2026-02-05",
    source: "cold-outreach",
    priority: "medium",
    notes: "Budget not approved for Q1. May revisit in Q3.",
    tags: ["lost", "budget"],
  },
  {
    id: "d022",
    title: "LBM Lifestyle Exclusive Wholesale Deal",
    contactId: "c005",
    contactName: "Kavita Nair",
    companyName: "Luxe Lifestyle Co.",
    vertical: "admin",
    value: 750000,
    currency: "INR",
    stage: "won",
    probability: 100,
    expectedClose: "2026-01-30",
    assignedTo: "Rahul Verma",
    createdDate: "2025-12-15",
    lastActivity: "2026-01-30",
    source: "partner",
    priority: "high",
    notes: "Closed successfully. Delivery ongoing.",
    tags: ["won", "wholesale"],
  },
  {
    id: "d023",
    title: "EventHub Startup Network Pass",
    contactId: "c004",
    contactName: "Suresh Iyer",
    companyName: "EventPro India",
    vertical: "eventhub",
    value: 35000,
    currency: "INR",
    stage: "qualified",
    probability: 45,
    expectedClose: "2026-04-10",
    assignedTo: "Priya Menon",
    createdDate: "2026-02-10",
    lastActivity: "2026-02-22",
    source: "website",
    priority: "low",
    notes: "Interested in pilot access before committing.",
    tags: ["startup", "pilot"],
  },
  {
    id: "d024",
    title: "FaireDesk Seller Analytics Add-on",
    contactId: "c007",
    contactName: "Sarah Mitchell",
    companyName: "Boutique Haven LLC",
    vertical: "faire",
    value: 8500,
    currency: "USD",
    stage: "proposal",
    probability: 65,
    expectedClose: "2026-03-30",
    assignedTo: "Arjun Nair",
    createdDate: "2026-02-18",
    lastActivity: "2026-02-27",
    source: "inbound",
    priority: "medium",
    notes: "Existing customer upsell. High conversion probability.",
    tags: ["upsell", "analytics"],
  },
  {
    id: "d025",
    title: "GoyoTours Corporate Retreat — Chengdu",
    contactId: "c011",
    contactName: "Lin Wei",
    companyName: "Horizon Group",
    vertical: "events",
    value: 980000,
    currency: "INR",
    stage: "qualified",
    probability: 50,
    expectedClose: "2026-04-20",
    assignedTo: "Arjun Nair",
    createdDate: "2026-02-01",
    lastActivity: "2026-02-25",
    source: "partner",
    priority: "high",
    notes: "Second deal from same account. Cross-sell from deal d011.",
    tags: ["corporate-retreat", "china"],
  },
];

export const crmActivities: CrmActivity[] = [
  {
    id: "a001",
    type: "call",
    title: "Discovery call with Priya Sharma",
    description: "Discussed pain points around HR compliance tracking. Priya confirmed budget allocation for Q1.",
    contactId: "c001",
    contactName: "Priya Sharma",
    dealId: "d001",
    dealTitle: "LegalNations HR Suite — Annual License",
    vertical: "hr",
    performedBy: "Rahul Verma",
    completedAt: "2026-02-25T10:30:00",
    status: "completed",
    outcome: "Positive. Proposal requested within 2 days.",
  },
  {
    id: "a002",
    type: "email",
    title: "Proposal sent to Aditya Kapoor",
    description: "Sent detailed USDrop AI Pro Plan proposal including pricing tiers and onboarding timeline.",
    contactId: "c002",
    contactName: "Aditya Kapoor",
    dealId: "d002",
    dealTitle: "USDrop AI Pro Plan — Q1 Onboarding",
    vertical: "sales",
    performedBy: "Sneha Reddy",
    completedAt: "2026-02-26T14:00:00",
    status: "completed",
    outcome: "Opened. Reply expected by EOD.",
  },
  {
    id: "a003",
    type: "meeting",
    title: "GoyoTours pricing finalization — Mei Lin",
    description: "In-person meeting in Shanghai. Reviewed group tour itinerary and negotiated visa support add-on.",
    contactId: "c003",
    contactName: "Mei Lin",
    dealId: "d003",
    dealTitle: "GoyoTours China Group Package — 80 Pax",
    vertical: "events",
    performedBy: "Arjun Nair",
    completedAt: "2026-02-24T09:00:00",
    status: "completed",
    outcome: "Agreement on pricing. Contract draft to follow.",
  },
  {
    id: "a004",
    type: "whatsapp",
    title: "Follow-up message to Suresh Iyer",
    description: "Sent event calendar overview via WhatsApp. Asked about org size and event frequency.",
    contactId: "c004",
    contactName: "Suresh Iyer",
    dealId: "d004",
    dealTitle: "EventHub Corporate Membership",
    vertical: "eventhub",
    performedBy: "Priya Menon",
    completedAt: "2026-02-22T16:45:00",
    status: "completed",
    outcome: "Read. No reply yet.",
  },
  {
    id: "a005",
    type: "email",
    title: "Catalog sent to Kavita Nair",
    description: "Shared the LBM Spring 2026 catalog with 240 SKU selection guide.",
    contactId: "c005",
    contactName: "Kavita Nair",
    dealId: "d005",
    dealTitle: "LBM Lifestyle B2B Catalog — Season Drop",
    vertical: "admin",
    performedBy: "Rahul Verma",
    completedAt: "2026-02-20T11:00:00",
    status: "completed",
    outcome: "Catalog downloaded. Shortlist expected next week.",
  },
  {
    id: "a006",
    type: "call",
    title: "Intro call with Rohan Mehta",
    description: "Cold outreach call. Introduced EazyToSell franchise model and starter kit benefits.",
    contactId: "c006",
    contactName: "Rohan Mehta",
    dealId: "d006",
    dealTitle: "EazyToSell Franchise Starter Kit",
    vertical: "ets",
    performedBy: "Sneha Reddy",
    completedAt: "2026-02-19T15:00:00",
    status: "completed",
    outcome: "Interested. Requested intro deck.",
  },
  {
    id: "a007",
    type: "task",
    title: "Send intro deck to Rohan Mehta",
    description: "Prepare and send EazyToSell franchise starter kit pitch deck with ROI projections.",
    contactId: "c006",
    contactName: "Rohan Mehta",
    dealId: "d006",
    dealTitle: "EazyToSell Franchise Starter Kit",
    vertical: "ets",
    performedBy: "Sneha Reddy",
    scheduledAt: "2026-02-28T12:00:00",
    status: "overdue",
  },
  {
    id: "a008",
    type: "meeting",
    title: "Onboarding kickoff — Sarah Mitchell",
    description: "Virtual kickoff for FaireDesk Premium. Covered account setup, catalog upload, and buyer matching.",
    contactId: "c007",
    contactName: "Sarah Mitchell",
    dealId: "d007",
    dealTitle: "FaireDesk Premium Marketplace Access",
    vertical: "faire",
    performedBy: "Arjun Nair",
    completedAt: "2026-02-16T18:30:00",
    status: "completed",
    outcome: "Onboarding successful. Account live.",
  },
  {
    id: "a009",
    type: "call",
    title: "Product demo — Deepak Joshi",
    description: "Live HRMS platform demo covering payroll, attendance, and compliance modules.",
    contactId: "c008",
    contactName: "Deepak Joshi",
    dealId: "d008",
    dealTitle: "HRMS Enterprise Platform — 500 Seats",
    vertical: "hrms",
    performedBy: "Priya Menon",
    completedAt: "2026-02-23T11:00:00",
    status: "completed",
    outcome: "Very positive. Trial extended for 2 weeks.",
  },
  {
    id: "a010",
    type: "email",
    title: "ATS comparison document sent — Ananya Singh",
    description: "Sent side-by-side comparison of ATS Pro vs two competitors with feature matrix.",
    contactId: "c009",
    contactName: "Ananya Singh",
    dealId: "d009",
    dealTitle: "ATS Pro — Annual Recruitment Suite",
    vertical: "ats",
    performedBy: "Rahul Verma",
    completedAt: "2026-02-26T09:30:00",
    status: "completed",
    outcome: "Opened twice. Decision next week.",
  },
  {
    id: "a011",
    type: "whatsapp",
    title: "Discovery check-in with Vikram Bose",
    description: "Quick WhatsApp check-in about SocialDesk platform interest and current tools.",
    contactId: "c010",
    contactName: "Vikram Bose",
    dealId: "d010",
    dealTitle: "SocialDesk Content Management — 6 Months",
    vertical: "social",
    performedBy: "Sneha Reddy",
    completedAt: "2026-02-21T13:00:00",
    status: "completed",
    outcome: "Interested but busy. Call scheduled for Mar 3.",
  },
  {
    id: "a012",
    type: "meeting",
    title: "Proposal review — Lin Wei",
    description: "Video call reviewing the Beijing + Xi'an package proposal in detail. Discussed hotel categories and guide quality.",
    contactId: "c011",
    contactName: "Lin Wei",
    dealId: "d011",
    dealTitle: "GoyoTours Beijing + Xi'an Package — 40 Pax",
    vertical: "events",
    performedBy: "Arjun Nair",
    completedAt: "2026-02-25T08:00:00",
    status: "completed",
    outcome: "Good progress. Group lead confirmation pending.",
  },
  {
    id: "a013",
    type: "call",
    title: "Contract negotiation — Amit Chaudhary",
    description: "Detailed call on contract terms, SLAs, and compliance module scope.",
    contactId: "c013",
    contactName: "Amit Chaudhary",
    dealId: "d012",
    dealTitle: "LegalNations Compliance Audit Module",
    vertical: "hr",
    performedBy: "Rahul Verma",
    completedAt: "2026-02-27T14:00:00",
    status: "completed",
    outcome: "Terms mostly agreed. Legal review ongoing.",
  },
  {
    id: "a014",
    type: "note",
    title: "Internal note — Emma Thompson renewal flag",
    description: "FaireDesk annual deal won. Set auto-renewal reminder for Jan 2027. Explore upsell opportunities.",
    contactId: "c014",
    contactName: "Emma Thompson",
    dealId: "d013",
    dealTitle: "FaireDesk Annual Wholesale Access",
    vertical: "faire",
    performedBy: "Arjun Nair",
    completedAt: "2026-02-20T17:00:00",
    status: "completed",
  },
  {
    id: "a015",
    type: "email",
    title: "Partnership terms email — Pooja Krishnan",
    description: "Sent draft partnership agreement for the LBM Fashion Drop collaboration.",
    contactId: "c015",
    contactName: "Pooja Krishnan",
    dealId: "d014",
    dealTitle: "LBM Lifestyle Fashion Drop — Partnership",
    vertical: "admin",
    performedBy: "Sneha Reddy",
    completedAt: "2026-02-24T10:00:00",
    status: "completed",
    outcome: "In review with their legal team.",
  },
  {
    id: "a016",
    type: "call",
    title: "Technical scoping — Rajesh Kumar",
    description: "Discussed USDrop supplier API integration requirements. Rajesh's tech team needs API docs.",
    contactId: "c016",
    contactName: "Rajesh Kumar",
    dealId: "d015",
    dealTitle: "USDrop AI Supplier Integration",
    vertical: "sales",
    performedBy: "Priya Menon",
    completedAt: "2026-02-20T16:00:00",
    status: "completed",
    outcome: "API docs to be shared. Follow-up in 2 weeks.",
  },
  {
    id: "a017",
    type: "task",
    title: "Prepare Chengdu retreat itinerary — Lin Wei",
    description: "Create detailed 5-day Chengdu corporate retreat itinerary with team-building activities.",
    contactId: "c011",
    contactName: "Lin Wei",
    dealId: "d025",
    dealTitle: "GoyoTours Corporate Retreat — Chengdu",
    vertical: "events",
    performedBy: "Arjun Nair",
    scheduledAt: "2026-03-01T12:00:00",
    status: "scheduled",
  },
  {
    id: "a018",
    type: "email",
    title: "HRMS trial activation — Geeta Rao",
    description: "Sent HRMS trial account credentials and onboarding guide. Invited to webinar on Mar 4.",
    contactId: "c018",
    contactName: "Geeta Rao",
    dealId: "d017",
    dealTitle: "HRMS SME Bundle — Quarterly",
    vertical: "hrms",
    performedBy: "Rahul Verma",
    completedAt: "2026-02-25T09:00:00",
    status: "completed",
    outcome: "Trial activated. Webinar registered.",
  },
  {
    id: "a019",
    type: "whatsapp",
    title: "Post-webinar follow-up — Akira Tanaka",
    description: "Sent WhatsApp message with Japan-China bridge tour highlights and next steps.",
    contactId: "c017",
    contactName: "Akira Tanaka",
    dealId: "d018",
    dealTitle: "GoyoTours Japan-China Bridge Tour",
    vertical: "events",
    performedBy: "Arjun Nair",
    completedAt: "2026-02-22T19:00:00",
    status: "completed",
    outcome: "Read. Interested. Detailed itinerary requested.",
  },
  {
    id: "a020",
    type: "task",
    title: "Send API docs to Rajesh Kumar",
    description: "Share USDrop AI supplier API documentation and sandbox credentials.",
    contactId: "c016",
    contactName: "Rajesh Kumar",
    dealId: "d015",
    dealTitle: "USDrop AI Supplier Integration",
    vertical: "sales",
    performedBy: "Priya Menon",
    scheduledAt: "2026-02-27T15:00:00",
    status: "overdue",
  },
  {
    id: "a021",
    type: "meeting",
    title: "Deal closing call — Sunita Desai",
    description: "Final closing call for LegalNations Full Compliance Suite. Contract signed during the call.",
    contactId: "c020",
    contactName: "Sunita Desai",
    dealId: "d016",
    dealTitle: "LegalNations Full Compliance Suite",
    vertical: "hr",
    performedBy: "Priya Menon",
    completedAt: "2026-02-10T11:00:00",
    status: "completed",
    outcome: "Deal WON. ₹6,80,000 closed. Onboarding started.",
  },
  {
    id: "a022",
    type: "call",
    title: "Upsell discovery — Sarah Mitchell",
    description: "Called to discuss analytics add-on interest. Sarah showed keen interest in sales analytics.",
    contactId: "c007",
    contactName: "Sarah Mitchell",
    dealId: "d024",
    dealTitle: "FaireDesk Seller Analytics Add-on",
    vertical: "faire",
    performedBy: "Arjun Nair",
    completedAt: "2026-02-27T17:00:00",
    status: "completed",
    outcome: "Very interested. Proposal to be sent.",
  },
  {
    id: "a023",
    type: "email",
    title: "Initial outreach — Karan Malhotra",
    description: "Cold email introducing SocialDesk and offering a free brand audit session.",
    contactId: "c019",
    contactName: "Karan Malhotra",
    dealId: "d020",
    dealTitle: "SocialDesk Brand Audit Package",
    vertical: "social",
    performedBy: "Sneha Reddy",
    completedAt: "2026-02-17T10:30:00",
    status: "completed",
    outcome: "No reply yet. Follow-up in 5 days.",
  },
  {
    id: "a024",
    type: "task",
    title: "Follow-up with Karan Malhotra",
    description: "Send follow-up email if no response to initial outreach by Mar 1.",
    contactId: "c019",
    contactName: "Karan Malhotra",
    dealId: "d020",
    dealTitle: "SocialDesk Brand Audit Package",
    vertical: "social",
    performedBy: "Sneha Reddy",
    scheduledAt: "2026-03-01T10:00:00",
    status: "scheduled",
  },
  {
    id: "a025",
    type: "note",
    title: "Lost deal analysis — ATS Basic (Ananya Singh)",
    description: "Lost to Keka due to price. Their offer was 30% cheaper. Need to create SME pricing tier.",
    contactId: "c009",
    contactName: "Ananya Singh",
    dealId: "d019",
    dealTitle: "ATS Basic — SME Plan",
    vertical: "ats",
    performedBy: "Rahul Verma",
    completedAt: "2026-02-01T18:00:00",
    status: "completed",
  },
  {
    id: "a026",
    type: "meeting",
    title: "LBM closing call — Kavita Nair",
    description: "Final terms discussion for the exclusive wholesale deal. Agreed on payment schedule.",
    contactId: "c005",
    contactName: "Kavita Nair",
    dealId: "d022",
    dealTitle: "LBM Lifestyle Exclusive Wholesale Deal",
    vertical: "admin",
    performedBy: "Rahul Verma",
    completedAt: "2026-01-30T14:00:00",
    status: "completed",
    outcome: "Deal WON. ₹7,50,000 closed.",
  },
  {
    id: "a027",
    type: "task",
    title: "Product demo prep — Deepak Joshi",
    description: "Prepare customized HRMS demo environment with People First HR's industry vertical setup.",
    contactId: "c008",
    contactName: "Deepak Joshi",
    dealId: "d008",
    dealTitle: "HRMS Enterprise Platform — 500 Seats",
    vertical: "hrms",
    performedBy: "Priya Menon",
    scheduledAt: "2026-03-07T10:00:00",
    status: "scheduled",
  },
  {
    id: "a028",
    type: "whatsapp",
    title: "Contract update — Amit Chaudhary",
    description: "WhatsApp update: Legal review expected to complete by Mar 2. Contract to be signed thereafter.",
    contactId: "c013",
    contactName: "Amit Chaudhary",
    dealId: "d012",
    dealTitle: "LegalNations Compliance Audit Module",
    vertical: "hr",
    performedBy: "Rahul Verma",
    completedAt: "2026-02-27T20:00:00",
    status: "completed",
    outcome: "Acknowledged. Contract signing confirmed for Mar 3.",
  },
  {
    id: "a029",
    type: "email",
    title: "FaireDesk analytics proposal — Emma Thompson",
    description: "Sent upsell proposal for the Seller Analytics Add-on with projected ROI data.",
    contactId: "c014",
    contactName: "Emma Thompson",
    dealId: "d024",
    dealTitle: "FaireDesk Seller Analytics Add-on",
    vertical: "faire",
    performedBy: "Arjun Nair",
    scheduledAt: "2026-03-01T09:00:00",
    status: "scheduled",
  },
  {
    id: "a030",
    type: "call",
    title: "Quarterly review call — Sunita Desai",
    description: "First QBR with LegalConsult India. Reviewed compliance module adoption and expansion scope.",
    contactId: "c020",
    contactName: "Sunita Desai",
    dealId: "d016",
    dealTitle: "LegalNations Full Compliance Suite",
    vertical: "hr",
    performedBy: "Priya Menon",
    scheduledAt: "2026-03-10T11:00:00",
    status: "scheduled",
  },
];

export const messageTemplates: MessageTemplate[] = [
  {
    id: "t001",
    name: "New Lead Introduction",
    type: "email",
    stage: "new",
    verticals: ["all"],
    subject: "Introducing TeamSync — Built for {{company}}",
    body: `Hi {{name}},

I'm reaching out from TeamSync — a multi-vertical business operations portal trusted by fast-growing teams.

I noticed {{company}} is scaling rapidly, and I'd love to explore how we can support your {{vertical}} operations.

Would you be open to a quick 15-minute call this week?

Best regards,
{{sender_name}}
TeamSync`,
    variables: ["{{name}}", "{{company}}", "{{vertical}}", "{{sender_name}}"],
    usageCount: 48,
    createdBy: "Rahul Verma",
    createdDate: "2026-01-05",
    tags: ["cold-outreach", "intro"],
  },
  {
    id: "t002",
    name: "Follow-up After First Call",
    type: "email",
    stage: "contacted",
    verticals: ["all"],
    subject: "Great speaking with you, {{name}} — Next Steps",
    body: `Hi {{name}},

Thank you for taking the time to connect today. It was great learning more about {{company}}'s goals.

As discussed, I'm sharing:
1. Our product overview deck
2. A tailored pricing estimate for your team size
3. Customer success stories from similar companies

Please let me know if you'd like to schedule a deeper dive demo.

Looking forward to our next conversation!

Warm regards,
{{sender_name}}`,
    variables: ["{{name}}", "{{company}}", "{{sender_name}}"],
    usageCount: 62,
    createdBy: "Sneha Reddy",
    createdDate: "2026-01-08",
    tags: ["follow-up", "post-call"],
  },
  {
    id: "t003",
    name: "Proposal Submission",
    type: "email",
    stage: "proposal",
    verticals: ["all"],
    subject: "Your Custom Proposal — {{deal_title}}",
    body: `Hi {{name}},

Please find attached our detailed proposal for {{deal_title}}.

Summary:
• Investment: {{value}}
• Implementation timeline: {{timeline}}
• Proposed start date: {{start_date}}

The proposal covers all requirements we discussed, including {{key_feature_1}} and {{key_feature_2}}.

I'm available for a review call at your convenience. What works best for your schedule?

Best,
{{sender_name}}`,
    variables: ["{{name}}", "{{deal_title}}", "{{value}}", "{{timeline}}", "{{start_date}}", "{{key_feature_1}}", "{{key_feature_2}}", "{{sender_name}}"],
    usageCount: 35,
    createdBy: "Rahul Verma",
    createdDate: "2026-01-12",
    tags: ["proposal", "formal"],
  },
  {
    id: "t004",
    name: "WhatsApp — Quick Follow-up",
    type: "whatsapp",
    stage: "follow-up",
    verticals: ["all"],
    body: `Hi {{name}} 👋 

Just checking in on the proposal I sent over for {{company}}. Did you get a chance to review it?

Happy to answer any questions or jump on a quick call. What works for you? 😊`,
    variables: ["{{name}}", "{{company}}"],
    usageCount: 89,
    createdBy: "Priya Menon",
    createdDate: "2026-01-10",
    tags: ["whatsapp", "quick"],
  },
  {
    id: "t005",
    name: "GoyoTours — Group Package Introduction",
    type: "email",
    stage: "new",
    verticals: ["events"],
    subject: "Exclusive China Group Tour Packages for {{company}}",
    body: `Dear {{name}},

GoyoTours specializes in premium B2B China travel experiences for corporate groups.

We offer:
• Curated itineraries for Beijing, Shanghai, Xi'an, Chengdu & Guilin
• Dedicated bilingual guides
• Visa assistance and travel insurance
• Group sizes from 15 to 200+ pax

Our packages start from ₹12,500 per person for a 5-night group tour.

Would you like to receive our 2026 corporate tour brochure?

Warm regards,
{{sender_name}}
GoyoTours — China B2B Travel`,
    variables: ["{{name}}", "{{company}}", "{{sender_name}}"],
    usageCount: 27,
    createdBy: "Arjun Nair",
    createdDate: "2026-01-15",
    tags: ["tours", "b2b", "china"],
  },
  {
    id: "t006",
    name: "LegalNations — Compliance Intro",
    type: "email",
    stage: "new",
    verticals: ["hr"],
    subject: "Stay Ahead of HR Compliance — {{company}}",
    body: `Hi {{name}},

Managing HR compliance across multiple states has never been more complex. LegalNations helps companies like {{company}} stay fully compliant — automatically.

Key capabilities:
• Real-time compliance alerts for all Indian labour laws
• Automated payroll and PF/ESI filings
• Audit-ready documentation at a click
• 24/7 compliance support team

We've helped 200+ companies avoid compliance penalties.

Can I show you a 20-minute platform walkthrough this week?

Best,
{{sender_name}}
LegalNations`,
    variables: ["{{name}}", "{{company}}", "{{sender_name}}"],
    usageCount: 41,
    createdBy: "Rahul Verma",
    createdDate: "2026-01-18",
    tags: ["compliance", "hr"],
  },
  {
    id: "t007",
    name: "Negotiation — Final Offer",
    type: "email",
    stage: "negotiation",
    verticals: ["all"],
    subject: "Our Best Offer for {{company}} — Valid Until {{expiry_date}}",
    body: `Hi {{name}},

I've worked with our team to put together our best possible offer for {{company}}:

Revised Investment: {{final_value}}
Added benefits:
• {{bonus_1}}
• {{bonus_2}}
• Priority onboarding support

This offer is valid until {{expiry_date}}.

I believe this represents exceptional value, and I'm confident we'll deliver great results for your team.

Looking forward to welcoming {{company}} aboard.

{{sender_name}}`,
    variables: ["{{name}}", "{{company}}", "{{final_value}}", "{{bonus_1}}", "{{bonus_2}}", "{{expiry_date}}", "{{sender_name}}"],
    usageCount: 19,
    createdBy: "Sneha Reddy",
    createdDate: "2026-01-22",
    tags: ["negotiation", "final-offer"],
  },
  {
    id: "t008",
    name: "Re-engagement — Long Silence",
    type: "email",
    stage: "re-engage",
    verticals: ["all"],
    subject: "Checking in — {{company}} + TeamSync",
    body: `Hi {{name}},

It's been a while since we last connected, and I wanted to reach out to see how things are going at {{company}}.

A lot has changed on our end:
• {{new_feature_1}} is now live
• {{new_feature_2}} has been added based on customer feedback
• We've onboarded 50+ new clients this quarter

I'd love to reconnect and see if there's an opportunity to help {{company}} with {{pain_point}}.

Would a brief 10-minute call work this week?

{{sender_name}}`,
    variables: ["{{name}}", "{{company}}", "{{new_feature_1}}", "{{new_feature_2}}", "{{pain_point}}", "{{sender_name}}"],
    usageCount: 23,
    createdBy: "Priya Menon",
    createdDate: "2026-01-25",
    tags: ["re-engage", "win-back"],
  },
  {
    id: "t009",
    name: "WhatsApp — Meeting Reminder",
    type: "whatsapp",
    stage: "general",
    verticals: ["all"],
    body: `Hi {{name}}! 👋

Just a quick reminder about our call scheduled for {{meeting_time}} today.

Here's the meeting link: {{meeting_link}}

Looking forward to speaking with you!

{{sender_name}}`,
    variables: ["{{name}}", "{{meeting_time}}", "{{meeting_link}}", "{{sender_name}}"],
    usageCount: 74,
    createdBy: "Arjun Nair",
    createdDate: "2026-01-28",
    tags: ["reminder", "meeting"],
  },
  {
    id: "t010",
    name: "SMS — Appointment Confirmation",
    type: "sms",
    stage: "general",
    verticals: ["all"],
    body: `Hi {{name}}, your meeting with TeamSync is confirmed for {{date}} at {{time}}. Call link: {{link}}. Reply STOP to unsubscribe.`,
    variables: ["{{name}}", "{{date}}", "{{time}}", "{{link}}"],
    usageCount: 56,
    createdBy: "Rahul Verma",
    createdDate: "2026-02-01",
    tags: ["sms", "appointment"],
  },
  {
    id: "t011",
    name: "LinkedIn — Connection Request",
    type: "linkedin",
    stage: "new",
    verticals: ["all"],
    body: `Hi {{name}}, I came across {{company}} and was impressed by your work in {{industry}}. I lead partnerships at TeamSync — we help teams like yours manage operations across sales, HR, and logistics from a single portal. Would love to connect!`,
    variables: ["{{name}}", "{{company}}", "{{industry}}"],
    usageCount: 33,
    createdBy: "Sneha Reddy",
    createdDate: "2026-02-03",
    tags: ["linkedin", "connection"],
  },
  {
    id: "t012",
    name: "HRMS — Free Trial Invitation",
    type: "email",
    stage: "qualified",
    verticals: ["hrms"],
    subject: "Your Free HRMS Trial is Ready — {{company}}",
    body: `Hi {{name}},

Based on our conversation, I've set up a 14-day free trial of TeamSync HRMS for {{company}}.

Your trial includes:
• Full access to Payroll, Attendance & Leave modules
• Up to {{seats}} employee seats
• Dedicated onboarding session on {{demo_date}}
• Priority support channel

Access your trial here: {{trial_link}}

We're excited to help {{company}} streamline your people operations.

{{sender_name}}
TeamSync HRMS`,
    variables: ["{{name}}", "{{company}}", "{{seats}}", "{{demo_date}}", "{{trial_link}}", "{{sender_name}}"],
    usageCount: 18,
    createdBy: "Priya Menon",
    createdDate: "2026-02-06",
    tags: ["trial", "hrms"],
  },
  {
    id: "t013",
    name: "Won Deal — Welcome Onboard",
    type: "email",
    stage: "won",
    verticals: ["all"],
    subject: "Welcome to TeamSync, {{company}}! 🎉",
    body: `Hi {{name}},

We are thrilled to welcome {{company}} to the TeamSync family!

Your onboarding is scheduled for {{onboarding_date}}. Here's what to expect:

Day 1: Account setup + team access
Day 2: Platform walkthrough with your dedicated CSM
Day 7: First check-in call

Your dedicated Customer Success Manager is {{csm_name}} ({{csm_email}}). Feel free to reach out anytime.

We're committed to making this an exceptional experience for your team.

Warmly,
{{sender_name}}
TeamSync`,
    variables: ["{{name}}", "{{company}}", "{{onboarding_date}}", "{{csm_name}}", "{{csm_email}}", "{{sender_name}}"],
    usageCount: 14,
    createdBy: "Rahul Verma",
    createdDate: "2026-02-08",
    tags: ["won", "onboarding", "welcome"],
  },
  {
    id: "t014",
    name: "WhatsApp — Proposal Nudge",
    type: "whatsapp",
    stage: "proposal",
    verticals: ["all"],
    body: `Hey {{name}}! Hope you're doing well 😊

Wanted to check if you had a chance to go through the proposal I sent for {{deal_title}}. 

Any questions or tweaks needed? Happy to hop on a quick call to walk you through it!`,
    variables: ["{{name}}", "{{deal_title}}"],
    usageCount: 67,
    createdBy: "Arjun Nair",
    createdDate: "2026-02-10",
    tags: ["whatsapp", "proposal", "nudge"],
  },
  {
    id: "t015",
    name: "FaireDesk — Seller Upsell",
    type: "email",
    stage: "general",
    verticals: ["faire"],
    subject: "Unlock More Sales on Faire — {{company}}",
    body: `Hi {{name}},

As an active FaireDesk seller, you've already seen great results. I wanted to share an opportunity to take things further.

Our Seller Analytics Add-on gives you:
• Real-time buyer behavior data
• Best-selling product predictions
• Reorder alerts for your top buyers
• Competitive benchmarking

Early adopters have seen a 23% increase in reorder rates.

Interested in a quick walkthrough? It takes just 15 minutes.

{{sender_name}}
FaireDesk Team`,
    variables: ["{{name}}", "{{company}}", "{{sender_name}}"],
    usageCount: 9,
    createdBy: "Arjun Nair",
    createdDate: "2026-02-18",
    tags: ["upsell", "faire", "analytics"],
  },
];

export const teamPerformance: TeamPerformance[] = [
  {
    id: "tp001",
    name: "Arjun Nair",
    role: "Senior Sales Manager",
    vertical: "events",
    leadsAssigned: 42,
    leadsConverted: 18,
    dealsWon: 5,
    dealsLost: 2,
    revenue: 3320000,
    avgDealSize: 664000,
    activitiesCompleted: 87,
    responseTime: 1.2,
    winRate: 71,
    target: 4000000,
    achieved: 3320000,
    rank: 1,
    auditEvents: [
      "Closed GoyoTours China Group Package deal (₹12,50,000) on Feb 24",
      "Won FaireDesk Premium deal ($18,000) — fastest close this quarter",
      "Converted 5 leads to deals in February alone",
    ],
  },
  {
    id: "tp002",
    name: "Rahul Verma",
    role: "Sales Manager",
    vertical: "hr",
    leadsAssigned: 38,
    leadsConverted: 15,
    dealsWon: 4,
    dealsLost: 3,
    revenue: 2440000,
    avgDealSize: 610000,
    activitiesCompleted: 71,
    responseTime: 1.8,
    winRate: 57,
    target: 3000000,
    achieved: 2440000,
    rank: 2,
    auditEvents: [
      "Won LBM Lifestyle Exclusive Wholesale (₹7,50,000) on Jan 30",
      "Closed 2 LegalNations deals worth ₹11,30,000 this quarter",
      "Highest activity count in HR vertical this month",
    ],
  },
  {
    id: "tp003",
    name: "Priya Menon",
    role: "Sales Manager",
    vertical: "hrms",
    leadsAssigned: 35,
    leadsConverted: 14,
    dealsWon: 3,
    dealsLost: 2,
    revenue: 1820000,
    avgDealSize: 606667,
    activitiesCompleted: 64,
    responseTime: 2.1,
    winRate: 60,
    target: 2500000,
    achieved: 1820000,
    rank: 3,
    auditEvents: [
      "Won LegalConsult India Full Compliance Suite (₹6,80,000)",
      "Delivered HRMS demo resulting in 2-week trial extension for People First HR",
      "100% on-time follow-ups in February",
    ],
  },
  {
    id: "tp004",
    name: "Sneha Reddy",
    role: "Sales Executive",
    vertical: "sales",
    leadsAssigned: 30,
    leadsConverted: 10,
    dealsWon: 2,
    dealsLost: 4,
    revenue: 870000,
    avgDealSize: 435000,
    activitiesCompleted: 58,
    responseTime: 3.2,
    winRate: 33,
    target: 1500000,
    achieved: 870000,
    rank: 4,
    auditEvents: [
      "Negotiating BrightBridge Commerce deal — close expected Mar 5",
      "Lost 2 EazyToSell deals due to budget constraints",
      "Active follow-up rate improved by 20% vs last month",
    ],
  },
  {
    id: "tp005",
    name: "Vikash Gupta",
    role: "Sales Executive",
    vertical: "ets",
    leadsAssigned: 25,
    leadsConverted: 8,
    dealsWon: 2,
    dealsLost: 3,
    revenue: 640000,
    avgDealSize: 320000,
    activitiesCompleted: 49,
    responseTime: 4.0,
    winRate: 40,
    target: 1200000,
    achieved: 640000,
    rank: 5,
    auditEvents: [
      "Won 2 EazyToSell franchise deals in Rajasthan region",
      "Closed QuickSell Retail expansion deal worth ₹2,20,000 (later reversed due to budget)",
    ],
  },
  {
    id: "tp006",
    name: "Deepa Iyer",
    role: "Sales Executive",
    vertical: "faire",
    leadsAssigned: 22,
    leadsConverted: 9,
    dealsWon: 3,
    dealsLost: 1,
    revenue: 580000,
    avgDealSize: 193333,
    activitiesCompleted: 44,
    responseTime: 2.5,
    winRate: 75,
    target: 800000,
    achieved: 580000,
    rank: 6,
    auditEvents: [
      "Highest win rate in the team (75%) for Q1",
      "Sourced 3 new Faire marketplace sellers from the US",
    ],
  },
  {
    id: "tp007",
    name: "Manish Tiwari",
    role: "BDR",
    vertical: "social",
    leadsAssigned: 40,
    leadsConverted: 7,
    dealsWon: 1,
    dealsLost: 5,
    revenue: 180000,
    avgDealSize: 180000,
    activitiesCompleted: 92,
    responseTime: 1.5,
    winRate: 17,
    target: 800000,
    achieved: 180000,
    rank: 7,
    auditEvents: [
      "Highest total activities in the team (92) — strong prospecting effort",
      "Low conversion rate — needs sales training on objection handling",
      "Pipeline of ₹6,50,000 in early stages",
    ],
  },
  {
    id: "tp008",
    name: "Ritika Sharma",
    role: "BDR",
    vertical: "hr",
    leadsAssigned: 35,
    leadsConverted: 6,
    dealsWon: 1,
    dealsLost: 4,
    revenue: 240000,
    avgDealSize: 240000,
    activitiesCompleted: 61,
    responseTime: 2.8,
    winRate: 20,
    target: 700000,
    achieved: 240000,
    rank: 8,
    auditEvents: [
      "Won first enterprise deal independently",
      "Improving — lead conversion up from 12% to 17% this month",
    ],
  },
  {
    id: "tp009",
    name: "Sameer Kapoor",
    role: "BDR",
    vertical: "eventhub",
    leadsAssigned: 28,
    leadsConverted: 5,
    dealsWon: 1,
    dealsLost: 3,
    revenue: 120000,
    avgDealSize: 120000,
    activitiesCompleted: 47,
    responseTime: 3.8,
    winRate: 25,
    target: 600000,
    achieved: 120000,
    rank: 9,
    auditEvents: [
      "Closing first EventHub deal — Startup Network Pass",
      "Response time needs improvement (3.8hr avg vs 2hr target)",
    ],
  },
  {
    id: "tp010",
    name: "Fatima Khan",
    role: "BDR",
    vertical: "ats",
    leadsAssigned: 20,
    leadsConverted: 3,
    dealsWon: 0,
    dealsLost: 2,
    revenue: 0,
    avgDealSize: 0,
    activitiesCompleted: 35,
    responseTime: 4.5,
    winRate: 0,
    target: 500000,
    achieved: 0,
    rank: 10,
    auditEvents: [
      "New team member — joined Feb 2026",
      "Building pipeline — 3 qualified leads in ATS vertical",
      "Enrolled in sales training program (Mar 2026)",
    ],
  },
];

export const ALL_VERTICALS_IN_CRM = [
  { id: "hr", name: "LegalNations", color: "#225AEA" },
  { id: "sales", name: "USDrop AI", color: "#F34147" },
  { id: "events", name: "GoyoTours", color: "#E91E63" },
  { id: "eventhub", name: "Event Hub", color: "#7C3AED" },
  { id: "admin", name: "LBM Lifestyle", color: "#673AB7" },
  { id: "ets", name: "EazyToSell", color: "#F97316" },
  { id: "faire", name: "FaireDesk", color: "#1A6B45" },
  { id: "hrms", name: "HR / HRMS", color: "#0EA5E9" },
  { id: "ats", name: "ATS", color: "#8B5CF6" },
  { id: "social", name: "SocialDesk", color: "#0D9488" },
  { id: "dev", name: "Developer", color: "#10B981" },
];
