export interface VerticalMember {
  id: string;
  verticalId: string;
  name: string;
  email: string;
  phone: string;
  role: string;
  department: string;
  status: "online" | "away" | "offline";
  location: string;
  skills: string[];
  joinedDate: string;
}

export interface ChatChannel {
  id: string;
  verticalId: string;
  name: string;
  type: "channel" | "dm";
  description: string;
  memberNames: string[];
  lastMessage: string;
  lastMessageTime: string;
  unreadCount: number;
  isPinned: boolean;
}

export interface ChatMessage {
  id: string;
  channelId: string;
  senderName: string;
  content: string;
  timestamp: string;
  isMe: boolean;
}

export interface SharedResource {
  id: string;
  verticalId: string;
  title: string;
  description: string;
  category: "Brochure" | "Script" | "Spreadsheet" | "Link" | "Presentation" | "Document" | "Template";
  type: "pdf" | "excel" | "ppt" | "doc" | "link" | "image";
  tags: string[];
  addedBy: string;
  addedDate: string;
  fileSize: string;
  url: string;
  isPinned: boolean;
  version: string;
}

export interface SharedTaskSubtask {
  id: string;
  title: string;
  completed: boolean;
}

export interface SharedTask {
  id: string;
  verticalId: string;
  title: string;
  description: string;
  status: "backlog" | "todo" | "in-progress" | "review" | "done";
  priority: "critical" | "high" | "medium" | "low";
  assigneeName: string;
  dueDate: string;
  tags: string[];
  createdDate: string;
  subtasks: SharedTaskSubtask[];
}

export const verticalMembers: VerticalMember[] = [
  { id: "VM-HR-001", verticalId: "hr", name: "Sneha Patel", email: "sneha.patel@lumin.com", phone: "+91 98765 43210", role: "HR Manager", department: "HR", status: "online", location: "Mumbai", skills: ["Recruitment", "Compliance", "Onboarding"], joinedDate: "2021-09-01" },
  { id: "VM-HR-002", verticalId: "hr", name: "Nisha Choudhary", email: "nisha.choudhary@lumin.com", phone: "+91 87654 32109", role: "Recruiter", department: "HR", status: "online", location: "Delhi", skills: ["Sourcing", "Interviews", "ATS"], joinedDate: "2024-02-10" },
  { id: "VM-HR-003", verticalId: "hr", name: "Pooja Bhat", email: "pooja.bhat@lumin.com", phone: "+91 76543 21098", role: "HR Executive", department: "HR", status: "away", location: "Bengaluru", skills: ["Payroll", "Employee Relations", "HRMS"], joinedDate: "2023-11-03" },
  { id: "VM-HR-004", verticalId: "hr", name: "Amit Desai", email: "amit.desai@lumin.com", phone: "+91 65432 10987", role: "HR Director", department: "HR", status: "offline", location: "Pune", skills: ["Strategy", "Leadership", "Policy"], joinedDate: "2021-03-20" },

  { id: "VM-SALES-001", verticalId: "sales", name: "Karan Gupta", email: "karan.gupta@lumin.com", phone: "+91 98123 45678", role: "Sales Executive", department: "Sales", status: "online", location: "Delhi", skills: ["Dropshipping", "CRM", "Lead Generation"], joinedDate: "2024-01-08" },
  { id: "VM-SALES-002", verticalId: "sales", name: "Vikram Singh", email: "vikram.singh@lumin.com", phone: "+91 87012 34567", role: "Marketing Lead", department: "Marketing", status: "online", location: "Bengaluru", skills: ["Paid Ads", "SEO", "Content Marketing"], joinedDate: "2022-11-05" },
  { id: "VM-SALES-003", verticalId: "sales", name: "Priya Verma", email: "priya.verma@lumin.com", phone: "+91 76901 23456", role: "Sales Development Rep", department: "Sales", status: "away", location: "Mumbai", skills: ["Cold Outreach", "LinkedIn", "Email Campaigns"], joinedDate: "2024-06-15" },
  { id: "VM-SALES-004", verticalId: "sales", name: "Raj Malhotra", email: "raj.malhotra@lumin.com", phone: "+91 65890 12345", role: "Account Manager", department: "Sales", status: "offline", location: "Hyderabad", skills: ["Client Relations", "Upselling", "Forecasting"], joinedDate: "2023-04-20" },

  { id: "VM-EVENTS-001", verticalId: "events", name: "Deepak Sharma", email: "deepak.sharma@lumin.com", phone: "+91 98234 56789", role: "Tour Manager", department: "Operations", status: "online", location: "Bengaluru", skills: ["Tour Planning", "Logistics", "Vendor Management"], joinedDate: "2022-03-10" },
  { id: "VM-EVENTS-002", verticalId: "events", name: "Anita Joshi", email: "anita.joshi@lumin.com", phone: "+91 87123 45678", role: "Operations Lead", department: "Operations", status: "away", location: "Mumbai", skills: ["Itinerary Design", "Hotel Booking", "Group Coordination"], joinedDate: "2021-08-22" },
  { id: "VM-EVENTS-003", verticalId: "events", name: "Rahul Singh", email: "rahul.singh@lumin.com", phone: "+91 76012 34567", role: "Visa Coordinator", department: "Compliance", status: "online", location: "Delhi", skills: ["Visa Processing", "Documentation", "Embassy Liaison"], joinedDate: "2023-01-14" },

  { id: "VM-HUB-001", verticalId: "eventhub", name: "Sonal Mehta", email: "sonal.mehta@lumin.com", phone: "+91 98345 67890", role: "Events Lead", department: "Events", status: "online", location: "Mumbai", skills: ["Event Planning", "Networking", "Stakeholder Management"], joinedDate: "2023-05-01" },
  { id: "VM-HUB-002", verticalId: "eventhub", name: "Nikhil Rao", email: "nikhil.rao@lumin.com", phone: "+91 87234 56789", role: "Event Coordinator", department: "Events", status: "online", location: "Bengaluru", skills: ["Logistics", "Registration", "On-ground Operations"], joinedDate: "2024-01-20" },
  { id: "VM-HUB-003", verticalId: "eventhub", name: "Priyanka Das", email: "priyanka.das@lumin.com", phone: "+91 76123 45678", role: "Vendor Manager", department: "Operations", status: "away", location: "Delhi", skills: ["Vendor Negotiation", "Budget Management", "Contracts"], joinedDate: "2023-09-15" },

  { id: "VM-ADMIN-001", verticalId: "admin", name: "Arjun Mehta", email: "arjun.mehta@lumin.com", phone: "+91 98456 78901", role: "Tech Lead", department: "Engineering", status: "online", location: "Bengaluru", skills: ["Full-stack", "Architecture", "DevOps"], joinedDate: "2023-01-15" },
  { id: "VM-ADMIN-002", verticalId: "admin", name: "Priya Sharma", email: "priya.sharma@lumin.com", phone: "+91 87345 67890", role: "Lead Designer", department: "Design", status: "online", location: "Mumbai", skills: ["UI/UX", "Figma", "Brand Design"], joinedDate: "2022-06-20" },
  { id: "VM-ADMIN-003", verticalId: "admin", name: "Siddharth Rao", email: "siddharth.rao@lumin.com", phone: "+91 76234 56789", role: "Product Manager", department: "Product", status: "away", location: "Delhi", skills: ["Roadmapping", "Agile", "Analytics"], joinedDate: "2022-08-14" },
  { id: "VM-ADMIN-004", verticalId: "admin", name: "Rohan Joshi", email: "rohan.joshi@lumin.com", phone: "+91 65123 45678", role: "DevOps Engineer", department: "Engineering", status: "offline", location: "Pune", skills: ["CI/CD", "Kubernetes", "Monitoring"], joinedDate: "2022-04-15" },

  { id: "VM-DEV-001", verticalId: "dev", name: "Arjun Mehta", email: "arjun.mehta@lumin.com", phone: "+91 98456 78901", role: "Tech Lead", department: "Engineering", status: "online", location: "Bengaluru", skills: ["React", "Node.js", "System Design"], joinedDate: "2023-01-15" },
  { id: "VM-DEV-002", verticalId: "dev", name: "Rohan Joshi", email: "rohan.joshi@lumin.com", phone: "+91 65123 45678", role: "DevOps Engineer", department: "Engineering", status: "online", location: "Pune", skills: ["Docker", "GitHub Actions", "AWS"], joinedDate: "2022-04-15" },
  { id: "VM-DEV-003", verticalId: "dev", name: "Rahul Kumar", email: "rahul.kumar@lumin.com", phone: "+91 54012 34567", role: "Frontend Developer", department: "Engineering", status: "away", location: "Hyderabad", skills: ["React", "TypeScript", "Tailwind"], joinedDate: "2025-02-20" },

  { id: "VM-ETS-001", verticalId: "ets", name: "Naveen Pillai", email: "naveen.pillai@lumin.com", phone: "+91 98567 89012", role: "Franchise Manager", department: "Franchise Ops", status: "online", location: "Chennai", skills: ["Franchise Development", "Onboarding", "P&L Management"], joinedDate: "2022-07-10" },
  { id: "VM-ETS-002", verticalId: "ets", name: "Sonia Agarwal", email: "sonia.agarwal@lumin.com", phone: "+91 87456 78901", role: "Account Executive", department: "Sales", status: "online", location: "Mumbai", skills: ["Franchise Sales", "CRM", "Client Relations"], joinedDate: "2023-02-01" },
  { id: "VM-ETS-003", verticalId: "ets", name: "Tarun Shah", email: "tarun.shah@lumin.com", phone: "+91 76345 67890", role: "Operations Head", department: "Operations", status: "away", location: "Ahmedabad", skills: ["Supply Chain", "Operations", "Inventory"], joinedDate: "2021-10-05" },
  { id: "VM-ETS-004", verticalId: "ets", name: "Meera Iyer", email: "meera.iyer@lumin.com", phone: "+91 65234 56789", role: "Support Executive", department: "Support", status: "offline", location: "Bengaluru", skills: ["Customer Support", "Issue Resolution", "Franchise Helpdesk"], joinedDate: "2023-08-20" },
];

export const chatChannels: ChatChannel[] = [
  { id: "CH-HR-001", verticalId: "hr", name: "hr-general", type: "channel", description: "General HR team discussions", memberNames: ["Sneha Patel", "Nisha Choudhary", "Pooja Bhat", "Amit Desai"], lastMessage: "The new leave policy draft is ready for review.", lastMessageTime: "10:42 AM", unreadCount: 3, isPinned: true },
  { id: "CH-HR-002", verticalId: "hr", name: "announcements", type: "channel", description: "Company-wide HR announcements", memberNames: ["Sneha Patel", "Amit Desai"], lastMessage: "Q1 appraisal cycle begins March 1.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },
  { id: "CH-HR-003", verticalId: "hr", name: "hiring-pipeline", type: "channel", description: "Active recruitment discussions", memberNames: ["Nisha Choudhary", "Sneha Patel", "Amit Desai"], lastMessage: "3 candidates shortlisted for Senior Dev role.", lastMessageTime: "9:15 AM", unreadCount: 5, isPinned: false },
  { id: "DM-HR-001", verticalId: "hr", name: "Nisha Choudhary", type: "dm", description: "", memberNames: ["Nisha Choudhary"], lastMessage: "Can you share the JD template?", lastMessageTime: "11:00 AM", unreadCount: 1, isPinned: false },
  { id: "DM-HR-002", verticalId: "hr", name: "Amit Desai", type: "dm", description: "", memberNames: ["Amit Desai"], lastMessage: "Got it, will review EOD.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },

  { id: "CH-SALES-001", verticalId: "sales", name: "sales-general", type: "channel", description: "USDrop AI sales team hub", memberNames: ["Karan Gupta", "Vikram Singh", "Priya Verma", "Raj Malhotra"], lastMessage: "Q1 pipeline looking strong — 47 active leads!", lastMessageTime: "9:30 AM", unreadCount: 4, isPinned: true },
  { id: "CH-SALES-002", verticalId: "sales", name: "pipeline", type: "channel", description: "Deal tracking and pipeline updates", memberNames: ["Karan Gupta", "Raj Malhotra"], lastMessage: "Moved TechStore Pro to Proposal stage.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },
  { id: "CH-SALES-003", verticalId: "sales", name: "announcements", type: "channel", description: "Sales team announcements", memberNames: ["Vikram Singh"], lastMessage: "New product launch on March 15 — prep your pitches.", lastMessageTime: "Feb 26", unreadCount: 0, isPinned: false },
  { id: "DM-SALES-001", verticalId: "sales", name: "Vikram Singh", type: "dm", description: "", memberNames: ["Vikram Singh"], lastMessage: "Sending you the campaign brief now.", lastMessageTime: "10:15 AM", unreadCount: 2, isPinned: false },
  { id: "DM-SALES-002", verticalId: "sales", name: "Raj Malhotra", type: "dm", description: "", memberNames: ["Raj Malhotra"], lastMessage: "Client call went well, follow-up tomorrow.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },

  { id: "CH-EVENTS-001", verticalId: "events", name: "goyo-general", type: "channel", description: "GoyoTours operations team", memberNames: ["Deepak Sharma", "Anita Joshi", "Rahul Singh"], lastMessage: "Beijing group confirmed for April 5th departure.", lastMessageTime: "11:20 AM", unreadCount: 2, isPinned: true },
  { id: "CH-EVENTS-002", verticalId: "events", name: "tour-ops", type: "channel", description: "Active tour planning and logistics", memberNames: ["Deepak Sharma", "Anita Joshi"], lastMessage: "Hotel in Shanghai confirmed — 42 rooms block.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },
  { id: "DM-EVENTS-001", verticalId: "events", name: "Anita Joshi", type: "dm", description: "", memberNames: ["Anita Joshi"], lastMessage: "Visa docs from Group 3 still pending.", lastMessageTime: "9:45 AM", unreadCount: 3, isPinned: false },

  { id: "CH-HUB-001", verticalId: "eventhub", name: "hub-general", type: "channel", description: "Event Hub team discussions", memberNames: ["Sonal Mehta", "Nikhil Rao", "Priyanka Das"], lastMessage: "Founders Summit registration is now live!", lastMessageTime: "8:50 AM", unreadCount: 6, isPinned: true },
  { id: "CH-HUB-002", verticalId: "eventhub", name: "vendor-coordination", type: "channel", description: "Vendor booking and follow-ups", memberNames: ["Priyanka Das", "Sonal Mehta"], lastMessage: "SoundWave confirmed for the Delhi event.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },
  { id: "DM-HUB-001", verticalId: "eventhub", name: "Nikhil Rao", type: "dm", description: "", memberNames: ["Nikhil Rao"], lastMessage: "Check-in badges printed — dropping off tomorrow.", lastMessageTime: "10:30 AM", unreadCount: 1, isPinned: false },

  { id: "CH-ADMIN-001", verticalId: "admin", name: "lbm-general", type: "channel", description: "LBM Lifestyle core team", memberNames: ["Arjun Mehta", "Priya Sharma", "Siddharth Rao", "Rohan Joshi"], lastMessage: "New brand guidelines pushed to Figma.", lastMessageTime: "10:05 AM", unreadCount: 2, isPinned: true },
  { id: "CH-ADMIN-002", verticalId: "admin", name: "announcements", type: "channel", description: "Important team announcements", memberNames: ["Arjun Mehta"], lastMessage: "Sprint 12 review is this Friday 4 PM.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },
  { id: "CH-ADMIN-003", verticalId: "admin", name: "product", type: "channel", description: "Product roadmap discussions", memberNames: ["Siddharth Rao", "Arjun Mehta", "Priya Sharma"], lastMessage: "Dashboard redesign approved — moving to dev.", lastMessageTime: "Feb 26", unreadCount: 0, isPinned: false },
  { id: "DM-ADMIN-001", verticalId: "admin", name: "Priya Sharma", type: "dm", description: "", memberNames: ["Priya Sharma"], lastMessage: "Color tokens updated in Tailwind config.", lastMessageTime: "11:10 AM", unreadCount: 1, isPinned: false },

  { id: "CH-DEV-001", verticalId: "dev", name: "dev-general", type: "channel", description: "Engineering team discussions", memberNames: ["Arjun Mehta", "Rohan Joshi", "Rahul Kumar"], lastMessage: "Portal v2 deployed to staging — please test.", lastMessageTime: "9:00 AM", unreadCount: 4, isPinned: true },
  { id: "CH-DEV-002", verticalId: "dev", name: "deployments", type: "channel", description: "Deployment logs and release notes", memberNames: ["Rohan Joshi", "Arjun Mehta"], lastMessage: "Production deploy — v2.4.1 — SUCCESS ✓", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },
  { id: "DM-DEV-001", verticalId: "dev", name: "Rohan Joshi", type: "dm", description: "", memberNames: ["Rohan Joshi"], lastMessage: "Pipeline fixed — should pass now.", lastMessageTime: "10:40 AM", unreadCount: 0, isPinned: false },

  { id: "CH-ETS-001", verticalId: "ets", name: "ets-general", type: "channel", description: "EazyToSell team discussions", memberNames: ["Naveen Pillai", "Sonia Agarwal", "Tarun Shah", "Meera Iyer"], lastMessage: "Franchise partner Ramesh Kumar signed up!", lastMessageTime: "8:30 AM", unreadCount: 5, isPinned: true },
  { id: "CH-ETS-002", verticalId: "ets", name: "franchise-ops", type: "channel", description: "Franchise onboarding and operations", memberNames: ["Naveen Pillai", "Tarun Shah"], lastMessage: "New batch of 500 units shipped from Yiwu.", lastMessageTime: "Yesterday", unreadCount: 0, isPinned: false },
  { id: "CH-ETS-003", verticalId: "ets", name: "announcements", type: "channel", description: "EazyToSell announcements", memberNames: ["Naveen Pillai"], lastMessage: "March franchise camp registrations open.", lastMessageTime: "Feb 25", unreadCount: 0, isPinned: false },
  { id: "DM-ETS-001", verticalId: "ets", name: "Sonia Agarwal", type: "dm", description: "", memberNames: ["Sonia Agarwal"], lastMessage: "Proposal sent — awaiting their response.", lastMessageTime: "11:00 AM", unreadCount: 2, isPinned: false },
];

export const chatMessages: ChatMessage[] = [
  { id: "MSG-HR-001", channelId: "CH-HR-001", senderName: "Amit Desai", content: "Good morning everyone! Quick reminder — all performance review forms need to be submitted by March 5th.", timestamp: "9:00 AM", isMe: false },
  { id: "MSG-HR-002", channelId: "CH-HR-001", senderName: "Sneha Patel", content: "Thanks Amit! I'll send a reminder email to all managers today.", timestamp: "9:04 AM", isMe: false },
  { id: "MSG-HR-003", channelId: "CH-HR-001", senderName: "Nisha Choudhary", content: "Should we also set up a Calendly for 1-on-1s? Last quarter some managers were confused about the process.", timestamp: "9:12 AM", isMe: false },
  { id: "MSG-HR-004", channelId: "CH-HR-001", senderName: "Sneha Patel", content: "Great idea Nisha. I'll create a shared calendar link.", timestamp: "9:15 AM", isMe: true },
  { id: "MSG-HR-005", channelId: "CH-HR-001", senderName: "Pooja Bhat", content: "Also wanted to flag — we have 2 new joiners next Monday. Rahul Kumar and Divya Nair. Need to prep their onboarding kits.", timestamp: "10:01 AM", isMe: false },
  { id: "MSG-HR-006", channelId: "CH-HR-001", senderName: "Sneha Patel", content: "On it! Will share the checklist with you by EOD Pooja.", timestamp: "10:05 AM", isMe: true },
  { id: "MSG-HR-007", channelId: "CH-HR-001", senderName: "Nisha Choudhary", content: "The new leave policy draft is ready for review.", timestamp: "10:42 AM", isMe: false },

  { id: "MSG-HR-011", channelId: "CH-HR-003", senderName: "Nisha Choudhary", content: "Posted the JD for Senior Backend Dev on LinkedIn and Naukri. Already got 12 applications.", timestamp: "9:00 AM", isMe: false },
  { id: "MSG-HR-012", channelId: "CH-HR-003", senderName: "Sneha Patel", content: "Great! Let's screen and shortlist by Thursday. Target 3-4 for panel interviews next week.", timestamp: "9:05 AM", isMe: true },
  { id: "MSG-HR-013", channelId: "CH-HR-003", senderName: "Nisha Choudhary", content: "3 candidates shortlisted for Senior Dev role.", timestamp: "9:15 AM", isMe: false },

  { id: "MSG-SALES-001", channelId: "CH-SALES-001", senderName: "Karan Gupta", content: "Closed another deal this morning! BeautyStore India upgraded to Pro plan. 🎉", timestamp: "9:00 AM", isMe: false },
  { id: "MSG-SALES-002", channelId: "CH-SALES-001", senderName: "Vikram Singh", content: "Amazing Karan! That's our 3rd Pro upgrade this month. Campaign ROI is really paying off.", timestamp: "9:10 AM", isMe: false },
  { id: "MSG-SALES-003", channelId: "CH-SALES-001", senderName: "Raj Malhotra", content: "I have a demo call with FashionMart tomorrow — will share the deck tonight.", timestamp: "9:20 AM", isMe: false },
  { id: "MSG-SALES-004", channelId: "CH-SALES-001", senderName: "Priya Verma", content: "Just sent 20 LinkedIn outreach messages to electronics store owners. Response rate has been around 18% lately.", timestamp: "9:25 AM", isMe: false },
  { id: "MSG-SALES-005", channelId: "CH-SALES-001", senderName: "Karan Gupta", content: "Q1 pipeline looking strong — 47 active leads!", timestamp: "9:30 AM", isMe: true },

  { id: "MSG-EVENTS-001", channelId: "CH-EVENTS-001", senderName: "Deepak Sharma", content: "April Beijing group is finalized — 38 pax. Hotels and transfers are all booked.", timestamp: "10:00 AM", isMe: false },
  { id: "MSG-EVENTS-002", channelId: "CH-EVENTS-001", senderName: "Anita Joshi", content: "Visa applications submitted for 34 of them. Remaining 4 have some document issues — following up.", timestamp: "10:15 AM", isMe: false },
  { id: "MSG-EVENTS-003", channelId: "CH-EVENTS-001", senderName: "Rahul Singh", content: "Coordinating with the Beijing embassy. They said turnaround is 5 working days.", timestamp: "10:30 AM", isMe: false },
  { id: "MSG-EVENTS-004", channelId: "CH-EVENTS-001", senderName: "Deepak Sharma", content: "Beijing group confirmed for April 5th departure.", timestamp: "11:20 AM", isMe: true },

  { id: "MSG-HUB-001", channelId: "CH-HUB-001", senderName: "Sonal Mehta", content: "Great news — IBS Delhi Founders Summit is fully booked! 320 registrations received.", timestamp: "8:00 AM", isMe: false },
  { id: "MSG-HUB-002", channelId: "CH-HUB-001", senderName: "Nikhil Rao", content: "That was fast! Do we need to open a waitlist?", timestamp: "8:05 AM", isMe: false },
  { id: "MSG-HUB-003", channelId: "CH-HUB-001", senderName: "Sonal Mehta", content: "Yes, setting up a waitlist with 50 slots. Nikhil can you update the event page?", timestamp: "8:10 AM", isMe: true },
  { id: "MSG-HUB-004", channelId: "CH-HUB-001", senderName: "Nikhil Rao", content: "On it! Will update in the next 30 mins.", timestamp: "8:15 AM", isMe: false },
  { id: "MSG-HUB-005", channelId: "CH-HUB-001", senderName: "Priyanka Das", content: "SoundWave AV confirmed their setup — arriving the day before for installation.", timestamp: "8:40 AM", isMe: false },
  { id: "MSG-HUB-006", channelId: "CH-HUB-001", senderName: "Sonal Mehta", content: "Founders Summit registration is now live!", timestamp: "8:50 AM", isMe: true },

  { id: "MSG-ADMIN-001", channelId: "CH-ADMIN-001", senderName: "Priya Sharma", content: "Finished the new component library documentation. All Shadcn overrides are now listed with examples.", timestamp: "9:30 AM", isMe: false },
  { id: "MSG-ADMIN-002", channelId: "CH-ADMIN-001", senderName: "Arjun Mehta", content: "Perfect timing! I needed that for the onboarding doc for Rahul.", timestamp: "9:35 AM", isMe: false },
  { id: "MSG-ADMIN-003", channelId: "CH-ADMIN-001", senderName: "Siddharth Rao", content: "Also sharing the updated product roadmap — Q2 priorities are locked.", timestamp: "9:45 AM", isMe: false },
  { id: "MSG-ADMIN-004", channelId: "CH-ADMIN-001", senderName: "Rohan Joshi", content: "Prod deploy went smooth this morning. Zero downtime.", timestamp: "9:55 AM", isMe: false },
  { id: "MSG-ADMIN-005", channelId: "CH-ADMIN-001", senderName: "Priya Sharma", content: "New brand guidelines pushed to Figma.", timestamp: "10:05 AM", isMe: true },

  { id: "MSG-DEV-001", channelId: "CH-DEV-001", senderName: "Arjun Mehta", content: "Staging build is up! Please test the new DataTable component — especially filters and pagination.", timestamp: "8:30 AM", isMe: false },
  { id: "MSG-DEV-002", channelId: "CH-DEV-001", senderName: "Rahul Kumar", content: "On it! Found a small issue with the column sorting — fixing now.", timestamp: "8:45 AM", isMe: false },
  { id: "MSG-DEV-003", channelId: "CH-DEV-001", senderName: "Rohan Joshi", content: "CI pipeline is all green. No issues in the test suite.", timestamp: "8:55 AM", isMe: false },
  { id: "MSG-DEV-004", channelId: "CH-DEV-001", senderName: "Arjun Mehta", content: "Portal v2 deployed to staging — please test.", timestamp: "9:00 AM", isMe: true },

  { id: "MSG-ETS-001", channelId: "CH-ETS-001", senderName: "Naveen Pillai", content: "Welcome update — Ramesh Kumar from Nagpur just signed the franchise agreement! He's our 15th partner.", timestamp: "8:00 AM", isMe: false },
  { id: "MSG-ETS-002", channelId: "CH-ETS-001", senderName: "Sonia Agarwal", content: "Amazing Naveen! I'll send him the onboarding kit today.", timestamp: "8:05 AM", isMe: false },
  { id: "MSG-ETS-003", channelId: "CH-ETS-001", senderName: "Tarun Shah", content: "Inventory for his first order is in transit from Yiwu — ETA March 5th.", timestamp: "8:15 AM", isMe: false },
  { id: "MSG-ETS-004", channelId: "CH-ETS-001", senderName: "Meera Iyer", content: "I'll set up a welcome call with him this week to walk through the portal.", timestamp: "8:20 AM", isMe: false },
  { id: "MSG-ETS-005", channelId: "CH-ETS-001", senderName: "Naveen Pillai", content: "Franchise partner Ramesh Kumar signed up!", timestamp: "8:30 AM", isMe: true },
];

export const sharedResources: SharedResource[] = [
  { id: "RES-HR-001", verticalId: "hr", title: "Employee Handbook 2026", description: "Comprehensive guide to company policies, benefits, code of conduct, leave policies, and grievance procedures. Updated for 2026 with new remote work guidelines.", category: "Document", type: "pdf", tags: ["policy", "onboarding", "HR"], addedBy: "Sneha Patel", addedDate: "2026-01-10", fileSize: "2.4 MB", url: "#", isPinned: true, version: "v4.2" },
  { id: "RES-HR-002", verticalId: "hr", title: "Offer Letter Template", description: "Standard offer letter template for all employment types including full-time, contract, and internship positions. Includes variable compensation tables.", category: "Template", type: "doc", tags: ["offer", "template", "hiring"], addedBy: "Nisha Choudhary", addedDate: "2025-11-20", fileSize: "185 KB", url: "#", isPinned: false, version: "v2.1" },
  { id: "RES-HR-003", verticalId: "hr", title: "HR Policy Manual", description: "Detailed HR policy document covering attendance, performance management, disciplinary procedures, and benefits administration.", category: "Document", type: "pdf", tags: ["policy", "compliance"], addedBy: "Amit Desai", addedDate: "2025-09-15", fileSize: "1.8 MB", url: "#", isPinned: false, version: "v3.0" },
  { id: "RES-HR-004", verticalId: "hr", title: "Onboarding Checklist", description: "Interactive checklist for new employee onboarding — covers IT setup, introductions, policy reading, system access, and 30-60-90 day goals.", category: "Link", type: "link", tags: ["onboarding", "checklist"], addedBy: "Pooja Bhat", addedDate: "2026-02-01", fileSize: "", url: "https://notion.so", isPinned: false, version: "v1.5" },
  { id: "RES-HR-005", verticalId: "hr", title: "Salary Bands FY2026", description: "Confidential salary bands by role, level, and location. Used for offer decisions, performance increments, and equity reviews.", category: "Spreadsheet", type: "excel", tags: ["salary", "compensation", "confidential"], addedBy: "Sneha Patel", addedDate: "2026-01-02", fileSize: "420 KB", url: "#", isPinned: false, version: "v1.0" },
  { id: "RES-HR-006", verticalId: "hr", title: "Exit Interview Form", description: "Structured exit interview form to gather feedback from departing employees. Includes satisfaction ratings, reason for leaving, and suggestions.", category: "Template", type: "doc", tags: ["exit", "feedback", "template"], addedBy: "Pooja Bhat", addedDate: "2025-10-05", fileSize: "95 KB", url: "#", isPinned: false, version: "v1.2" },

  { id: "RES-SALES-001", verticalId: "sales", title: "USDrop AI Product Brochure", description: "Full product brochure for USDrop AI platform — covers features, pricing, case studies, and onboarding process. Ready to share with prospects.", category: "Brochure", type: "pdf", tags: ["brochure", "product", "sales"], addedBy: "Vikram Singh", addedDate: "2026-01-20", fileSize: "3.2 MB", url: "#", isPinned: true, version: "v2.0" },
  { id: "RES-SALES-002", verticalId: "sales", title: "Sales Discovery Script", description: "Structured discovery call script for qualifying dropshipping prospects. Includes question bank, objection handling, and closing techniques.", category: "Script", type: "ppt", tags: ["script", "discovery", "sales"], addedBy: "Karan Gupta", addedDate: "2025-12-10", fileSize: "1.1 MB", url: "#", isPinned: false, version: "v3.1" },
  { id: "RES-SALES-003", verticalId: "sales", title: "Competitor Analysis Q1 2026", description: "Deep-dive comparison of USDrop AI vs Oberlo, AutoDS, and Zendrop. Includes feature matrix, pricing comparison, and our competitive advantages.", category: "Spreadsheet", type: "excel", tags: ["competitive", "research", "Q1"], addedBy: "Vikram Singh", addedDate: "2026-02-05", fileSize: "680 KB", url: "#", isPinned: false, version: "v1.0" },
  { id: "RES-SALES-004", verticalId: "sales", title: "LinkedIn Sales Navigator Guide", description: "Step-by-step guide to using LinkedIn Sales Navigator for prospecting dropshipping store owners and ecommerce entrepreneurs.", category: "Link", type: "link", tags: ["linkedin", "prospecting", "tools"], addedBy: "Priya Verma", addedDate: "2025-11-15", fileSize: "", url: "https://linkedin.com", isPinned: false, version: "v1.0" },
  { id: "RES-SALES-005", verticalId: "sales", title: "Q1 2026 Pricing Sheet", description: "Current pricing for all USDrop AI plans — Starter, Growth, Pro, and Enterprise. Includes discount matrix and promotional offers.", category: "Spreadsheet", type: "excel", tags: ["pricing", "plans", "Q1"], addedBy: "Raj Malhotra", addedDate: "2026-01-05", fileSize: "215 KB", url: "#", isPinned: false, version: "v2.3" },
  { id: "RES-SALES-006", verticalId: "sales", title: "USDrop Investor Pitch Deck", description: "Investor-grade pitch deck covering market opportunity, product overview, traction metrics, team, and funding ask.", category: "Presentation", type: "ppt", tags: ["pitch", "investor", "deck"], addedBy: "Vikram Singh", addedDate: "2025-10-20", fileSize: "8.5 MB", url: "#", isPinned: false, version: "v1.4" },

  { id: "RES-EVENTS-001", verticalId: "events", title: "China Tour Brochure 2026", description: "Premium tour brochure for all China packages — Beijing, Shanghai, Chengdu, Xi'an routes with hotel options, inclusions, and pricing.", category: "Brochure", type: "pdf", tags: ["china", "tours", "brochure"], addedBy: "Deepak Sharma", addedDate: "2026-01-15", fileSize: "5.8 MB", url: "#", isPinned: true, version: "v3.0" },
  { id: "RES-EVENTS-002", verticalId: "events", title: "China Visa Application Guide", description: "Step-by-step guide for Chinese tourist visa applications — document checklist, embassy contacts, processing times by city, and common rejection reasons.", category: "Document", type: "doc", tags: ["visa", "china", "guide"], addedBy: "Rahul Singh", addedDate: "2026-02-10", fileSize: "340 KB", url: "#", isPinned: false, version: "v2.1" },
  { id: "RES-EVENTS-003", verticalId: "events", title: "Hotel Booking SOP", description: "Standard operating procedure for hotel block bookings — includes preferred partner list, negotiation checklist, cancellation terms, and group rate guidelines.", category: "Document", type: "doc", tags: ["hotels", "SOP", "operations"], addedBy: "Anita Joshi", addedDate: "2025-08-20", fileSize: "280 KB", url: "#", isPinned: false, version: "v1.3" },
  { id: "RES-EVENTS-004", verticalId: "events", title: "Itinerary Templates Library", description: "Collection of 8 ready-to-customize itinerary templates for 5-day, 7-day, and 10-day China tours. Available in English and Hindi.", category: "Template", type: "excel", tags: ["itinerary", "template", "planning"], addedBy: "Deepak Sharma", addedDate: "2025-11-01", fileSize: "520 KB", url: "#", isPinned: false, version: "v2.0" },
  { id: "RES-EVENTS-005", verticalId: "events", title: "Emergency Contacts Directory", description: "Emergency contacts for all China cities — hospitals, police, Indian embassy, local guides, and insurance hotlines. Must be shared with every tour group.", category: "Link", type: "link", tags: ["emergency", "contacts", "safety"], addedBy: "Anita Joshi", addedDate: "2026-01-20", fileSize: "", url: "https://notion.so", isPinned: false, version: "v1.0" },

  { id: "RES-HUB-001", verticalId: "eventhub", title: "Event Planning Master Checklist", description: "Comprehensive checklist for all networking events — covers 90 days out to day-of timeline, covering venue, AV, catering, registrations, and follow-ups.", category: "Document", type: "doc", tags: ["planning", "checklist", "master"], addedBy: "Sonal Mehta", addedDate: "2026-01-05", fileSize: "220 KB", url: "#", isPinned: true, version: "v2.4" },
  { id: "RES-HUB-002", verticalId: "eventhub", title: "Vendor Contact Directory", description: "Complete vendor database with contact details, rates, availability, and past event history for AV, catering, photography, decoration, and security vendors.", category: "Spreadsheet", type: "excel", tags: ["vendors", "contacts", "directory"], addedBy: "Priyanka Das", addedDate: "2026-02-01", fileSize: "380 KB", url: "#", isPinned: false, version: "v1.8" },
  { id: "RES-HUB-003", verticalId: "eventhub", title: "AV & Tech Setup Guide", description: "Technical setup guide for audio-visual equipment at various venue types — includes mic placement, projector specs, lighting, and streaming setup for hybrid events.", category: "Document", type: "pdf", tags: ["AV", "tech", "setup"], addedBy: "Nikhil Rao", addedDate: "2025-10-15", fileSize: "1.2 MB", url: "#", isPinned: false, version: "v1.1" },
  { id: "RES-HUB-004", verticalId: "eventhub", title: "Event Budget Template", description: "Structured budget planning spreadsheet for networking events — includes venue, catering, AV, marketing, transport, and contingency categories with formulas.", category: "Template", type: "excel", tags: ["budget", "template", "finance"], addedBy: "Sonal Mehta", addedDate: "2025-12-20", fileSize: "295 KB", url: "#", isPinned: false, version: "v3.0" },
  { id: "RES-HUB-005", verticalId: "eventhub", title: "Attendee Communication Scripts", description: "Email and WhatsApp message templates for attendee communication — registration confirmation, reminder sequences, day-of instructions, and post-event follow-up.", category: "Script", type: "doc", tags: ["comms", "templates", "attendees"], addedBy: "Priyanka Das", addedDate: "2026-01-25", fileSize: "145 KB", url: "#", isPinned: false, version: "v1.6" },
  { id: "RES-HUB-006", verticalId: "eventhub", title: "Post-Event Survey Form", description: "NPS-based post-event feedback survey for attendees — covers overall satisfaction, speaker quality, venue rating, networking value, and improvement suggestions.", category: "Link", type: "link", tags: ["survey", "feedback", "NPS"], addedBy: "Nikhil Rao", addedDate: "2026-02-10", fileSize: "", url: "https://forms.google.com", isPinned: false, version: "v2.0" },

  { id: "RES-ADMIN-001", verticalId: "admin", title: "Company Policy Manual 2026", description: "Master policy document for LBM Lifestyle — covers code of conduct, data privacy, vendor policies, expense reimbursement, and conflict of interest guidelines.", category: "Document", type: "pdf", tags: ["policy", "compliance", "company"], addedBy: "Arjun Mehta", addedDate: "2026-01-02", fileSize: "3.1 MB", url: "#", isPinned: true, version: "v5.0" },
  { id: "RES-ADMIN-002", verticalId: "admin", title: "Brand Guidelines v3", description: "Complete brand identity guidelines — logo usage, color palette, typography, photography style, tone of voice, and digital asset specifications.", category: "Brochure", type: "pdf", tags: ["brand", "design", "guidelines"], addedBy: "Priya Sharma", addedDate: "2026-01-15", fileSize: "12.4 MB", url: "#", isPinned: false, version: "v3.0" },
  { id: "RES-ADMIN-003", verticalId: "admin", title: "Operations Playbook", description: "Standard operating procedures for all business functions — includes process flows for onboarding, vendor management, reporting, and escalation protocols.", category: "Document", type: "doc", tags: ["operations", "SOP", "processes"], addedBy: "Siddharth Rao", addedDate: "2025-09-01", fileSize: "880 KB", url: "#", isPinned: false, version: "v2.2" },
  { id: "RES-ADMIN-004", verticalId: "admin", title: "Vendor Master List", description: "Consolidated list of all approved vendors — includes contact details, contract status, payment terms, and performance ratings for each category.", category: "Spreadsheet", type: "excel", tags: ["vendors", "procurement"], addedBy: "Rohan Joshi", addedDate: "2026-02-05", fileSize: "640 KB", url: "#", isPinned: false, version: "v1.9" },
  { id: "RES-ADMIN-005", verticalId: "admin", title: "Organisation Chart 2026", description: "Current organizational structure — includes all departments, reporting lines, headcount, and open positions. Updated as of February 2026.", category: "Document", type: "image", tags: ["org", "structure", "team"], addedBy: "Priya Sharma", addedDate: "2026-02-01", fileSize: "1.5 MB", url: "#", isPinned: false, version: "v1.0" },
  { id: "RES-ADMIN-006", verticalId: "admin", title: "Business Plan FY2026", description: "Annual business plan for LBM Lifestyle — revenue targets, expansion roadmap, budget allocation, key initiatives, and OKRs for all verticals.", category: "Presentation", type: "ppt", tags: ["business plan", "strategy", "FY2026"], addedBy: "Arjun Mehta", addedDate: "2025-12-28", fileSize: "6.2 MB", url: "#", isPinned: false, version: "v1.0" },

  { id: "RES-DEV-001", verticalId: "dev", title: "System Architecture Diagram", description: "High-level architecture of the TeamSync portal — includes frontend/backend separation, API structure, data flow, and infrastructure components on Replit.", category: "Document", type: "doc", tags: ["architecture", "technical", "system"], addedBy: "Arjun Mehta", addedDate: "2026-02-10", fileSize: "850 KB", url: "#", isPinned: true, version: "v2.1" },
  { id: "RES-DEV-002", verticalId: "dev", title: "API Documentation", description: "Complete API reference for all backend endpoints — includes request/response schemas, authentication, error codes, and usage examples.", category: "Link", type: "link", tags: ["API", "docs", "backend"], addedBy: "Arjun Mehta", addedDate: "2025-12-01", fileSize: "", url: "https://docs.example.com", isPinned: false, version: "v1.0" },
  { id: "RES-DEV-003", verticalId: "dev", title: "Design System Guide", description: "Developer guide for the TeamSync design system — component usage, Tailwind config, dark mode tokens, animation patterns, and data-testid conventions.", category: "Link", type: "link", tags: ["design system", "components", "frontend"], addedBy: "Arjun Mehta", addedDate: "2026-01-15", fileSize: "", url: "https://dev/style-guide", isPinned: false, version: "v1.0" },
  { id: "RES-DEV-004", verticalId: "dev", title: "GitHub Repositories", description: "Links to all project repositories — TeamSync portal, mobile app experiments, design assets, and DevOps infrastructure scripts.", category: "Link", type: "link", tags: ["github", "repos", "code"], addedBy: "Rohan Joshi", addedDate: "2025-11-10", fileSize: "", url: "https://github.com", isPinned: false, version: "v1.0" },
  { id: "RES-DEV-005", verticalId: "dev", title: "Deployment Runbook", description: "Step-by-step deployment guide for production releases — includes pre-deploy checklist, Replit deploy process, rollback procedures, and monitoring setup.", category: "Document", type: "doc", tags: ["deployment", "runbook", "DevOps"], addedBy: "Rohan Joshi", addedDate: "2026-01-20", fileSize: "310 KB", url: "#", isPinned: false, version: "v1.3" },
  { id: "RES-DEV-006", verticalId: "dev", title: "Security Checklist", description: "Security review checklist for all new features — covers input validation, auth, data exposure, dependency audits, and OWASP Top 10 compliance checks.", category: "Document", type: "doc", tags: ["security", "checklist", "compliance"], addedBy: "Rohan Joshi", addedDate: "2025-12-15", fileSize: "180 KB", url: "#", isPinned: false, version: "v2.0" },

  { id: "RES-ETS-001", verticalId: "ets", title: "Franchise Agreement Template", description: "Standard franchise agreement covering territory rights, fee structure, operational standards, renewal terms, and exit clauses. Reviewed by legal team.", category: "Template", type: "pdf", tags: ["franchise", "legal", "agreement"], addedBy: "Naveen Pillai", addedDate: "2025-10-01", fileSize: "2.8 MB", url: "#", isPinned: true, version: "v4.1" },
  { id: "RES-ETS-002", verticalId: "ets", title: "Product Catalog 2026", description: "Full product catalog with 200+ SKUs — includes product images, descriptions, MOQ, China cost, India MRP, and recommended retail pricing.", category: "Brochure", type: "pdf", tags: ["products", "catalog", "SKUs"], addedBy: "Tarun Shah", addedDate: "2026-01-10", fileSize: "18.5 MB", url: "#", isPinned: false, version: "v2.0" },
  { id: "RES-ETS-003", verticalId: "ets", title: "Commission Calculator", description: "Excel tool for calculating franchise partner commissions based on monthly sales volume, product category, and performance tier.", category: "Spreadsheet", type: "excel", tags: ["commission", "calculator", "finance"], addedBy: "Sonia Agarwal", addedDate: "2026-01-25", fileSize: "340 KB", url: "#", isPinned: false, version: "v1.5" },
  { id: "RES-ETS-004", verticalId: "ets", title: "EazyToSell CRM Guide", description: "User guide for the EazyToSell franchise management portal — covers pipeline management, order tracking, proposal generation, and reporting.", category: "Link", type: "link", tags: ["CRM", "guide", "portal"], addedBy: "Meera Iyer", addedDate: "2026-02-01", fileSize: "", url: "https://ets/dashboard", isPinned: false, version: "v1.0" },
  { id: "RES-ETS-005", verticalId: "ets", title: "Franchise Onboarding Kit", description: "Complete onboarding package for new franchise partners — includes welcome guide, store setup checklist, training schedule, and first-order guide.", category: "Document", type: "pdf", tags: ["onboarding", "franchise", "kit"], addedBy: "Naveen Pillai", addedDate: "2025-12-05", fileSize: "4.2 MB", url: "#", isPinned: false, version: "v3.0" },
  { id: "RES-ETS-006", verticalId: "ets", title: "Monthly KPI Report Template", description: "Standardized KPI reporting template for franchise partners — tracks sales volume, footfall, order fulfillment rate, customer satisfaction, and profitability.", category: "Spreadsheet", type: "excel", tags: ["KPI", "reporting", "monthly"], addedBy: "Tarun Shah", addedDate: "2025-09-20", fileSize: "260 KB", url: "#", isPinned: false, version: "v2.1" },
];

export const sharedTasks: SharedTask[] = [
  { id: "T-HR-001", verticalId: "hr", title: "Onboard Rahul Kumar", description: "Complete new employee onboarding — set up laptop, email, Slack, all system access, and schedule orientation sessions with each department head.", status: "in-progress", priority: "high", assigneeName: "Sneha Patel", dueDate: "2026-03-03", tags: ["onboarding", "new-hire"], createdDate: "2026-02-25", subtasks: [{ id: "st-1", title: "Set up laptop and accounts", completed: true }, { id: "st-2", title: "Send welcome email", completed: true }, { id: "st-3", title: "Schedule dept introductions", completed: false }, { id: "st-4", title: "Complete Day 1 checklist", completed: false }] },
  { id: "T-HR-002", verticalId: "hr", title: "Q1 Performance Reviews", description: "Coordinate performance review cycle — distribute forms to managers, schedule calibration meetings, and compile final ratings by March 15.", status: "todo", priority: "high", assigneeName: "Sneha Patel", dueDate: "2026-03-15", tags: ["performance", "Q1"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Send review forms to managers", completed: false }, { id: "st-2", title: "Schedule calibration meetings", completed: false }, { id: "st-3", title: "Compile ratings", completed: false }] },
  { id: "T-HR-003", verticalId: "hr", title: "Update Leave Policy", description: "Revise the leave policy to include new paternity leave provisions, work-from-home allowances, and mental health days as per the new labor law amendments.", status: "in-progress", priority: "medium", assigneeName: "Pooja Bhat", dueDate: "2026-03-10", tags: ["policy", "compliance"], createdDate: "2026-02-15", subtasks: [{ id: "st-1", title: "Draft new provisions", completed: true }, { id: "st-2", title: "Legal review", completed: false }, { id: "st-3", title: "Get MD approval", completed: false }] },
  { id: "T-HR-004", verticalId: "hr", title: "Walk-in Drive — Senior Backend Dev", description: "Organize walk-in recruitment drive for Senior Backend Developer position — book venue, coordinate panel, shortlist from applications.", status: "todo", priority: "high", assigneeName: "Nisha Choudhary", dueDate: "2026-03-08", tags: ["recruitment", "hiring"], createdDate: "2026-02-22", subtasks: [{ id: "st-1", title: "Post JD on all platforms", completed: true }, { id: "st-2", title: "Shortlist applications", completed: false }, { id: "st-3", title: "Book venue and panel", completed: false }] },
  { id: "T-HR-005", verticalId: "hr", title: "Refresh Job Description Templates", description: "Update JD templates for all 12 common roles to reflect current tech stack, remote work policies, and new compensation structures.", status: "done", priority: "medium", assigneeName: "Nisha Choudhary", dueDate: "2026-02-25", tags: ["JD", "templates"], createdDate: "2026-02-10", subtasks: [{ id: "st-1", title: "Audit existing JDs", completed: true }, { id: "st-2", title: "Update templates", completed: true }, { id: "st-3", title: "Upload to ATS", completed: true }] },
  { id: "T-HR-006", verticalId: "hr", title: "Compliance Audit — PF & ESI", description: "Conduct internal compliance audit for PF and ESI contributions for January and February payroll cycles.", status: "backlog", priority: "critical", assigneeName: "Amit Desai", dueDate: "2026-03-20", tags: ["compliance", "payroll"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Gather payroll data", completed: false }, { id: "st-2", title: "Cross-check with EPFO records", completed: false }] },
  { id: "T-HR-007", verticalId: "hr", title: "Employee Engagement Survey", description: "Design and launch Q1 employee engagement survey — target 80% participation rate and share results with management by end of March.", status: "review", priority: "medium", assigneeName: "Pooja Bhat", dueDate: "2026-03-05", tags: ["engagement", "survey"], createdDate: "2026-02-18", subtasks: [{ id: "st-1", title: "Design survey questions", completed: true }, { id: "st-2", title: "Set up in Google Forms", completed: true }, { id: "st-3", title: "Send to all employees", completed: false }] },
  { id: "T-HR-008", verticalId: "hr", title: "HR System Migration Planning", description: "Plan and document the migration from current HRMS to the new platform. Identify data fields, test migration scripts, and plan employee training.", status: "backlog", priority: "low", assigneeName: "Sneha Patel", dueDate: "2026-04-15", tags: ["HRMS", "migration", "tech"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Map current data fields", completed: false }, { id: "st-2", title: "Evaluate new platform", completed: false }] },
  { id: "T-HR-009", verticalId: "hr", title: "Internship Program Q2", description: "Design summer internship program — partner with 5 colleges, create stipend structure, project assignments, and evaluation framework.", status: "todo", priority: "medium", assigneeName: "Nisha Choudhary", dueDate: "2026-03-25", tags: ["internship", "campus"], createdDate: "2026-02-24", subtasks: [{ id: "st-1", title: "Shortlist partner colleges", completed: false }, { id: "st-2", title: "Define stipend structure", completed: false }] },

  { id: "T-SALES-001", verticalId: "sales", title: "Q1 Sales Target Review", description: "Review Q1 sales performance against targets — prepare slide deck with deal breakdown, win/loss analysis, and Q2 forecast.", status: "in-progress", priority: "high", assigneeName: "Karan Gupta", dueDate: "2026-03-15", tags: ["Q1", "review", "targets"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Pull CRM data", completed: true }, { id: "st-2", title: "Build slide deck", completed: false }, { id: "st-3", title: "Review with Vikram", completed: false }] },
  { id: "T-SALES-002", verticalId: "sales", title: "LinkedIn Outreach Campaign", description: "Run targeted LinkedIn outreach to 100 ecommerce store owners per week for 4 weeks. Track opens, responses, and conversions.", status: "in-progress", priority: "medium", assigneeName: "Priya Verma", dueDate: "2026-03-28", tags: ["linkedin", "outreach", "campaign"], createdDate: "2026-02-15", subtasks: [{ id: "st-1", title: "Build prospect list", completed: true }, { id: "st-2", title: "Draft message sequences", completed: true }, { id: "st-3", title: "Week 1 outreach", completed: true }, { id: "st-4", title: "Week 2-4 outreach", completed: false }] },
  { id: "T-SALES-003", verticalId: "sales", title: "FashionMart Demo Prep", description: "Prepare customized demo for FashionMart prospect — build their store scenario in USDrop sandbox, prepare ROI calculator, and draft proposal.", status: "todo", priority: "critical", assigneeName: "Raj Malhotra", dueDate: "2026-03-01", tags: ["demo", "prospect"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Build demo store scenario", completed: false }, { id: "st-2", title: "Prepare ROI calculator", completed: false }, { id: "st-3", title: "Draft proposal", completed: false }] },
  { id: "T-SALES-004", verticalId: "sales", title: "Product Launch Campaign — March 15", description: "Coordinate marketing campaign for March 15 product launch — email blast, social media posts, and webinar for existing users.", status: "todo", priority: "high", assigneeName: "Vikram Singh", dueDate: "2026-03-14", tags: ["launch", "marketing"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "Draft email sequence", completed: false }, { id: "st-2", title: "Create social assets", completed: false }, { id: "st-3", title: "Set up webinar", completed: false }] },
  { id: "T-SALES-005", verticalId: "sales", title: "Update CRM Data", description: "Clean up and update Salesforce CRM — remove duplicates, update deal stages, add missing contact details for Q1 pipeline.", status: "done", priority: "low", assigneeName: "Karan Gupta", dueDate: "2026-02-28", tags: ["CRM", "data"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Remove duplicate records", completed: true }, { id: "st-2", title: "Update deal stages", completed: true }] },
  { id: "T-SALES-006", verticalId: "sales", title: "Competitor Pricing Analysis", description: "Research and document competitor pricing changes since January. Update our competitive positioning matrix.", status: "review", priority: "medium", assigneeName: "Vikram Singh", dueDate: "2026-03-05", tags: ["competitive", "pricing"], createdDate: "2026-02-18", subtasks: [{ id: "st-1", title: "Research competitor sites", completed: true }, { id: "st-2", title: "Update pricing matrix", completed: true }, { id: "st-3", title: "Share with team", completed: false }] },
  { id: "T-SALES-007", verticalId: "sales", title: "Onboard 3 New Pro Subscribers", description: "Lead personalized onboarding for the 3 new Pro plan subscribers — setup calls, store configuration, and first supplier introductions.", status: "backlog", priority: "high", assigneeName: "Raj Malhotra", dueDate: "2026-03-10", tags: ["onboarding", "pro"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Schedule onboarding calls", completed: false }] },
  { id: "T-SALES-008", verticalId: "sales", title: "Webinar — Winning Products Masterclass", description: "Organize and host webinar on finding winning dropshipping products using USDrop AI — target 200 attendees.", status: "backlog", priority: "medium", assigneeName: "Priya Verma", dueDate: "2026-03-22", tags: ["webinar", "content"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Define webinar agenda", completed: false }, { id: "st-2", title: "Set up registration page", completed: false }] },
  { id: "T-SALES-009", verticalId: "sales", title: "Partner Channel Program Design", description: "Design a reseller/affiliate partner program for USDrop AI — commission structure, onboarding kit, co-marketing assets.", status: "backlog", priority: "low", assigneeName: "Vikram Singh", dueDate: "2026-04-01", tags: ["partners", "channel"], createdDate: "2026-02-25", subtasks: [{ id: "st-1", title: "Research partner program models", completed: false }] },

  { id: "T-EVENTS-001", verticalId: "events", title: "April Beijing Group — Final Logistics", description: "Finalize all logistics for April 5 Beijing departure — confirm airline seats, transfer vehicles, hotel check-in details, and tour guide contacts.", status: "in-progress", priority: "critical", assigneeName: "Deepak Sharma", dueDate: "2026-03-01", tags: ["Beijing", "April", "logistics"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Confirm airline seats", completed: true }, { id: "st-2", title: "Confirm hotel rooms", completed: true }, { id: "st-3", title: "Brief tour guides", completed: false }] },
  { id: "T-EVENTS-002", verticalId: "events", title: "Visa Follow-up — 4 Pending Applicants", description: "Follow up with Beijing embassy on 4 visa applications with document issues. Collect missing documents from clients and resubmit.", status: "todo", priority: "critical", assigneeName: "Rahul Singh", dueDate: "2026-03-02", tags: ["visa", "urgent"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "Contact clients for documents", completed: false }, { id: "st-2", title: "Resubmit applications", completed: false }] },
  { id: "T-EVENTS-003", verticalId: "events", title: "Q2 Tour Brochure Update", description: "Update China tour brochure for Q2 2026 — new hotel partners, updated pricing, and 2 new city add-on options.", status: "backlog", priority: "medium", assigneeName: "Deepak Sharma", dueDate: "2026-03-20", tags: ["brochure", "Q2"], createdDate: "2026-02-25", subtasks: [{ id: "st-1", title: "Collect new hotel info", completed: false }, { id: "st-2", title: "Design new brochure pages", completed: false }] },
  { id: "T-EVENTS-004", verticalId: "events", title: "Group Insurance Renewal", description: "Renew group travel insurance policy for all GoyoTours groups. Compare 3 providers and select best coverage.", status: "review", priority: "high", assigneeName: "Anita Joshi", dueDate: "2026-03-10", tags: ["insurance", "compliance"], createdDate: "2026-02-10", subtasks: [{ id: "st-1", title: "Get quotes from 3 providers", completed: true }, { id: "st-2", title: "Compare coverage", completed: true }, { id: "st-3", title: "Get MD approval", completed: false }] },
  { id: "T-EVENTS-005", verticalId: "events", title: "New Partner Hotel — Chengdu", description: "Negotiate and finalize partnership with new 5-star hotel in Chengdu for 2026 groups. Target 15% group discount.", status: "in-progress", priority: "medium", assigneeName: "Anita Joshi", dueDate: "2026-03-15", tags: ["hotels", "Chengdu"], createdDate: "2026-02-18", subtasks: [{ id: "st-1", title: "Initial meeting with hotel", completed: true }, { id: "st-2", title: "Negotiate group rates", completed: false }] },
  { id: "T-EVENTS-006", verticalId: "events", title: "Emergency Protocol Update", description: "Update emergency response protocol for all active tours — include new embassy contacts, hospital directories, and evacuation procedures.", status: "done", priority: "high", assigneeName: "Rahul Singh", dueDate: "2026-02-20", tags: ["emergency", "protocol"], createdDate: "2026-02-05", subtasks: [{ id: "st-1", title: "Update embassy contacts", completed: true }, { id: "st-2", title: "Update hospital directories", completed: true }, { id: "st-3", title: "Distribute to all guides", completed: true }] },
  { id: "T-EVENTS-007", verticalId: "events", title: "Digital Booking System Evaluation", description: "Evaluate 3 online booking systems for GoyoTours — automated visa tracking, group management, and payment collection features.", status: "backlog", priority: "low", assigneeName: "Deepak Sharma", dueDate: "2026-04-01", tags: ["tech", "booking"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Shortlist 3 platforms", completed: false }] },
  { id: "T-EVENTS-008", verticalId: "events", title: "May Shanghai Premium Tour", description: "Set up the May Shanghai premium small-group tour — 12 pax, luxury hotels, private guide, fine dining inclusions.", status: "todo", priority: "medium", assigneeName: "Deepak Sharma", dueDate: "2026-03-25", tags: ["Shanghai", "premium"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "Book luxury hotels", completed: false }, { id: "st-2", title: "Arrange private guide", completed: false }] },

  { id: "T-HUB-001", verticalId: "eventhub", title: "IBS Delhi Founders Summit — Day-of Plan", description: "Finalize the day-of operations plan for March 15 summit — registration desk setup, volunteer briefing, AV check, speaker green room, and contingency protocols.", status: "in-progress", priority: "critical", assigneeName: "Sonal Mehta", dueDate: "2026-03-12", tags: ["Delhi", "summit", "day-of"], createdDate: "2026-02-25", subtasks: [{ id: "st-1", title: "Finalize volunteer roster", completed: true }, { id: "st-2", title: "Venue walkthrough", completed: true }, { id: "st-3", title: "AV tech rehearsal", completed: false }, { id: "st-4", title: "Print all materials", completed: false }] },
  { id: "T-HUB-002", verticalId: "eventhub", title: "Investor Meet Q2 — Venue Booking", description: "Confirm and book venue for Q2 Investor Meet in Mumbai — targeting Oberoi Business Hub or ITC Grand Central, for 100-120 pax.", status: "todo", priority: "high", assigneeName: "Priyanka Das", dueDate: "2026-03-05", tags: ["Mumbai", "investor", "venue"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Request quotes from 2 venues", completed: false }, { id: "st-2", title: "Site visit", completed: false }, { id: "st-3", title: "Confirm booking", completed: false }] },
  { id: "T-HUB-003", verticalId: "eventhub", title: "Speaker Confirmation — Tech Summit", description: "Confirm 5 keynote speakers for Tech Founders Conference. Send confirmation emails, collect bios, and coordinate travel/hotel.", status: "in-progress", priority: "high", assigneeName: "Nikhil Rao", dueDate: "2026-03-08", tags: ["speakers", "conference"], createdDate: "2026-02-22", subtasks: [{ id: "st-1", title: "Send confirmation to 5 speakers", completed: true }, { id: "st-2", title: "Collect bios and headshots", completed: false }, { id: "st-3", title: "Arrange hotel for outstation speakers", completed: false }] },
  { id: "T-HUB-004", verticalId: "eventhub", title: "Post-Event Report — Feb Workshop", description: "Compile post-event report for Feb Founders Workshop — attendance metrics, NPS scores, budget actuals, and recommendations.", status: "review", priority: "medium", assigneeName: "Sonal Mehta", dueDate: "2026-03-03", tags: ["report", "post-event"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Compile attendance data", completed: true }, { id: "st-2", title: "Analyze NPS scores", completed: true }, { id: "st-3", title: "Write report", completed: false }] },
  { id: "T-HUB-005", verticalId: "eventhub", title: "Event Website — Update for March Events", description: "Update event hub website/landing pages for March events — new event listings, speaker profiles, and registration widgets.", status: "done", priority: "medium", assigneeName: "Nikhil Rao", dueDate: "2026-02-28", tags: ["website", "updates"], createdDate: "2026-02-15", subtasks: [{ id: "st-1", title: "Update event listings", completed: true }, { id: "st-2", title: "Add speaker profiles", completed: true }, { id: "st-3", title: "Test registration flow", completed: true }] },
  { id: "T-HUB-006", verticalId: "eventhub", title: "Vendor Rate Negotiations — Q2", description: "Renegotiate rates with key vendors for Q2 events — target 10% reduction in AV and catering costs vs Q1.", status: "backlog", priority: "medium", assigneeName: "Priyanka Das", dueDate: "2026-03-20", tags: ["vendors", "negotiation", "Q2"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Compile Q1 vendor spend", completed: false }, { id: "st-2", title: "Prepare negotiation brief", completed: false }] },
  { id: "T-HUB-007", verticalId: "eventhub", title: "Sponsorship Deck — Annual Networking Summit", description: "Design sponsorship proposal deck for Annual Networking Summit — packages from ₹1L to ₹10L with branding and speaking opportunities.", status: "todo", priority: "high", assigneeName: "Sonal Mehta", dueDate: "2026-03-10", tags: ["sponsorship", "deck"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "Define sponsorship tiers", completed: false }, { id: "st-2", title: "Design deck", completed: false }] },
  { id: "T-HUB-008", verticalId: "eventhub", title: "Volunteer Training Guide", description: "Create training guide for event volunteers — covers registration process, venue navigation, AV support, and emergency protocols.", status: "backlog", priority: "low", assigneeName: "Nikhil Rao", dueDate: "2026-03-25", tags: ["volunteers", "training"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Outline guide sections", completed: false }] },
  { id: "T-HUB-009", verticalId: "eventhub", title: "App for Event Check-in — Evaluation", description: "Evaluate 3 mobile check-in apps for events — QR scanning, badge printing integration, and real-time attendance dashboard.", status: "backlog", priority: "low", assigneeName: "Priyanka Das", dueDate: "2026-04-05", tags: ["tech", "checkin", "app"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Research check-in apps", completed: false }] },

  { id: "T-ADMIN-001", verticalId: "admin", title: "Portal v2 — UAT Completion", description: "Complete user acceptance testing for Portal v2 — all 7 verticals, cross-browser testing, mobile responsiveness, and performance benchmarks.", status: "in-progress", priority: "critical", assigneeName: "Arjun Mehta", dueDate: "2026-03-05", tags: ["UAT", "portal", "testing"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Test all 7 verticals", completed: false }, { id: "st-2", title: "Cross-browser testing", completed: false }, { id: "st-3", title: "Performance benchmarks", completed: false }] },
  { id: "T-ADMIN-002", verticalId: "admin", title: "Brand Guidelines v3 Rollout", description: "Coordinate rollout of Brand Guidelines v3 across all teams — share Figma link, hold Q&A session, and update all existing templates.", status: "in-progress", priority: "high", assigneeName: "Priya Sharma", dueDate: "2026-03-08", tags: ["brand", "guidelines"], createdDate: "2026-02-22", subtasks: [{ id: "st-1", title: "Finalize brand guidelines v3", completed: true }, { id: "st-2", title: "Share with all teams", completed: false }, { id: "st-3", title: "Update existing templates", completed: false }] },
  { id: "T-ADMIN-003", verticalId: "admin", title: "Q2 Product Roadmap", description: "Define and lock Q2 product roadmap — stakeholder workshops, priority scoring, and executive presentation by March 10.", status: "todo", priority: "high", assigneeName: "Siddharth Rao", dueDate: "2026-03-10", tags: ["roadmap", "Q2", "product"], createdDate: "2026-02-24", subtasks: [{ id: "st-1", title: "Stakeholder workshops", completed: false }, { id: "st-2", title: "Priority scoring", completed: false }, { id: "st-3", title: "Executive presentation", completed: false }] },
  { id: "T-ADMIN-004", verticalId: "admin", title: "Security Audit — Access Controls", description: "Audit all system access controls — review user permissions, deactivate old accounts, and document access matrix.", status: "review", priority: "critical", assigneeName: "Rohan Joshi", dueDate: "2026-03-03", tags: ["security", "audit"], createdDate: "2026-02-15", subtasks: [{ id: "st-1", title: "Audit user accounts", completed: true }, { id: "st-2", title: "Review permission levels", completed: true }, { id: "st-3", title: "Document access matrix", completed: false }] },
  { id: "T-ADMIN-005", verticalId: "admin", title: "Annual Company Offsite Planning", description: "Plan Q2 company offsite — venue selection, team activities, agenda design, and logistics for 25 people.", status: "backlog", priority: "medium", assigneeName: "Priya Sharma", dueDate: "2026-04-10", tags: ["offsite", "team"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Shortlist venues", completed: false }] },
  { id: "T-ADMIN-006", verticalId: "admin", title: "Vendor Contract Renewals", description: "Review and renew 6 expiring vendor contracts — legal review, renegotiate terms, and get approvals.", status: "todo", priority: "medium", assigneeName: "Siddharth Rao", dueDate: "2026-03-20", tags: ["vendors", "contracts"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "List expiring contracts", completed: false }, { id: "st-2", title: "Legal review", completed: false }] },
  { id: "T-ADMIN-007", verticalId: "admin", title: "Dashboard Redesign — Dev Handoff", description: "Complete design handoff for the dashboard redesign — Figma specs, component notes, and asset exports for dev team.", status: "done", priority: "high", assigneeName: "Priya Sharma", dueDate: "2026-02-27", tags: ["design", "handoff"], createdDate: "2026-02-18", subtasks: [{ id: "st-1", title: "Export Figma specs", completed: true }, { id: "st-2", title: "Write component notes", completed: true }, { id: "st-3", title: "Dev team review", completed: true }] },
  { id: "T-ADMIN-008", verticalId: "admin", title: "Monitoring & Alerting Setup", description: "Set up production monitoring with uptime alerts, error rate thresholds, and weekly performance dashboards.", status: "in-progress", priority: "high", assigneeName: "Rohan Joshi", dueDate: "2026-03-07", tags: ["monitoring", "DevOps"], createdDate: "2026-02-21", subtasks: [{ id: "st-1", title: "Set up uptime monitoring", completed: true }, { id: "st-2", title: "Configure error alerts", completed: false }, { id: "st-3", title: "Build performance dashboard", completed: false }] },
  { id: "T-ADMIN-009", verticalId: "admin", title: "Data Backup Policy", description: "Define and implement data backup policy — daily automated backups, 30-day retention, and quarterly restore tests.", status: "backlog", priority: "medium", assigneeName: "Rohan Joshi", dueDate: "2026-03-25", tags: ["data", "backup", "policy"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Define backup schedule", completed: false }] },

  { id: "T-DEV-001", verticalId: "dev", title: "Universal Sections — Chat, Team, Resources, Tasks", description: "Build 4 universal pages (Chat, Team, Resources, Tasks) that work across all 7 verticals using shared mock data and URL-based vertical detection.", status: "in-progress", priority: "critical", assigneeName: "Arjun Mehta", dueDate: "2026-03-01", tags: ["universal", "feature", "frontend"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Mock data file", completed: true }, { id: "st-2", title: "Chat page", completed: false }, { id: "st-3", title: "Team page", completed: false }, { id: "st-4", title: "Resources page", completed: false }, { id: "st-5", title: "Tasks page", completed: false }] },
  { id: "T-DEV-002", verticalId: "dev", title: "Fix Column Sorting Bug — DataTable", description: "Investigate and fix the column sorting bug in the shared DataTable component where sorted state persists across page navigations.", status: "in-progress", priority: "high", assigneeName: "Rahul Kumar", dueDate: "2026-03-02", tags: ["bug", "DataTable", "sorting"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "Reproduce the bug", completed: true }, { id: "st-2", title: "Identify root cause", completed: false }, { id: "st-3", title: "Fix and test", completed: false }] },
  { id: "T-DEV-003", verticalId: "dev", title: "Mobile Responsive Audit", description: "Audit all 7 verticals for mobile responsiveness — document breakpoints that are broken and prioritize fixes for Q2.", status: "todo", priority: "medium", assigneeName: "Rahul Kumar", dueDate: "2026-03-10", tags: ["mobile", "responsive", "audit"], createdDate: "2026-02-24", subtasks: [{ id: "st-1", title: "Test all verticals on mobile", completed: false }, { id: "st-2", title: "Document broken breakpoints", completed: false }] },
  { id: "T-DEV-004", verticalId: "dev", title: "Production Deploy — v2.4.1", description: "Deploy v2.4.1 to production — includes EazyToSell commission calculator, Event Hub vendor module, and DataTable performance fixes.", status: "done", priority: "high", assigneeName: "Rohan Joshi", dueDate: "2026-02-27", tags: ["deployment", "production"], createdDate: "2026-02-25", subtasks: [{ id: "st-1", title: "Deploy to staging", completed: true }, { id: "st-2", title: "Run smoke tests", completed: true }, { id: "st-3", title: "Production deploy", completed: true }] },
  { id: "T-DEV-005", verticalId: "dev", title: "Dark Mode Audit & Fixes", description: "Identify and fix all dark mode inconsistencies across the portal — missing dark variants, hardcoded colors, and contrast issues.", status: "backlog", priority: "medium", assigneeName: "Rahul Kumar", dueDate: "2026-03-20", tags: ["dark-mode", "UI"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Audit all pages", completed: false }] },
  { id: "T-DEV-006", verticalId: "dev", title: "Performance Optimization — Dashboard Pages", description: "Optimize dashboard pages load time — lazy load components, memoize computed values, and reduce unnecessary re-renders.", status: "review", priority: "medium", assigneeName: "Arjun Mehta", dueDate: "2026-03-05", tags: ["performance", "optimization"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Profile current performance", completed: true }, { id: "st-2", title: "Implement lazy loading", completed: true }, { id: "st-3", title: "Measure improvement", completed: false }] },
  { id: "T-DEV-007", verticalId: "dev", title: "TypeScript Strict Mode Migration", description: "Enable TypeScript strict mode across the project and fix all resulting type errors. Improves code safety and IDE experience.", status: "backlog", priority: "low", assigneeName: "Arjun Mehta", dueDate: "2026-04-01", tags: ["TypeScript", "refactor"], createdDate: "2026-02-25", subtasks: [{ id: "st-1", title: "Enable strict mode", completed: false }, { id: "st-2", title: "Fix type errors", completed: false }] },
  { id: "T-DEV-008", verticalId: "dev", title: "Automated Testing Setup", description: "Set up Vitest + React Testing Library — write unit tests for shared components (DataTable, StatsCard, StatusBadge) and integration tests for key flows.", status: "todo", priority: "medium", assigneeName: "Rahul Kumar", dueDate: "2026-03-25", tags: ["testing", "Vitest"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "Set up Vitest", completed: false }, { id: "st-2", title: "Write DataTable tests", completed: false }] },

  { id: "T-ETS-001", verticalId: "ets", title: "Ramesh Kumar — Full Onboarding", description: "Complete onboarding for new franchise partner Ramesh Kumar — store setup, product training, first order processing, and portal walkthrough.", status: "in-progress", priority: "critical", assigneeName: "Naveen Pillai", dueDate: "2026-03-05", tags: ["onboarding", "franchise"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Send welcome kit", completed: true }, { id: "st-2", title: "Store setup call", completed: false }, { id: "st-3", title: "Product training session", completed: false }, { id: "st-4", title: "First order guidance", completed: false }] },
  { id: "T-ETS-002", verticalId: "ets", title: "March Franchise Camp", description: "Organize 2-day franchise partner camp in Nagpur — agenda design, venue booking, training sessions, and resource kits for 8 attendees.", status: "in-progress", priority: "high", assigneeName: "Sonia Agarwal", dueDate: "2026-03-20", tags: ["franchise camp", "training"], createdDate: "2026-02-22", subtasks: [{ id: "st-1", title: "Confirm 8 attendees", completed: true }, { id: "st-2", title: "Book venue and hotel", completed: false }, { id: "st-3", title: "Design agenda", completed: false }] },
  { id: "T-ETS-003", verticalId: "ets", title: "Q1 Shipment — 500 Units", description: "Track and receive March shipment of 500 units from Yiwu — coordinate customs clearance, quality check, and distribution to franchise partners.", status: "in-progress", priority: "critical", assigneeName: "Tarun Shah", dueDate: "2026-03-07", tags: ["shipment", "logistics"], createdDate: "2026-02-25", subtasks: [{ id: "st-1", title: "Track shipment from Yiwu", completed: true }, { id: "st-2", title: "Customs documentation ready", completed: false }, { id: "st-3", title: "Quality check on arrival", completed: false }] },
  { id: "T-ETS-004", verticalId: "ets", title: "Commission Calculator v2", description: "Update commission calculator with new product categories and tiered commission structure for Q2. Add export to PDF feature.", status: "done", priority: "medium", assigneeName: "Sonia Agarwal", dueDate: "2026-02-25", tags: ["calculator", "commission"], createdDate: "2026-02-10", subtasks: [{ id: "st-1", title: "Add new categories", completed: true }, { id: "st-2", title: "Update tier structure", completed: true }, { id: "st-3", title: "PDF export", completed: true }] },
  { id: "T-ETS-005", verticalId: "ets", title: "Partner Support Helpdesk Setup", description: "Set up dedicated helpdesk for franchise partners — ticketing system, FAQ base, and escalation SLA of 4 business hours.", status: "todo", priority: "medium", assigneeName: "Meera Iyer", dueDate: "2026-03-15", tags: ["helpdesk", "support"], createdDate: "2026-02-26", subtasks: [{ id: "st-1", title: "Set up ticketing system", completed: false }, { id: "st-2", title: "Build FAQ base", completed: false }] },
  { id: "T-ETS-006", verticalId: "ets", title: "3 New Franchise Prospects — Proposal", description: "Prepare and send customized proposals to 3 qualified franchise prospects — include territory analysis, ROI projections, and pricing options.", status: "review", priority: "high", assigneeName: "Sonia Agarwal", dueDate: "2026-03-04", tags: ["prospects", "proposals"], createdDate: "2026-02-20", subtasks: [{ id: "st-1", title: "Territory analysis for 3", completed: true }, { id: "st-2", title: "Draft proposals", completed: true }, { id: "st-3", title: "Review with Naveen", completed: false }] },
  { id: "T-ETS-007", verticalId: "ets", title: "Q2 Product Sourcing — Yiwu", description: "Plan Q2 product sourcing trip to Yiwu — identify 20 new SKUs, negotiate prices, and finalize supplier contracts.", status: "backlog", priority: "medium", assigneeName: "Tarun Shah", dueDate: "2026-04-15", tags: ["sourcing", "Yiwu", "Q2"], createdDate: "2026-02-27", subtasks: [{ id: "st-1", title: "Plan trip dates", completed: false }, { id: "st-2", title: "Shortlist target suppliers", completed: false }] },
  { id: "T-ETS-008", verticalId: "ets", title: "Partner Performance Reviews — Q4", description: "Review Q4 performance for all 14 existing franchise partners — sales metrics, compliance scores, and renewal eligibility.", status: "todo", priority: "high", assigneeName: "Naveen Pillai", dueDate: "2026-03-12", tags: ["performance", "Q4", "franchise"], createdDate: "2026-02-24", subtasks: [{ id: "st-1", title: "Pull Q4 sales data", completed: false }, { id: "st-2", title: "Score each partner", completed: false }] },
  { id: "T-ETS-009", verticalId: "ets", title: "EazyToSell App — Concept Design", description: "Initiate concept design for a mobile app for franchise partners — order tracking, inventory check, and commission dashboard.", status: "backlog", priority: "low", assigneeName: "Meera Iyer", dueDate: "2026-04-20", tags: ["app", "mobile", "concept"], createdDate: "2026-02-28", subtasks: [{ id: "st-1", title: "Define core features", completed: false }] },
];
