import type { ContactCategory, ContactPriority, ImportantContact } from "@/types/contacts";
export type { ContactCategory, ContactPriority, ImportantContact };

export const importantContacts: ImportantContact[] = [
  {
    id: "CON-001",
    name: "Jason Huang",
    title: "Director",
    organization: "Guangzhou Connect Tours",
    category: "partner",
    verticalIds: ["goyotours"],
    phone: "+86 136 0020 8888",
    whatsapp: "8613600208888",
    email: "jason@gzconnecttours.com",
    website: "www.gzconnecttours.com",
    city: "Guangzhou",
    country: "China",
    priority: "high",
    notes: "Primary China ground partner. Handles all China-side logistics — transfers, guides, Canton Fair registration, hotel check-ins. Available on WeChat/WhatsApp 24/7.",
    tags: ["China", "Ground Partner", "Canton Fair", "Key Contact"],
    added_by: "Priya Kapoor",
    created_at: "2022-03-01",
    is_shared: false,
  },
  {
    id: "CON-002",
    name: "Jenny Li",
    title: "Senior Bilingual Guide",
    organization: "Silk Route Guides",
    category: "guide",
    verticalIds: ["goyotours"],
    phone: "+86 135 0021 9999",
    whatsapp: "8613500219999",
    email: "jenny@silkrouteguides.cn",
    website: "www.silkrouteguides.cn",
    city: "Guangzhou",
    country: "China",
    priority: "high",
    notes: "Hindi + Mandarin bilingual guide. Specialist in Canton Fair navigation. Indian clients love her. 8+ years experience. Also covers Shanghai and Yiwu.",
    tags: ["Guide", "Hindi Speaking", "Canton Fair", "Shanghai", "Yiwu"],
    added_by: "Priya Kapoor",
    created_at: "2022-05-10",
    is_shared: false,
  },
  {
    id: "CON-003",
    name: "Anita Sharma",
    title: "Senior Visa Consultant",
    organization: "Global Visa Services India",
    category: "visa_agent",
    verticalIds: ["goyotours"],
    phone: "+91 98200 12345",
    whatsapp: "919820012345",
    email: "anita@globalvisaindia.com",
    website: "www.globalvisaindia.com",
    city: "Mumbai",
    country: "India",
    priority: "high",
    notes: "China visa specialist for groups. 7-10 working day processing. Very reliable. Offers document checklists for clients. Business visa + tourist visa both.",
    tags: ["Visa", "China", "Mumbai", "Group Applications"],
    added_by: "Amit Verma",
    created_at: "2022-06-01",
    is_shared: false,
  },
  {
    id: "CON-004",
    name: "Mr. Visa Section Officer",
    title: "Visa Section Head",
    organization: "Chinese Embassy New Delhi",
    category: "embassy",
    verticalIds: ["goyotours"],
    phone: "+91 11 2611 2345",
    whatsapp: "",
    email: "chinaembassy.visa@delhi.gov.cn",
    website: "www.china-embassy.org.cn/ind",
    city: "New Delhi",
    country: "India",
    priority: "medium",
    notes: "Embassy visa section. Appointment-based. Use for escalated visa issues. Walk-in not allowed — prior appointment required via website.",
    tags: ["Embassy", "China", "Visa", "Delhi"],
    added_by: "Priya Kapoor",
    created_at: "2022-04-15",
    is_shared: false,
  },
  {
    id: "CON-005",
    name: "Consul General Office",
    title: "Consular Services",
    organization: "Chinese Consulate Mumbai",
    category: "embassy",
    verticalIds: ["goyotours"],
    phone: "+91 22 2264 1328",
    whatsapp: "",
    email: "consul_mumbai@china.gov.cn",
    website: "http://mumbai.china-consulate.org",
    city: "Mumbai",
    country: "India",
    priority: "medium",
    notes: "Mumbai consulate for Maharashtra, Goa, Gujarat applicants. Handles group visa applications. Contact for any visa rejection appeals.",
    tags: ["Consulate", "China", "Visa", "Mumbai"],
    added_by: "Amit Verma",
    created_at: "2023-01-10",
    is_shared: false,
  },
  {
    id: "CON-006",
    name: "Liu Wei",
    title: "Sales Manager",
    organization: "Marriott Hotel Guangzhou",
    category: "hotel",
    verticalIds: ["goyotours"],
    phone: "+86 20 8666 6888",
    whatsapp: "8602086666888",
    email: "sales.guangzhou@marriott.com",
    website: "www.marriott.com",
    city: "Guangzhou",
    country: "China",
    priority: "medium",
    notes: "5-star Marriott contact for HK Canton exclusive package. Provides group rates and early check-in for our guests. Good relationship since 2022.",
    tags: ["Hotel", "5-star", "Guangzhou", "Group Rates"],
    added_by: "Priya Kapoor",
    created_at: "2022-08-20",
    is_shared: false,
  },
  {
    id: "CON-007",
    name: "Rakesh Nair",
    title: "Group Sales Manager",
    organization: "Air India",
    category: "logistics",
    verticalIds: ["goyotours"],
    phone: "+91 11 2462 2220",
    whatsapp: "911124622220",
    email: "groupsales@airindia.in",
    website: "www.airindia.in",
    city: "Delhi",
    country: "India",
    priority: "medium",
    notes: "Air India group bookings for China routes. Mumbai-Guangzhou, Delhi-Hong Kong. Contact for group rates (10+ pax) and seat blocks.",
    tags: ["Flights", "Air India", "Group Booking", "Mumbai", "Delhi"],
    added_by: "Amit Verma",
    created_at: "2023-02-05",
    is_shared: false,
  },
  {
    id: "CON-008",
    name: "Canton Fair Registration Office",
    title: "International Exhibitor Services",
    organization: "Canton Fair (China Import and Export Fair)",
    category: "government",
    verticalIds: ["goyotours"],
    phone: "+86 20 2606 2828",
    whatsapp: "",
    email: "service@cantonfair.org.cn",
    website: "www.cantonfair.org.cn",
    city: "Guangzhou",
    country: "China",
    priority: "high",
    notes: "Official Canton Fair registration office. Group badge applications should be sent 45 days in advance. All 3 phases need separate registration.",
    tags: ["Canton Fair", "Registration", "Official", "Group Badges"],
    added_by: "Priya Kapoor",
    created_at: "2022-03-15",
    is_shared: false,
  },
  {
    id: "CON-009",
    name: "Cathy Chan",
    title: "Operations Manager",
    organization: "HK Star Hospitality Services",
    category: "partner",
    verticalIds: ["goyotours"],
    phone: "+852 9123 4567",
    whatsapp: "85291234567",
    email: "cathy@hkstarhospitality.com",
    website: "",
    city: "Hong Kong",
    country: "China",
    priority: "medium",
    notes: "HK ground operations partner. Handles HK airport transfers, Victoria Harbour cruise, city tour guide, shopping escort. Excellent with Indian clients.",
    tags: ["Hong Kong", "Ground Partner", "Transfers", "City Tour"],
    added_by: "Priya Kapoor",
    created_at: "2022-09-01",
    is_shared: false,
  },
  {
    id: "CON-010",
    name: "Sunil Mehta",
    title: "Group Business Head",
    organization: "Royal Star Travel Insurance",
    category: "finance",
    verticalIds: ["goyotours"],
    phone: "+91 98330 56789",
    whatsapp: "919833056789",
    email: "sunil@royalstarinsurance.com",
    website: "www.royalstarinsurance.com",
    city: "Mumbai",
    country: "India",
    priority: "low",
    notes: "Group travel insurance specialist. China specific policies. Medical + trip cancellation + baggage. Best rates for 10+ pax. 24/7 claim helpline.",
    tags: ["Insurance", "Travel", "Group Policy", "Medical Cover"],
    added_by: "Amit Verma",
    created_at: "2023-03-10",
    is_shared: false,
  },
  {
    id: "CON-011",
    name: "Sarah Mitchell",
    title: "State Formation Specialist",
    organization: "Delaware Division of Corporations",
    category: "government",
    verticalIds: ["legalnations"],
    phone: "+1 302 739 3073",
    whatsapp: "",
    email: "dosd@delaware.gov",
    website: "corp.delaware.gov",
    city: "Dover",
    country: "USA",
    priority: "high",
    notes: "Primary Delaware state contact for LLC and Corporation filings. Used for urgent formation tracking and expedite requests.",
    tags: ["Delaware", "LLC", "Corporation", "Filing", "State"],
    added_by: "Sneha Patel",
    created_at: "2021-06-01",
    is_shared: false,
  },
  {
    id: "CON-012",
    name: "Wyoming Secretary of State",
    title: "Business Filings Division",
    organization: "Wyoming Secretary of State",
    category: "government",
    verticalIds: ["legalnations"],
    phone: "+1 307 777 7311",
    whatsapp: "",
    email: "filing@wyo.gov",
    website: "wyobiz.wyo.gov",
    city: "Cheyenne",
    country: "USA",
    priority: "medium",
    notes: "Wyoming LLC filings. Anonymous LLC option. No state income tax. Popular for privacy-focused clients.",
    tags: ["Wyoming", "LLC", "Anonymous", "State Filing"],
    added_by: "Arjun Mehta",
    created_at: "2021-08-15",
    is_shared: false,
  },
  {
    id: "CON-013",
    name: "Kevin Bradley",
    title: "Account Manager",
    organization: "Northwest Registered Agent",
    category: "legal",
    verticalIds: ["legalnations"],
    phone: "+1 509 768 2249",
    whatsapp: "",
    email: "kevin@northwestregisteredagent.com",
    website: "www.northwestregisteredagent.com",
    city: "Spokane, WA",
    country: "USA",
    priority: "high",
    notes: "Registered agent service for all US states. White-label option available. Best for clients wanting annual compliance support. Our volume discount account.",
    tags: ["Registered Agent", "All States", "Compliance", "White Label"],
    added_by: "Sneha Patel",
    created_at: "2021-05-01",
    is_shared: false,
  },
  {
    id: "CON-014",
    name: "Priya Kapoor (Immigration Liaison)",
    title: "Immigration Affairs Manager",
    organization: "USCIS Customer Service",
    category: "government",
    verticalIds: ["legalnations"],
    phone: "+1 800 375 5283",
    whatsapp: "",
    email: "uscis.contact@dhs.gov",
    website: "www.uscis.gov",
    city: "Washington, DC",
    country: "USA",
    priority: "medium",
    notes: "USCIS contact line for I-129, EIN, and business immigration matters. Use Emma chatbot first. For complex cases escalate to field office.",
    tags: ["USCIS", "Immigration", "EIN", "Federal"],
    added_by: "Arjun Mehta",
    created_at: "2022-01-20",
    is_shared: false,
  },
  {
    id: "CON-015",
    name: "Robert Channing",
    title: "Partner — Business Law",
    organization: "Channing & Associates LLP",
    category: "legal",
    verticalIds: ["legalnations"],
    phone: "+1 302 555 0192",
    whatsapp: "",
    email: "rchanning@channinglaw.com",
    website: "www.channinglaw.com",
    city: "Wilmington, DE",
    country: "USA",
    priority: "high",
    notes: "Legal counsel for complex multi-member LLC formations, operating agreements, and dispute resolution. On retainer for LegalNations clients who need attorney involvement.",
    tags: ["Attorney", "Delaware", "LLC", "Operating Agreement", "Legal Counsel"],
    added_by: "Sneha Patel",
    created_at: "2021-09-01",
    is_shared: false,
  },
  {
    id: "CON-016",
    name: "Alibaba Trade Manager Team",
    title: "B2B Trade Support",
    organization: "Alibaba International",
    category: "supplier",
    verticalIds: ["usdrop"],
    phone: "+86 571 8502 2088",
    whatsapp: "",
    email: "trade@alibaba-inc.com",
    website: "www.alibaba.com",
    city: "Hangzhou",
    country: "China",
    priority: "high",
    notes: "Primary supplier platform support. Use for Trade Assurance disputes, Gold Supplier verification, and product sourcing assistance.",
    tags: ["Alibaba", "Supplier", "Trade Assurance", "B2B"],
    added_by: "Vikram Singh",
    created_at: "2022-02-10",
    is_shared: false,
  },
  {
    id: "CON-017",
    name: "AliExpress Global Support",
    title: "Seller & Buyer Relations",
    organization: "AliExpress",
    category: "supplier",
    verticalIds: ["usdrop"],
    phone: "+86 571 8837 6688",
    whatsapp: "",
    email: "support@aliexpress.com",
    website: "www.aliexpress.com",
    city: "Hangzhou",
    country: "China",
    priority: "medium",
    notes: "AliExpress platform support for sourcing and disputes. Use for tracking issues and supplier escalations on USDrop AI platform orders.",
    tags: ["AliExpress", "Dropshipping", "Supplier", "Platform"],
    added_by: "Vikram Singh",
    created_at: "2022-03-15",
    is_shared: false,
  },
  {
    id: "CON-018",
    name: "Amit Bhatia",
    title: "Senior Account Manager",
    organization: "Customs Connect India",
    category: "logistics",
    verticalIds: ["usdrop"],
    phone: "+91 98700 87654",
    whatsapp: "919870087654",
    email: "amit@customsconnect.in",
    website: "www.customsconnect.in",
    city: "Delhi",
    country: "India",
    priority: "medium",
    notes: "Customs clearance and import duty calculation specialist for D2C product imports from China. Handles HSN classification, BIS certification queries.",
    tags: ["Customs", "Import", "D2C", "Delhi", "BIS"],
    added_by: "Vikram Singh",
    created_at: "2022-05-20",
    is_shared: false,
  },
  {
    id: "CON-019",
    name: "Shopify Partner Support",
    title: "Partner Program",
    organization: "Shopify Inc.",
    category: "partner",
    verticalIds: ["usdrop"],
    phone: "+1 888 746 7439",
    whatsapp: "",
    email: "partners@shopify.com",
    website: "partners.shopify.com",
    city: "Ottawa",
    country: "Canada",
    priority: "medium",
    notes: "Shopify Partner portal support. Use for app development, theme queries, and store migration support. USDrop AI is an official Shopify Partner.",
    tags: ["Shopify", "Partner", "E-commerce", "App"],
    added_by: "Vikram Singh",
    created_at: "2021-11-01",
    is_shared: false,
  },
  {
    id: "CON-020",
    name: "Faire Customer Support",
    title: "Brand Partner Support",
    organization: "Faire Marketplace",
    category: "partner",
    verticalIds: ["faire"],
    phone: "+1 888 671 7770",
    whatsapp: "",
    email: "brands@faire.com",
    website: "www.faire.com/brand",
    city: "San Francisco",
    country: "USA",
    priority: "high",
    notes: "Faire brand partner support for all 6 storefronts. Use for order disputes, account access issues, terms of service questions, and payment reconciliation.",
    tags: ["Faire", "Platform Support", "Brand Account", "Orders", "Disputes"],
    added_by: "Sneha Patel",
    created_at: "2023-04-01",
    is_shared: false,
  },
  {
    id: "CON-021",
    name: "Jake Thornton",
    title: "Regional Customs Broker",
    organization: "US Customs Brokerage Group",
    category: "logistics",
    verticalIds: ["faire"],
    phone: "+1 213 555 0187",
    whatsapp: "",
    email: "jake@uscbg.com",
    website: "www.uscbg.com",
    city: "Los Angeles",
    country: "USA",
    priority: "medium",
    notes: "US customs broker for wholesale import shipments. Handles FDA registration, duty classification (HTS codes) for our Indian goods entering US via Faire.",
    tags: ["Customs", "Import USA", "HTS Code", "FDA", "Wholesale"],
    added_by: "Priya Sharma",
    created_at: "2023-05-15",
    is_shared: false,
  },
  {
    id: "CON-022",
    name: "FedEx Business Solutions",
    title: "Corporate Account Team",
    organization: "FedEx International",
    category: "logistics",
    verticalIds: ["faire"],
    phone: "+1 800 463 3339",
    whatsapp: "",
    email: "corporate@fedex.com",
    website: "www.fedex.com",
    city: "Memphis, TN",
    country: "USA",
    priority: "medium",
    notes: "Corporate FedEx account for all 6 Faire brand shipments to US retailers. Volume discount applied. Contact for international shipping from India to US.",
    tags: ["FedEx", "Shipping", "International", "Corporate Account"],
    added_by: "Priya Sharma",
    created_at: "2023-06-01",
    is_shared: false,
  },
  {
    id: "CON-023",
    name: "Ramesh Kumar",
    title: "Payroll Processing Manager",
    organization: "Greytip Software (greytHR)",
    category: "finance",
    verticalIds: ["hrms"],
    phone: "+91 80 6801 6801",
    whatsapp: "918006801681",
    email: "support@greytip.com",
    website: "www.greythr.com",
    city: "Bengaluru",
    country: "India",
    priority: "high",
    notes: "greytHR payroll software support. Contact for compliance updates (PF/ESI rate changes), payslip configuration, and bulk salary processing issues.",
    tags: ["Payroll", "greytHR", "Software", "PF", "ESI"],
    added_by: "Ananya Iyer",
    created_at: "2022-09-01",
    is_shared: false,
  },
  {
    id: "CON-024",
    name: "EPFO Helpdesk",
    title: "Employee Provident Fund Office",
    organization: "EPFO — Mumbai Regional Office",
    category: "government",
    verticalIds: ["hrms"],
    phone: "+91 22 2203 4567",
    whatsapp: "",
    email: "epfo.mumbai@epfindia.gov.in",
    website: "www.epfindia.gov.in",
    city: "Mumbai",
    country: "India",
    priority: "high",
    notes: "EPFO regional office for PF deposit, ECR filing, and UAN activation queries. Use for PF transfer cases and inspection notices.",
    tags: ["PF", "EPFO", "Government", "Compliance", "UAN"],
    added_by: "Ananya Iyer",
    created_at: "2022-07-15",
    is_shared: false,
  },
  {
    id: "CON-025",
    name: "Deepak Menon",
    title: "Corporate Salary Account Manager",
    organization: "HDFC Bank — Corporate Banking",
    category: "finance",
    verticalIds: ["hrms"],
    phone: "+91 98760 34567",
    whatsapp: "919876034567",
    email: "deepak.menon@hdfcbank.com",
    website: "www.hdfcbank.com",
    city: "Mumbai",
    country: "India",
    priority: "medium",
    notes: "HDFC corporate salary account RM. Use for bulk salary transfer issues, account opening for new employees, and corporate FD queries.",
    tags: ["HDFC", "Bank", "Salary", "Corporate", "Bulk Transfer"],
    added_by: "Ananya Iyer",
    created_at: "2022-08-01",
    is_shared: false,
  },
  {
    id: "CON-026",
    name: "Naukri Account Manager",
    title: "Enterprise Sales Manager",
    organization: "Naukri.com (Info Edge India)",
    category: "media",
    verticalIds: ["ats"],
    phone: "+91 0120 3912000",
    whatsapp: "",
    email: "enterprise@naukri.com",
    website: "www.naukri.com",
    city: "Noida",
    country: "India",
    priority: "high",
    notes: "Naukri enterprise account for job postings. Manages our annual subscription, resdex credits, and candidate database access. Renews in September.",
    tags: ["Naukri", "Job Portal", "Recruitment", "Resdex", "ATS"],
    added_by: "Karthik Menon",
    created_at: "2022-09-15",
    is_shared: false,
  },
  {
    id: "CON-027",
    name: "LinkedIn Talent Solutions",
    title: "Recruiter Account Support",
    organization: "LinkedIn India",
    category: "media",
    verticalIds: ["ats"],
    phone: "+91 22 6230 1200",
    whatsapp: "",
    email: "talent@linkedin.com",
    website: "business.linkedin.com/talent-solutions",
    city: "Mumbai",
    country: "India",
    priority: "medium",
    notes: "LinkedIn Recruiter license management and InMail support. Use for job slot issues, sponsored job queries, and candidate outreach credit top-ups.",
    tags: ["LinkedIn", "Recruiter", "InMail", "Job Posting"],
    added_by: "Karthik Menon",
    created_at: "2023-01-10",
    is_shared: false,
  },
  {
    id: "CON-028",
    name: "Mr. Suprans (Founder)",
    title: "Founder & Managing Director",
    organization: "Suprans Group",
    category: "partner",
    verticalIds: ["all"],
    phone: "+91 99999 00001",
    whatsapp: "919999900001",
    email: "suprans@suprans.in",
    website: "www.suprans.in",
    city: "Mumbai",
    country: "India",
    priority: "high",
    notes: "Founder of the Suprans Group. Decision maker for all verticals. Contact directly for strategic decisions, major partnerships, and founder approvals.",
    tags: ["Founder", "Suprans Group", "Decision Maker", "All Verticals"],
    added_by: "System",
    created_at: "2021-01-01",
    is_shared: true,
  },
  {
    id: "CON-029",
    name: "CA Nilesh Joshi",
    title: "Chartered Accountant",
    organization: "Joshi & Co. Chartered Accountants",
    category: "finance",
    verticalIds: ["all"],
    phone: "+91 98200 77890",
    whatsapp: "919820077890",
    email: "nilesh@joshica.com",
    website: "",
    city: "Mumbai",
    country: "India",
    priority: "high",
    notes: "Group CA for Suprans Group. Handles GST, income tax, TDS, and annual audits for all entities. Also handles TCS on international tour packages.",
    tags: ["CA", "GST", "Tax", "Audit", "TCS", "All Verticals"],
    added_by: "System",
    created_at: "2021-01-15",
    is_shared: true,
  },
  {
    id: "CON-030",
    name: "Adv. Prakash Malhotra",
    title: "Corporate Legal Advisor",
    organization: "Malhotra Law Associates",
    category: "legal",
    verticalIds: ["all"],
    phone: "+91 98110 45678",
    whatsapp: "919811045678",
    email: "prakash@malhotralaw.in",
    website: "",
    city: "Delhi",
    country: "India",
    priority: "high",
    notes: "Group legal advisor. Handles contracts, disputes, trademark filings, and entity structuring across all Suprans Group businesses.",
    tags: ["Legal", "Advocate", "Contracts", "Trademark", "All Verticals"],
    added_by: "System",
    created_at: "2021-02-01",
    is_shared: true,
  },
  {
    id: "CON-031",
    name: "ICICI Bank — Corporate RM",
    title: "Relationship Manager",
    organization: "ICICI Bank — Corporate Banking",
    category: "finance",
    verticalIds: ["all"],
    phone: "+91 98920 12345",
    whatsapp: "919892012345",
    email: "corporate.rm@icicibank.com",
    website: "www.icicibank.com",
    city: "Mumbai",
    country: "India",
    priority: "medium",
    notes: "ICICI Group corporate account RM. Manages current accounts, forex transactions, and group banking needs. Contact for wire transfers and forex rates.",
    tags: ["ICICI", "Bank", "Forex", "Corporate", "All Verticals"],
    added_by: "System",
    created_at: "2021-03-01",
    is_shared: true,
  },
  {
    id: "CON-032",
    name: "Supriya Nambiar",
    title: "IT Systems Admin",
    organization: "Suprans Group IT",
    category: "other",
    verticalIds: ["all"],
    phone: "+91 98333 88777",
    whatsapp: "919833388777",
    email: "supriya.it@suprans.in",
    website: "",
    city: "Mumbai",
    country: "India",
    priority: "medium",
    notes: "Internal IT admin for all systems — email, server, CRM access, VPN, and software licenses. Contact for user creation and access management.",
    tags: ["IT", "Internal", "Admin", "Systems", "All Verticals"],
    added_by: "System",
    created_at: "2021-01-10",
    is_shared: true,
  },
  {
    id: "CON-033",
    name: "Vijay Prabhu",
    title: "Office Manager",
    organization: "Suprans Group Mumbai HQ",
    category: "other",
    verticalIds: ["all"],
    phone: "+91 97600 11234",
    whatsapp: "919760011234",
    email: "vijay.office@suprans.in",
    website: "",
    city: "Mumbai",
    country: "India",
    priority: "low",
    notes: "Office manager — handles couriers, petty cash, office supplies, and facility management for Mumbai HQ. Key for physical mail and document deliveries.",
    tags: ["Office", "Facilities", "Internal", "Mumbai HQ"],
    added_by: "System",
    created_at: "2021-01-10",
    is_shared: true,
  },
  {
    id: "CON-034",
    name: "Richa Gupta",
    title: "Group Bookings Coordinator",
    organization: "IndiGo Airlines",
    category: "logistics",
    verticalIds: ["goyotours"],
    phone: "+91 124 617 3838",
    whatsapp: "911246173838",
    email: "groups@goindigo.in",
    website: "www.goindigo.in",
    city: "Gurugram",
    country: "India",
    priority: "medium",
    notes: "IndiGo group desk for 15+ pax bookings. Best economy rates for Mumbai-Hong Kong route. Must book 60 days in advance for group rates.",
    tags: ["IndiGo", "Flights", "Group Booking", "Hong Kong", "Economy"],
    added_by: "Amit Verma",
    created_at: "2023-04-20",
    is_shared: false,
  },
  {
    id: "CON-035",
    name: "Meta Business Support",
    title: "Business Account Support",
    organization: "Meta (Facebook & Instagram)",
    category: "media",
    verticalIds: ["social"],
    phone: "+1 650 543 4800",
    whatsapp: "",
    email: "business@support.facebook.com",
    website: "www.facebook.com/business",
    city: "Menlo Park, CA",
    country: "USA",
    priority: "high",
    notes: "Meta Business Suite support for all social vertical Facebook and Instagram accounts. Use for ad account issues, page verification, and content appeals.",
    tags: ["Meta", "Facebook", "Instagram", "Ads", "Social Media"],
    added_by: "Sanjana Das",
    created_at: "2023-07-01",
    is_shared: false,
  },
  {
    id: "CON-036",
    name: "YouTube Creator Support",
    title: "Partner Support",
    organization: "YouTube (Google)",
    category: "media",
    verticalIds: ["social"],
    phone: "+1 650 253 0000",
    whatsapp: "",
    email: "creator-support@youtube.com",
    website: "support.google.com/youtube",
    city: "Mountain View, CA",
    country: "USA",
    priority: "medium",
    notes: "YouTube Creator support for channel issues, monetization queries, copyright disputes, and community guidelines appeals.",
    tags: ["YouTube", "Creator", "Video", "Monetization", "Social Media"],
    added_by: "Sanjana Das",
    created_at: "2023-07-15",
    is_shared: false,
  },
  {
    id: "CON-037",
    name: "Ajay Singh",
    title: "Admin & Compliance Head",
    organization: "Suprans Admin Division",
    category: "government",
    verticalIds: ["lbm"],
    phone: "+91 98100 11111",
    whatsapp: "919810011111",
    email: "ajay.admin@suprans.in",
    website: "",
    city: "Mumbai",
    country: "India",
    priority: "high",
    notes: "Internal admin head for Suprans Group. Handles regulatory compliance, inter-entity communication, and government liaison across all entities.",
    tags: ["Admin", "Compliance", "Internal", "Government Liaison"],
    added_by: "System",
    created_at: "2021-01-05",
    is_shared: false,
  },
  {
    id: "CON-038",
    name: "AWS Enterprise Support",
    title: "Enterprise Account Team",
    organization: "Amazon Web Services",
    category: "partner",
    verticalIds: ["dev"],
    phone: "+1 206 266 4064",
    whatsapp: "",
    email: "aws-enterprise@amazon.com",
    website: "aws.amazon.com",
    city: "Seattle, WA",
    country: "USA",
    priority: "high",
    notes: "AWS Enterprise Support plan for Suprans tech infrastructure. Use for critical production incidents, cost optimization reviews, and architecture guidance.",
    tags: ["AWS", "Cloud", "Infrastructure", "Enterprise", "Dev"],
    added_by: "Dev Team",
    created_at: "2022-04-01",
    is_shared: false,
  },
  {
    id: "CON-039",
    name: "EazyToSell Partner Support",
    title: "Platform Support Manager",
    organization: "EazyToSell Platform",
    category: "partner",
    verticalIds: ["ets"],
    phone: "+91 98200 54321",
    whatsapp: "919820054321",
    email: "support@eazytosell.com",
    website: "www.eazytosell.com",
    city: "Mumbai",
    country: "India",
    priority: "high",
    notes: "EazyToSell platform support for integration queries, commission disputes, and seller account management. Business hours only.",
    tags: ["EazyToSell", "Platform", "D2C", "Integration"],
    added_by: "ETS Team",
    created_at: "2022-10-01",
    is_shared: false,
  },
  {
    id: "CON-040",
    name: "Chen Jian",
    title: "Group Sales Manager",
    organization: "Guangzhou International Hotel",
    category: "hotel",
    verticalIds: ["goyotours"],
    phone: "+86 20 8331 1888",
    whatsapp: "862083311888",
    email: "groups@gzintlhotel.com",
    website: "",
    city: "Guangzhou",
    country: "China",
    priority: "medium",
    notes: "Main 4-star hotel contact for all Canton Fair group packages (Phase 1, 2, 3). Provides room block rates and Indian breakfast arrangement. Reliable partner.",
    tags: ["Hotel", "4-star", "Canton Fair", "Group Rates", "Guangzhou"],
    added_by: "Priya Kapoor",
    created_at: "2023-01-15",
    is_shared: false,
  },
];
