import type { FaireStoreStatus, ProductLifecycleState, ProductSaleState, OrderState, OrderItemState, OrderCancelReason, FreeShippingReason, OrderSource, ShipmentType, FaireStore, FaireProductVariant, FaireProductReview, FaireProduct, FaireAddress, FaireOrderItemDiscount, FaireOrderItem, FaireShipment, FairePayoutCosts, FaireBrandDiscount, FaireOrder, FaireRetailer } from "@/types/faire";
export type { FaireStoreStatus, ProductLifecycleState, ProductSaleState, OrderState, OrderItemState, OrderCancelReason, FreeShippingReason, OrderSource, ShipmentType, FaireStore, FaireProductVariant, FaireProductReview, FaireProduct, FaireAddress, FaireOrderItemDiscount, FaireOrderItem, FaireShipment, FairePayoutCosts, FaireBrandDiscount, FaireOrder, FaireRetailer };


// ─── Stores ────────────────────────────────────────────────────────────────────

export const faireStores: FaireStore[] = [
  {
    id: "store-001",
    name: "Suprans Lifestyle",
    brandToken: "b_sup_8f2a1c",
    apiKeyConfigured: true,
    status: "connected",
    category: "Home & Living",
    city: "Austin",
    state: "TX",
    totalProducts: 14,
    totalOrders: 186,
    monthlyRevenue: 38400,
    avgOrderValue: 312,
    activeRetailers: 48,
    rating: 4.8,
    joinedDate: "2023-03-15",
    lastSync: "2026-02-28T08:44:00Z",
    todayOrders: 3,
  },
  {
    id: "store-002",
    name: "LBM Home & Living",
    brandToken: "b_lbm_4d7e2b",
    apiKeyConfigured: true,
    status: "connected",
    category: "Home Decor",
    city: "Portland",
    state: "OR",
    totalProducts: 22,
    totalOrders: 241,
    monthlyRevenue: 44800,
    avgOrderValue: 278,
    activeRetailers: 62,
    rating: 4.6,
    joinedDate: "2022-11-08",
    lastSync: "2026-02-28T08:44:00Z",
    todayOrders: 5,
  },
  {
    id: "store-003",
    name: "Gullee Craft Co.",
    brandToken: "b_gullee_9c3f5a",
    apiKeyConfigured: true,
    status: "connected",
    category: "Artisan Goods",
    city: "Brooklyn",
    state: "NY",
    totalProducts: 18,
    totalOrders: 124,
    monthlyRevenue: 21600,
    avgOrderValue: 194,
    activeRetailers: 34,
    rating: 4.9,
    joinedDate: "2023-07-20",
    lastSync: "2026-02-28T08:44:00Z",
    todayOrders: 2,
  },
  {
    id: "store-004",
    name: "Heritage Artisan",
    brandToken: "b_heritage_6a1d8c",
    apiKeyConfigured: false,
    status: "disconnected",
    category: "Ceramics & Pottery",
    city: "Santa Fe",
    state: "NM",
    totalProducts: 9,
    totalOrders: 68,
    monthlyRevenue: 13200,
    avgOrderValue: 224,
    activeRetailers: 19,
    rating: 4.7,
    joinedDate: "2024-01-12",
    lastSync: "2026-02-14T10:20:00Z",
    todayOrders: 0,
  },
  {
    id: "store-005",
    name: "Pure Essentials",
    brandToken: "b_pure_2e9b4f",
    apiKeyConfigured: true,
    status: "connected",
    category: "Wellness & Beauty",
    city: "Denver",
    state: "CO",
    totalProducts: 16,
    totalOrders: 312,
    monthlyRevenue: 48200,
    avgOrderValue: 186,
    activeRetailers: 74,
    rating: 4.5,
    joinedDate: "2022-06-30",
    lastSync: "2026-02-28T08:44:00Z",
    todayOrders: 7,
  },
  {
    id: "store-006",
    name: "Nature's Basket",
    brandToken: "b_nature_7f4a2d",
    apiKeyConfigured: true,
    status: "error",
    category: "Food & Pantry",
    city: "Seattle",
    state: "WA",
    totalProducts: 11,
    totalOrders: 89,
    monthlyRevenue: 8600,
    avgOrderValue: 142,
    activeRetailers: 28,
    rating: 4.3,
    joinedDate: "2024-05-22",
    lastSync: "2026-02-27T16:30:00Z",
    todayOrders: 1,
  },
];

// ─── Products ──────────────────────────────────────────────────────────────────

export const faireProducts: FaireProduct[] = [
  {
    id: "p_prod001",
    storeId: "store-001",
    name: "Handwoven Cotton Throw",
    description: "Luxurious hand-woven cotton throw blanket with natural dyes. Perfect for boutique and home goods retailers.",
    category: "Textiles",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 4,
    units_per_case: 4,
    made_in_country: "IND",
    taxonomy_type: "HOME_DECOR",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2023-04-10",
    updated_at: "2026-01-15",
    tags: ["handwoven", "natural", "cotton", "sustainable"],
    variants: [
      { id: "po_var001a", productId: "p_prod001", sku: "SUP-THR-IVR", name: "Ivory", wholesale_price_cents: 4200, retail_price_cents: 9800, available_quantity: 84, backordered_until: null, options: [{ name: "Color", value: "Ivory" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var001b", productId: "p_prod001", sku: "SUP-THR-TER", name: "Terracotta", wholesale_price_cents: 4200, retail_price_cents: 9800, available_quantity: 56, backordered_until: null, options: [{ name: "Color", value: "Terracotta" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var001c", productId: "p_prod001", sku: "SUP-THR-SLA", name: "Slate Blue", wholesale_price_cents: 4200, retail_price_cents: 9800, available_quantity: 0, backordered_until: "2026-03-15", options: [{ name: "Color", value: "Slate Blue" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [
      { id: "rev-001a", productId: "p_prod001", retailer_name: "The Cozy Corner Boutique", rating: 5, comment: "Our customers absolutely love these throws. Great quality and fast shipping!", created_at: "2026-01-20" },
      { id: "rev-001b", productId: "p_prod001", retailer_name: "Nest & Nook", rating: 5, comment: "Reordered 3 times already. Always consistent quality.", created_at: "2025-12-05" },
    ],
  },
  {
    id: "p_prod002",
    storeId: "store-001",
    name: "Soy Wax Pillar Candle Set",
    description: "Set of 3 hand-poured soy wax pillar candles with botanical inclusions. 50-hour burn time per candle.",
    category: "Candles & Home Fragrance",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 6,
    units_per_case: 6,
    made_in_country: "USA",
    taxonomy_type: "CANDLES",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2023-05-22",
    updated_at: "2026-02-01",
    tags: ["soy", "candle", "botanical", "gift"],
    variants: [
      { id: "po_var002a", productId: "p_prod002", sku: "SUP-CND-LAV", name: "Lavender & Cedar", wholesale_price_cents: 2800, retail_price_cents: 6800, available_quantity: 120, backordered_until: null, options: [{ name: "Scent", value: "Lavender & Cedar" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var002b", productId: "p_prod002", sku: "SUP-CND-SAN", name: "Sandalwood & Amber", wholesale_price_cents: 2800, retail_price_cents: 6800, available_quantity: 96, backordered_until: null, options: [{ name: "Scent", value: "Sandalwood & Amber" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var002c", productId: "p_prod002", sku: "SUP-CND-CIT", name: "Citrus & Sea Salt", wholesale_price_cents: 2800, retail_price_cents: 6800, available_quantity: 72, backordered_until: null, options: [{ name: "Scent", value: "Citrus & Sea Salt" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [
      { id: "rev-002a", productId: "p_prod002", retailer_name: "Bloom & Gather", rating: 5, comment: "Best-selling candles in our store!", created_at: "2026-02-10" },
    ],
  },
  {
    id: "p_prod003",
    storeId: "store-002",
    name: "Rattan Fruit Bowl",
    description: "Handcrafted rattan fruit bowl with natural finish. Sustainably sourced materials from certified suppliers.",
    category: "Kitchen & Dining",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 6,
    units_per_case: 6,
    made_in_country: "IDN",
    taxonomy_type: "KITCHEN",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2022-12-01",
    updated_at: "2025-11-20",
    tags: ["rattan", "natural", "kitchen", "sustainable"],
    variants: [
      { id: "po_var003a", productId: "p_prod003", sku: "LBM-RFB-SM", name: "Small (10\")", wholesale_price_cents: 1800, retail_price_cents: 4200, available_quantity: 200, backordered_until: null, options: [{ name: "Size", value: "Small" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var003b", productId: "p_prod003", sku: "LBM-RFB-LG", name: "Large (14\")", wholesale_price_cents: 2600, retail_price_cents: 6200, available_quantity: 140, backordered_until: null, options: [{ name: "Size", value: "Large" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [
      { id: "rev-003a", productId: "p_prod003", retailer_name: "The Green Pantry", rating: 4, comment: "Beautiful product. Packaging could be improved.", created_at: "2025-10-15" },
    ],
  },
  {
    id: "p_prod004",
    storeId: "store-002",
    name: "Linen Napkin Set",
    description: "Set of 4 stonewashed linen napkins. Gets softer with every wash. Available in 6 earthy tones.",
    category: "Kitchen & Dining",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 4,
    units_per_case: 4,
    made_in_country: "LTU",
    taxonomy_type: "KITCHEN",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2022-12-15",
    updated_at: "2025-12-10",
    tags: ["linen", "stonewashed", "napkins", "table"],
    variants: [
      { id: "po_var004a", productId: "p_prod004", sku: "LBM-NAP-NTR", name: "Natural", wholesale_price_cents: 2200, retail_price_cents: 5200, available_quantity: 180, backordered_until: null, options: [{ name: "Color", value: "Natural" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var004b", productId: "p_prod004", sku: "LBM-NAP-SAG", name: "Sage", wholesale_price_cents: 2200, retail_price_cents: 5200, available_quantity: 120, backordered_until: null, options: [{ name: "Color", value: "Sage" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var004c", productId: "p_prod004", sku: "LBM-NAP-DUS", name: "Dusty Rose", wholesale_price_cents: 2200, retail_price_cents: 5200, available_quantity: 96, backordered_until: null, options: [{ name: "Color", value: "Dusty Rose" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [],
  },
  {
    id: "p_prod005",
    storeId: "store-003",
    name: "Hand-Stamped Leather Journal",
    description: "Refillable leather journal with hand-stamped botanical cover. A5 size, 200 pages of cream paper.",
    category: "Stationery & Office",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 3,
    units_per_case: 6,
    made_in_country: "USA",
    taxonomy_type: "STATIONERY",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2023-08-01",
    updated_at: "2026-01-05",
    tags: ["leather", "journal", "handmade", "botanical"],
    variants: [
      { id: "po_var005a", productId: "p_prod005", sku: "GLC-JRN-BRN", name: "Brown — Fern", wholesale_price_cents: 3400, retail_price_cents: 8200, available_quantity: 60, backordered_until: null, options: [{ name: "Color", value: "Brown" }, { name: "Design", value: "Fern" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var005b", productId: "p_prod005", sku: "GLC-JRN-TAN", name: "Tan — Wildflower", wholesale_price_cents: 3400, retail_price_cents: 8200, available_quantity: 45, backordered_until: null, options: [{ name: "Color", value: "Tan" }, { name: "Design", value: "Wildflower" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [
      { id: "rev-005a", productId: "p_prod005", retailer_name: "Papercraft Studio", rating: 5, comment: "One of our top-10 best sellers. Customers come back for refills.", created_at: "2026-02-05" },
    ],
  },
  {
    id: "p_prod006",
    storeId: "store-003",
    name: "Macramé Wall Hanging",
    description: "Hand-knotted macramé wall art using natural cotton rope. Each piece is unique.",
    category: "Wall Art & Decor",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 2,
    units_per_case: 2,
    made_in_country: "USA",
    taxonomy_type: "HOME_DECOR",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2023-09-10",
    updated_at: "2025-12-20",
    tags: ["macrame", "wall art", "handmade", "cotton"],
    variants: [
      { id: "po_var006a", productId: "p_prod006", sku: "GLC-MAC-SM", name: "Small (12\"×18\")", wholesale_price_cents: 3800, retail_price_cents: 8800, available_quantity: 32, backordered_until: null, options: [{ name: "Size", value: "Small" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var006b", productId: "p_prod006", sku: "GLC-MAC-LG", name: "Large (18\"×36\")", wholesale_price_cents: 6800, retail_price_cents: 15800, available_quantity: 14, backordered_until: null, options: [{ name: "Size", value: "Large" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [],
  },
  {
    id: "p_prod007",
    storeId: "store-004",
    name: "Wheel-Thrown Ceramic Mug",
    description: "Artisan wheel-thrown ceramic mug with speckled glaze. Microwave and dishwasher safe. 12oz capacity.",
    category: "Kitchen & Dining",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 6,
    units_per_case: 6,
    made_in_country: "USA",
    taxonomy_type: "KITCHEN",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2024-02-01",
    updated_at: "2026-02-10",
    tags: ["ceramic", "handmade", "mug", "pottery"],
    variants: [
      { id: "po_var007a", productId: "p_prod007", sku: "HRT-MUG-WHT", name: "White Speckle", wholesale_price_cents: 2400, retail_price_cents: 5800, available_quantity: 72, backordered_until: null, options: [{ name: "Glaze", value: "White Speckle" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var007b", productId: "p_prod007", sku: "HRT-MUG-BLU", name: "Ocean Blue", wholesale_price_cents: 2400, retail_price_cents: 5800, available_quantity: 48, backordered_until: null, options: [{ name: "Glaze", value: "Ocean Blue" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var007c", productId: "p_prod007", sku: "HRT-MUG-MOS", name: "Mossy Green", wholesale_price_cents: 2400, retail_price_cents: 5800, available_quantity: 0, backordered_until: "2026-04-01", options: [{ name: "Glaze", value: "Mossy Green" }], lifecycle_state: "PUBLISHED", sale_state: "SALES_PAUSED" },
    ],
    reviews: [
      { id: "rev-007a", productId: "p_prod007", retailer_name: "Gather & Grind Coffee", rating: 5, comment: "Our café carries these and customers always ask where to buy more.", created_at: "2025-11-28" },
    ],
  },
  {
    id: "p_prod008",
    storeId: "store-005",
    name: "Lavender Body Oil",
    description: "Cold-pressed lavender and jojoba body oil. Organic certified, vegan, and cruelty-free. 4oz amber bottle.",
    category: "Bath & Body",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 6,
    units_per_case: 12,
    made_in_country: "USA",
    taxonomy_type: "BEAUTY",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2022-07-15",
    updated_at: "2026-01-20",
    tags: ["organic", "vegan", "lavender", "body oil"],
    variants: [
      { id: "po_var008a", productId: "p_prod008", sku: "PRE-OIL-LAV-4", name: "4oz", wholesale_price_cents: 1600, retail_price_cents: 3800, available_quantity: 240, backordered_until: null, options: [{ name: "Size", value: "4oz" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var008b", productId: "p_prod008", sku: "PRE-OIL-LAV-8", name: "8oz", wholesale_price_cents: 2800, retail_price_cents: 6400, available_quantity: 120, backordered_until: null, options: [{ name: "Size", value: "8oz" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [
      { id: "rev-008a", productId: "p_prod008", retailer_name: "Serenity Spa Boutique", rating: 5, comment: "Our #1 selling body oil. Clients love the scent.", created_at: "2026-02-14" },
      { id: "rev-008b", productId: "p_prod008", retailer_name: "Bloom Wellness", rating: 4, comment: "Great product, wish there were more scent options.", created_at: "2025-12-20" },
    ],
  },
  {
    id: "p_prod009",
    storeId: "store-005",
    name: "Rose Facial Serum",
    description: "Concentrated rose hip and vitamin C facial serum. Brightening and anti-aging formula. 1oz dropper bottle.",
    category: "Skincare",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 6,
    units_per_case: 12,
    made_in_country: "USA",
    taxonomy_type: "BEAUTY",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2022-09-01",
    updated_at: "2026-02-01",
    tags: ["serum", "vitamin C", "rosehip", "anti-aging"],
    variants: [
      { id: "po_var009a", productId: "p_prod009", sku: "PRE-SRM-ROS-1", name: "1oz Dropper", wholesale_price_cents: 2200, retail_price_cents: 5200, available_quantity: 180, backordered_until: null, options: [{ name: "Size", value: "1oz" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [],
  },
  {
    id: "p_prod010",
    storeId: "store-006",
    name: "Wildflower Honey",
    description: "Raw, unfiltered Pacific Northwest wildflower honey. Harvested from our partner bee farms. 12oz jar.",
    category: "Food & Beverage",
    lifecycle_state: "PUBLISHED",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 12,
    units_per_case: 12,
    made_in_country: "USA",
    taxonomy_type: "FOOD",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2024-06-01",
    updated_at: "2026-02-05",
    tags: ["honey", "organic", "raw", "PNW"],
    variants: [
      { id: "po_var010a", productId: "p_prod010", sku: "NAT-HON-WLD-12", name: "12oz Jar", wholesale_price_cents: 1200, retail_price_cents: 2800, available_quantity: 360, backordered_until: null, options: [{ name: "Size", value: "12oz" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
      { id: "po_var010b", productId: "p_prod010", sku: "NAT-HON-WLD-32", name: "32oz Jar", wholesale_price_cents: 2800, retail_price_cents: 6400, available_quantity: 80, backordered_until: null, options: [{ name: "Size", value: "32oz" }], lifecycle_state: "PUBLISHED", sale_state: "FOR_SALE" },
    ],
    reviews: [
      { id: "rev-010a", productId: "p_prod010", retailer_name: "The Harvest Table", rating: 4, comment: "Pure quality. Customers love supporting local beekeepers.", created_at: "2025-12-01" },
    ],
  },
  {
    id: "p_prod011",
    storeId: "store-003",
    name: "Pressed Botanical Print",
    description: "Archival quality pressed botanical prints. Printed on 300gsm cotton rag paper. Unframed.",
    category: "Wall Art & Decor",
    lifecycle_state: "DRAFT",
    sale_state: "FOR_SALE",
    minimum_order_quantity: 4,
    units_per_case: 4,
    made_in_country: "USA",
    taxonomy_type: "ART",
    unit_multiplier: 1,
    preorderable: true,
    created_at: "2026-02-01",
    updated_at: "2026-02-28",
    tags: ["botanical", "print", "art", "wall decor"],
    variants: [
      { id: "po_var011a", productId: "p_prod011", sku: "GLC-PRT-FRN-8", name: "Fern — 8\"×10\"", wholesale_price_cents: 2200, retail_price_cents: 5200, available_quantity: 0, backordered_until: null, options: [{ name: "Design", value: "Fern" }, { name: "Size", value: "8×10" }], lifecycle_state: "DRAFT", sale_state: "FOR_SALE" },
      { id: "po_var011b", productId: "p_prod011", sku: "GLC-PRT-WLD-8", name: "Wildflower — 8\"×10\"", wholesale_price_cents: 2200, retail_price_cents: 5200, available_quantity: 0, backordered_until: null, options: [{ name: "Design", value: "Wildflower" }, { name: "Size", value: "8×10" }], lifecycle_state: "DRAFT", sale_state: "FOR_SALE" },
    ],
    reviews: [],
  },
  {
    id: "p_prod012",
    storeId: "store-001",
    name: "Chunky Knit Pillow Cover",
    description: "Hand-knitted chunky pillow covers in natural undyed wool. Fits 18×18 inserts.",
    category: "Textiles",
    lifecycle_state: "UNPUBLISHED",
    sale_state: "SALES_PAUSED",
    minimum_order_quantity: 4,
    units_per_case: 4,
    made_in_country: "PER",
    taxonomy_type: "HOME_DECOR",
    unit_multiplier: 1,
    preorderable: false,
    created_at: "2024-10-15",
    updated_at: "2026-01-10",
    tags: ["knit", "pillow", "wool", "handmade"],
    variants: [
      { id: "po_var012a", productId: "p_prod012", sku: "SUP-PIL-OAT", name: "Oatmeal", wholesale_price_cents: 3600, retail_price_cents: 8400, available_quantity: 0, backordered_until: null, options: [{ name: "Color", value: "Oatmeal" }], lifecycle_state: "UNPUBLISHED", sale_state: "SALES_PAUSED" },
    ],
    reviews: [],
  },
];

// ─── Shipments ─────────────────────────────────────────────────────────────────

const s_ship001: FaireShipment = {
  id: "s_ship001", orderId: "bo_ord009", tracking_code: "1Z999AA10123456784",
  carrier: "UPS", shipped_at: "2026-02-18", maker_cost_cents: 2300, shipping_type: "SHIP_ON_YOUR_OWN",
};
const s_ship002: FaireShipment = {
  id: "s_ship002", orderId: "bo_ord010", tracking_code: "9400111899223408332000",
  carrier: "USPS", shipped_at: "2026-02-20", maker_cost_cents: 1500, shipping_type: "SHIP_ON_YOUR_OWN",
};
const s_ship003: FaireShipment = {
  id: "s_ship003", orderId: "bo_ord007", tracking_code: "774899172137",
  carrier: "FedEx", shipped_at: "2026-02-24", maker_cost_cents: 1800, shipping_type: "SHIP_ON_YOUR_OWN",
};
const s_ship003b: FaireShipment = {
  id: "s_ship003b", orderId: "bo_ord011", tracking_code: "774899172138",
  carrier: "FedEx", shipped_at: "2026-02-24", maker_cost_cents: 2200, shipping_type: "SHIP_ON_YOUR_OWN",
};
const s_ship004: FaireShipment = {
  id: "s_ship004", orderId: "bo_ord008", tracking_code: "1Z999AA10123456790",
  carrier: "UPS", shipped_at: "2026-02-25", maker_cost_cents: 1900, shipping_type: "SHIP_ON_YOUR_OWN",
};
const s_ship004b: FaireShipment = {
  id: "s_ship004b", orderId: "bo_ord012", tracking_code: "1Z999AA10123456791",
  carrier: "UPS", shipped_at: "2026-02-25", maker_cost_cents: 1600, shipping_type: "SHIP_ON_YOUR_OWN",
};
const s_ship005: FaireShipment = {
  id: "s_ship005", orderId: "bo_ord013", tracking_code: "9400111899223408332111",
  carrier: "USPS", shipped_at: "2026-02-26", maker_cost_cents: 1200, shipping_type: "SHIP_ON_YOUR_OWN",
};
const s_ship006: FaireShipment = {
  id: "s_ship006", orderId: "bo_ord014", tracking_code: "1Z999AA10123456799",
  carrier: "UPS", shipped_at: "2026-01-20", maker_cost_cents: 2300, shipping_type: "SHIP_ON_YOUR_OWN",
};

// ─── Orders ────────────────────────────────────────────────────────────────────

export const faireOrders: FaireOrder[] = [
  {
    id: "bo_ord001", display_id: "28841AA", storeId: "store-001", retailer_id: "r_ret001",
    state: "NEW", source: "MARKETPLACE", is_free_shipping: false, free_shipping_reason: undefined,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, purchase_order_number: undefined,
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 8400, commission_bps: 2500 },
    items: [
      { id: "oi_001a", order_id: "bo_ord001", product_id: "p_prod001", variant_id: "po_var001a", product_name: "Handwoven Cotton Throw", variant_name: "Ivory", sku: "SUP-THR-IVR", quantity: 4, price_cents: 4200, state: "PROCESSING", includes_tester: false, discounts: [] },
      { id: "oi_001b", order_id: "bo_ord001", product_id: "p_prod002", variant_id: "po_var002a", product_name: "Soy Wax Pillar Candle Set", variant_name: "Lavender & Cedar", sku: "SUP-CND-LAV", quantity: 6, price_cents: 2800, state: "PROCESSING", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "The Cozy Corner Boutique", address1: "142 Broadway Ave", city: "Nashville", state: "Tennessee", state_code: "TN", postal_code: "37201", country: "United States", country_code: "USA" },
    created_at: "2026-02-28T07:12:00Z", updated_at: "2026-02-28T07:12:00Z",
  },
  {
    id: "bo_ord002", display_id: "28842BB", storeId: "store-002", retailer_id: "r_ret002",
    state: "NEW", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: "Please include brand catalog in package.", purchase_order_number: "PO-7842",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 3900, commission_bps: 2500 },
    items: [
      { id: "oi_002a", order_id: "bo_ord002", product_id: "p_prod003", variant_id: "po_var003b", product_name: "Rattan Fruit Bowl", variant_name: "Large (14\")", sku: "LBM-RFB-LG", quantity: 6, price_cents: 2600, state: "PROCESSING", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "Bloom & Gather", address1: "881 N Michigan Ave", city: "Chicago", state: "Illinois", state_code: "IL", postal_code: "60611", country: "United States", country_code: "USA" },
    created_at: "2026-02-28T08:04:00Z", updated_at: "2026-02-28T08:04:00Z",
  },
  {
    id: "bo_ord003", display_id: "28843CC", storeId: "store-005", retailer_id: "r_ret003",
    state: "NEW", source: "FAIRE_DIRECT", is_free_shipping: true, free_shipping_reason: "FREE_SHIPPING_THRESHOLD",
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, sales_rep_name: "Jordan Rivera",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 0, commission_bps: 0 },
    items: [
      { id: "oi_003a", order_id: "bo_ord003", product_id: "p_prod008", variant_id: "po_var008a", product_name: "Lavender Body Oil", variant_name: "4oz", sku: "PRE-OIL-LAV-4", quantity: 12, price_cents: 1600, state: "PROCESSING", includes_tester: false, discounts: [] },
      { id: "oi_003b", order_id: "bo_ord003", product_id: "p_prod009", variant_id: "po_var009a", product_name: "Rose Facial Serum", variant_name: "1oz Dropper", sku: "PRE-SRM-ROS-1", quantity: 6, price_cents: 2200, state: "PROCESSING", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "Serenity Spa Boutique", address1: "7299 N Scottsdale Rd", city: "Scottsdale", state: "Arizona", state_code: "AZ", postal_code: "85253", country: "United States", country_code: "USA" },
    created_at: "2026-02-28T08:45:00Z", updated_at: "2026-02-28T08:45:00Z",
  },
  {
    id: "bo_ord004", display_id: "28800DD", storeId: "store-001", retailer_id: "r_ret004",
    state: "PROCESSING", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, ship_after: "2026-03-01T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 4200, commission_bps: 2500 },
    items: [
      { id: "oi_004a", order_id: "bo_ord004", product_id: "p_prod001", variant_id: "po_var001b", product_name: "Handwoven Cotton Throw", variant_name: "Terracotta", sku: "SUP-THR-TER", quantity: 4, price_cents: 4200, state: "PRE_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "Nest & Nook", address1: "2204 NW Thurman St", city: "Portland", state: "Oregon", state_code: "OR", postal_code: "97210", country: "United States", country_code: "USA" },
    created_at: "2026-02-26T14:30:00Z", updated_at: "2026-02-27T09:00:00Z",
  },
  {
    id: "bo_ord005", display_id: "28801EE", storeId: "store-002", retailer_id: "r_ret005",
    state: "PRE_TRANSIT", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null,
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 6600, commission_bps: 2500 },
    items: [
      { id: "oi_005a", order_id: "bo_ord005", product_id: "p_prod004", variant_id: "po_var004a", product_name: "Linen Napkin Set", variant_name: "Natural", sku: "LBM-NAP-NTR", quantity: 8, price_cents: 2200, state: "PRE_TRANSIT", includes_tester: false, discounts: [] },
      { id: "oi_005b", order_id: "bo_ord005", product_id: "p_prod004", variant_id: "po_var004b", product_name: "Linen Napkin Set", variant_name: "Sage", sku: "LBM-NAP-SAG", quantity: 4, price_cents: 2200, state: "PRE_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "The Green Pantry", address1: "401 Hayes St", city: "San Francisco", state: "California", state_code: "CA", postal_code: "94102", country: "United States", country_code: "USA" },
    created_at: "2026-02-25T11:15:00Z", updated_at: "2026-02-26T08:00:00Z",
  },
  {
    id: "bo_ord006", display_id: "28790FF", storeId: "store-003", retailer_id: "r_ret006",
    state: "PRE_TRANSIT", source: "TRADESHOW", is_free_shipping: true, free_shipping_reason: "FREE_SHIPPING_THRESHOLD",
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: "Gift wrap each journal please.",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 10200, commission_bps: 2500 },
    items: [
      { id: "oi_006a", order_id: "bo_ord006", product_id: "p_prod005", variant_id: "po_var005a", product_name: "Hand-Stamped Leather Journal", variant_name: "Brown — Fern", sku: "GLC-JRN-BRN", quantity: 6, price_cents: 3400, state: "PRE_TRANSIT", includes_tester: false, discounts: [] },
      { id: "oi_006b", order_id: "bo_ord006", product_id: "p_prod005", variant_id: "po_var005b", product_name: "Hand-Stamped Leather Journal", variant_name: "Tan — Wildflower", sku: "GLC-JRN-TAN", quantity: 6, price_cents: 3400, state: "PRE_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "Papercraft Studio", address1: "1550 17th St", city: "Denver", state: "Colorado", state_code: "CO", postal_code: "80202", country: "United States", country_code: "USA" },
    created_at: "2026-02-24T09:20:00Z", updated_at: "2026-02-25T11:00:00Z",
  },
  {
    id: "bo_ord007", display_id: "28780GG", storeId: "store-005", retailer_id: "r_ret007",
    state: "IN_TRANSIT", source: "MARKETPLACE", is_free_shipping: true, free_shipping_reason: "FREE_SHIPPING_THRESHOLD",
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, payment_initiated_at: undefined, estimated_payout_at: "2026-03-10T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 8400, commission_bps: 2500 },
    items: [
      { id: "oi_007a", order_id: "bo_ord007", product_id: "p_prod008", variant_id: "po_var008b", product_name: "Lavender Body Oil", variant_name: "8oz", sku: "PRE-OIL-LAV-8", quantity: 12, price_cents: 2800, state: "IN_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship003],
    address: { name: "Bloom Wellness", address1: "2222 S Lamar Blvd", city: "Austin", state: "Texas", state_code: "TX", postal_code: "78704", country: "United States", country_code: "USA" },
    created_at: "2026-02-22T10:30:00Z", updated_at: "2026-02-24T14:00:00Z",
  },
  {
    id: "bo_ord008", display_id: "28770HH", storeId: "store-002", retailer_id: "r_ret008",
    state: "IN_TRANSIT", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, estimated_payout_at: "2026-03-12T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 7600, commission_bps: 2500 },
    items: [
      { id: "oi_008a", order_id: "bo_ord008", product_id: "p_prod003", variant_id: "po_var003a", product_name: "Rattan Fruit Bowl", variant_name: "Small (10\")", sku: "LBM-RFB-SM", quantity: 12, price_cents: 1800, state: "IN_TRANSIT", includes_tester: false, discounts: [] },
      { id: "oi_008b", order_id: "bo_ord008", product_id: "p_prod004", variant_id: "po_var004c", product_name: "Linen Napkin Set", variant_name: "Dusty Rose", sku: "LBM-NAP-DUS", quantity: 4, price_cents: 2200, state: "IN_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship004],
    address: { name: "Gather & Grind Coffee", address1: "1600 Pike Place", city: "Seattle", state: "Washington", state_code: "WA", postal_code: "98101", country: "United States", country_code: "USA" },
    created_at: "2026-02-21T16:00:00Z", updated_at: "2026-02-25T10:00:00Z",
  },
  {
    id: "bo_ord009", display_id: "28700II", storeId: "store-001", retailer_id: "r_ret001",
    state: "DELIVERED", source: "MARKETPLACE", is_free_shipping: true, free_shipping_reason: "FREE_SHIPPING_THRESHOLD",
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, payment_initiated_at: "2026-02-22T00:10:34Z", estimated_payout_at: "2026-02-22T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 8400, commission_bps: 2500 },
    items: [
      { id: "oi_009a", order_id: "bo_ord009", product_id: "p_prod002", variant_id: "po_var002b", product_name: "Soy Wax Pillar Candle Set", variant_name: "Sandalwood & Amber", sku: "SUP-CND-SAN", quantity: 12, price_cents: 2800, state: "DELIVERED", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship001],
    address: { name: "The Cozy Corner Boutique", address1: "142 Broadway Ave", city: "Nashville", state: "Tennessee", state_code: "TN", postal_code: "37201", country: "United States", country_code: "USA" },
    created_at: "2026-02-14T09:00:00Z", updated_at: "2026-02-20T12:00:00Z",
  },
  {
    id: "bo_ord010", display_id: "28680JJ", storeId: "store-005", retailer_id: "r_ret009",
    state: "DELIVERED", source: "MARKETPLACE", is_free_shipping: true, free_shipping_reason: "FREE_SHIPPING_THRESHOLD",
    brand_discounts: [
      { id: "bpc_k3w2kb97tp", code: "WELLNESS10", includes_free_shipping: false, discount_percentage: 10, discount_type: "PERCENTAGE" },
    ],
    has_pending_retailer_cancellation_request: false,
    notes: null, payment_initiated_at: "2026-02-24T00:10:34Z", estimated_payout_at: "2026-02-24T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 11400, commission_bps: 2500 },
    items: [
      { id: "oi_010a", order_id: "bo_ord010", product_id: "p_prod009", variant_id: "po_var009a", product_name: "Rose Facial Serum", variant_name: "1oz Dropper", sku: "PRE-SRM-ROS-1", quantity: 12, price_cents: 2200, state: "DELIVERED", includes_tester: false, discounts: [] },
      { id: "oi_010b", order_id: "bo_ord010", product_id: "p_prod008", variant_id: "po_var008a", product_name: "Lavender Body Oil", variant_name: "4oz", sku: "PRE-OIL-LAV-4", quantity: 12, price_cents: 1600, state: "DELIVERED", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship002],
    address: { name: "Sol Wellness", address1: "800 Lincoln Rd", city: "Miami", state: "Florida", state_code: "FL", postal_code: "33139", country: "United States", country_code: "USA" },
    created_at: "2026-02-16T08:00:00Z", updated_at: "2026-02-22T16:00:00Z",
  },
  {
    id: "bo_ord011", display_id: "28650KK", storeId: "store-003", retailer_id: "r_ret010",
    state: "IN_TRANSIT", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, estimated_payout_at: "2026-03-11T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 6800, commission_bps: 2500 },
    items: [
      { id: "oi_011a", order_id: "bo_ord011", product_id: "p_prod006", variant_id: "po_var006b", product_name: "Macramé Wall Hanging", variant_name: "Large (18\"×36\")", sku: "GLC-MAC-LG", quantity: 4, price_cents: 6800, state: "IN_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship003b],
    address: { name: "The Artful Home", address1: "675 Ponce De Leon Ave", city: "Atlanta", state: "Georgia", state_code: "GA", postal_code: "30308", country: "United States", country_code: "USA" },
    created_at: "2026-02-20T13:00:00Z", updated_at: "2026-02-24T11:00:00Z",
  },
  {
    id: "bo_ord012", display_id: "28620LL", storeId: "store-006", retailer_id: "r_ret011",
    state: "IN_TRANSIT", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, estimated_payout_at: "2026-03-12T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 7200, commission_bps: 2500 },
    items: [
      { id: "oi_012a", order_id: "bo_ord012", product_id: "p_prod010", variant_id: "po_var010a", product_name: "Wildflower Honey", variant_name: "12oz Jar", sku: "NAT-HON-WLD-12", quantity: 24, price_cents: 1200, state: "IN_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship004b],
    address: { name: "The Harvest Table", address1: "3601 E Thomas Rd", city: "Phoenix", state: "Arizona", state_code: "AZ", postal_code: "85018", country: "United States", country_code: "USA" },
    created_at: "2026-02-19T10:00:00Z", updated_at: "2026-02-25T09:00:00Z",
  },
  {
    id: "bo_ord013", display_id: "28590MM", storeId: "store-005", retailer_id: "r_ret012",
    state: "IN_TRANSIT", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, estimated_payout_at: "2026-03-13T00:00:00Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 2400, commission_bps: 2500 },
    items: [
      { id: "oi_013a", order_id: "bo_ord013", product_id: "p_prod008", variant_id: "po_var008a", product_name: "Lavender Body Oil", variant_name: "4oz", sku: "PRE-OIL-LAV-4", quantity: 6, price_cents: 1600, state: "IN_TRANSIT", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship005],
    address: { name: "Petal + Co", address1: "100 N 6th St", city: "Minneapolis", state: "Minnesota", state_code: "MN", postal_code: "55403", country: "United States", country_code: "USA" },
    created_at: "2026-02-21T08:00:00Z", updated_at: "2026-02-26T14:00:00Z",
  },
  {
    id: "bo_ord014", display_id: "28400NN", storeId: "store-001", retailer_id: "r_ret004",
    state: "DELIVERED", source: "MARKETPLACE", is_free_shipping: true, free_shipping_reason: "FREE_SHIPPING_THRESHOLD",
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: null, payment_initiated_at: "2026-01-27T00:10:34Z",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 8400, commission_bps: 2500 },
    items: [
      { id: "oi_014a", order_id: "bo_ord014", product_id: "p_prod001", variant_id: "po_var001a", product_name: "Handwoven Cotton Throw", variant_name: "Ivory", sku: "SUP-THR-IVR", quantity: 8, price_cents: 4200, state: "DELIVERED", includes_tester: false, discounts: [] },
    ],
    shipments: [s_ship006],
    address: { name: "Nest & Nook", address1: "2204 NW Thurman St", city: "Portland", state: "Oregon", state_code: "OR", postal_code: "97210", country: "United States", country_code: "USA" },
    created_at: "2026-01-14T10:00:00Z", updated_at: "2026-01-25T12:00:00Z",
  },
  {
    id: "bo_ord015", display_id: "28380OO", storeId: "store-002", retailer_id: "r_ret002",
    state: "CANCELED", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: false,
    notes: "Retailer requested cancel — ordering different variant.",
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 0, commission_bps: 2500 },
    items: [
      { id: "oi_015a", order_id: "bo_ord015", product_id: "p_prod004", variant_id: "po_var004a", product_name: "Linen Napkin Set", variant_name: "Natural", sku: "LBM-NAP-NTR", quantity: 4, price_cents: 2200, state: "CANCELED", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "Bloom & Gather", address1: "881 N Michigan Ave", city: "Chicago", state: "Illinois", state_code: "IL", postal_code: "60611", country: "United States", country_code: "USA" },
    created_at: "2026-01-12T09:00:00Z", updated_at: "2026-01-13T11:00:00Z",
  },
  {
    id: "bo_ord016", display_id: "28350PP", storeId: "store-004", retailer_id: "r_ret013",
    state: "BACKORDERED", source: "MARKETPLACE", is_free_shipping: false,
    brand_discounts: [], has_pending_retailer_cancellation_request: true,
    notes: null,
    payout_costs: { payout_fee_cents: 0, payout_fee_bps: 0, commission_cents: 7200, commission_bps: 2500 },
    items: [
      { id: "oi_016a", order_id: "bo_ord016", product_id: "p_prod007", variant_id: "po_var007c", product_name: "Wheel-Thrown Ceramic Mug", variant_name: "Mossy Green", sku: "HRT-MUG-MOS", quantity: 12, price_cents: 2400, state: "BACKORDERED", includes_tester: false, discounts: [] },
    ],
    shipments: [],
    address: { name: "Inner Glow Studio", address1: "8605 Santa Monica Blvd", city: "Los Angeles", state: "California", state_code: "CA", postal_code: "90069", country: "United States", country_code: "USA" },
    created_at: "2026-02-10T08:00:00Z", updated_at: "2026-02-10T08:00:00Z",
  },
];

// ─── Shipments export ──────────────────────────────────────────────────────────

export const faireShipments: FaireShipment[] = [
  s_ship001, s_ship002, s_ship003, s_ship003b, s_ship004, s_ship004b, s_ship005, s_ship006,
];

// ─── Retailers ─────────────────────────────────────────────────────────────────

export const faireRetailers: FaireRetailer[] = [
  {
    id: "r_ret001", name: "Sarah Mitchell", email: "orders@cozycorner.com", retailer_token: "r_coz_8f2a1c",
    store_name: "The Cozy Corner Boutique", city: "Nashville", state: "TN", country: "US",
    website: "https://cozycornerboutique.com", instagram: "@cozycornerboutique",
    description: "Curated home goods and lifestyle boutique in the heart of Nashville.",
    created_at: "2023-06-01", total_orders: 14, total_spent: 4820, last_ordered: "2026-02-28",
    storeIds: ["store-001", "store-002"], status: "active",
  },
  {
    id: "r_ret002", name: "Emma Rodriguez", email: "buying@bloomandgather.co", retailer_token: "r_blm_4d7e2b",
    store_name: "Bloom & Gather", city: "Chicago", state: "IL", country: "US",
    website: "https://bloomandgather.co", instagram: "@bloomandgatherchi",
    description: "Floral design studio and home goods shop in Chicago's West Loop.",
    created_at: "2022-12-15", total_orders: 28, total_spent: 7640, last_ordered: "2026-02-28",
    storeIds: ["store-002", "store-003"], status: "active",
  },
  {
    id: "r_ret003", name: "Jennifer Park", email: "orders@serenityspa.com", retailer_token: "r_ser_9c3f5a",
    store_name: "Serenity Spa Boutique", city: "Scottsdale", state: "AZ", country: "US",
    website: "https://serenityspa.com", instagram: "@serenityspaaz",
    description: "Luxury day spa and wellness retail boutique in Scottsdale.",
    created_at: "2023-01-20", total_orders: 22, total_spent: 6920, last_ordered: "2026-02-28",
    storeIds: ["store-005"], status: "active",
  },
  {
    id: "r_ret004", name: "Alex Chen", email: "wholesale@nestandnook.com", retailer_token: "r_nst_6a1d8c",
    store_name: "Nest & Nook", city: "Portland", state: "OR", country: "US",
    website: "https://nestandnook.com", instagram: "@nestandnookpdx",
    description: "Scandinavian-inspired home goods and gifts shop in Portland.",
    created_at: "2023-03-10", total_orders: 18, total_spent: 5240, last_ordered: "2026-02-26",
    storeIds: ["store-001", "store-003"], status: "active",
  },
  {
    id: "r_ret005", name: "Marcus Johnson", email: "wholesale@thegreenpantry.com", retailer_token: "r_grn_2e9b4f",
    store_name: "The Green Pantry", city: "San Francisco", state: "CA", country: "US",
    website: "https://thegreenpantry.com", instagram: "@thegreenpantrysf",
    description: "Sustainable food and home goods store focused on zero-waste living.",
    created_at: "2022-09-15", total_orders: 32, total_spent: 8180, last_ordered: "2026-02-25",
    storeIds: ["store-002", "store-006"], status: "active",
  },
  {
    id: "r_ret006", name: "Diana Patel", email: "orders@papercraftstudio.com", retailer_token: "r_pap_7f4a2d",
    store_name: "Papercraft Studio", city: "Denver", state: "CO", country: "US",
    website: "https://papercraftstudio.com", instagram: "@papercraftstudioco",
    description: "Artisan stationery and craft supply shop with curated maker goods.",
    created_at: "2023-08-22", total_orders: 10, total_spent: 3240, last_ordered: "2026-02-24",
    storeIds: ["store-003"], status: "active",
  },
  {
    id: "r_ret007", name: "Priya Kumar", email: "wholesale@bloomwellness.co", retailer_token: "r_blw_1b8c4e",
    store_name: "Bloom Wellness", city: "Austin", state: "TX", country: "US",
    website: "https://bloomwellness.co", instagram: "@bloomwellnessatx",
    description: "Holistic wellness boutique and apothecary in South Austin.",
    created_at: "2022-11-01", total_orders: 24, total_spent: 6480, last_ordered: "2026-02-22",
    storeIds: ["store-005"], status: "active",
  },
  {
    id: "r_ret008", name: "Tyler Brooks", email: "orders@gatherandgrind.com", retailer_token: "r_gg_5d2a7f",
    store_name: "Gather & Grind Coffee", city: "Seattle", state: "WA", country: "US",
    website: "https://gatherandgrind.com", instagram: "@gatherandgrindcoffee",
    description: "Specialty coffee shop and curated home goods destination in Pike Place.",
    created_at: "2023-05-14", total_orders: 8, total_spent: 2480, last_ordered: "2026-02-21",
    storeIds: ["store-002", "store-004"], status: "active",
  },
  {
    id: "r_ret009", name: "Isabella Santos", email: "buyer@solwellness.com", retailer_token: "r_sol_3c6e9a",
    store_name: "Sol Wellness", city: "Miami", state: "FL", country: "US",
    website: "https://solwellness.com", instagram: "@solwellnessmiami",
    description: "Luxury wellness and beauty boutique on Lincoln Road, Miami Beach.",
    created_at: "2023-02-28", total_orders: 16, total_spent: 4920, last_ordered: "2026-02-16",
    storeIds: ["store-005"], status: "active",
  },
  {
    id: "r_ret010", name: "Robert Kim", email: "wholesale@artfulhome.com", retailer_token: "r_art_8e1b3d",
    store_name: "The Artful Home", city: "Atlanta", state: "GA", country: "US",
    website: "https://artfulhome.com", instagram: "@artfulhomeatlanta",
    description: "Contemporary art and home decor gallery in Ponce City Market.",
    created_at: "2023-06-30", total_orders: 6, total_spent: 1840, last_ordered: "2026-02-20",
    storeIds: ["store-003", "store-004"], status: "active",
  },
  {
    id: "r_ret011", name: "Olivia Turner", email: "orders@harvesttable.com", retailer_token: "r_hrv_4f9c2b",
    store_name: "The Harvest Table", city: "Phoenix", state: "AZ", country: "US",
    website: "https://harvesttable.com", instagram: "@harvesttablephx",
    description: "Farm-to-table restaurant retail shop specializing in local and artisan foods.",
    created_at: "2024-07-10", total_orders: 4, total_spent: 1120, last_ordered: "2026-02-19",
    storeIds: ["store-006"], status: "active",
  },
  {
    id: "r_ret012", name: "Grace Lee", email: "wholesale@petalandco.com", retailer_token: "r_ptl_6d8e1a",
    store_name: "Petal + Co", city: "Minneapolis", state: "MN", country: "US",
    website: "https://petalandco.com", instagram: "@petalandcomn",
    description: "Botanically inspired lifestyle boutique in Minneapolis.",
    created_at: "2024-01-15", total_orders: 7, total_spent: 1640, last_ordered: "2026-02-21",
    storeIds: ["store-005"], status: "active",
  },
  {
    id: "r_ret013", name: "Natalie Wong", email: "orders@innerglowstudio.com", retailer_token: "r_ing_2a5f8c",
    store_name: "Inner Glow Studio", city: "Los Angeles", state: "CA", country: "US",
    website: "https://innerglowstudio.com", instagram: "@innerglowla",
    description: "Wellness and beauty studio in West Hollywood with curated retail.",
    created_at: "2024-03-20", total_orders: 3, total_spent: 860, last_ordered: "2026-02-10",
    storeIds: ["store-004", "store-005"], status: "active",
  },
];
