import { useMemo } from "react";
import { DataTable, type Column } from "@/components/hr/data-table";
import { TableSkeleton } from "@/components/ui/table-skeleton";
import { StatsCard } from "@/components/hr/stats-card";
import { StatusBadge } from "@/components/hr/status-badge";
import { Badge } from "@/components/ui/badge";
import { PageTransition, Stagger, StaggerItem, Fade } from "@/components/ui/animated";
import { StatsCardSkeleton } from "@/components/ui/card-skeleton";
import { useSimulatedLoading } from "@/hooks/use-simulated-loading";
import { formationTasks, stageDefinitions, teamMembers } from "@/lib/mock-data";
import type { FormationTask } from "@shared/schema";
import { ListTodo, Clock, CheckCircle2, AlertTriangle, Zap } from "lucide-react";
import { PageShell } from "@/components/layout";
import { PersonCell, CompanyCell } from "@/components/ui/avatar-cells";

const priorityDot: Record<string, string> = {
  high: "bg-red-500",
  medium: "bg-amber-500",
  low: "bg-slate-400",
};

const statusVariantMap: Record<string, "success" | "error" | "warning" | "info" | "neutral"> = {
  pending: "warning",
  "in-progress": "info",
  completed: "success",
  overdue: "error",
};

export default function TaskBoard() {
  const loading = useSimulatedLoading();

  const stats = useMemo(() => {
    const pending = formationTasks.filter((t) => t.status === "pending").length;
    const inProgress = formationTasks.filter((t) => t.status === "in-progress").length;
    const completed = formationTasks.filter((t) => t.status === "completed").length;
    const overdue = formationTasks.filter((t) => t.status === "overdue").length;
    return { pending, inProgress, completed, overdue };
  }, []);

  const columns: Column<FormationTask>[] = [
    {
      key: "title",
      header: "Task",
      sortable: true,
      render: (item) => (
        <div className="flex flex-col gap-0.5">
          <div className="flex items-center gap-1.5">
            <span className="text-sm font-medium" data-testid={`text-task-title-${item.id}`}>{item.title}</span>
            {item.autoGenerated && (
              <Badge variant="outline" className="text-[10px] px-1.5 py-0" data-testid={`badge-auto-${item.id}`}>
                <Zap className="size-2.5 mr-0.5" />
                Auto
              </Badge>
            )}
          </div>
          <span className="text-xs text-muted-foreground">{item.description}</span>
        </div>
      ),
    },
    {
      key: "clientName",
      header: "Client",
      sortable: true,
      render: (item) => <CompanyCell name={item.clientName} size="sm" />,
    },
    {
      key: "stage",
      header: "Stage",
      sortable: true,
      render: (item) => {
        const stageDef = stageDefinitions.find((s) => s.number === item.stage);
        return (
          <span className="text-xs text-muted-foreground">
            {item.stage}. {stageDef?.name}
          </span>
        );
      },
    },
    {
      key: "assignedTo",
      header: "Assigned To",
      sortable: true,
      render: (item) => <PersonCell name={item.assignedTo} size="sm" />,
    },
    {
      key: "dueDate",
      header: "Due Date",
      sortable: true,
      render: (item) => {
        const isOverdue = item.status !== "completed" && new Date(item.dueDate) < new Date();
        return (
          <span className={`text-sm ${isOverdue ? "text-red-600 dark:text-red-400 font-medium" : "text-muted-foreground"}`}>
            {item.dueDate}
          </span>
        );
      },
    },
    {
      key: "priority",
      header: "Priority",
      sortable: true,
      render: (item) => (
        <div className="flex items-center gap-1.5">
          <span className={`size-2 rounded-full ${priorityDot[item.priority]}`} />
          <span className="text-sm capitalize">{item.priority}</span>
        </div>
      ),
    },
    {
      key: "status",
      header: "Status",
      render: (item) => {
        const label = item.status === "in-progress" ? "In Progress" : item.status.charAt(0).toUpperCase() + item.status.slice(1);
        return <StatusBadge status={label} variant={statusVariantMap[item.status]} />;
      },
    },
  ];

  const assignees = useMemo(() => {
    return Array.from(new Set(formationTasks.map((t) => t.assignedTo)));
  }, []);

  return (
    <PageShell>
      <PageTransition>
{loading ? (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6">
            {Array.from({ length: 4 }).map((_, i) => (
              <StatsCardSkeleton key={i} />
            ))}
          </div>
        ) : (
          <Stagger className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6" staggerInterval={0.06}>
            <StaggerItem>
              <StatsCard
                title="Pending"
                value={stats.pending}
                icon={<Clock className="size-5" />}
                change={`${stats.pending} awaiting action`}
                changeType="warning"
              />
            </StaggerItem>
            <StaggerItem>
              <StatsCard
                title="In Progress"
                value={stats.inProgress}
                icon={<ListTodo className="size-5" />}
                change="Currently being worked on"
                changeType="neutral"
              />
            </StaggerItem>
            <StaggerItem>
              <StatsCard
                title="Completed"
                value={stats.completed}
                icon={<CheckCircle2 className="size-5" />}
                change="Tasks done"
                changeType="positive"
              />
            </StaggerItem>
            <StaggerItem>
              <StatsCard
                title="Overdue"
                value={stats.overdue}
                icon={<AlertTriangle className="size-5" />}
                change={stats.overdue > 0 ? "Needs immediate attention" : "All clear"}
                changeType={stats.overdue > 0 ? "negative" : "positive"}
              />
            </StaggerItem>
          </Stagger>
        )}

        <Fade direction="up" distance={10} delay={0.2}>
          {loading ? (
            <TableSkeleton rows={8} columns={6} />
          ) : (
            <DataTable
              data={formationTasks}
              columns={columns}
              searchPlaceholder="Search tasks..."
              searchKey="title"
              filters={[
                {
                  label: "Status",
                  key: "status",
                  options: ["pending", "in-progress", "completed", "overdue"],
                },
                {
                  label: "Priority",
                  key: "priority",
                  options: ["high", "medium", "low"],
                },
                {
                  label: "Assigned To",
                  key: "assignedTo",
                  options: assignees,
                },
                {
                  label: "Stage",
                  key: "stage",
                  options: stageDefinitions.map((s) => String(s.number)),
                },
              ]}
              emptyTitle="No tasks found"
              emptyDescription="There are no tasks matching your filters."
            />
          )}
        </Fade>
      </PageTransition>
    </PageShell>
  );
}
