import { db } from "./db";
import { devProjects, devTasks, devSubtasks, devComments } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDevData(forceReseed = false) {
  const existingProjects = await db.select().from(devProjects);
  if (existingProjects.length > 0 && !forceReseed) {
    console.log("[dev-seed] Data already exists, skipping seed");
    return;
  }

  if (forceReseed && existingProjects.length > 0) {
    console.log("[dev-seed] Force reseed: clearing existing data...");
    await db.delete(devComments);
    await db.delete(devSubtasks);
    await db.delete(devTasks);
    await db.delete(devProjects);
  }

  console.log("[dev-seed] Seeding real TeamSync project data...");

  const [tsProject] = await db.insert(devProjects).values({
    name: "TeamSync Portal",
    key: "TS",
    description: "Multi-vertical B2B SaaS portal — 17 verticals, central design system, Supabase backend, React + TypeScript + Express",
    color: "#6366f1",
    status: "active",
    owner: "Sneha Patel",
  }).returning();

  const [lnProject] = await db.insert(devProjects).values({
    name: "LegalNations",
    key: "LN",
    description: "US company formation vertical — KYC, IRS compliance, document vault, multi-state formation pipeline",
    color: "#10b981",
    status: "active",
    owner: "Sneha Patel",
  }).returning();

  const [udProject] = await db.insert(devProjects).values({
    name: "USDrop AI",
    key: "UD",
    description: "Dropshipping & Shopify store management — AI product research, supplier matching, store automation",
    color: "#f59e0b",
    status: "active",
    owner: "Sneha Patel",
  }).returning();

  const [gtProject] = await db.insert(devProjects).values({
    name: "GoyoTours",
    key: "GT",
    description: "China B2B travel — tour packages, vendor management, booking calendar, hotels",
    color: "#ec4899",
    status: "active",
    owner: "Sneha Patel",
  }).returning();

  const [etsProject] = await db.insert(devProjects).values({
    name: "EazyToSell",
    key: "ETS",
    description: "B2B wholesale — price engine, order tracking, proposal PDF export, client pipeline",
    color: "#8b5cf6",
    status: "active",
    owner: "Sneha Patel",
  }).returning();

  const [intProject] = await db.insert(devProjects).values({
    name: "Internal Tools",
    key: "INT",
    description: "Shared infrastructure — CI/CD, error boundaries, performance audits, component library docs",
    color: "#64748b",
    status: "active",
    owner: "Sneha Patel",
  }).returning();

  const taskSeeds: Array<{
    projectId: string;
    taskCode: string;
    title: string;
    description: string;
    status: string;
    priority: string;
    type: string;
    assignee: string;
    tags: string[];
    storyPoints?: number;
    subtasks?: Array<{ title: string; completed: boolean }>;
    comments?: Array<{ author: string; content: string }>;
  }> = [
    {
      projectId: tsProject.id,
      taskCode: "TS-001",
      title: "Central design token system (DS object)",
      description: "Build comprehensive DS object in design-tokens.ts covering color (accent/text/bg/surface/system/border/chart/status), font (family/weight/size/leading), heading (h1-h6), radius (scale+semantic), shadow (scale+semantic). All tokens map to CSS variables in index.css and Tailwind config.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["design-system", "tokens", "css"],
      storyPoints: 8,
      subtasks: [
        { title: "DS.color — accent, text, bg, surface, system, border, chart, status", completed: true },
        { title: "DS.font — family, weight, size, leading", completed: true },
        { title: "DS.heading — h1 through h6 with font-family + font-weight + font-size + line-height", completed: true },
        { title: "DS.radius — scale (none/sm/md/lg/xl/2xl/full) + semantic (card/button/input/badge/dialog/popover)", completed: true },
        { title: "DS.shadow — scale (none/sm/md/lg/xl/2xl) + semantic (card/dropdown/dialog/popover/toast)", completed: true },
        { title: "Add --success/--warning/--info CSS variables + Tailwind color extensions", completed: true },
        { title: "Remove duplicate Tailwind keyframes", completed: true },
      ],
      comments: [
        { author: "Replit Agent", content: "Completed all DS sections. Tokens now cover color, font, heading, radius, shadow with both scale and semantic variants." },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-002",
      title: "Merge Dev Knowledge Base into Universal Resources",
      description: "Extend SharedResource with categories Process/SOP/Playbook/Workflow/Learning + type 'knowledge' + optional content field. Add 8 KB items to sharedResources. Enhance Resources page with expandable knowledge items, category icons, filter pills. Delete standalone KB page.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["dev-vertical", "resources", "kb-merge"],
      storyPoints: 5,
      subtasks: [
        { title: "Extend SharedResource interface with new categories and content field", completed: true },
        { title: "Add 8 KB items (RES-DEV-007 through 014) to mock-data-shared.ts", completed: true },
        { title: "Add category-aware icons (ClipboardList, Shield, Workflow, Lightbulb)", completed: true },
        { title: "Add expandable content section below grid for knowledge items", completed: true },
        { title: "Delete dev/resources.tsx, remove route and nav entry", completed: true },
        { title: "Update replit.md documentation", completed: true },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-003",
      title: "Restructure Dev vertical — minimal pages, DB-backed task mgmt",
      description: "Consolidated Dev pages from 10 to 5. Merged 4 Design System pages into 1 tabbed page. Created dev_projects/dev_tasks/dev_subtasks/dev_comments tables in PostgreSQL. Seeded real TeamSync task history. Wired projects/board/dashboard to DB via React Query. Removed Dev Board page.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["dev-vertical", "restructure", "database"],
      storyPoints: 13,
      subtasks: [
        { title: "Create Drizzle schema for dev_projects, dev_tasks, dev_subtasks, dev_comments", completed: true },
        { title: "Push schema to PostgreSQL", completed: true },
        { title: "Create API routes (CRUD for projects, tasks, subtasks, comments)", completed: true },
        { title: "Seed real TeamSync project/task history", completed: true },
        { title: "Merge 4 Design System pages into 1 tabbed page", completed: true },
        { title: "Wire projects page to DB via React Query", completed: true },
        { title: "Wire project board to DB via React Query", completed: true },
        { title: "Wire dashboard to DB via React Query", completed: true },
        { title: "Remove Dev Board page and clean nav", completed: true },
        { title: "Update replit.md", completed: true },
      ],
      comments: [
        { author: "Replit Agent", content: "Design System was already merged into 1 tabbed page with Style Guide, Components, Icons, and Library tabs. Removed standalone Dev Board page (/dev/board) and cleaned up sidebar navigation. All 3 pages (dashboard, projects, project-board) now fetch from PostgreSQL via React Query instead of mock data." },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-004",
      title: "6 canonical detail view types",
      description: "Standardized 6 detail view patterns: SmallDetailModal, DetailModal, LargeDetailSheet, LargeDetailDialog, FullPageDetailTabbed, FullPageDetailColumns. All use SidebarField helper. Documented in detail-view-blocks.tsx and page-layout.tsx.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["design-system", "detail-views", "components"],
      storyPoints: 8,
      subtasks: [
        { title: "SmallDetailModal — compact overlay for quick info", completed: true },
        { title: "DetailModal — standard dialog with sidebar fields", completed: true },
        { title: "LargeDetailSheet — slide-in sheet for rich content", completed: true },
        { title: "LargeDetailDialog — large dialog for complex forms", completed: true },
        { title: "FullPageDetailTabbed — full page with tab navigation", completed: true },
        { title: "FullPageDetailColumns — full page with 2-column layout", completed: true },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-005",
      title: "Universal pages — Team, Chat, Resources, Tasks, Tickets, Reports",
      description: "Build 7 universal pages that work across all verticals with vertical-aware filtering. Each page detects the current vertical from URL and shows scoped data. Includes Kanban board, DataTable views, detail dialogs.",
      status: "done",
      priority: "critical",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["universal", "multi-vertical", "core"],
      storyPoints: 21,
      subtasks: [
        { title: "Universal Team page with member cards and status", completed: true },
        { title: "Universal Chat with channels, DMs, message threads", completed: true },
        { title: "Universal Resources with grid/list views and preview modal", completed: true },
        { title: "Universal Tasks with Kanban + List + detail dialog", completed: true },
        { title: "Universal Tickets with priority filtering and detail view", completed: true },
        { title: "Universal Reports with chart widgets", completed: true },
        { title: "Universal Important Contacts", completed: true },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-006",
      title: "Supabase integration — tasks, tickets, channels, users, contacts",
      description: "Connect core entities to Supabase PostgreSQL. Create tables for tasks, task_subtasks, task_activity, tickets, channels, channel_messages, contacts, resources, notifications, users, user_verticals. Implement CRUD via server/supabase.ts helper functions.",
      status: "done",
      priority: "critical",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["supabase", "backend", "database"],
      storyPoints: 13,
      subtasks: [
        { title: "Supabase client setup with SERVICE_ROLE_KEY", completed: true },
        { title: "Core task CRUD (getCoreTasksByVertical, create, update, delete)", completed: true },
        { title: "Ticket CRUD operations", completed: true },
        { title: "Channel and message operations", completed: true },
        { title: "User and contact management", completed: true },
        { title: "Resource and notification operations", completed: true },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-007",
      title: "PersonCell + CompanyCell avatar components",
      description: "Standard avatar components using DiceBear API. PersonCell uses Micah style, CompanyCell uses Glass style. All person names must use PersonCell, all company names must use CompanyCell. Exported from @/lib/ds.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["design-system", "avatars", "components"],
      storyPoints: 3,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-008",
      title: "AI Chat assistant with tool-calling",
      description: "TeamSync AI co-pilot with conversation history (Supabase-backed), streaming responses via SSE, tool-calling for database queries (readRecords, queryWithSQL, createRecord). Vertical-aware context. Uses OpenAI GPT-4o via Replit integration.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["ai", "chat", "openai", "tool-calling"],
      storyPoints: 13,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-009",
      title: "Image Studio — AI image generation",
      description: "Universal Image Studio page with AI image generation via DALL-E/Flux. Gallery view, prompt history, style presets, aspect ratio selection. Generated images stored in Supabase. Available across all verticals.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["ai", "images", "dalle"],
      storyPoints: 8,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-010",
      title: "Notification system with real-time panel",
      description: "Notification bell in top nav with slide-out panel. Grouped by source (Tasks, Tickets, Chat, System). Read/unread states, mark all read, filter by source. Supabase-backed persistence.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["notifications", "real-time", "ui"],
      storyPoints: 5,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-011",
      title: "USDrop AI admin redesign proposal",
      description: "Proposed 5-group, 16-page redesign: Command Center, Sales & Growth, Client Success, Content & Learning, Analytics. Client journey pipeline + sales optimization focused. Awaiting user approval before implementation.",
      status: "todo",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["usdrop", "redesign", "proposal"],
      storyPoints: 21,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-012",
      title: "Conditional calendar coloring and role-based nav",
      description: "Implement Softr/ClickUp-inspired features: conditional calendar coloring based on event type/status, role-based nav visibility for different user roles, collapsible sidebar sections.",
      status: "todo",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["calendar", "roles", "nav"],
      storyPoints: 8,
    },
    {
      projectId: lnProject.id,
      taskCode: "LN-001",
      title: "Formation pipeline — 7-stage workflow",
      description: "Full company formation pipeline with 7 stages: Intake, KYC/AML, State Filing, EIN Application, Banking Setup, Compliance Setup, Delivery. Stage stepper component with full and mini variants. 20 mock clients across all stages.",
      status: "done",
      priority: "critical",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["pipeline", "workflow", "formation"],
      storyPoints: 13,
    },
    {
      projectId: lnProject.id,
      taskCode: "LN-002",
      title: "Document vault with categories and verification",
      description: "Document management system with categories (Articles, EIN Letter, BOI Receipt, Operating Agreement, Bank Docs, Passport, Address Proof, Filing Receipt, IRS Confirmation). Upload, verify, and organize client documents.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["documents", "vault", "kyc"],
      storyPoints: 8,
    },
    {
      projectId: lnProject.id,
      taskCode: "LN-003",
      title: "Compliance tracker — annual reports and BOI",
      description: "Track annual report deadlines, BOI rechecks, and state alerts. Auto-reminder system for upcoming compliance deadlines. Status tracking (compliant/due/overdue).",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["compliance", "annual-reports", "tracking"],
      storyPoints: 5,
    },
    {
      projectId: lnProject.id,
      taskCode: "LN-004",
      title: "Multi-state formation support",
      description: "Expand formation pipeline to support multiple states with state-specific requirements, filing fees, and processing times. State selection in intake form.",
      status: "backlog",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["multi-state", "formation"],
      storyPoints: 8,
    },
    {
      projectId: udProject.id,
      taskCode: "UD-001",
      title: "Product library with categories and suppliers",
      description: "Product catalog with category management, supplier linking, cost/price tracking, and product performance metrics. Grid and list views with filters.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["products", "catalog", "suppliers"],
      storyPoints: 8,
    },
    {
      projectId: udProject.id,
      taskCode: "UD-002",
      title: "Store management and fulfillment tracking",
      description: "Shopify store dashboard with order fulfillment tracking, inventory sync, and revenue analytics. Multi-store support.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["stores", "fulfillment", "shopify"],
      storyPoints: 8,
    },
    {
      projectId: udProject.id,
      taskCode: "UD-003",
      title: "AI product research engine",
      description: "AI-powered product research tool for finding winning products. Trend analysis, competitor research, profit margin calculator. Integrated with GPT-4o.",
      status: "backlog",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["ai", "research", "products"],
      storyPoints: 13,
    },
    {
      projectId: gtProject.id,
      taskCode: "GT-001",
      title: "Tour package builder with pricing tiers",
      description: "Create and manage tour packages with multiple pricing tiers (Budget, Standard, Premium). Itinerary builder with day-by-day activities, hotel assignments, and transport logistics.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["tours", "packages", "pricing"],
      storyPoints: 8,
    },
    {
      projectId: gtProject.id,
      taskCode: "GT-002",
      title: "Booking calendar with availability view",
      description: "Calendar view showing tour availability, bookings, and capacity. Support for recurring tours and seasonal pricing adjustments.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["calendar", "bookings", "availability"],
      storyPoints: 5,
    },
    {
      projectId: gtProject.id,
      taskCode: "GT-003",
      title: "Hotel and vendor management",
      description: "Manage hotel inventory and vendor relationships for tour operations. Rate negotiation tracking and vendor scorecards.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["hotels", "vendors", "management"],
      storyPoints: 5,
    },
    {
      projectId: etsProject.id,
      taskCode: "ETS-001",
      title: "EazyToSell vertical — all 10 pages",
      description: "Full EazyToSell vertical build: Dashboard, Pipeline, Client Detail, Payments, Calculator, Templates, Products, Proposals, Orders, Settings. Complete B2B wholesale management system.",
      status: "done",
      priority: "critical",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["ets", "vertical", "full-build"],
      storyPoints: 21,
      subtasks: [
        { title: "Dashboard with KPIs and pipeline summary", completed: true },
        { title: "Client pipeline with stage management", completed: true },
        { title: "Client detail page with order history", completed: true },
        { title: "Payment tracking and invoicing", completed: true },
        { title: "Price calculator with duty rates", completed: true },
        { title: "Document templates", completed: true },
        { title: "Product catalog", completed: true },
        { title: "Proposal builder", completed: true },
        { title: "Order management", completed: true },
        { title: "Settings page", completed: true },
      ],
    },
    {
      projectId: etsProject.id,
      taskCode: "ETS-002",
      title: "Price engine v2 — dynamic duty rates by category",
      description: "Enhanced pricing engine with dynamic HS code-based duty rate calculation. Support for landed cost breakdown, insurance, and freight charges per category.",
      status: "backlog",
      priority: "medium",
      type: "improvement",
      assignee: "Replit Agent",
      tags: ["pricing", "duty-rates", "calculator"],
      storyPoints: 8,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-013",
      title: "Faire integration — order sync, products, retailers",
      description: "Full Faire marketplace integration: store credential management, order sync from Faire API, product sync, retailer extraction and enrichment. Multi-store support with store switcher.",
      status: "done",
      priority: "critical",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["faire", "integration", "api"],
      storyPoints: 21,
      subtasks: [
        { title: "Store credential management (OAuth tokens)", completed: true },
        { title: "Order sync from Faire API", completed: true },
        { title: "Product sync and lifecycle management", completed: true },
        { title: "Retailer extraction from orders", completed: true },
        { title: "Retailer enrichment with contact data", completed: true },
        { title: "Store switcher component", completed: true },
        { title: "FaireDesk dashboard with real data", completed: true },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-014",
      title: "HRMS vertical — employees, payroll, attendance, org chart",
      description: "Human Resource Management System vertical with employee directory, payroll management, attendance tracking, department management, org chart, onboarding flows, leave management, performance reviews, goals tracking.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["hrms", "employees", "payroll"],
      storyPoints: 21,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-015",
      title: "ATS vertical — jobs, candidates, interviews, offers",
      description: "Applicant Tracking System: job postings, candidate pipeline, application tracking, interview scheduling, evaluation forms, offer management, talent pool, analytics dashboard.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["ats", "recruiting", "candidates"],
      storyPoints: 21,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-016",
      title: "CRM vertical — leads, contacts, deals, pipeline",
      description: "Customer Relationship Management: lead capture, prospect management, deal pipeline, contact management, activity tracking, email templates, performance analytics, payment links.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["crm", "leads", "deals"],
      storyPoints: 21,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-017",
      title: "Social Media Management vertical",
      description: "Social media management: post composer, content calendar, campaign management, media library, approval workflows, assignment management, analytics dashboard.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["social", "content", "campaigns"],
      storyPoints: 13,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-018",
      title: "Finance vertical — ledger, payments, cashbook, journal",
      description: "Finance management: general ledger, payment tracking, cashbook, journal entries, shared expenses, intercompany transactions, compliance reporting.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["finance", "ledger", "payments"],
      storyPoints: 13,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-019",
      title: "OMS vertical — orders, inventory, shipments, purchase orders",
      description: "Order Management System: order processing, inventory management, shipment tracking, purchase orders, returns handling, product catalog, supplier management, location management.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["oms", "orders", "inventory"],
      storyPoints: 13,
    },
    {
      projectId: intProject.id,
      taskCode: "INT-001",
      title: "Shared component library — DataTable, StatusBadge, FormDialog",
      description: "Core reusable components: DataTable with search/filter/sort/pagination, StatusBadge with variant mapping, FormDialog for create/edit forms, KanbanBoard with DnD, StatsCard, HeroBanner, PageShell layout.",
      status: "done",
      priority: "critical",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["components", "library", "reusable"],
      storyPoints: 13,
    },
    {
      projectId: intProject.id,
      taskCode: "INT-002",
      title: "Vertical switcher and multi-tenant navigation",
      description: "Dropdown vertical switcher in top nav. Each vertical has its own sidebar navigation, color accent, and tagline. Supports 17 verticals with role-based visibility.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["navigation", "verticals", "multi-tenant"],
      storyPoints: 8,
    },
    {
      projectId: intProject.id,
      taskCode: "INT-003",
      title: "Dark mode support",
      description: "Full dark mode with ThemeProvider, localStorage persistence, smooth transitions. All components support light/dark variants via Tailwind dark: classes and CSS variables.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["dark-mode", "theme", "accessibility"],
      storyPoints: 5,
    },
    {
      projectId: intProject.id,
      taskCode: "INT-004",
      title: "Bank transaction management and reconciliation",
      description: "Bank transaction import, categorization, and reconciliation system. Support for multi-currency with USD conversion. Transaction proof uploads. Used by Finance and Faire verticals.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["banking", "transactions", "reconciliation"],
      storyPoints: 8,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-020",
      title: "Replit environment import and setup",
      description: "Migrated TeamSync project to Replit environment. Installed all npm packages, configured Supabase secrets (SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY), verified server starts on port 5000 with Vite HMR. OpenAI integration via Replit's built-in connector.",
      status: "done",
      priority: "critical",
      type: "task",
      assignee: "Replit Agent",
      tags: ["devops", "replit", "setup"],
      storyPoints: 3,
      subtasks: [
        { title: "Install all npm dependencies from package.json", completed: true },
        { title: "Configure SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY secrets", completed: true },
        { title: "Verify Express server starts on port 5000", completed: true },
        { title: "Verify Vite HMR connection", completed: true },
        { title: "Verify dev-seed runs and populates database", completed: true },
      ],
      comments: [
        { author: "Replit Agent", content: "Import completed successfully. All packages installed, Supabase secrets configured, server running on port 5000 with Vite dev server proxy. Dev seed populated 35 tasks across 6 projects." },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-021",
      title: "EventHub vertical — event lifecycle management",
      description: "Full EventHub vertical: event creation, attendee management, check-in system, venue management, vendor coordination, budget tracking, lead capture, analytics dashboard.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["eventhub", "events", "attendees"],
      storyPoints: 13,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-022",
      title: "Suprans vertical — lead intake and enrichment",
      description: "Lead intake hub with inbound processing, identity enrichment pipeline, assignment management. Supports multi-source lead capture and automated enrichment workflows.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["suprans", "leads", "enrichment"],
      storyPoints: 8,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-023",
      title: "Faire marketplace — full vertical build",
      description: "Complete Faire marketplace management: store management, product sync, order tracking, fulfillment, shipments, retailer management, quotations, partner portal, ledger, bank transactions, pricing, vendor management, inventory, applications.",
      status: "done",
      priority: "critical",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["faire", "marketplace", "ecommerce"],
      storyPoints: 21,
      subtasks: [
        { title: "Store management with API credential handling", completed: true },
        { title: "Product sync and lifecycle from Faire API", completed: true },
        { title: "Order tracking and detail views", completed: true },
        { title: "Fulfillment workflow", completed: true },
        { title: "Shipment tracking", completed: true },
        { title: "Retailer management and enrichment", completed: true },
        { title: "Quotation builder", completed: true },
        { title: "Partner portal", completed: true },
        { title: "Financial ledger and bank transactions", completed: true },
        { title: "Pricing engine", completed: true },
        { title: "Vendor management", completed: true },
        { title: "Inventory tracking", completed: true },
        { title: "Application management", completed: true },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-024",
      title: "LBM Admin vertical — team management and settings",
      description: "Admin/management vertical with team oversight dashboard, settings configuration, and cross-vertical reporting.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["admin", "management", "settings"],
      storyPoints: 5,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-025",
      title: "Client portal — LegalNations white-label",
      description: "Client-facing portal for LegalNations customers. Dashboard with company status, document access, invoice history, messaging. Separate layout from admin with clean branding.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["portal", "client-facing", "legalnations"],
      storyPoints: 8,
      subtasks: [
        { title: "Portal layout with client branding", completed: true },
        { title: "Client dashboard with formation status", completed: true },
        { title: "Company list and detail views", completed: true },
        { title: "Document access portal", completed: true },
        { title: "Invoice history and payment status", completed: true },
        { title: "Client messaging interface", completed: true },
      ],
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-026",
      title: "Vendor quotation portal",
      description: "External vendor-facing portal for quotation responses and ledger access. Allows vendors to view and respond to quotation requests from Faire vertical.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["portal", "vendor", "quotations"],
      storyPoints: 5,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-027",
      title: "User management and access control",
      description: "Universal user management pages: user list with vertical assignments, user group management with permission sets. Available across all verticals for admin users.",
      status: "done",
      priority: "high",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["users", "access-control", "permissions"],
      storyPoints: 5,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-028",
      title: "PWA support and mobile responsiveness",
      description: "Progressive Web App manifest, install prompt component, responsive design across all verticals. Touch-friendly navigation and mobile-optimized layouts.",
      status: "todo",
      priority: "medium",
      type: "improvement",
      assignee: "Replit Agent",
      tags: ["pwa", "mobile", "responsive"],
      storyPoints: 8,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-029",
      title: "Real-time WebSocket notifications",
      description: "Replace polling-based notification checks with WebSocket connections for real-time updates. Broadcast task assignments, ticket updates, and chat messages instantly.",
      status: "backlog",
      priority: "medium",
      type: "improvement",
      assignee: "Replit Agent",
      tags: ["websocket", "real-time", "notifications"],
      storyPoints: 8,
    },
    {
      projectId: tsProject.id,
      taskCode: "TS-030",
      title: "Deployment and production build optimization",
      description: "Optimize production build: code splitting per vertical, lazy loading for route chunks, image optimization, CDN asset serving. Configure Replit deployment settings.",
      status: "backlog",
      priority: "high",
      type: "improvement",
      assignee: "Replit Agent",
      tags: ["deployment", "performance", "optimization"],
      storyPoints: 8,
    },
    {
      projectId: intProject.id,
      taskCode: "INT-005",
      title: "Animated transitions and micro-interactions",
      description: "Framer Motion integration for page transitions (PageTransition), stagger animations (Stagger/StaggerItem), fade-in effects (Fade). Simulated loading states via useSimulatedLoading hook.",
      status: "done",
      priority: "medium",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["animations", "framer-motion", "ux"],
      storyPoints: 5,
    },
    {
      projectId: intProject.id,
      taskCode: "INT-006",
      title: "Announcement banner system",
      description: "Dismissible announcement banner at top of app for system-wide messages. Used for feature announcements, maintenance notices. Supports custom colors and icons.",
      status: "done",
      priority: "low",
      type: "feature",
      assignee: "Replit Agent",
      tags: ["ui", "banner", "announcements"],
      storyPoints: 2,
    },
  ];

  for (const seed of taskSeeds) {
    const { subtasks: subtaskData, comments: commentData, ...taskData } = seed;
    const [task] = await db.insert(devTasks).values(taskData).returning();

    if (subtaskData && subtaskData.length > 0) {
      await db.insert(devSubtasks).values(
        subtaskData.map((s, i) => ({
          taskId: task.id,
          title: s.title,
          completed: s.completed,
          sortOrder: i,
        }))
      );
    }

    if (commentData && commentData.length > 0) {
      await db.insert(devComments).values(
        commentData.map(c => ({
          taskId: task.id,
          author: c.author,
          content: c.content,
        }))
      );
    }
  }

  console.log(`[dev-seed] Seeded ${taskSeeds.length} tasks across 6 projects`);
}
